ruby/lib/ThreatExchange.rb
Caught an edge that I didn't see in testing when an individual query would not have any paging key in the response it would throw an error. Fixed.
=> Minor Bugfix

pytx/pytx/common.py, pytx/pytx/request.py, pytx/pytx/vocabulary.py
Added threat_type to objects query
=> Allow to query by threat_type

members/get_members.py
Displays the contact email address, where available, for each member of ThreatExchange.
=> Pull member email address with get_members

pytx/DESCRIPTION.rst, pytx/README.rst, pytx/setup.py
fixed setup.py and pushed to pypi to streamline builds and development of tools using pytx
https://pypi.python.org/pypi/pytx
=> Omercnet pip prep

pytx/README.rst
Highlighting having to use type_ over type.
=> Add another example to the pytx readme.

pytx/README.rst
Adding documentation build badge from readthedocs.
=> Update README.rst to include documentation build badge

doc/threat_exchange.md
I added a concrete example of adding a connection between two indicator
nodes.
=> Improve docs for adding connections

doc/threat_exchange.md
Adding docs for the malware_family object and cleaned up some errors /
attributes we don’t support.
=> Adds docs for malware_family and more!

doc/threat_exchange.md
Update documentation for Platform v2.4. Corrects the malware family ID.
=> Documentation updates

threat_indicators/get_indicators.py
This can be used to increase batch size of requests
=> Adds a limit parameter to get_indicators.py

members/get_members.py
The current script is reading the old environment variables
=> Fix get_members.py to use correct environment variables

php/BaseSearch.php, php/BaseUpload.php, php/IndicatorSearch.php, php/IndicatorUpload.php, php/ThreatExchangeConfig.php, php/ThreatExchangeUtils.php, php/upload.php, php/upload_file.example
I updated the indicator search and upload code to use the new
descriptor objects that were included in v2.4
=> Upgraded PHP APIs to use v2.4 of ThreatExchange

doc/threat_exchange.md
Addresses issue #59, updating the docs for threat_descriptors and other
doc cleanup.
=> Update documentation with correct threat_descriptor fields

doc/threat_exchange.md
Adds documentation for the precision and review_status fields.
=> Add precision and review_status to threat descriptor fields

doc/threat_exchange.md
The example for the HTML_ID attribute was poor, so I fixed it.
=> [docs] Fixed an example

malware/get_samples.py
Fixes missing import from previous merge.
=> Fixed import error for urllib2 HTTPError and URLError

pytx/pytx/common.py, pytx/pytx/request.py
Connections requires the right classes to be returned.
=> Fix searching for connections.

pytx/README.rst, pytx/docs/index.rst, pytx/docs/pytx.logger.rst, pytx/docs/quickstart.rst
This adds more info to the quickstart guide outlining the new features
people can use.
=> Update documentation for pytx.

pytx/README.rst, pytx/docs/quickstart.rst, pytx/pytx/__init__.py, pytx/pytx/common.py, pytx/pytx/request.py, pytx/pytx/vocabulary.py
This adds the ability to search on owner and status using .objects().
Now that v2.5 is out we are also bumping to that.
=> Add owner and status to .objects() and bump to v2.5.

pytx/pytx/malware.py, pytx/pytx/malware_family.py, pytx/pytx/threat_descriptor.py, pytx/pytx/threat_exchange_member.py, pytx/pytx/threat_indicator.py, pytx/pytx/threat_privacy_group.py, pytx/pytx/vocabulary.py
Keeping up with vocabulary changes. These were all found in the latest developer docs.
=> pytx: lots of vocabulary updates.

pytx/pytx/malware.py, pytx/pytx/vocabulary.py
These are new vocab terms for Malware which provide the size of the
sample and the size of the compressed sample.
=> Adding sample_size and sample_size_compressed.

pytx/pytx/common.py
=> Fixing spelling mistake.

pytx/docs/pytx.utils.rst, pytx/pytx/__init__.py, pytx/pytx/malware.py, pytx/pytx/malware_family.py, pytx/pytx/threat_descriptor.py, pytx/pytx/threat_exchange_member.py, pytx/pytx/threat_indicator.py, pytx/pytx/utils.py, pytx/requirements.txt, pytx/setup.py
=> Moving utility functions to pytx

README.md, pytx/README.rst
Moving bootstrapping script documentation from pytx readme to faceboo…k/ThreatExchange readme
=> Readme change

LICENSE, php/BaseSearch.php, php/BaseUpload.php, php/IndicatorSearch.php, php/IndicatorUpload.php, php/MalwareFamilySearch.php, php/MalwareSearch.php, php/ThreatExchangeConfig.php, php/ThreatExchangeUtils.php, php/query_file.example, php/search.php, php/search_usage.example, php/upload.php, php/upload_file.example, php/upload_usage.example, ruby/LICENSE.txt
=> Updated Copyright headers.

pytx/docs/index.rst
Missing several files from the index causing them to be excluded from generated documentation.
=> Fix docs to include latest stuff.

ruby/lib/ThreatExchange.rb
Pagination in the ruby client was broken because it checked for a Symbol instead of String in the parsed JSON. A few other minor changes in the library.
=> Fix ruby client pagination, and refactor.

pytx/README.rst
=> Fix readthedocs link.

hashing/te-tag-query-java/com/facebook/threatexchange/Net.java, hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java, hashing/te-tag-query-java/com/facebook/threatexchange/Utils.java
=> Work off to-do's from previous PR

hashing/tmk/README.md
See https://github.com/facebook/ThreatExchange/issues/200
=> Add ./ to tmk-clusterize commands.

hashing/tmk/cpp/Makefile, hashing/tmk/cpp/bin/tmk-query-with-faiss.cpp
Added minimal support for faiss in Makefil which seems to be working for me. Please take a look.
=> tmk Makefile support for query with faiss.

hashing/tmk/README-more.md, hashing/tmk/README.md
Updating README files. A followup of #199.
=> Update readme files to include tmk-query-with-faiss.

hashing/pdq/python/README.md, hashing/pdq/python/pdqhashing/__init__.py, hashing/pdq/python/pdqhashing/hasher/__init__.py, hashing/pdq/python/pdqhashing/hasher/pdq_hasher.py, hashing/pdq/python/pdqhashing/tests/__init__.py, hashing/pdq/python/pdqhashing/tests/hash256_test.py, hashing/pdq/python/pdqhashing/tests/matrix_test.py, hashing/pdq/python/pdqhashing/tests/pdq_test.py, hashing/pdq/python/pdqhashing/tools/__init__.py, hashing/pdq/python/pdqhashing/tools/pdq_photo_hasher_tool.py, hashing/pdq/python/pdqhashing/types/__init__.py, hashing/pdq/python/pdqhashing/types/containers.py, hashing/pdq/python/pdqhashing/types/exceptions.py, hashing/pdq/python/pdqhashing/types/hash256.py, hashing/pdq/python/pdqhashing/utils/__init__.py, hashing/pdq/python/pdqhashing/utils/matrix.py
Adding implementation of the PDQ algorithm for Python.
=> Initial Python implementation of PDQ algorithm

hashing/te-tag-query-java/com/facebook/threatexchange/DescriptorFilterers.java, hashing/te-tag-query-java/com/facebook/threatexchange/DescriptorFormatters.java, hashing/te-tag-query-java/com/facebook/threatexchange/HashFormatters.java, hashing/te-tag-query-java/com/facebook/threatexchange/Net.java, hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java, hashing/te-tag-query-java/com/facebook/threatexchange/ThreatDescriptor.java, hashing/te-tag-query-java/com/facebook/threatexchange/Utils.java
Testing: re-ran all the commands at https://github.com/facebook/ThreatExchange/blob/master/hashing/te-tag-query-java/README.md
=> Include more fields in the output: review_status, description, last_updated

hashing/te-tag-query-java/README.md, hashing/te-tag-query-java/com/facebook/threatexchange/IndicatorTypeFilterers.java, hashing/te-tag-query-java/com/facebook/threatexchange/Net.java, hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java
since it operates on data before all fields have been read.
=> rename descriptor-filter to indicator-type-filter

README.md, hashing/te-tag-query-python/te-tag-query-python, pytx/README.rst, ruby/README.md
As noted at https://developers.facebook.com/docs/threat-exchange/reference/changelog#2020-06-02
`README.md` / `README.rst` layout verified by inspection at https://github.com/johnkerl/ThreatExchange
=> README.md updates to support June 2 Python/Ruby releases

hashing/te-tag-query-java/README.md, hashing/te-tag-query-java/com/facebook/threatexchange/DescriptorFormatters.java, hashing/te-tag-query-java/com/facebook/threatexchange/DescriptorPostParameters.java, hashing/te-tag-query-java/com/facebook/threatexchange/Net.java, hashing/te-tag-query-java/com/facebook/threatexchange/SimpleJSONWriter.java, hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java, hashing/te-tag-query-java/com/facebook/threatexchange/ThreatDescriptor.java
Follow-on to https://github.com/facebook/ThreatExchange/pull/256 -- another PR adding in some new features in the Ruby/Python ports which are absent in the Java port.
Testing: run the commands in `README.md`.
=> Copy-handler

pytx3/pytx3/__init__.py, pytx3/pytx3/cli/__init__.py, pytx3/pytx3/cli/command_base.py, pytx3/pytx3/cli/fetch.py, pytx3/pytx3/cli/label.py, pytx3/pytx3/cli/main.py, pytx3/pytx3/cli/match.py, pytx3/pytx3/collab_config.py, pytx3/pytx3/common.py, pytx3/pytx3/content_type/__init__.py, pytx3/pytx3/content_type/content_base.py, pytx3/pytx3/content_type/meta.py, pytx3/pytx3/content_type/photo.py, pytx3/pytx3/content_type/text.py, pytx3/pytx3/content_type/video.py, pytx3/pytx3/dataset.py, pytx3/pytx3/descriptor.py, pytx3/pytx3/signal_type/__init__.py, pytx3/pytx3/signal_type/md5.py, pytx3/pytx3/signal_type/pdq.py, pytx3/pytx3/signal_type/raw_text.py, pytx3/pytx3/signal_type/signal_base.py, pytx3/pytx3/signal_type/trend_query.py, pytx3/pytx3/signal_type/url.py, pytx3/pytx3/signal_type/video_tmk_pdqf.py
Copyright headers are required for first-party source files.
Closes T71465833.
=> Add copyright notice statements

pytx3/pytx3/TE.py
Summary:
We aren't using very many of the functions in TE.Net.
Remove many of the unused one.
Test Plan:
```
$ pytx3 fetch
```
Didn't asplode
=> [pytx3] Slim down copy of TE.net

pytx3/pytx3/signal_type/raw_text.py, pytx3/pytx3/signal_type/signal_base.py, pytx3/setup.py
Summary:
Text matching has been a problem for partners, and we had been
telling them "just use levenshtein distance with 95% match", based on
what would map closest to Facebook's systems. Since then, we realized
there was actually a significant amount of normalization happening first.
We sent partners some rough ideas, and there are plenty of articles on
the internet (and plenty of python libraries) that do some kinds of
normalization and distance.
My goals are the following:
1. The suggested normalization should be simple enough that someone
could easily port it to another language from reading this code.
2. Take on the minimum amount of dependency complexity
3. The highest possible incremental value over raw string comparison.
4. Spend less than 3 hours implementing it
This is attempt …
=> [pytx3] Implement simple normalization + distance on text matching

README.md
summary: Edit the top level read me to match the new layout and current contents of the top level directory
test plan: Ensure all links to other files in the repo are still correct
=> Top level readme

pytx3/setup.py
I didn't push a new verison of pytx3 with fixes. So do that, and do some fixes related to formatting changes.
=> [pytx3] 0.0.8 and setup.py fixes

pytx3/pytx3/hashing/pdq_faiss_matcher.py, pytx3/tests/hashing/test_pdq_faiss_matcher.py, pytx3/tests/test_common.py
Summary
=======
I forgot the copyright lines at the start of the new files created
in some recent PRs.
We may want to look into if we can have a github action to remind
us to add the headers to new source files.
=> Add missing copyright headers to new test files

.github/PULL_REQUEST_TEMPLATE.md
Summary
---------
Adding a simple pull request template to nudge PRs to standard format.
Test Plan
---------
Submitted this PR and confirmed that it has the requested PR format automatically.
=> Add basic PR template

README.md
Summary
---------
Added Contributing Guide and License link for ThreatExchange Repository in the README.md
=> Added Contributing Guide

CODEOWNERS
Never seen codeowners before, I also want notifications!
Summary
---------
Read the syntax at https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners, and just followed it
Test Plan
---------
Nothin
=> Update CODEOWNERS to include Dcallies in globals

python-threatexchange/tests/hashing/test_pdq_utils.py, python-threatexchange/threatexchange/hashing/pdq_utils.py
Summary
---------
Adds copyright to test file and docstring to `pdq_utils.py`
Test Plan
---------
No logical changes, will check CI builds.
=> Add copyright and docstrings

python-threatexchange/threatexchange/cli/experimental_fetch.py
Summary
---------
Ran code formatter over the files to address current lint failure in master.
Test Plan
---------
CI lint build passes.
=> Fix Code Format

CODEOWNERS
=> Remove self from CODEOWNERS

.github/labeler.yml
Summary
---------
Automatically label HMA related PRs
Test Plan
---------
None as this must be merged to master before the workflow will pick up the change.
=> Auto label HMA related PRs

hasher-matcher-actioner/.terraform.lock.hcl
I'm not entirely sure how this happened, but I think I need to commit this.
=> [hma] sync lockfile

python-threatexchange/threatexchange/signal_type/signal_base.py
Summary
---------
If you try and use experimental-fetch right off the bat, it fails to find the existing statefile directories. 
Test Plan
---------
```
rm ~/state_dir
threatexchange experimentalfetch
```
=> [py-tx] fix directory creation with experimental-fetch

python-threatexchange/threatexchange/cli/fetch.py
Summary
---------
Facebook is exporting malformed trend_queries in some cases. While they shouldn't do that, the library probably also shouldn't crash.
Fixes: https://github.com/facebook/ThreatExchange/issues/357
Test Plan
---------
Run fetch on collaboration with malformed trend_queries, doesn't asplode
=> [py-tx] Paper over signal type deserialization errors

CODEOWNERS, hasher-matcher-actioner/Makefile
Summary
---------
I don't know a lot about Make, but I think it's a useful way to record setup steps. The main advantage here is that you can bootstrap the dev instance as a Facebook dev without reading too much.
Test Plan
---------
Run all make commands locally.
=> [hma] Add initial Makefile

python-threatexchange/threatexchange/api.py, python-threatexchange/threatexchange/cli/command_base.py, python-threatexchange/threatexchange/cli/experimental_fetch.py, python-threatexchange/threatexchange/cli/fetch.py, python-threatexchange/threatexchange/cli/label.py, python-threatexchange/threatexchange/cli/main.py, python-threatexchange/threatexchange/cli/match.py, python-threatexchange/threatexchange/dataset.py, python-threatexchange/threatexchange/descriptor.py, python-threatexchange/threatexchange/indicator.py
Summary
---------
TE.net is a dinosaur from another era, and it does a lot of interesting things that need various cleanups (class/module state, java-style class wrapper, naming conventions, directly using GET/POSTS in some commands). We're still a couple of rounds away from getting it into a good shape.
Test Plan
---------
I didn't test this super hard, so it's possible it breaks.
```
$ threatexchange fetch --full # sample data
$ threatexchange experimental-fetch --full # sample data
$ threatexchange label false_positive descriptor 3805925856125337 
```
=> [py-tx] Refactor TE.py to api.py

.github/workflows/hma-master-push.yaml, .github/workflows/hma-pull-request.yaml, hasher-matcher-actioner/Makefile, hasher-matcher-actioner/scripts/write_backend_config.sh
Summary
---------
There are two CI hooks as part of this PR.
1. PR Validator (runs `terraform fmt` and `terraform validate` without using a remote backend.
2. Master push validate and test (runs `terraform apply` and creates an integration test friendly environment with a custom prefix "tftest".
Note: Concurrent execution of workflows (multiple terraform apply) on the same prefix will have undefined results. This can be solved, if we see a lot of activity on master, we'll have another stab at this.
Test Plan
---------
Locally, `terraform fmt` was run, but to actually evaluate, the workflows must be run. Since we tie the execution of the workflow to the 'pull_request_target' [1] event, we must first merge this PR into master and raise a subsequent pull request to validate the PR. …
=> First stab at pull-request, master-push gh actions

python-threatexchange/threatexchange/signal_type/index.py
Summary
---------
This is part of the diff series to move state out of SignalType directly and into its own class, though overall functionality will be basically the same.
A followup diff will add a simple linear search + pickle solution as a default implementation.
Test Plan
---------
black, mypy
=> [py-tx] index base

hasher-matcher-actioner/hma-lite/API.md, hasher-matcher-actioner/hma-lite/hmalite/app.py, hasher-matcher-actioner/hma-lite/hmalite/matcher.py
Summary
---
Add a flask blueprint that provides one endpoint accessible via GET or POST as detailed in API.md
Test plan
---
First run the application
```
$> FLASK_APP=hmalite.app:app FLASK_ENV=development flask run
```
Then run the tests. Because the matches are random, you might need to run the tests a few times to get the outputs you want.
GET Request
```
$> curl -v "http://localhost:5000/v1/hashes/query?hash=tyui"
```
Note the status header.
POST Requests
```
$> curl --header "Content-Type: application/json" \
--request POST \
--data '{"hashes":["xyz", "abc"]}' \
http://localhost:5000/v1/hashes/query
```
=> Add mock APIs for matching single and multiple hashes

hasher-matcher-actioner/hma-lite/hmalite/app.py, hasher-matcher-actioner/hma-lite/hmalite/templates/index.html
Summary
---------
Add Quick UI
Test Plan
---------
Move Fast
=> Add simple ui elements

hasher-matcher-actioner/hma-lite/hmalite/app.py, hasher-matcher-actioner/hma-lite/hmalite/templates/index.html, hasher-matcher-actioner/hma-lite/hmalite/templates/results.html
Summary
---------
Add form for uploading an image directly and results page
Test Plan
---------
Demo-ed to @Dcallies  but your mileage may vary...
=> Clean up static page for hmalite and provide photo upload form

hasher-matcher-actioner/hma-lite/hmalite/app.py, hasher-matcher-actioner/hma-lite/hmalite/config.py
Summary
---------
Adds a simple flask config. I'm not a huge fan of it being untyped, but not sure if it's easy to fix either.
Test Plan
---------
Spent several hours learning various ways to fail to run. The winning strategy ended up being:
1. Code in devserver
2. Test by running flask directly and then curling it 
2. push to fork repo
3. pull from fork repo onto laptop (in git-bash)
4. in powershell, build a docker image
5. run the docker image with `docker run -d -p 5000:80 lite`
6. visit localhost:5000 in browser
I know there are many possible optimizations to the above, but this is the only route that works so far. I am not a good engineer.
=> [hmalite] flask config

hasher-matcher-actioner/hma-lite/hmalite/app.py, hasher-matcher-actioner/hma-lite/hmalite/config.py, python-threatexchange/threatexchange/hashing/pdq_faiss_matcher.py, python-threatexchange/threatexchange/signal_type/pdq_index.py
Summary
---------
This is the output of some number of hours of disorganized hacking, and so is not the cleanest diff.
Somewhere in this pile, there is:
1. Handling configs (supported patterns = written as file, overridden with environ)
2. A bug fix for the PDQ index library
3. Moving things around
Test Plan
---------
Finally figured out how to connect from my browser to the devserver:
ssh -L 5000:localhost:5000
will do the trick. In my case, it took me a few hours to learn that something was reserving 5000, and so needed to switch to 5001.
May contain random bugs.
=> [ise][hma-lite] config

hasher-matcher-actioner/hma-lite/hmalite/app.py, hasher-matcher-actioner/hma-lite/hmalite/config.py, hasher-matcher-actioner/hma-lite/hmalite/index.py, hasher-matcher-actioner/hma-lite/hmalite/matcher.py
Summary
---------
This PR is actually dependent on https://github.com/facebook/ThreatExchange/pull/388, but I have no idea how to correctly represent that.
This PR makes the for querying hashes connect to the index instead of mocked returns.
Test Plan
---------
```
$ curl localhost:5000/v1/hashes/query?hash=b3485b12693aa21374197089daa65b4db57d9eb68acb4d467db4eceaaa85c350
{
"match": true,
"result": [
{
"distance": -1,
"meta": {
"hash": "b3485b12693aa21374197089daa65b4db57d9eb68acb4d467db4eceaaa85c350",
"meta": [
"3525057520847482",
"2020-07-31T18:47:52+0000",
"media_priority_pdq_samples disputed media_priority_samples media_type_photo"
]
}
}
]
}
$ curl -X POST localhost:5000/v1/hashes/query -H "Content-Type: application/json" -d '{"hashes": ["3be791183317d478924b3 …
```
=> [hmalite] Api more

hasher-matcher-actioner/hma-lite/hmalite/templates/index.html, hasher-matcher-actioner/hma-lite/hmalite/templates/results.html
Summary
---------
Replaced basic html templates with a more aesthetically pleasing version using bootstrap
Test Plan
---------
Locally tested in browsers and built into HMA-Lite Docker Image
=> Updated html templates using bootstrap

hasher-matcher-actioner/hmalib/lambdas/fetcher.py
Summary
---------
Hello world function
=> Create Boilerplate code for TE Fetcher

hasher-matcher-actioner/terraform/fetcher/main.tf, hasher-matcher-actioner/terraform/fetcher/variables.tf, hasher-matcher-actioner/terraform/main.tf
Summary
---------
I did some terraform things to connect a DynamoDB table to the fetcher. 
Test Plan
---------
terraform apply-ied to my dev instance. 
Will test that it works in a followup diff.
=> [hma] terraform for fetch configs

hasher-matcher-actioner/hma-lite/README.md
=> [docs] Update README.md

hasher-matcher-actioner/terraform/fetcher/main.tf
Summary
---------
Probably a merge failure from me :'( 
Test Plan
---------
terraform init
terraform apply
=> [hma][terraform] Fix syntax errors in fetcher

hasher-matcher-actioner/hmalib/lambdas/api/status_api.py, hasher-matcher-actioner/requirements.txt, hasher-matcher-actioner/terraform/api/main.tf
Summary
---------
Add routes to `status_api.py` 
Test Plan
---------
(Ask me for a demo)
=> add simple routes

hasher-matcher-actioner/hmalib/common.py, hasher-matcher-actioner/hmalib/dto.py, hasher-matcher-actioner/hmalib/lambdas/api/api_auth.py, hasher-matcher-actioner/hmalib/lambdas/api/api_root.py, hasher-matcher-actioner/hmalib/lambdas/fetcher.py, hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_hasher.py, hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_indexer.py, hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_matcher.py, hasher-matcher-actioner/hmalib/metrics/__init__.py, hasher-matcher-actioner/hmalib/metrics/cloudwatch.py
Summary
---------
Updated lambdas to use common get_logger to avoid updating the root logger
and ran `black hasher-matcher-actioner/hmalib/`
Test Plan
---------
```
terraform -chdir=terraform destroy
terraform -chdir=terraform apply
make dev_test_instance
```
=> Update logging in lambdas and run formatter

hasher-matcher-actioner/hmalib/aws_secrets.py
Summary
---------
A new python file and class to load AWS secrets. 
As we add more secrets we should add functions to the AWSSecrets class to load them
secrets can either be stored as strings or raw binary and so have
Test Plan
---------
Ran locally by adding line to bottom `print(AWSSecrets().te_api_data().api_token)`
and confirming that the correct access token secret is printed out
Need to hard code `AWS_REGION` to "us-east-1"
=> Create python file to load secrets

hasher-matcher-actioner/webapp/package-lock.json, hasher-matcher-actioner/webapp/package.json, hasher-matcher-actioner/webapp/public/index.html, hasher-matcher-actioner/webapp/src/App.js, hasher-matcher-actioner/webapp/src/index.js
Summary
---------
Test Plan
---------
=> Webapp wireframe prototype v0.

hasher-matcher-actioner/terraform/.terraform.lock.hcl, hasher-matcher-actioner/terraform/variables.tf, hasher-matcher-actioner/webapp/src/Matches.js
Summary
---------
This PR:
1. Calls an API method on the gateway with a hardcoded API URL (mine) with a hardcoded token (added to tvars)
2. Adds a function to try and let other people copy this horrid code
3. Renders the matches list kinda sorta
Test Plan
---------
=> [hma] Call API from UI

.github/labeler.yml, .github/workflows/hmalib-ci.yaml, .github/workflows/python-threatexchange-ci.yaml, CODEOWNERS, hasher-matcher-actioner/hmalib/aws_secrets.py, hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_hasher.py
Summary
---------
Add same CI formatter check we have for python-threatexchange to hmalib (requires that I run `black hasher-matcher-actioner/hmalib`
Test Plan
---------
Not an easy thing to test until it's live...
=> Update codeowners, labeler, and workflow

hasher-matcher-actioner/webapp/src/MatchDetails.js
Summary
---------
I figured action taken is an interesting bit of result, and it's not on any page. Seems like we might want to see it here.
Test Plan
---------
=> [hma][ui] Add reference to actioner action in mock

hasher-matcher-actioner/hmalib/lambdas/api/api_root.py, hasher-matcher-actioner/webapp/src/Api.js, hasher-matcher-actioner/webapp/src/Matches.js, hasher-matcher-actioner/webapp/src/Upload.js
Summary
---------
You can now use the uploads page on the UI to upload to the images 'folder' in the s3 bucket. I also refactored API requests to their own file.
Test Plan
---------
`terraform apply` and update `API_ROOT` + `API_TOKEN` in `Api.js` to match your deployed instance.
then navigate to the /uploads page either from aws or by spinning up the webapp locally. 
You should be able to submit a file and have it appear in the s3 bucket (for the hma pipeline to try and match).
=> add Api.js and connect upload image to UI

python-threatexchange/threatexchange/cli/experimental_fetch.py
Summary
---------
Run formatted from vscode
Test Plan
---------
More lint checks pass.
=> [py-te] black format to fix lint

.github/workflows/hma-ci-pull-request.yaml, hasher-matcher-actioner/hmalib/lambdas/fetcher.py, hasher-matcher-actioner/hmalib/models.py, hasher-matcher-actioner/hmalib/tests/test_models.py, hasher-matcher-actioner/mypy.ini, hasher-matcher-actioner/requirements-dev.txt, hasher-matcher-actioner/terraform/hashing-data/main.tf
Summary
---------
Timestamp is a reserved word, there are ways around it but UpdateAt is clearer anyway.
Add query interface to be used in API and possibly actioners.
Test Plan
---------
`make dev_test_instance` passes 
also added `hmalib/tests/test_models.py` which the CI runs.
=> [HMA] rename Timestamp to UpdatedAt and expand models for querying 

hasher-matcher-actioner/hmalib/lambdas/fetcher.py, hasher-matcher-actioner/terraform/fetcher/main.tf, hasher-matcher-actioner/terraform/variables.tf
Summary
---------
- Edit permissions to allow fetcher to read+write s3 checkpoint and PDQ file
- Edit permissions to allow fetcher to get threat exchange api key secret
- create THREAT_EXCHANGE_PDQ_DATA_KEY environment variable
Test Plan
---------
`terraform apply`
Look at fetcher logs and see no errors
Delete privacy group checkpoints and pdq files using AWS UI and see that they are regenerated
=> Make fetcher work

hasher-matcher-actioner/terraform/fetcher/main.tf, hasher-matcher-actioner/terraform/fetcher/variables.tf, hasher-matcher-actioner/terraform/main.tf, hasher-matcher-actioner/terraform/variables.tf
Summary
---------
Meant to do this before. Move the fetcher frequency variable from just the fetcher module to the to a top level tfvars variable
Test Plan
---------
`terraform validate && terraform apply`
=> Move Fetcher frequency variable to top level

hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_indexer.py
Summary
---------
I think I found the issue
Test Plan
---------
@eriksendc
=> Does this work brian

hasher-matcher-actioner/Makefile, hasher-matcher-actioner/terraform/main.tf, hasher-matcher-actioner/terraform/outputs.tf, hasher-matcher-actioner/tests/scripts/check_deployed_instance.py
Summary
---------
#460 unintentionally broke our test commands in the Makefile.
This makes the necessary changes to provide test signals and run the smoke test script again.
Test Plan
---------
Ran the following commands and confirmed output + checked the cloudwatch logs of the indexer.
`make dev_test_instance`
`make dev_upload_test_signal`
=> [hma] update test commands and script

hasher-matcher-actioner/hmalib/lambdas/fetcher.py
Summary
---------
Demo flow for mengyang
Make log more readable
Test Plan
---------
tested locally 
`python3 -m hmalib.lambdas.fetcher`
`black hmalib`
`mypy hmalib`
tested in aws:
`terraform apply`
`make docker`
`make upload_docker`
`aws lambda update-function-code --function-name jeberl_fetcher --image-uri 521978645842.dkr.ecr.us-east-1.amazonaws.com/hma-lambda-dev:jeberl`
Saw logs change in aws
=> Update fetcher to have better logs

hasher-matcher-actioner/hmalib/common/actioner_models.py, hasher-matcher-actioner/hmalib/lambdas/actions/action_evaluator.py, hasher-matcher-actioner/hmalib/lambdas/actions/action_performer.py
Summary
---------
Refactor to make @eriksendc and my work separate
Test Plan
---------
`mypy hmalib && black hmalib`
=> Refactor actioner

hasher-matcher-actioner/hmalib/common/actioner_models.py, hasher-matcher-actioner/hmalib/lambdas/actions/action_performer.py, hasher-matcher-actioner/hmalib/tests/test_actioner.py
Summary
---------
Initial mock of the get_action_performer function. This will eventually read configs from s3 and dynamically determine which performer to use 
Test Plan
---------
1. go to https://webhook.site/ to get a unique URL
2.  add to the WebhookActionPerformer constructor
3. run `python3 -m hmalib.lambdas.actions.action_performer`
4. check that the webhook was recieved
=> mock action performer configs

hasher-matcher-actioner/hmalib/lambdas/actions/action_evaluator.py, hasher-matcher-actioner/terraform/actions/main.tf, hasher-matcher-actioner/terraform/actions/variables.tf, hasher-matcher-actioner/terraform/main.tf
Summary
---------
We will eventually put a queue between these functions be for now this just splits them up in aws so that @eriksendc and I can work separately
Test Plan
---------
`terraform validate && terraform apply`
`make docker && make upload docker`
Confirmed functions work correctly by testing in aws
=> Split actioner into multiple functions in terraform

hasher-matcher-actioner/hmalib/lambdas/actions/action_evaluator.py, hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_matcher.py, hasher-matcher-actioner/hmalib/models.py
Summary
---------
This PR introduces converting the TE concept of tags into "classifications", and wires them up to be sent through from matching to evaluation, and on to action execution.
Test Plan
---------
1. `make upload_docker`
2. `make dev_upload_test_data`
3. wait for hashing and matching to occur
4. validate CloudWatch logs for matcher shows classifications in MatchMessage
5. validate CloudWatch logs for action evaluator shows classifications in MatchMessage
6. validate webhook call contains classifications from MatchMessage
=> Actioner evaluate one rule

hasher-matcher-actioner/hmalib/lambdas/actions/action_evaluator.py, hasher-matcher-actioner/hmalib/lambdas/actions/action_performer.py, hasher-matcher-actioner/hmalib/lambdas/actions/reactioner.py, hasher-matcher-actioner/terraform/actions/main.tf, hasher-matcher-actioner/terraform/actions/variables.tf, hasher-matcher-actioner/terraform/main.tf
Summary
---------
Separate actions and reactions into separate queues.
Test Plan
---------
4. `make dev_upload_test_data`
5. wait for hashing and matching to occur
6. validate CloudWatch logs: see that action_performer got a MatchMessage
7. validate CloudWatch logs: see that reactioner got a MatchMessage
=> Actions queues

hasher-matcher-actioner/hmalib/aws_secrets.py
Summary
---------
Nit from @schatten 's comment on #507
Test Plan
---------
CI
=> Remove region

hasher-matcher-actioner/hmalib/common/actioner_models.py, hasher-matcher-actioner/hmalib/common/config.py, hasher-matcher-actioner/hmalib/common/reactioner_models.py, hasher-matcher-actioner/hmalib/common/tests/config_test.py, hasher-matcher-actioner/hmalib/lambdas/actions/action_performer.py
Summary
---------
Followup from @jeberl's diff. Use new subtype to cover action case, hopefully works exactly as expected.
Test Plan
---------
mypy and pytest are green, will work with others for more.
=> [hma][action] Convert configs to HMAConfigWithSubtypes

.gitignore, hasher-matcher-actioner/webapp/package-lock.json, hasher-matcher-actioner/webapp/package.json, hasher-matcher-actioner/webapp/src/Settings.jsx
Summary
---------
Add more details to the actioner configs page
Next step, make it editable
Also some small changes that we requested from earlier PR
Test Plan
---------
=> display actioner details

hasher-matcher-actioner/hmalib/common/actioner_models.py, hasher-matcher-actioner/hmalib/common/tests/test_action_rule_evaluation.py, hasher-matcher-actioner/hmalib/lambdas/actions/action_evaluator.py
Summary
---------
This PR implements action evaluation (measuring up a match message against action rules and getting a resulting set of actions out the other side). Simple tests included! :)
Test Plan
---------
0. python -m py.test
4. `make dev_upload_test_data`
5. wait for hashing and matching to occur
6. validate CloudWatch logs: see that action_performer got an ActionMessage
=> Implemented action evaluation along with some tests.

hasher-matcher-actioner/webapp/src/components/ContentMatchTable.jsx, hasher-matcher-actioner/webapp/src/components/OpinionChangeConfirmModal.jsx, hasher-matcher-actioner/webapp/src/components/OpinionTableCell.jsx, hasher-matcher-actioner/webapp/src/pages/ContentDetails.jsx
Summary
---------
A little bit of clean up on the details page. 
No logical changes just addressing some some warnings/errors in the dev tool console  
Test Plan
---------
Made sure the change opinion flow still works 
(context: last commit of #530)
=> [hma] fix console errors on details UI

hasher-matcher-actioner/.devcontainer/Dockerfile, hasher-matcher-actioner/.devcontainer/devcontainer.json
Summary
---------
Finally makes it possible to not have changes to the devcontainer file which reduces the possibility of merge conflicts. 
Test Plan
---------
Rebuilt container and verified that the default user when I open terminal is my unixname.
=> devcontainers: infer unixname from env; add github cli

hasher-matcher-actioner/webapp/src/Api.jsx, hasher-matcher-actioner/webapp/src/App.jsx, hasher-matcher-actioner/webapp/src/Upload.jsx, hasher-matcher-actioner/webapp/src/components/SubmitContentFields.jsx, hasher-matcher-actioner/webapp/src/pages/SubmitContent.jsx, hasher-matcher-actioner/webapp/src/utils/constants.jsx
Summary
---------
Builds off of the API Created in #535
URL Support and recording the metadata are both critical features that I will work on adding. 
For the purpose of this PR this page is a slightly nicer upload page with room to grow :)  
Thanks! 
Test Plan
---------
Demo video: (bridge was a repeat upload else the video would have to wait 2-3 minutes for the hash and matches to show up)
https://user-images.githubusercontent.com/7664526/116619587-a3f04180-a90e-11eb-898f-16ad0c9ff283.mov
=> [hma][ui] Connect Submit Content API to new UI Page

hasher-matcher-actioner/hmalib/lambdas/api/stats.py, hasher-matcher-actioner/hmalib/metrics/query.py
Summary
--------
Current master is broken. I had not checked mypy output before merging my pull request #554. This fixes those type issues.
Test Plan
---------
=> Various type issues in api.stats and metrics.query

hasher-matcher-actioner/hmalib/lambdas/api/datasets_api.py
Summary
---------
This PR is to update sync/delete privacy groups response message 
Test Plan
---------
2. mypy hmalib
4. make docker
5. make upload_docker 
6.  terraform apply
7. test delete and sync api in local
=> update sync/delete privacy groups response message

hasher-matcher-actioner/webapp/src/components/settings/ThreatExchangePrivacyGroupCard.jsx
Summary
---------
this PR is to change the way of triggering tooltip from 'click' to 'focus'
Test Plan
---------
test localhost UI changes
https://user-images.githubusercontent.com/81996660/117906453-f03e6880-b2a2-11eb-8b8f-da022dbe36d8.mov
=> change the way of triggering tooltip

hasher-matcher-actioner/terraform/pdq-signals/main.tf
Summary
---------
Quick  IAM allow rule permission fix to allow counts to be added from #571
Test Plan
---------
tf apply and made sure hasher and matcher lambda can update the counts.
=> [HMA] update allow rule

hasher-matcher-actioner/hmalib/lambdas/api/actions_api.py, hasher-matcher-actioner/hmalib/lambdas/api/api_root.py, hasher-matcher-actioner/webapp/src/components/settings/ThreatExchangePrivacyGroupCard.jsx
Summary
---------
This PR is to create create/read/update/delete apis to for ActionPerformer in DynamoDB
Test Plan
---------
2. mypy hmalib
4. python -m hmalib.lambdas.api.api_root
5. test all apis in postman
https://user-images.githubusercontent.com/81996660/118007684-5adebb00-b31a-11eb-8869-5c7c68f14d53.mov
=> Action performer api

hasher-matcher-actioner/hmalib/common/classification_models.py, hasher-matcher-actioner/hmalib/common/message_models.py, hasher-matcher-actioner/hmalib/common/tests/test_writebacker.py, hasher-matcher-actioner/hmalib/common/writebacker_models.py, hasher-matcher-actioner/hmalib/lambdas/actions/action_evaluator.py, hasher-matcher-actioner/hmalib/lambdas/actions/writebacker.py, hasher-matcher-actioner/hmalib/lambdas/api/api_root.py, hasher-matcher-actioner/hmalib/lambdas/api/matches.py, hasher-matcher-actioner/hmalib/lambdas/fetcher.py, hasher-matcher-actioner/terraform/actions/main.tf, hasher-matcher-actioner/terraform/actions/outputs.tf, hasher-matcher-actioner/terraform/api/main.tf, hasher-matcher-actioner/terraform/api/variables.tf, hasher-matcher-actioner/terraform/main.tf, hasher-matcher-actioner/webapp/package-lock.json
Summary
---------
Connect the api to the Writeback Framework so that true and false positives can be sent.
Future PRs will implement and e2e test False Positive and True positive writebacks
Test Plan
---------
mypy && make_uplaod docker
From UI press true-positive. Look at logs to see that writeback message is enqueued
=> Connect Api to writebacker

hasher-matcher-actioner/.devcontainer/Dockerfile
Summary
---------
Add `less` to the docker image
Test Plan
---------
Rebuilt the container.
=> devcontainers: add less

python-threatexchange/threatexchange/api.py
Summary
---------
After #584 realized there were 2 more edits to pytx3 I needed for writebacks. Would like to add these before I bump the version to 0.0.20 in #585 
Specifically, two changes:
1. Add function to remove a Reaction from a ThreatDescriptor
2. Add a `fields` argument to get_threat_descriptors function
Some context on 2
In writing the Writebacker I need to load the current privacy_groups from our ThreatDescriptor (to see if one needs to be removed). However any app can only see privacy groups for descriptor it owns. Therefore, we cannot ask for this field when we are loading all descriptors for a given indicator (error was thrown) and must make a second call to the api to load these private fields. A cursory look at graph API documentation did not reveal an easy way to only …
=> Edits to pytx3 necessary for writebacker

hasher-matcher-actioner/webapp/src/Api.jsx, hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/ActionPerformerColumns.jsx, hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/ActionPerformerRows.jsx, hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/WebhookActioner.jsx, hasher-matcher-actioner/webapp/src/components/settings/ThreatExchangePrivacyGroupCard.jsx, hasher-matcher-actioner/webapp/src/pages/settings/ActionSettingsTab.jsx
Summary
---------
previous PR: https://github.com/facebook/ThreatExchange/pull/573, https://github.com/facebook/ThreatExchange/pull/581
this PR is to update actions tab to read/create/update/delete action performers from dynamoDB
Test Plan
---------
https://user-images.githubusercontent.com/81996660/118894954-331bc400-b8d3-11eb-9e24-26094c1b95ed.mov
=> actions UI

hasher-matcher-actioner/hmalib/common/actioner_models.py, hasher-matcher-actioner/hmalib/common/content_models.py, hasher-matcher-actioner/hmalib/common/tests/test_content_models.py, hasher-matcher-actioner/hmalib/lambdas/actions/action_performer.py
Summary
---------
Addition to Diff 2/5 of #583 from @eriksendc suggestion
Test Plan
---------
Same as #583
=> [HMA] store action performer as well in action event

hasher-matcher-actioner/webapp/src/Api.jsx, hasher-matcher-actioner/webapp/src/components/settings/ActionRulesTableRow.jsx, hasher-matcher-actioner/webapp/src/pages/settings/ActionRuleSettingsTab.jsx
Summary
---------
This PR wires up the action rules UI to its API. Action rules can now be added, edited and deleted in the UI.
Test Plan
---------
https://user-images.githubusercontent.com/8974354/119040100-00310900-b983-11eb-874d-54abec609cf8.mp4
=> Action Rules UI / API Integration

hasher-matcher-actioner/webapp/src/pages/settings/ThreatExchangeSettingsTab.jsx
Summary
---------
this PR is to change toast position to upper right to sync with other pages
Test Plan
---------
=> change toast position to upper right

hasher-matcher-actioner/scripts/storm_submissions_api
Summary
---------
Quick fix to adjust for changes to submit API made in #617
Test Plan
---------
@schatten tested in locally as did I.
=> hotfix of storm script

hasher-matcher-actioner/terraform/authentication/outputs.tf
Summary
---------
#628 broke tf for those with use_shared_user_pool="True"
Test Plan
---------
`$ terraform -chdir=terraform plan`
=> [hma][tf] hotfix for those using shared user pool

hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_matcher.py, hasher-matcher-actioner/scripts/script_utils.py, hasher-matcher-actioner/scripts/storm_submissions_api
Summary
---------
Based on a patch from @schatten. minor but worth merging before continuing work on the scripts. 
- Slightly changes the `HasherMatcherActionerAPI` submit method interface.
- Make output in `storm_submissions_api` depend on a flag.
- Catch and print request errors
Test Plan
---------
Ran the script live and in parallel.
=> [hma][scripts] basic changes to storm script

hasher-matcher-actioner/scripts/script_utils.py, hasher-matcher-actioner/scripts/set_tf_outputs_in_local_env.sh, hasher-matcher-actioner/scripts/storm_submissions_api, hasher-matcher-actioner/scripts/submit_content_test.py
Summary
---------
Add retry with exponential backoff to submit requests send to the hma instance.  
Test Plan
---------
Manually ran storm at a decent scale and saw that failures were retried.
=> [hma][scripts] Add retry to storm script

hasher-matcher-actioner/webapp/src/pages/settings/ThreatExchangeSettingsTab.jsx
Summary
---------
this PR is to fix the issue that ThreatExchange tab is broken when click sync button. The issue is that we have changed one param name in datasets api, but didn't make all corresponding changes in UI
Test Plan
---------
before fix:
after fix:
=> fix undefined datasets issue

hasher-matcher-actioner/terraform/dashboard/outputs.tf, hasher-matcher-actioner/terraform/main.tf, hasher-matcher-actioner/webapp/src/pages/Dashboard.jsx
Summary
---------
See title. Dashboard is now a part of tf apply as of #681 
Test Plan
---------
=> [hma][ui] Add link to aws dashboard on HMA UI Dashboard Page

hasher-matcher-actioner/webapp/src/components/ContentMatchTable.jsx, hasher-matcher-actioner/webapp/src/components/settings/ThreatExchangePrivacyGroupCard.jsx, hasher-matcher-actioner/webapp/src/pages/settings/ActionRuleSettingsTab.jsx, hasher-matcher-actioner/webapp/src/pages/settings/ActionSettingsTab.jsx, hasher-matcher-actioner/webapp/src/pages/settings/ThreatExchangeSettingsTab.jsx
Summary
---------
No functional changes just wording and description changes
Test Plan
---------
=> Standardize on UI terminology

hasher-matcher-actioner/scripts/get_auth_token, hasher-matcher-actioner/scripts/listener.py, hasher-matcher-actioner/scripts/script_utils.py, hasher-matcher-actioner/scripts/soak_test_system, hasher-matcher-actioner/scripts/submit_content_test.py, hasher-matcher-actioner/terraform/actions/main.tf, hasher-matcher-actioner/terraform/actions/variables.tf, hasher-matcher-actioner/terraform/main.tf, hasher-matcher-actioner/terraform/pdq-signals/main.tf, hasher-matcher-actioner/terraform/pdq-signals/variables.tf, hasher-matcher-actioner/terraform/variables.tf
Summary
---------
In prep for writing a guide to soak testing I wanted to smooth over some of the rougher edges that exists in these scripts.
- Make `scripts/get_auth_token` actually helpful (see test plan and example usage in docstring)
- Have `scripts/submit_content_test.py` and therefore soak tests clean up action configs after they finish.
- Remove listener class from `scripts/submit_content_test.py` because it was only used in soak tests.
- Have `scripts/submit_content_test.py` run a cleaner e2e test (without listener)
- Add `set_sqs_windows_to_min  = true` option for tfvars for much faster testing (otherwise each test is a 2 minute min)
Test Plan
---------
Repeated soak test for listener changes from #690 
`get_auth_token` doesn't need the aws web ui/console now to get a test user. …
=> [hma][script] refactors and increase utility in test scripts

hasher-matcher-actioner/hmalib/common/mocks.py, hasher-matcher-actioner/hmalib/common/writebacker_models.py, hasher-matcher-actioner/hmalib/lambdas/api/tests/test_middleware.py, hasher-matcher-actioner/hmalib/metrics/cloudwatch.py, hasher-matcher-actioner/scripts/gen_fake_cloudwatch_metrics.py, hasher-matcher-actioner/terraform/actions/variables.tf, hasher-matcher-actioner/terraform/datastore/main.tf, hasher-matcher-actioner/webapp/src/components/settings/ThreatExchangePrivacyGroupCard.jsx, hasher-matcher-actioner/webapp/src/utils/NumberUtils.jsx, python-threatexchange/tests/hashing/test_pdq_hasher.py, python-threatexchange/tests/test_api.py
Summary
---------
.
Test Plan
---------
Only comment changes.
=> [hma] add missing Copyright Headers 

hasher-matcher-actioner/hmalib/lambdas/api/datasets_api.py, hasher-matcher-actioner/webapp/.eslintrc.json, hasher-matcher-actioner/webapp/package-lock.json, hasher-matcher-actioner/webapp/package.json, hasher-matcher-actioner/webapp/src/components/HolidaysDatasetInformationBlock.tsx, hasher-matcher-actioner/webapp/src/pages/Settings.jsx, hasher-matcher-actioner/webapp/src/pages/Settings.tsx, hasher-matcher-actioner/webapp/src/pages/settings/ThreatExchangeSettingsTab.tsx
Summary
---------
This PR will do two things:
1. convert ThreatExchangeSettingsTab, HolidaysDatasetInformationBlock, Settings file to tsx file and fix type errors
2. fix the issue that UI will display errors when updating a dataset which has string privacry group id
Future Action
---------
Need to also convert ThreatExchangePrivacyGroupCard to tsx file, but there is a known issue with ion-icon package and typescript, will spend little more time to look into this issue
Test Plan
---------
2. mypy hmalib
4. make docker
5. make upload_docker 
6. terraform apply
7.  test localhost for all test cases on ThreatExchange setting tab
https://user-images.githubusercontent.com/81996660/124833552-5c101b00-df4c-11eb-99f6-2189cab854a4.mov
=> Convert threatexchange settings typescript

hasher-matcher-actioner/terraform/dashboard/main.tf
Various changes to the dashboard have been done as part of the PR. If you keep this description open while you review, you'll find that the changes here are laid out in the same order as the diff.
**Changes across the dashboard**
- Add Titles to the dashboard, so the graph labels are not so long that they get ellipsized
**API Section Updates:**
- Switch from the regular lambda widget to a custom one for API. I want to show the response times in a separate graph.
- Also because the concurrent executions were super-low in scale compared to the number of invocations once we started doing URL only submissions where the response times are fairly low.
- Add an API Response times widget
- In status codes graph, display %age 5xx and 4xx instead of absolute. I expect in production the number of …
=> Various Changes to Cloudwatch Dashboard

hasher-matcher-actioner/requirements-dev.txt, hasher-matcher-actioner/scripts/README.md, hasher-matcher-actioner/scripts/listener.py, hasher-matcher-actioner/scripts/soak_test_system, hasher-matcher-actioner/scripts/submit_content_test.py, hasher-matcher-actioner/scripts/submitter.py
Summary
---------
- First attempt at adding latency stats to the soak test.
- Adds a timestamp to content_id sent by submitter
- When the Listener receives and action request for that content_id it compares it to the current time. 
- While running you can see average latency of most recent 10 requests
- After exiting the soak using `numpy` and `panda` I create a timeseries of latencies by the minute
- As well as appending the record of each submission-time_received pair to a file
- Moves SubmittingThread to its own file Submitter.py
- Laying groundwork to turn Submitter and Listener into Background daemon processes for increased flexibility.
- Added README with soak test basics and example usage.
Test Plan
---------
Went through steps written in the readme (copied here):
```
$ cd hma-dir …
```
=> [hma][scripts] Add latency stats and refactor soak test

.github/workflows/golang-ci.yaml
Summary
---------
Attempt number 1 
Test Plan
---------
Ran commands locally and saw the same error. Not overly familiar with go but this seemed to fix it.
=> fix go CI workflow

.github/workflows/golang-ci.yaml
Summary
--------
Attempt number 2
Test Plan
----------
Ran commands locally and saw the same error. Not overly familiar with go but this seemed to fix it.
=> fix go CI workflow 2

hasher-matcher-actioner/Makefile, hasher-matcher-actioner/scripts/set_tf_outputs_in_local_env.sh, hasher-matcher-actioner/scripts/submit_content_test.py
Summary
---------
I wrote the library in `submit_content_test.py` in a way that it could be used as a basic but quick regression test awhile ago. However it wasn't as user friendly as I'd prefer.
This PR adds help text to the script and makes it callable from `make`. However it is likely users will need to run other commands before hand, did my best to document those as well. 
Test Plan
---------
Right after tf apply:
```
$ make dev_test_instance   
Attempting to run submit_content_test, due to make limitations you may need to run additional commands first.
This simple tests should take a little over 2 minutes to complete (due to sqs timeout).
python3 scripts/submit_content_test.py
Error: Failed to find HMA_API_URL in environ.
Easiest way to add this to your environment is `source …
```
=> [hma][scripts] add dev_test_instance make command

hasher-matcher-actioner/hmalib/common/content_models.py
Summary
---------
`ContentObject` in `content_models.py` does something a little hacky due to limitations in `ADD` [update expression](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.ADD)
I tired to find another way around this change this but the cleanest solution I found was just making it clear why it is there in comments. (Otherwise we would have to query before update for these objects).
Test Plan
---------
Submit test from python code and the UI.
=> [hma] update additional_field placeholder for content object and explain why it exists

hasher-matcher-actioner/webapp/package-lock.json, hasher-matcher-actioner/webapp/package.json
Summary
---------
After all of @BarrettOlson's type scripting work I needed to update my package.json file. This should ensure no one else has to
Test Plan
---------
UI Runs now
=> package lock

hasher-matcher-actioner/hmalib/lambdas/api/matches.py
Summary
---------
MatchesForHashResponse object based it's reply on ThreatExchangeSignalMetadata however (also added to docstring):
ThreatExchangeSignalMetadata is used to store metadata in dynamodb
and handle opinion changes on said signal. However the request this object
responds to only handles directly accessing the index. Because of this
not all fields of the object are relevant or accurate.
This PR removes the irrelevant 'pending_opinion_change' and inaccurate 'updated_at' fields from the reply. 
Unfortunately "updated_at" would required either an indexer refactor or a ddb call (likely both) to be accurate so it is likely worth holding off on such changes until there is a clear use case for it.   
There is a lot of ways to handle this removal, I choose the API layer to keep the …
=> [hma][api] remove fields from MatchesForHashResponse matches

hasher-matcher-actioner/hmalib/common/configs/actioner.py, hasher-matcher-actioner/hmalib/common/configs/evaluator.py, hasher-matcher-actioner/webapp/package-lock.json, hasher-matcher-actioner/webapp/src/Api.tsx, hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/ActionPerformerRows.tsx, hasher-matcher-actioner/webapp/src/components/settings/ActionRuleFormColumns.tsx, hasher-matcher-actioner/webapp/src/components/settings/ActionRulesTableRow.tsx, hasher-matcher-actioner/webapp/src/pages/settings/ActionRuleSettingsTab.tsx, hasher-matcher-actioner/webapp/src/pages/settings/ActionSettingsTab.tsx, hasher-matcher-actioner/webapp/src/pages/settings/ThreatExchangeSettingsTab.tsx
Summary
---------
Add better comments and use of Classes to clearly tie Frontend and backend
Stop using `'0'` as the placeholder for "no action specified" and instead use `''`
also print error messages when saving changes leads to error
Test Plan
---------
Tested in UI that action rules can be created updated and deleted
Tested that Action Rules stay in sync with actions
Tested that if put create action request fails error is output:
Uploading Screen Recording 2021-09-09 at 3.05.10 PM.mov…
=> Refactor ActionRules

hasher-matcher-actioner/CONTRIBUTING.md, hasher-matcher-actioner/hmalib/scripts/cli/main.py, hasher-matcher-actioner/hmalib/scripts/cli/run_api.py
Summary
---------
Could not re-use run_lambda because you'd want the API to keep running and not die after one request is answered.  
Also minor corrections to Correcting.md. 
Test Plan
--------
=> Run API locally + instructions on using the scripts

hasher-matcher-actioner/hmalib/banks/bank_operations.py, hasher-matcher-actioner/hmalib/common/messages/bank.py, hasher-matcher-actioner/hmalib/common/messages/submit.py, hasher-matcher-actioner/hmalib/common/models/bank.py, hasher-matcher-actioner/hmalib/common/models/models_base.py, hasher-matcher-actioner/hmalib/common/models/tests/ddb_test_common.py, hasher-matcher-actioner/hmalib/common/models/tests/test_bank_member_signals_to_process.py, hasher-matcher-actioner/hmalib/common/models/tests/test_pipeline_models.py, hasher-matcher-actioner/hmalib/common/models/tests/test_signal_uniqueness.py, hasher-matcher-actioner/hmalib/hashing/unified_hasher.py, hasher-matcher-actioner/hmalib/lambdas/api/api_root.py, hasher-matcher-actioner/hmalib/lambdas/api/bank.py, hasher-matcher-actioner/hmalib/lambdas/api/tests/test_bank_member_pagination.py, hasher-matcher-actioner/hmalib/lambdas/hashing.py, hasher-matcher-actioner/hmalib/lambdas/matcher.py, hasher-matcher-actioner/terraform/datastore/main.tf, hasher-matcher-actioner/terraform/hasher/main.tf, hasher-matcher-actioner/terraform/hasher/variables.tf, hasher-matcher-actioner/terraform/main.tf
Summary
---------
Tests for the same.  
- add signals to the index - remove signals from the index  
* Defines new message type: `BankSubmissionMessage` 
* Publishes this message to the hashing queue with a presigned_url when a bank member is added 
* The hashing lambda hashes this media into  appropriate signal types and calls `bank_operations.add_bank_member_signal` 
* Removed content_id from ContentSignal class because it was not getting used and would have conflicted with bank submissions. Bank submissions don't have content_Id.  
> Note: Decided to add `bank_operations.add_bank_member_signal` because it is possible that partners may add hashes directly to bank in case they delete the original media because of legal requirements.  
Test Plan
---------
Deployed webapp and lambdas to my …
=> Hash and write BankMemberSignal objects when a member is added

hasher-matcher-actioner/hmalib/common/models/bank.py, hasher-matcher-actioner/hmalib/lambdas/api/bank.py, hasher-matcher-actioner/terraform/datastore/main.tf, hasher-matcher-actioner/webapp/src/forms/BankDetailsForm.tsx, hasher-matcher-actioner/webapp/src/forms/BankMemberForm.tsx, hasher-matcher-actioner/webapp/src/pages/bank-management/ViewBank.tsx, hasher-matcher-actioner/webapp/src/styles/_app.scss, hasher-matcher-actioner/webapp/src/styles/_themed-form.scss
Summary
---------
* Ignore the branch name please. :) 
- add api to fetch the the bank member + its signals  
Test Plan
---------
Usual python stuff.
```
```
Also, tested the APIs after adding the entities.
=> [hma][api] API to get bank_members with signals

pdq/cpp/index/mih.h, tmk/cpp/hashing/bufferhashers.cpp, tmk/cpp/raster/timeresamplers.h
Summary
---------
include <stdexcept> where necessary
Test Plan
---------
ran `make clean; make`, which compiles successfully
=> include <stdexcept> where necessary

hasher-matcher-actioner/terraform/actions/variables.tf, hasher-matcher-actioner/terraform/api/main.tf, hasher-matcher-actioner/terraform/api/variables.tf, hasher-matcher-actioner/terraform/counters/variables.tf, hasher-matcher-actioner/terraform/dashboard/main.tf, hasher-matcher-actioner/terraform/dashboard/variables.tf, hasher-matcher-actioner/terraform/fetcher/variables.tf, hasher-matcher-actioner/terraform/hasher/variables.tf, hasher-matcher-actioner/terraform/hashing-data/variables.tf, hasher-matcher-actioner/terraform/indexer/variables.tf, hasher-matcher-actioner/terraform/matcher/variables.tf
Summary
---
instead infer from 'data.aws_region' where required
Test Plan
---
```
$ terraform apply
No changes. Your infrastructure matches the configuration.
```
=> Remove usage of region as a variable,

hasher-matcher-actioner/Makefile, hasher-matcher-actioner/README.md, hasher-matcher-actioner/hmalib/lambdas/api/api_root.py, hasher-matcher-actioner/setup.py
Summary
---------
0.0.24 unfortunately broke api_root.
Test Plan
---------
```
terraform -chdir=terraform apply
make dev_test_instance
```
=> [hma] update hmalib setup.py to 0.0.25 of python-threatexchange to fix import error 

hasher-matcher-actioner/hmalib/hashing/unified_hasher.py, hasher-matcher-actioner/hmalib/lambdas/hashing.py
Summary
---------
see title.
Test Plan
---------
Before:
submit to HMA with values that will error (bad url or file format)
see that it is being retried for no reason.
After:
submit to HMA with values that will error (bad url or file format)
see that error is logged once but not repeated and other hashes are sent to matcher.
=> [hma] add try-catch on hasher to avoid pointless tries

hasher-matcher-actioner/hmalib/common/models/count.py
Summary
---------
title.
Test Plan
---------
```
make dev_apply_with_newest_docker_image
export HMA_TOKEN='<redacted>'
make dev_test_instance 
```
=> [hma][counts] remove random 4 in SKEY_PREFIX for ParameterizedCount

python-threatexchange/threatexchange/signal_type/tests/test_tlsh_hash_and_match.py, python-threatexchange/threatexchange/signal_type/tlsh_pdf.py, python-threatexchange/threatexchange/signal_type/url_md5.py
Summary
---------
Remove fake state hack from `signal_type/tlsh_pdf.py` and update INDICATOR_TYPE + tests. once the sample data exists this should allow for tlsh hash matching on those signals
and updated var name to make mypy happy in `url_md5.py`
Test Plan
---------
`pytest`
=> [pytx][minor] clean up in `signal_type/tlsh_pdf.py` and `signal_type/url_md5.py`

hasher-matcher-actioner/.devcontainer/post-create
I only noticed some of the CRLF problems from reading the logs. I think doing this will properly fail the update
=> post-create will properly crash for issues

hasher-matcher-actioner/.devcontainer/.gitignore
Summary
---------
Wasn't sure if I could do it at the same time as moving, so here you go
Test Plan
---------
I didn't
=> Ignore devcontainer.json

python-threatexchange/mypy.ini
Summary
---------
This doesn't reproduce locally, but maybe this will fix it.
Test Plan
---------
Let's see what serverside lint says.
=> [py-tex] Attempt to fix urllib typing error

python-threatexchange/threatexchange/fetcher/collab_config.py, python-threatexchange/threatexchange/fetcher/fetch_api.py, python-threatexchange/threatexchange/fetcher/fetch_state.py
Summary
---------
We need to specialize collabconfig in order to give specific instructions to the fetcher, so go ahead and add an interface for that (even though it's duplicated).
Also add "Base" to the name of a few classes that are expected to be overridden to help with that,
Also minor delints in other files.
Test Plan
---------
Lets see if my local linter works!
=> [py-te][fetcher] collab config

hasher-matcher-actioner/hmalib/banks/bank_operations.py, hasher-matcher-actioner/hmalib/common/models/bank.py, hasher-matcher-actioner/hmalib/common/models/models_base.py, hasher-matcher-actioner/hmalib/lambdas/api/bank.py, hasher-matcher-actioner/hmalib/lambdas/matcher.py, hasher-matcher-actioner/hmalib/matchers/matchers_base.py, hasher-matcher-actioner/hmalib/matchers/tests/test_match_filters.py, hasher-matcher-actioner/webapp/src/Api.tsx, hasher-matcher-actioner/webapp/src/components/PillBox.tsx, hasher-matcher-actioner/webapp/src/forms/BankDetailsForm.tsx, hasher-matcher-actioner/webapp/src/forms/BankMemberForm.tsx, hasher-matcher-actioner/webapp/src/messages/BankMessages.tsx, hasher-matcher-actioner/webapp/src/pages/bank-management/AddBankMemberModal.tsx, hasher-matcher-actioner/webapp/src/pages/bank-management/AddBankModal.tsx, hasher-matcher-actioner/webapp/src/pages/bank-management/ViewBank.tsx, hasher-matcher-actioner/webapp/src/pages/bank-management/ViewBankMember.tsx, hasher-matcher-actioner/webapp/src/styles/_pill-box.scss
Summary
---------
- Also add an update bank-member API. - Includes breaking updates to API.tsx. (Fixed in next commit)  
Test Plan
---------
mypy, black,
https://user-images.githubusercontent.com/217056/150912062-76335446-36c5-4905-adc5-129d229f2502.mp4
1. Created a new bank with tags
2. Created a new bank without tags
3. Edited a bank's tags (delete, add)
1. Created a new bank-member with tags
2. Created a new bank-member without tags
3. Edited a bank-member's tags (delete, add)
Added a tag `teacup` to a bank_member. The resulting match message from submitting this image to HMA was found to have the correct `ClassificationLabel`:
```
[INFO]	2022-01-25T05:20:57.863Z	d126a4b6-611d-5239-9333-fedfebd2effa	Evaluating match_message: MatchMessage(content_key='d1bf7cef-0d79-4c93-8820-61c7bfa6ee70 …
```
=> [HMA] Support adding and editing tags for Banks and BankMembers

hasher-matcher-actioner/webapp/src/Sidebar.tsx, hasher-matcher-actioner/webapp/src/pages/bank-management/ViewAllBanks.tsx
=> Banks launch

hasher-matcher-actioner/webapp/src/Api.tsx
Summary
---------
One field was missed from my requested rename. 
Test Plan
---------
Before: cannot create new banks on UI
After: can create new banks on UI
=> [hma][ui][bugfix] update create new bank request field to work

hasher-matcher-actioner/webapp/package-lock.json
Summary
---------
#927 took issue with our `package-lock.json` figured I would address a few more packages as well
Test Plan
---------
`npm install`
`npm audit fix` # to address any easy fixes
`npm start` # to make sure the webapp still builds
=> [hma][webapp] update package-lock.json to address minor vulnerability

python-threatexchange/README.md
A coming soon section (and a new badge)
Summary
---------
Just a tiny update to readme for incoming changes.
Test Plan
---------
View in preview
=> [py-tx] README.md updates

python-threatexchange/threatexchange/cli/cli_config.py, python-threatexchange/threatexchange/cli/config_cmd.py, python-threatexchange/threatexchange/cli/main.py, python-threatexchange/threatexchange/extensions/README.md, python-threatexchange/threatexchange/extensions/__init__.py, python-threatexchange/threatexchange/extensions/manifest.py, python-threatexchange/threatexchange/extensions/text_tlsh/__init__.py, python-threatexchange/threatexchange/extensions/text_tlsh/tests/test_tlsh_hash_and_match.py, python-threatexchange/threatexchange/extensions/text_tlsh/text_tlsh.py, python-threatexchange/threatexchange/signal_type/tests/test_hash_from_x.py
Summary
---------
This PR proposes and implements an approach for grouping extensions of the `threatexchange` library ( #953). The full approach is described in the README, but tl;dr, put this in your favorite module:
```
TX_MANIFEST = ThreatExchangeExtensionManifest(
signal_types=(FooSignal, BarSignal),
content_types=(BazContent,),
apis=(ZedAPI,)
)
```
Test Plan
---------
Until I finish e2e testing, there might not be a super easy unittest path. Until then, here's some CLI things
```
$ threatexchange hash text -S text_tlsh -T 'Hello this is a very long string with more stuff even more stuff why do you need so many bytes' 
usage: threatexchange hash [-h] [--signal-type {pdq,video_md5,raw_text,url,url_md5,trend_query}] [--as-text] {photo,video,url,text} content [content ...]
threatexchange …
```
=> [py-tx] Approach for extensions

python-threatexchange/threatexchange/extensions/README.md
=> Fixup extensions README.md

README.md
Summary
---------
1. Split up descriptions of projects and the description of the public API
2. Update to python-threatexchange's 
3. Re-order the sections
Test Plan
---------
Look at it with preview
=> Update to root README.md

python-threatexchange/threatexchange/signal_type/raw_text.py, python-threatexchange/threatexchange/signal_type/tests/__init__.py, python-threatexchange/threatexchange/signal_type/tests/signal_type_test_helper.py, python-threatexchange/threatexchange/signal_type/tests/test_raw_text.py
Summary
---------
I noticed this bug. Instead of fixing it like a normal person, I also wasted several hours making you a testing framework of questionable usefulness. Please enjoy responsibly, if at all. 
Test Plan
---------
mypy and py.test
=> [pytx] Fix text matching, add a stupid framework for testing signal types

python-threatexchange/threatexchange/signal_type/tests/signal_type_test_helper.py
Summary
---------
I failed to correctly merge it my upstream change, so here's a new diff. Feel free to just merge directly if it looks good.
Test Plan
---------
lololol
=> [pytx] Barret's requested doc changes

pdq/video/README.md
Add basic description of vPDQ algorithm in README.
=> README for video PDQ

README.md
Summary
---------
Tiny update to root README to describe project.
Test Plan
---------
Viewed
=> Update root README for vPDQ

python-threatexchange/threatexchange/stopncii/api.py, python-threatexchange/threatexchange/stopncii/tests/test_api.py
Summary
---------
1. Handle multiple function keys
2. Correctly set params for get
3. pageSize to args
Test Plan
---------
```
$ python
>>> from threatexchange.stopncii.api import StopNCIIAPI
>>> api = StopNCIIAPI(sub_key, fetch_function_key)
>>> api.fetch_hashes(page_size=2)
```
=> [py-tx] Minor fixes to StopNCII API

hasher-matcher-actioner/hmalib/lambdas/api/api_root.py, hasher-matcher-actioner/hmalib/lambdas/api/lcc.py, hasher-matcher-actioner/hmalib/scripts/cli/run_api.py
=> Setup API implementation for interval squashing

python-threatexchange/threatexchange/cli/hash_cmd.py, python-threatexchange/threatexchange/cli/helpers.py, python-threatexchange/threatexchange/cli/main.py, python-threatexchange/threatexchange/cli/match_cmd.py, python-threatexchange/threatexchange/cli/tests/e2e_test_helper.py, python-threatexchange/threatexchange/cli/tests/hash_cmd_test.py, python-threatexchange/threatexchange/cli/tests/match_cmd_test.py, python-threatexchange/threatexchange/cli/tests/sample_data_e2e_test.py, python-threatexchange/threatexchange/signal_type/md5.py
Summary
---------
This is similar to #984, except on the match command instead. I think I wrote it in a way that should be quick to port later.
Stacked on #996
Test Plan
---------
updated unittests
=> [pytx][stacked] threatexchange match input update

python-threatexchange/threatexchange/cli/main.py, python-threatexchange/threatexchange/ncmec/__init__.py, python-threatexchange/threatexchange/ncmec/hash_api.py, python-threatexchange/threatexchange/ncmec/tests/test_hash_api.py
Summary
---------
An implementation for the NCMEC hash API from reading https://report.cybertip.org/hashsharing/v2
Test Plan
---------
I pasted some of the examples from the documentation into the test, similar to what I did for StopNCII.
=> [py-tx] NCMEC API. GET status and entries

hasher-matcher-actioner/CONTRIBUTING.md
Summary
---------
1. Moved config files to terraform subsection
2. Added VPC limit error
Test Plan
---------
N/A
=> Minor update to HMA Contributing.md

hasher-matcher-actioner/hmalib/indexers/lcc.py, hasher-matcher-actioner/hmalib/indexers/tests/test_lcc_indexer.py, hasher-matcher-actioner/hmalib/metrics/__init__.py, hasher-matcher-actioner/terraform/lcc_custodian/main.tf
Summary
---------
Add new dashboard with 2 metrics following from the LCC API
=> Dashboard support for LCC and Metrics for gathering data

python-threatexchange/threatexchange/cli/config_cmd.py, python-threatexchange/threatexchange/cli/main.py, python-threatexchange/threatexchange/fetcher/apis/fb_threatexchange_api.py, python-threatexchange/threatexchange/fetcher/apis/file_api.py, python-threatexchange/threatexchange/fetcher/apis/static_sample.py, python-threatexchange/threatexchange/fetcher/apis/stop_ncii_api.py, python-threatexchange/threatexchange/fetcher/fetch_api.py, python-threatexchange/threatexchange/meta.py
Summary
---------
A tiny bit of cleanup while I decide what to do with the Delta/Update problem that implementing the NCMEC API has given me.
Test Plan
---------
```
ThreatExchange/python-threatexchange$ python -m mypy threatexchange
```
(Though I always get confused about which version we are using in production)
=> [pytx] Apply generics to SignalExchangeAPI

.github/workflows/python-threatexchange-ci.yaml, .github/workflows/python-threatexchange-release.yaml
Summary
---------
3.6 is no longer supported. Let's no longer support in on py-tx
Test Plan
---------
How do I test this?
=> [pytx] No more 3.6 support

hasher-matcher-actioner/CONTRIBUTING.md
=> Update HMA CONTRIBUTING.md for devcontainer help

pdq/cpp/common/pdqhashtypes.cpp, pdq/cpp/common/pdqhashtypes.h
Summary
---------
Add a standalone hamming distance function for VPDQ implementation.
Test Plan
---------
Wouldn't affect pdq usage.
=> [VPDQ] Add standalone function

python-threatexchange/README.md
Big-ol rewrite. I didn't plug it into a text editor, so probably a ton of grammars and speeling errors
Mostly fixes #985
=> [pytx] README.md rewrite for 1.0

python-threatexchange/README.md
Had some time at a coffee shop, so add some more to the readme
Summary
---------
Add a general overview, and some shortcuts for connecting to exchanges.
Test Plan
---------
Lookit it
=> [pytx] Incremental README improvements

python-threatexchange/threatexchange/cli/match_cmd.py
Summary
---------
Continuing with rewriting all the helps, now do match.
Test Plan
---------
```
$ threatexchange match --help
usage: threatexchange match [-h] [--only-signal ONLY_SIGNAL] [--hashes] [--show-false-positives] [--hide-disputed] content_type ...
Match content to fetched signals
Runs the given content through applicable SignalTypes, and compare it
with previously fetched signals stored in the index files. Only
SignalTypes supported by the CLI and your extensions can be matched,
even if you can fetch them. Any matches will be printed to screen.
You can pass in data to the command in a few different ways:
```
$ threatexchange match photo my_photo.jpg
$ echo This is my cool text | threatexchange match text -
$ threatexchange match text -- This is my cool text
```
The output of …
```
=> [pytx][cli] match --help rewrite

python-threatexchange/threatexchange/cli/label_cmd.py
Summary
---------
Continuing onward, rewrite the help for the label command. This is extra challenging because this command basically doesn't work yet! 
Also some half-hearted, un-tested cleanups of the command itself.
I actually considered hiding this command instead, and saving it for a future version. What do you think?
Test Plan
---------
```
$ threatexchange label --help
usage: threatexchange label [-h] [--labels CSV | --seen | --false-positive | --true-positive] [--only-signals ONLY_SIGNALS [ONLY_SIGNALS ...] | --as-hash SIGNAL_TYPE] collab content_type ...
[WIP] Label signals and content for sharing.
Warning! This command is still under construction, and is not yet stable.
Please open an issue at https://github.com/facebook/ThreatExchange/issues
if you need the development team to …
```
=> [pytx][cli] label --help rewrite

python-threatexchange/threatexchange/fetcher/apis/fb_threatexchange_api.py
Summary
---------
I did this intentionally at one point, but now I don't like it. Do all our breaking changes now I suppose.
Test Plan
---------
py.test
=> [pytx] fb_threat_exchage => fb_threatexchange

python-threatexchange/threatexchange/cli/config_cmd.py
Summary
---------
I incorrectly resolved a conflict in a previous PR
Test Plan
---------
$ tx config signal
=> [pytx][cli] Fix bad conflict resolution

vpdq/python/__init__.py
Summary
---------
This empty file apparently creates an un-checkoutable file that always looks modified to my index, and no amounts of resets, unstages, or checkouts seems to fix it.
Making it not a 0 byte file seems to work though.
Test Plan
---------
No longer shows as a missing file
=> [vpdq] Empty init file confuses git

pdq/README.md
Summary
---------
Help make these easier to find, give shoutouts.
Test Plan
---------
View in preview
=> [pdq][README] References to third party impls

.github/workflows/python-threatexchange-ci.yaml, .github/workflows/python-threatexchange-release.yaml, python-threatexchange/threatexchange/cli/config_cmd.py
Summary
---------
As voted on, unlock support for git origin and walrus `:=`
Test Plan
---------
mypy
=> [py-tx] Remove support for 3.7, now to 3.8

python-threatexchange/threatexchange/cli/config_cmd.py, python-threatexchange/threatexchange/exchanges/impl/ncmec_api.py
Summary
---------
Requested by a partner using NCMEC. This was originally "only_owner_ids" which died when I removed a lot of the default common arguments for collab config. Now we bring it back in its original form for NCMEC.
Provides a way to only accept entries from certain partners. The remainder are filtered as thought they do not exist.
Changing this value invalidates your old data, since you may have failed to previously fetch something. I can think of a few solutions:
1. Something that detects that you changed your config, and invalidates your old state
2. Move the collab_config into the signature of Naive convert. This seems okay, but will create a burden on future implementations like HMA, and also encourages over-fetching
3. Something else
Test Plan
---------
Pending, may send …
=> [pytx][ncmec] esp ID filter

python-threatexchange/threatexchange/exchanges/impl/fb_threatexchange_api.py
Summary
---------
This feature isn't implemented, so hide it
Test Plan
---------
mypy, py.test
=> [pytx] Disable alternative tokens for now

python-threatexchange/threatexchange/cli/command_base.py, python-threatexchange/threatexchange/cli/tests/fake_extension.py, python-threatexchange/threatexchange/exchanges/clients/stopncii/api.py, python-threatexchange/threatexchange/extensions/pdq_ocr/pdq_ocr.py, python-threatexchange/threatexchange/extensions/tlsh/text_tlsh.py, python-threatexchange/threatexchange/extensions/vpdq/video_vpdq.py, python-threatexchange/threatexchange/signal_type/md5.py, python-threatexchange/threatexchange/signal_type/raw_text.py, python-threatexchange/threatexchange/signal_type/signal_base.py, python-threatexchange/threatexchange/signal_type/trend_query.py, python-threatexchange/threatexchange/signal_type/url.py, python-threatexchange/threatexchange/signal_type/url_md5.py
not change to logic `self` -> `cls` for @classmethod args
=> [pytx][style] @classmethod should use cls not self

python-threatexchange/threatexchange/extensions/vpdq/vpdq_index.py, python-threatexchange/threatexchange/signal_type/index.py, python-threatexchange/threatexchange/signal_type/pdq_index.py, python-threatexchange/threatexchange/signal_type/signal_base.py, python-threatexchange/threatexchange/signal_type/trend_query.py
Summary
---------
This interface doesn't add much, let's nuke it.
Test Plan
---------
=> [pytx] Merge PickledSignalTypeIndex to Base

python-threatexchange/threatexchange/cli/tests/fake_extension.py, python-threatexchange/threatexchange/signal_type/md5.py, python-threatexchange/threatexchange/signal_type/pdq.py, python-threatexchange/threatexchange/signal_type/signal_base.py, python-threatexchange/threatexchange/signal_type/url.py, python-threatexchange/threatexchange/signal_type/url_md5.py
Summary
---------
A better version of #1093, just make it required
Test Plan
---------
=> [pytx] Make SignalIndex required

python-threatexchange/threatexchange/cli/cli_config.py, python-threatexchange/threatexchange/cli/config_cmd.py, python-threatexchange/threatexchange/cli/fetch_cmd.py, python-threatexchange/threatexchange/cli/main.py, python-threatexchange/threatexchange/common.py, python-threatexchange/threatexchange/exchanges/collab_config.py, python-threatexchange/threatexchange/exchanges/impl/tests/test_ncmec.py, python-threatexchange/threatexchange/exchanges/impl/tests/test_stopncii.py, python-threatexchange/threatexchange/exchanges/signal_exchange_api.py, python-threatexchange/threatexchange/interface_validation.py, python-threatexchange/threatexchange/signal_type/signal_base.py, python-threatexchange/threatexchange/type_mapping.py
Summary
---------
I didn't like this name, now I like it marginally more.
Test Plan
---------
mypy & py.test
=> [pytx] Rename meta.py => type_mapping.py

python-threatexchange/README.md
Summary
---------
Now in test repo, so that's how to find it.
Test Plan
---------
Ran command in devcontainer (after uninstalling hmalib with conflicting version, and local version)
=> [pytx] Test version installation

python-threatexchange/tests/hashing/test_pdq_utils.py, python-threatexchange/tests/hashing/utils.py, python-threatexchange/threatexchange/hashing/pdq_utils.py, python-threatexchange/threatexchange/signal_type/pdq.py
Summary
---------
Implement zero pdqHash, random pdqHash, similar pdqHash and validate_signal_str in pdq signal. These functions are created for future VPDQ benchmark. Create corresponding tests.
Test Plan
---------
unittest
=> [pytx] Add pdq utils and tests

python-threatexchange/README.md, python-threatexchange/threatexchange/cli/label_cmd.py, python-threatexchange/threatexchange/cli/match_cmd.py, python-threatexchange/threatexchange/cli/tests/config_cmd_extension_test.py, python-threatexchange/threatexchange/cli/tests/dataset_cmd_test.py, python-threatexchange/threatexchange/cli/tests/match_cmd_test.py, python-threatexchange/threatexchange/cli/tests/sample_data_e2e_test.py, python-threatexchange/threatexchange/exchanges/fetch_state.py, python-threatexchange/threatexchange/exchanges/impl/fb_threatexchange_api.py, python-threatexchange/threatexchange/exchanges/impl/file_api.py, python-threatexchange/threatexchange/exchanges/impl/ncmec_api.py, python-threatexchange/threatexchange/exchanges/impl/stop_ncii_api.py, python-threatexchange/threatexchange/exchanges/impl/tests/test_stopncii.py, python-threatexchange/threatexchange/exchanges/signal_exchange_api.py, python-threatexchange/threatexchange/exchanges/tests/test_state.py
Summary
---------
Maybe the outcome of the post titled "Open Source Naming Conventions for False Positives and Others". I don't like any of the names, and we are going to see these a whole lot (i.e. output of match command). 
It's important that the names make sense or at least aren't nonsensical
Test Plan
---------
Pending
=> [py-tx] New Names for SignalOpinionCategory

python-threatexchange/README.md
Who doesn't like badges?
Summary
---------
1. build status
2. pypy version
3. pypy download
Test Plan
---------
Viewed
=> [pytx][README] Add moar badges

python-threatexchange/threatexchange/cli/config_cmd.py, python-threatexchange/threatexchange/cli/tests/config_cmd_collabs_test.py, python-threatexchange/threatexchange/exchanges/clients/ncmec/hash_api.py, python-threatexchange/threatexchange/exchanges/clients/ncmec/tests/test_hash_api.py, python-threatexchange/threatexchange/exchanges/impl/ncmec_api.py, python-threatexchange/threatexchange/exchanges/impl/tests/test_ncmec.py, python-threatexchange/threatexchange/extensions/vpdq/tests/test_vpdq_hash_and_match.py
Summary
---------
1. Environment was not being set by the collab config. Ironically, it's because of the same bug copy pasted from ThreatExchange
2. You can't edit ncmec configs due to a strange combination of conditions.
Test Plan
---------
regression test for 2, mypy & py.test
=> [pytx][ncmec] Fix a few bugs with NCMEC settings

python-threatexchange/threatexchange/cli/label_cmd.py, python-threatexchange/threatexchange/exchanges/impl/fb_threatexchange_api.py, python-threatexchange/threatexchange/exchanges/signal_exchange_api.py
Summary
---------
Liberally apply YAGNI: You Ain't Gonna Need it
These interfaces are not meaningfully implemented, so delete them.
Remove the equivalents from the label command.
Test Plan
---------
=> [pytx] Remove unimplemented interfaces

python-threatexchange/README.md
1. More explanation of basic flow, define collaborations earlier
2. Explainers for how to setup various APIs
3. More details on version compatibility
=> [pytx][README] Updates from bug bash

python-threatexchange/threatexchange/extensions/vpdq/README.md
Summary
---------
A readme describes how FAISS works with vPDQ and links to vPDQ algorithm in the repo.
=> [vPDQ] Create pytx/extension/vpdq/README.md

python-threatexchange/CONTRIBUTING.md
More information on expectations for testing, typing, and pull requests
=> [py-tx] CONTRIBUTING.MD updates

python-threatexchange/threatexchange/cli/tests/fake_extension.py, python-threatexchange/threatexchange/exchanges/helpers.py, python-threatexchange/threatexchange/exchanges/impl/fb_threatexchange_api.py, python-threatexchange/threatexchange/exchanges/impl/ncmec_api.py, python-threatexchange/threatexchange/exchanges/impl/tests/test_ncmec.py, python-threatexchange/threatexchange/exchanges/signal_exchange_api.py, python-threatexchange/threatexchange/exchanges/tests/test_state.py
Summary
---------
The implementation of this feature seems to have disappeared after being added in #1079,  #1118 looks like it removed it by accident, and without testing it was missed.
Test Plan
---------
Added a test to try and catch regressions.
=> [pytx][ncmec][stacked] Fix only esp ids

python-threatexchange/CONTRIBUTING.md
Pasted into Word, hit F7 and just let it go to town
=> [pytx] Grammar/spelling pass in CONTRIBUTING.md

python-threatexchange/threatexchange/cli/fetch_cmd.py
Summary
---------
Found this useful while debugging
Test Plan
---------
```
threatexchange -v fetch
```
TODO: Add the example logging
=> [pytx] Slightly more logging for time

.github/workflows/vpdq-ci-python.yaml, vpdq/cpp/regtest.py, vpdq/python/tests/test_util.py, vpdq/python/tests/test_vpdq_hash.py
Summary
---------
Add github work flow for vpdq python library, since now it can be easily locally installed through vpdq-release.py script. Adjust test parameters with CPP github workflow.
Test Plan
---------
github workflow
=> [VPDQ] Add python test github workflow and clean up test

python-threatexchange/README.md
=> [pytx] Remove Refactor notice from README.md

python-threatexchange/threatexchange/exchanges/impl/ncmec_api.py, python-threatexchange/threatexchange/exchanges/tests/test_state_compatibility.py
Summary
---------
A bad merge deleted the pickle migration :'( 
Add a regression test.
This highlights the need for a way to detect this automatically - these are bad bugs when they happen.
Test Plan
---------
regression test
=> [pytx] Fix ncmec compat bug from bad merge from #1096

python-threatexchange/threatexchange/exchanges/clients/ncmec/hash_api.py
Summary
---------
This can be useful for reference, and as an alternative to just going to the endpoint. 
Test Plan
---------
Called manually with our credentials on NGO database
=> [pytx][ncmec] Add members endpoint

python-threatexchange/threatexchange/extensions/README.md
=> [py-tx] Extensions README for vPDQ

python-threatexchange/threatexchange/extensions/README.md
Paste into word and check spelling, small word changes
=> [py-tx] Extensions README speels and small tweaks

python-threatexchange/threatexchange/exchanges/clients/stopncii/api.py, python-threatexchange/threatexchange/exchanges/clients/stopncii/tests/test_api.py
Summary
---------
Followup from #1212
Test Plan
---------
lets see if CI passes
=> [pytx] Black format

hasher-matcher-actioner/.devcontainer/devcontainer.json, hasher-matcher-actioner/hmalib/fetching/fetcher.py, hasher-matcher-actioner/hmalib/fetching/tests/test_fetcher_and_bank_store.py
As in title.
Test Plan
---
CI Passes.
=> fix botched merge conflict resolution

hasher-matcher-actioner/README.md
Summary
---------
Fix minor typos in HMA readme file
=> fix minor typos in README

python-threatexchange/README.md
Summary
---------
https://github.com/badges/shields/issues/8671
Test Plan
---------
Viewed in preview, rendered a failing build (which it is)
=> [pytx] Fix build badge (without fixing build)

hasher-matcher-actioner/terraform/migrations/README.md
Summary
---------
In the title
=> Create README for migrations

hasher-matcher-actioner/README.md
Refer to newsroom post, slight change to summary and link to wiki.
=> Update HMA Readme

python-threatexchange/threatexchange/exchanges/signal_exchange_api.py
Summary
---------
Some comment updates explaining the storage requirements of the API interfaces before I start messing with them.
Test Plan
---------
Let's see with CI says
=> [pytx] Comment updates signal_exchange_api

python-threatexchange/threatexchange/exchanges/impl/fb_threatexchange_api.py
Summary
---------
Tiny cleanup of some unused things while I'm in the area.
Test Plan
---------
mypy
py.test
=> [py-tx][fb_tx] Remove some unused stuff

hasher-matcher-actioner/CONTRIBUTING.md
As a hint to wandering meta employees
=> [hma] Update CONTRIBUTING for vscode install

.github/workflows/python-threatexchange-ci.yaml
Summary
---------
Title
Test Plan
---------
Lets see what GH actions say
=> [pytx][ci] Update 3.8 to 3.11 for lint

python-threatexchange/setup.py
Summary
---------
To save those precious keystrokes
Test Plan
---------
`tx -h` - it works
=> Define 'tx' as additional CLI entry point

python-threatexchange/CONTRIBUTING.md
Add technical details for dev environment setup to accelerate contributor onboarding
=> [pytx] Add dev environment setup guidelines to CONTRIBUTING.md

open-media-match/.devcontainer/Dockerfile, open-media-match/.devcontainer/devcontainer.json, open-media-match/Dockerfile, open-media-match/README.md, open-media-match/pyproject.toml, open-media-match/src/OpenMediaMatch/__init__.py, open-media-match/src/OpenMediaMatch/app.py
Summary
---------
Create Open Media Match project skeleton
=> Create Open Media Match project skeleton

open-media-match/.devcontainer/Dockerfile, open-media-match/.devcontainer/devcontainer.json, open-media-match/.devcontainer/docker-compose.yaml, open-media-match/.devcontainer/omm_config.py, open-media-match/CONTRIBUTING.md, open-media-match/src/OpenMediaMatch/__init__.py
Summary
---------
Switch the devcontainer config to use docker-compose to bring up a Postgres container in addition to the Flask app container.
Test Plan
---------
Rebuild dev container environment in VSCode
=> Add Postgres to dev environment

vpdq/README.md
Just a quick tweak looking at #1346
=> [vpdq] README.md to reference mac/linux for binding

README.md
=> Update Root README.md to remove "coming soon" for vPDQ

open-media-match/src/OpenMediaMatch/storage/default.py, open-media-match/src/OpenMediaMatch/storage/interface.py, open-media-match/src/OpenMediaMatch/storage/mocked.py
Summary
---------
Run Black formatter against main
Test Plan
---------
CI
=> [omm] fix formatting

open-media-match/.devcontainer/devcontainer.json
Summary
---------
Install mypy and toml extensions, and delete some config items that were deprecated and redundant. This eliminates some of the noise from VSCode upon opening the project and building the dev container.
Test Plan
---------
Rebuild the devcontainer and watch out for annoying popups
=> [omm] Tidy up vscode devcontainer.json

open-media-match/pyproject.toml
Summary
---------
Whoops, should've caught this in https://github.com/facebook/ThreatExchange/pull/1355
Test Plan
---------
`black ./src`
=> [omm] Add requests package to pyproject.toml

open-media-match/src/OpenMediaMatch/background_tasks/fetcher.py, open-media-match/src/OpenMediaMatch/storage/interface.py, open-media-match/src/OpenMediaMatch/storage/mocked.py
Summary
---------
This started as an attempt to add background tasks, but then I backed away from it when I started reading things that seemed to say that it wasn't going to be possible in the normal server run.
Instead this turned into fetch interfaces, and a place where someone can manually trigger a fetch from the CLI in the near future.
Test Plan
---------
mypy
=> [omm] Fetch interfaces

python-threatexchange/threatexchange/utils/dataclass_json.py
Summary
---------
Used in #1376
Test Plan
---------
Lets see what CI says
=> [pytx] Expose dataclass_json asdict

open-media-match/CONTRIBUTING.md
Add Doug's note on migrations.
=> [omm] CONTRIBUTING.md

open-media-match/src/OpenMediaMatch/app.py, open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/database.py, open-media-match/src/OpenMediaMatch/storage/default.py, open-media-match/src/OpenMediaMatch/storage/interface.py, open-media-match/src/OpenMediaMatch/storage/mocked.py, open-media-match/src/OpenMediaMatch/tests/test_api.py, open-media-match/src/OpenMediaMatch/tests/utils.py, open-media-match/src/OpenMediaMatch/utils.py
Summary
---------
Twidding those bits. Thought it would be useful for the request to also send back the value that was created, to show defaults.
Test Plan
---------
New unittest
=> [omm] Even more bank api updates

open-media-match/src/OpenMediaMatch/database.py, open-media-match/src/OpenMediaMatch/tests/test_database.py, open-media-match/src/OpenMediaMatch/tests/utils.py
Summary
---------
Here's a simple workaround for storage these huge files in postgres, though it's unclear if this is what we want to do long-term. 
Test Plan
---------
Added a simple test for serialize/deserialize.
=> [omm] signal index table

open-media-match/src/OpenMediaMatch/blueprints/curation.py
Summary
---------
Starting to go down the api list
Test Plan
---------
```
$ curl -d '{"name":"TEST_BANK_2"}' -H "Content-Type: application/json" -H "Accept: application/json" -X POST localhost:5000/c/bank/TEST_BANK/content
{
"id": 1234,
"message": "TODO: this is a fake implementation!",
"signals": {
}
}
```
=> [omm] Fake add content api

open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/database.py, open-media-match/src/OpenMediaMatch/storage/interface.py, open-media-match/src/OpenMediaMatch/tests/test_database.py
Summary
---------
More scaffolding work, porting more over from #1374
Test Plan
---------
mypy . && py.test
=> [omm] fetching / exchange apis

open-media-match/src/OpenMediaMatch/database.py, open-media-match/src/OpenMediaMatch/tests/test_database.py
Summary
---------
Change ContentSignal to not have its own id and just have a composite pkey
Test Plan
---------
Added unittest
=> [omm] Test storing / retrieving signal content

open-media-match/src/OpenMediaMatch/blueprints/curation.py
Summary
---------
Add some simple crud (mostly unimplemented) for the content/signal types.
Test Plan
---------
Curl the two
=> [omm] apis for signal and content type

open-media-match/CONTRIBUTING.md
Summary
---------
Test Plan
---------
=> fix: change __init__.py to app.py in hello world instructions

open-media-match/.devcontainer/startup.sh, open-media-match/src/OpenMediaMatch/storage/default.py
Summary
---------
[omm] Fix dev container startup script (path case sensitive issue)
=> [omm] Fix dev container startup script (path case sensitive issue)

open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/storage/default.py, open-media-match/src/OpenMediaMatch/tests/test_api.py
Summary
---------
Allow to add content to bank.
Test Plan
---------
```
http://127.0.0.1:5000/c/bank/MY_TEST_BANK/content?url=https://github.com/facebook/ThreatExchange/blob/main/pdq/data/bridge-mods/aaa-orig.jpg?raw=true&content_type=photo
```
=> [omm] Allow to add content to bank

open-media-match/src/OpenMediaMatch/blueprints/hashing.py
Summary
---------
Added new hash route for POST method that will accept multipart/form-data file uploads.
Currently returns `501 Not Implemented`.
Test Plan
---------
No testing yet.
=> Initial hash method for posting files.

open-media-match/src/OpenMediaMatch/tests/test_api.py, open-media-match/src/OpenMediaMatch/tests/utils.py
Summary
---------
Adding test to the add bank content api
Test Plan
---------
test added
=> [omm] add test for add bank content

open-media-match/src/OpenMediaMatch/app.py
Summary
---------
Add more seed content to the database.
Test Plan
---------
```
flask seed
```
=> Added seeding for all examples

open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/tests/test_api.py
Summary
---------
- bank update takes bank name as parameter
- catch ValueError and IntegrityError to return HTTP 400 or 404 instead of 500
Test Plan
---------
- Modified existing test plan to match new error codes and to check update method
=> [omm] bank update modified to take bank name as input

open-media-match/src/OpenMediaMatch/storage/default.py, open-media-match/src/OpenMediaMatch/storage/interface.py, open-media-match/src/OpenMediaMatch/storage/mocked.py
Summary
---------
Interface to persist the index
Test Plan
---------
mypy
=> [omm] Store index iface

open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/tests/test_api.py
Summary
---------
- bank delete by name and not by id
- always return JSON in case of error for bank API
Test Plan
---------
- bank delete test plan added
=> [omm] bank delete by name

open-media-match/src/OpenMediaMatch/background_tasks/build_index.py
Summary
---------
Test Plan
---------
=> Implemented build_index

open-media-match/src/OpenMediaMatch/app.py, open-media-match/src/OpenMediaMatch/templates/index.html.j2
Summary
---------
Added signal and content types to index page.
Test Plan
---------
=> Adding Signal and Content Types to index page

open-media-match/src/OpenMediaMatch/blueprints/development.py
- feat: add a query endpoint to combine hashing and matching
- style: run black formatting
- feat: support query without specifying a signal type, and some other stuff
- splitting a string
=> splitting a string

open-media-match/.devcontainer/omm_config.py, open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/persistence.py, open-media-match/src/OpenMediaMatch/storage/default.py
Summary
---------
- support extension of signal types via omm_config.py
Test Plan
---------
- TBD
=> [omm] extension support for signal types

python-threatexchange/threatexchange/signal_type/md5.py, python-threatexchange/threatexchange/signal_type/pdq/signal.py
Summary
---------
Add helper method to generate random hash for data seeding
Test Plan
---------
=> Allow generate random hash for PDQ and MD5

open-media-match/README.md
Summary
---------
Readme update for CLIP signal type.
Test Plan
---------
- none
=> [omm] suggestion of readme update for testing CLIP signal type

open-media-match/src/OpenMediaMatch/blueprints/matching.py
Summary
---------
lookup now accepts url query param (GET) and uploaded file (POST) as well.
Test Plan
---------
```
vscode ➜ /workspace/src/OpenMediaMatch $ curl localhost:5000/c/bank/TEST_BANK/content -F photo=@b.jpg
{
"id": 19,
"signals": {
}
}
vscode ➜ /workspace/src/OpenMediaMatch $ curl 'localhost:5000/m/lookup?signal_type=pdq&signal=f8f8f0cee0f4a84f06370a22038f63f0b36e2ed596621e1d33e6b39c4e9c9b22'
[
"TEST_BANK"
]
vscode ➜ /workspace/src/OpenMediaMatch $ curl localhost:5000/m/lookup -F photo=@b.jpg
[
"TEST_BANK"
]
vscode ➜ /workspace/src/OpenMediaMatch $ curl localhost:5000/m/lookup?url=https://avatars.githubusercontent.com/u/5004497
[]
```
=> Upload support for lookup added.

open-media-match/src/OpenMediaMatch/templates/index.html.j2
Summary
---------
Test Plan
---------
=> [omm] split front-end sections

open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/storage/default.py, open-media-match/src/OpenMediaMatch/storage/interface.py, open-media-match/src/OpenMediaMatch/storage/mocked.py, open-media-match/src/OpenMediaMatch/tests/test_api.py
Summary
---------
Removed direct usage of SQLAlchemy in API and use storage interface instead
Test Plan
---------
- Nothing changed
=> [omm] use only storage interface for bank API

open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/templates/index.html.j2
Summary
---------
- add outline of forms for banks and content
Test Plan
---------
=> Lastminuteui

open-media-match/src/OpenMediaMatch/app.py, open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/templates/index.html.j2
Summary
---------
Implement the UI create bank
Test Plan
---------
Add a name, press submit, see the bank appear.
=> [omm] implement ui create bank

open-media-match/src/OpenMediaMatch/blueprints/hashing.py, open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/templates/index.html.j2
Summary
---------
UI for matching images against.
Test Plan
---------
=> [OMM] UI for matching content

open-media-match/src/OpenMediaMatch/templates/index.html.j2
Summary
---------
add ratios to ui
Test Plan
---------
=> adding enabled ratios to ui

open-media-match/src/OpenMediaMatch/blueprints/hashing.py
Summary
---------
- fix hash function (buffer base) when there are multiple signal types to use
Test Plan
---------
1. Setup Clip (see readme)
2. hash a picture:
curl -X POST -F photo=@image.jpg http://localhost:5000/c/bank/TEST_BANK/content
3. test with ui to match the image again
=> [omm] fix hashing with multiple signals

open-media-match/src/OpenMediaMatch/blueprints/development.py, open-media-match/src/OpenMediaMatch/storage/interface.py
Summary
---------
Simple API to trigger index rebuild
Test Plan
---------
I didn't lololol
=> [omm] dev api to rebuild index

open-media-match/src/OpenMediaMatch/blueprints/hashing.py, open-media-match/src/OpenMediaMatch/blueprints/ui.py
Summary
---------
We were limiting to one, lol
Test Plan
---------
Sending to benoit to test
=> [omm] ui lookup multiple

open-media-match/src/OpenMediaMatch/blueprints/development.py, open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/templates/index.html.j2
Summary
---------
Helpful?
Test Plan
---------
Pressed them buttons
=> [omm] Rebuild and factory reset buttons

open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/templates/index.html.j2
Summary
---------
Fixes add content UI
Test Plan
---------
=> Add content fix for UI

open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/templates/index.html.j2
Summary
---------
- fix add content ui (limitation on content type, work only for addcontent as photo)
Test Plan
---------
=> [omm] fix issues with ui addcontent

python-threatexchange/threatexchange/extensions/README.md
=> [py-tx] Update extensions README.md

open-media-match/CONTRIBUTING.md
Add rebuild recover notes, notes on how to run format/type/tests
=> [omm] update CONTRIBUTING.md

open-media-match/src/OpenMediaMatch/database.py, open-media-match/src/OpenMediaMatch/storage/default.py, open-media-match/src/OpenMediaMatch/tests/test_database.py
Summary
---------
Incremental progress on background task functionality. 
Test Plan
---------
Watched background task log output, see it succeeds.
=> [omm] Tracking tables for background tasks

open-media-match/src/OpenMediaMatch/background_tasks/build_index.py, open-media-match/src/OpenMediaMatch/blueprints/matching.py, open-media-match/src/OpenMediaMatch/database.py, open-media-match/src/OpenMediaMatch/storage/default.py, open-media-match/src/OpenMediaMatch/storage/interface.py, open-media-match/src/OpenMediaMatch/storage/mocked.py, open-media-match/src/OpenMediaMatch/tests/test_database.py
Summary
---------
Some more steps towards indexing being buttoned up. Hopefully not too much premature optimization. 
Test Plan
---------
Did a print of the count statement to make sure it looked like a simple enough SQL statement.
Just made sure that no index is built when empty. Noticed some pretty gnarly (but old) bugs on the way that need fixing.
=> [omm][index] Steps towards index checkpointing

open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/blueprints/hashing.py, open-media-match/src/OpenMediaMatch/blueprints/matching.py, open-media-match/src/OpenMediaMatch/database.py, open-media-match/src/OpenMediaMatch/storage/default.py, open-media-match/src/OpenMediaMatch/storage/interface.py, open-media-match/src/OpenMediaMatch/tests/test_api.py, open-media-match/src/OpenMediaMatch/tests/test_database.py
Summary
---------
1. Make index unique on name
2. Add hash insertion API for creation
3. Some more work on index checkpointing (more work to get current checkpoint out)
Test Plan
---------
New e2e test for direct hash insertion
=> [omm][index] index uniqueness, hash insert api, idx checkpointing

open-media-match/src/OpenMediaMatch/background_tasks/build_index.py, open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/database.py, open-media-match/src/OpenMediaMatch/storage/default.py, open-media-match/src/OpenMediaMatch/storage/interface.py, open-media-match/src/OpenMediaMatch/storage/mocked.py
Summary
---------
1. Implement index checkpoint properly
2. Iteration order is now stable in the default implementation
Test Plan
---------
Use the new explain() helper on getting the last item:
```
[
('Limit  (cost=0.15..5.17 rows=1 width=12)',), 
('  ->  Index Only Scan Backward using incremental_index_build_idx on content_signal  (cost=0.15..20.22 rows=4 width=12)',), 
("        Index Cond: (signal_type = 'pdq'::text)",)
]
```
=> [omm][index] Proper index checkpointing

open-media-match/src/OpenMediaMatch/app.py, open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/templates/bootstrap.html.j2, open-media-match/src/OpenMediaMatch/tests/test_e2e_workflow.py
Summary
---------
1. Move UI bits under /ui
2. Add a test that was accidentally excluded from the last diff
Test Plan
---------
Visit /ui/bootstrap
=> [omm][ui] Experiment with bootstrap

open-media-match/src/OpenMediaMatch/templates/bootstrap.html.j2
=> [omm][ui] Format html

open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/storage/interface.py, open-media-match/src/OpenMediaMatch/templates/components/add_to_bank_form.html.j2, open-media-match/src/OpenMediaMatch/templates/components/index_status.html.j2
Show index summary bar in the debug UI
=> [omm][ui] Index status

open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/blueprints/development.py, open-media-match/src/OpenMediaMatch/blueprints/hashing.py, open-media-match/src/OpenMediaMatch/blueprints/matching.py, open-media-match/src/OpenMediaMatch/utils.py
This is cleaner and simpler, and fixes the "_impl" workaround we had been trying.
=> [omm] Remove abort_to_json in favor of error handlers

open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/templates/bootstrap.html.j2, open-media-match/src/OpenMediaMatch/templates/components/content_signal.html.j2, open-media-match/src/OpenMediaMatch/templates/components/exchange_status.html.j2
Summary
---------
Collab/exchange fetch status.
Test Plan
---------
=> [omm][ui] Mock of collab status

open-media-match/src/OpenMediaMatch/app.py
Summary
---------
Just a straightforward change to demonstrate using click args
Test Plan
---------
Ran command with defaults, then waited for index  to build (~60 seconds), see green.
=> [omm] Show adding args to commands

open-media-match/src/OpenMediaMatch/storage/postgres/database.py
I ended up not using this, and in the future I'd rather put this on the index tables directly.
=> [omm][db] Remove unused task table

open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/storage/postgres/database.py, open-media-match/src/OpenMediaMatch/templates/components/create_exchange_modal.html.j2
Summary
---------
Now with a working-ish submission path from the UI.
Test Plan
---------
1. Click create
2. Submit
3. See database entry
More to go before it works e2e
=> [omm] Create exchange configs

open-media-match/src/OpenMediaMatch/background_tasks/fetcher.py, open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/storage/interface.py, open-media-match/src/OpenMediaMatch/storage/mocked.py, open-media-match/src/OpenMediaMatch/storage/postgres/database.py, open-media-match/src/OpenMediaMatch/storage/postgres/impl.py, open-media-match/src/OpenMediaMatch/templates/components/banks_grid.html.j2, open-media-match/src/OpenMediaMatch/templates/components/content_signal.html.j2, open-media-match/src/OpenMediaMatch/templates/components/create_exchange_modal.html.j2
Summary
---------
* Add some `required` to various form fields
* Delete collab terminology in favor of "exchange"
* Get submit form to create (and hint on error)
Test Plan
---------
* Create some sample configs
=> [omm][ui] Create exchange configs all the way

open-media-match/src/OpenMediaMatch/app.py, open-media-match/src/OpenMediaMatch/background_tasks/fetcher.py, open-media-match/src/OpenMediaMatch/storage/interface.py, open-media-match/src/OpenMediaMatch/storage/mocked.py, open-media-match/src/OpenMediaMatch/storage/postgres/database.py, open-media-match/src/OpenMediaMatch/storage/postgres/flask_utils.py, open-media-match/src/OpenMediaMatch/storage/postgres/impl.py
Summary
---------
Not all of these types are correct yet, and there's a few bugs, but we're making progress.
1. Fetch task now kinda fetches
2. It calls an interface that is not yet implemented
3. A possible implementation of the database is included in the postgres bits
Test Plan
---------
CI
=> [omm][fetch] More database work; Task now tries to fetch things

open-media-match/src/OpenMediaMatch/background_tasks/fetcher.py, open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/storage/interface.py, open-media-match/src/OpenMediaMatch/storage/mocked.py, open-media-match/src/OpenMediaMatch/storage/postgres/database.py, open-media-match/src/OpenMediaMatch/storage/postgres/impl.py, open-media-match/src/OpenMediaMatch/templates/components/exchange_status.html.j2
Summary
---------
Still just brute forcing through fetching. Have maybe a solution for inspecting the status.
Test Plan
---------
=> [omm][fetch] Fetch status and UI widget

.github/labeler.yml, .github/workflows/pr-labeler.yml
Seems like the syntax changed - looking at https://github.com/actions/labeler to find the new stuff
=> Fix labeler

.github/labeler.yml
=> [github] I am not a clever man

python-threatexchange/setup.py, python-threatexchange/threatexchange/signal_type/md5.py
Summary
---------
Turns out I broke this myself, lovely!
Test Plan
---------
CI
=> [py-tx] Fix the types

python-threatexchange/setup.py, python-threatexchange/threatexchange/cli/config_cmd.py, python-threatexchange/threatexchange/exchanges/signal_exchange_api.py
Summary
---------
These versions have been frozen for a while, let's unfreeze them and see what happens. 
Test Plan
---------
Gogo gadget CI
=> [py-tx] Unchain the versions

open-media-match/src/OpenMediaMatch/templates/components/create_exchange_modal.html.j2
Summary
---------
This is an issue I ran into and confused myself a few times, so add something to help.
Test Plan
---------
Put valid json, see it format prettily and green check
Put invalid json, see it redbox
=> [omm] Kinda sorta validate exchange settings json

open-media-match/src/OpenMediaMatch/storage/postgres/database.py, open-media-match/src/OpenMediaMatch/utils/fetch_benchmarking.py
Summary
---------
Loadtesting PDQ, so lets fetch only the PDQs
Test Plan
---------
Create via the UI, pasting in the JSON settings.
=> [omm] Benchmark API to fetch only certain signal types

open-media-match/pyproject.toml, open-media-match/src/OpenMediaMatch/background_tasks/build_index.py, open-media-match/src/OpenMediaMatch/background_tasks/fetcher.py, open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/utils/time_utils.py
Summary
---------
These tasks are so slow! But how slow?
Test Plan
---------
Look at them logs
=> [omm] Log task duration

open-media-match/src/OpenMediaMatch/background_tasks/fetcher.py, open-media-match/src/OpenMediaMatch/blueprints/curation.py, open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/templates/components/dev_mode_bar.html.j2, open-media-match/src/OpenMediaMatch/templates/components/exchange_status.html.j2
Summary
---------
* At 1.9M hashes, things are noticeably slowing 
* Add the ability to disable fetching from the UI
Test Plan
---------
Look at logs, see fetch stop happening after toggling off.
Here's the styling for disabled:
=> [omm] Enable/disable collab fetching

open-media-match/src/OpenMediaMatch/storage/postgres/database.py, open-media-match/src/OpenMediaMatch/storage/postgres/flask_utils.py, open-media-match/src/OpenMediaMatch/storage/postgres/impl.py, open-media-match/src/OpenMediaMatch/tests/omm_config.py, open-media-match/src/OpenMediaMatch/tests/test_postgres_storage_impl.py
Summary
---------
* Man, foreign keys are harder than I thought
* I had the foreign key on the wrong side for the ExchangeData -> BankContent cascade, which makes it so fetch deletes don't actually delete
Test Plan
---------
New test
=> [omm] Fetch cascade

open-media-match/src/OpenMediaMatch/storage/postgres/database.py, open-media-match/src/OpenMediaMatch/storage/postgres/flask_utils.py, open-media-match/src/OpenMediaMatch/storage/postgres/impl.py, open-media-match/src/OpenMediaMatch/tests/test_database.py
Summary
---------
Knock out a todo
Test Plan
---------
Lets see what CI says
=> [omm] Rename CollabConfig -> ExchangeConfig

open-media-match/.devcontainer/gunicorn_omm_config.py, open-media-match/.devcontainer/omm_config.py, open-media-match/src/OpenMediaMatch/background_tasks/__init__.py, open-media-match/src/OpenMediaMatch/storage/postgres/impl.py
Summary
---------
Missing copyright headers, unused imports, and some small text.
Test Plan
---------
Let's see what CI thinks.
=> [omm] A few random tiny cleanups

README.md
=> Update Top-level README.md

open-media-match/src/OpenMediaMatch/background_tasks/fetcher.py, open-media-match/src/OpenMediaMatch/blueprints/development.py, open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/storage/interface.py, open-media-match/src/OpenMediaMatch/storage/mocked.py, open-media-match/src/OpenMediaMatch/storage/postgres/impl.py, open-media-match/src/OpenMediaMatch/templates/components/dev_mode_bar.html.j2
Summary
---------
Actually use the credentials when fetchig
Test Plan
---------
Used new seed method, saw fetching happen against example tx repo.
=> [omm] Use credentials in fetch

open-media-match/src/OpenMediaMatch/static/js/autoreload.js, open-media-match/src/OpenMediaMatch/templates/bootstrap.html.j2
Summary
---------
This was more about testing static javascript than the actual functionality, which can interrupt someone trying to make a submission at 3 minutes and 40 seconds.
Also fix some lints
Test Plan
---------
Set the timeout to 5 seconds and then look at the page, see it gets reloaded.
=> [omm] Autoreload ui page after 4 minutes

open-media-match/src/OpenMediaMatch/blueprints/ui.py, open-media-match/src/OpenMediaMatch/templates/bootstrap.html.j2, open-media-match/src/OpenMediaMatch/templates/components/content_signal.html.j2, open-media-match/src/OpenMediaMatch/templates/components/index_status.html.j2
Summary
---------
* Tweak the credential message to only include an emoticon and helptext (with title=)
Test Plan
---------
=> Creds text

hasher-matcher-actioner/hmalib/indexers/lcc.py, python-threatexchange/threatexchange/cli/config_cmd.py, python-threatexchange/threatexchange/exchanges/impl/fb_threatexchange_api.py
Summary
---------
Return Type Mismatch: build_index_from_last_24h creates an index 
Formatting with black
Testing
---------
python -m mypy threatexchange
=> Return type mismatch

open-media-match/README.md
And add devcontainer migration instructions
=> [omm] Update README.md to point to HMA

hasher-matcher-actioner/README.md
=> [hma] Update README.md

hasher-matcher-actioner/CONTRIBUTING.md
=> [hma] Update CONTRIBUTING.md

python-threatexchange/threatexchange/cli/cli_config.py, python-threatexchange/threatexchange/exchanges/impl/ncmec_api.py, python-threatexchange/threatexchange/exchanges/impl/static_sample.py
Summary
---------
CI isn't cleared yet, but at least we removed the build errors!
More stabs at #1568 
Test Plan
---------
Let's see what CI says
=> [pytx] Run black

hasher-matcher-actioner/src/OpenMediaMatch/templates/bootstrap.html.j2
Summary
---------
It's a silly thing, but it makes me happy.
Test Plan
---------
=> [hma] Add favicon

hasher-matcher-actioner/src/OpenMediaMatch/blueprints/development.py
Summary
---------
Fix the dev banner redirects. Fixes #1591
Test Plan
---------
Verified by running locally.
=> Redirect to the homepage.

hasher-matcher-actioner/src/OpenMediaMatch/blueprints/curation.py, hasher-matcher-actioner/src/OpenMediaMatch/storage/postgres/impl.py, hasher-matcher-actioner/src/OpenMediaMatch/tests/test_api.py
Summary
---------
Unblocking @jagraff on experimenting with metadata storage, provide a description for it in the curator blueprint, and validate the inputs. Not yet stored, but will keep working down the stack.
Test Plan
---------
Update unittest
=> [omm] Add metadata to API

hasher-matcher-actioner/README.md
Summary
---------
Tried to add some more information on readme on how to use HMA and the setup for local/prod environments
=> [HMA] Readme changes to include how to use information

pdq/wasm/server.js
Summary
---------
Outreach from potential unsanitized relative path in the node test server, which allows reading arbitrary content (ref: https://cwe.mitre.org/data/definitions/22.html). Since this file is just for demo/testing purposes, I'm not worried about an attack, but maybe sanitize anyways.
Test Plan
---------
I cannot get node to run on my windows machine :/ I feel confident about the change without being able to run, but sorry future person trying to run the demo server if I broke it.
=> [pdq] Sanitize relative path on test server; format file

hasher-matcher-actioner/src/OpenMediaMatch/blueprints/ui.py, hasher-matcher-actioner/src/OpenMediaMatch/templates/components/add_to_bank_form.html.j2, hasher-matcher-actioner/src/OpenMediaMatch/templates/components/match_form.html.j2
Summary
---------
When testing HMA found that we have an issue on the templates missing variables. added it.
Test Plan
---------
Before: 
After:
=> [HMA] Fix Content Vars missing for template

pdq/README.md
Summary
---------
We have a logo, so link it in the README
Test Plan
---------
lookit
=> [pdq] Add logo in README.md

python-threatexchange/README.md
I missed this in the review, it's confusing vs just running via pip
=> [pytx] Remove docker run from README.md

hasher-matcher-actioner/CONTRIBUTING.md
Summary
---------
Add release instructions to contributing doc to explain how to release a new version of the project
Test Plan
---------
N/A
=> Update CONTRIBUTING.md to include release instructions

.github/workflows/hma-release.yaml
Summary
---------
We want to update the platforms on release image to ensure we have the correct ones.
Test Plan
---------
=> Update Platforms for Release of Docker image

python-threatexchange/threatexchange/exchanges/clients/fb_threatexchange/api.py, python-threatexchange/threatexchange/exchanges/clients/fb_threatexchange/tests/__init__.py, python-threatexchange/threatexchange/exchanges/clients/fb_threatexchange/tests/test_reactions_api.py
Summary
---------
Implement Matched/UpVote/DownVote in ThreatExchange Client API for issue 81879406
Test Plan
---------
- Add unit test
```
>>> from threatexchange.exchanges.clients.fb_threatexchange.api import ThreatExchangeAPI
>>> client = ThreatExchangeAPI(<API KEY>)
>>> client.get_threat_descriptors(["6759614597433667"])
[{'raw_indicator': 'Hello world', 'type': 'TEXT_STRING', 'added_on': '2023-08-02T17:00:23+0000', 'last_updated': '2023-08-02T17:00:23+0000', 'confidence': 50, 'privacy_type': 'HAS_PRIVACY_GROUP', 'review_status': 'REVIEWED_MANUALLY', 'status': 'NON_MALICIOUS', 'severity': 'WARNING', 'share_level': 'AMBER', 'id': '6759614597433667', 'tags': [], 'description': ''}]
>>> client.react_matched_threat_descriptor(["6759614597433667"])
>>> …
```
=> Implement Matched/UpVote/DownVote in ThreatExchange Client API

hasher-matcher-actioner/src/OpenMediaMatch/blueprints/development.py, hasher-matcher-actioner/src/OpenMediaMatch/blueprints/matching.py
Summary
---------
Fixes UI that broke due to return type change on lookup function
Test Plan
---------
=> Fix Broken UI due to lookup change

python-threatexchange/setup.py
Summary
---------
simple: change the contact info for pytx
fixes #1615
Test Plan
---------
n/a
=> update contact email address for pytx

python-threatexchange/threatexchange/exchanges/clients/fb_threatexchange/api.py, python-threatexchange/threatexchange/exchanges/impl/ncmec_api.py
Summary
---------
Update to graph API version 21
Test Plan
---------
`tx config api fb_threatexchange -L1` produces correct output
=> Update Graph API Version

CONTRIBUTING.md
Inspired by the many questions from the recent hackathon, update the top-level CONTRIBUTING
=> Updates to to-level CONTRIBUTING.md

python-threatexchange/CONTRIBUTING.md
Merged some things to the root-level
=> [py-tx] Update CONTRIBUTING.md

CONTRIBUTING.md
Merge some more good blocks from py-tx
=> More top-level CONTRIBUTING.md updates

hasher-matcher-actioner/src/OpenMediaMatch/templates/components/banks/actions_bar.html.j2
=> [hma] Add more copyright headers

api-reference-examples/curl/te-tag-query/README.md, api-reference-examples/java/te-tag-query/README.md, api-reference-examples/python/te-tag-query/README.md, api-reference-examples/ruby/te-tag-query/README.md, pdq/README.md, pdq/cpp/README.md, pdq/java/README.md, pdq/php/README.md, python-threatexchange/threatexchange/extensions/README.md, tmk/README.md
Summary
---------
change all contact info from @fb.com to @meta.com with grep
`grep -rl "@fb.com" . | xargs sed -i 's/@fb.com/@meta.com/g'`
fixes #1615 
Test Plan
---------
n/a
=> Update contact addresses from @fb -> @meta

python-threatexchange/threatexchange/cli/main.py, python-threatexchange/threatexchange/exchanges/clients/ncmec/hash_api.py, python-threatexchange/threatexchange/exchanges/clients/ncmec/tests/test_hash_api.py, python-threatexchange/threatexchange/exchanges/impl/ncmec_api.py
Summary
---------
* I worked on this during the hackathon, but never finished submitting it
* Most of this is minor QoL fixups from @aryzle's work - thanks arzyle! 
Test Plan
---------
* Manually submitted to test_NGO database using Meta credentials, then re-read to confirm updates were sent
* Existing unittests cover the refactored bit, and as proven by the need to e2e test this, it's hard to test the finnicky bits
=> [py-tx] Ncmec api feedback fixups

.github/workflows/python-threatexchange-ci.yaml, .github/workflows/python-threatexchange-release.yaml, python-threatexchange/setup.py
Summary
---------
Publish action is failing for mysterious reasons (#1709), maybe blindly increasing the version will help!
Test Plan
---------
Can build and publish locally (tested with pypi-test), but running into a lot of other mysterious problems as well - vpdq won't build on my devcontainer, for example.
=> [pytx] Bump ci+publish version

vpdq/pyproject.toml
cmake not found? Maybe we can specify cmake! 
See #1711
`pip install .`
Get a new error!
=> [vpdq] Random guess to fix build

vpdq/cpp/vpdq/cpp/hashing/ffmpegwrapper.cpp
Summary
---------
Continuing to noodle on #1711, hitting the same vpdq build issue as reported in #1691  
Test Plan
---------
from vpdq directory:
pip install .
Completes successfully
=> [vpdq] Get vpdq to build again locally

hasher-matcher-actioner/pyproject.toml
#1724 moves more things around
=> [hma] Require pytx >= 1.2.3

hasher-matcher-actioner/src/OpenMediaMatch/background_tasks/fetcher.py, hasher-matcher-actioner/src/OpenMediaMatch/storage/interface.py, hasher-matcher-actioner/src/OpenMediaMatch/storage/mocked.py
Summary
---------
Correct location should be pytx.storage, so let's do that
Test Plan
---------
Go go gadget continuous integration
=> [hma] Fix cli.storages -> storage

python-threatexchange/threatexchange/exchanges/clients/ncmec/hash_api.py, python-threatexchange/threatexchange/exchanges/clients/ncmec/tests/test_hash_api.py, python-threatexchange/threatexchange/exchanges/impl/ncmec_api.py, python-threatexchange/threatexchange/exchanges/impl/tests/test_ncmec.py, python-threatexchange/threatexchange/exchanges/tests/test_state_compatibility.py
Summary
---------
See #1744
I made a stab at trying for this without redoing the probing behavior.
Test Plan
---------
Pending, ran out of time this morning
=> [WIP][pytx] Attempt to fix NCMEC paging behavior

hasher-matcher-actioner/src/OpenMediaMatch/tests/test_e2e_workflow.py
=> [hma] black

hasher-matcher-actioner/CONTRIBUTING.md
Summary
---------
:p Fix some typos while I was onboarding to work on the latest HMA issue...
Btw, this onboarding doc is very good.
Test Plan
---------
Only doc changes– N/A
=> [hma] Fix typos in HMA contributing document

CONTRIBUTING.md, README.md, api-reference-examples/js/node/README.md, api-reference-examples/python-notebook/README.md, api-reference-examples/python/pytx/CONTRIBUTING.md, pdq/java/README.md, pdq/sql/README.md, pdq/wasm/README.md, python-threatexchange/CONTRIBUTING.md, python-threatexchange/threatexchange/extensions/README.md, tmk/README-more.md, vpdq/CONTRIBUTING.md, vpdq/README.md, vpdq/benchmark/README.MD
Summary
---------
It's kinda silly, but I was wondering how to do it _without_ removing spaces for sentences that had a line break.
https://github.com/facebook/ThreatExchange/pull/1762#discussion_r1954813278
```
This is a sentence[SPACE]
and it breaks back there.
```
We don't overwrite this type of formatting, which is expected, right?.
This would be kiinda hard to do with sed so I ended up trying a python script which works pretty well
Test Plan
---------
Only doc changes- not needed.
=> Trim formatting

python-threatexchange/mypy.ini
Summary
---------
Following #1746, clean up any dangling errors that show up in CI
Test Plan
---------
python3 -m mypy .
=> [pytx] Maybe fix types

.github/labeler.yml, .github/workflows/pr-labeler.yml, CONTRIBUTING.md, README.md, hasher-matcher-actioner/src/OpenMediaMatch/storage/interface.py, python-threatexchange/benchmarks/README.md, python-threatexchange/benchmarks/benchmark_pdq_faiss_matchers.py, vpdq/CONTRIBUTING.md
Summary
---------
I'm pretty sure labelling actions doesn't work. Trying to fix it and see if it works, that's why there's random typo fixes lol
Test Plan
---------
Let CI do it's thing
=> [CI] Fix labelling actions

python-threatexchange/threatexchange/extensions/README.md
Response to #1772, add some words about how to get access
=> [pytx] Update some language on extensions README

hasher-matcher-actioner/README.md
Response to #1772, add a reference to extensions in HMA README.
=> [hma] Add direct reference to extensions in README.md

.github/labeler.yml
Reading https://github.com/actions/labeler, trying to figre out why ours doesn't work, so just try random things.
=> [actions] Test labeling labeler.yml

python-threatexchange/README.md
Testing the labeler action mostly.
datastructure -> data structure
=> [pytx] Update README.md

.github/labeler.yml
With my newfound reading comprehension of https://github.com/actions/labeler, attempt to fix the labeler
=> [actions] Update labeler.yml

python-threatexchange/threatexchange/cli/cli_config.py, python-threatexchange/threatexchange/cli/config_cmd.py, python-threatexchange/threatexchange/cli/storage/__init__.py, python-threatexchange/threatexchange/cli/storage/interfaces.py
Summary
---------
See #1754 and the class comments - this provides a way for us to do the cutover one method at a time.
Test Plan
---------
Not called atm, so hopefully lint passes.
=> [pytx] Storage compatibility wrapper to demonstrate how we might do it

.github/workflows/pr-labeler.yml
=> [actions] Maybe fix label errors from forks

hasher-matcher-actioner/pyproject.toml, hasher-matcher-actioner/src/OpenMediaMatch/blueprints/matching.py, hasher-matcher-actioner/src/OpenMediaMatch/storage/postgres/impl.py
Summary
---------
In the previous version we moved around some imports (version incompatible change)! Fix up the callsites.
Test Plan
---------
=> [hma] Fix pytx lib imports

python-threatexchange/pytest.ini, python-threatexchange/threatexchange/storage/local_dbm.py, python-threatexchange/threatexchange/storage/tests/test_local_dbm.py
Summary
---------
See #1687 - this demonstrates how we might start building out a DBM interface for key components
Test Plan
---------
Let's see what CI thinks
=> [pytx] DbmStore starting point

hasher-matcher-actioner/src/OpenMediaMatch/app.py
Summary
---------
Fixes a bug I introduced in #1803 where the redirect logic is inverted.
Test Plan
---------
n/a
=> Fix bug in HMA redirect logic

tmk/README.md
The video hash benchmark is out! Let's put their findings in the README
=> [tmk] add reference to PHVSpec in README.md

.github/workflows/hma-ci.yaml, .github/workflows/python-threatexchange-ci.yaml
Summary
---------
I agree with https://github.com/facebook/ThreatExchange/pull/1821#issuecomment-2877695616
I think we should do this?
Test Plan
---------
=> [CI] Update github workflows with black --diff

hasher-matcher-actioner/reference_omm_configs/development_omm_config.py, hasher-matcher-actioner/src/OpenMediaMatch/blueprints/hashing.py, hasher-matcher-actioner/src/OpenMediaMatch/blueprints/matching.py, hasher-matcher-actioner/src/OpenMediaMatch/tests/omm_config.py, hasher-matcher-actioner/src/OpenMediaMatch/tests/test_hashing.py
Summary
---------
Add URL validation to the service as a way to prevent big files from download and SSRF prevention.
Also added possibility for whitelist of host to help with abuse prevention. 
Test Plan
---------
added test
=> [HMA] Add URL Validation for hashing.

hasher-matcher-actioner/README.md, hasher-matcher-actioner/hma-ui.md
Summary
---------
Make @julietshen's docs easier to find. See also #1835
Test Plan
---------
Look at it, see images
=> [hma] Add reference to ui docs in README.md, images

python-threatexchange/ROADMAP.md
Following up from discussion in HMA office hours.
=> [pytx] ROADMAP.md

hasher-matcher-actioner/docs/api.md
In pursuit of https://github.com/facebook/ThreatExchange/issues/1825, some *very* barebones docs on a few of the endpoints. 
This is not intended to be comprehensive or cover the entire API surface. I've essentially picked the ones I wish I knew about when I started writing code to use HMA, with the (undocumented) assumption that the reader has used the dev UI to get some banks going.
I've also fixed the heading levels while here.
=> [hma] Rudimentary docs for status, hashing, and matching functions

hasher-matcher-actioner/docs/architecture.md
All got broken by folder move. Relative paths ftl
=> [hma] Fix svgs in architecture.md

hasher-matcher-actioner/docs/roadmap.md
Summary
---------
Adds a suggestion for future roadmap projects.
Test Plan
---------
Viewed it in preview
=> [hma] roadmap.md
