facebook/ThreatExchange

doc/threat_exchange.md
php/BaseUpload.php
threat_indicators/post_compromised_credentials.py

We are going to require an explicit privacy_type setting on all requests starting next week. This pull request updates the documentation and the PHP and Python code to meet this requirement.

Add privacy_type as a mandatory field

---

ruby/Gemfile.lock
ruby/example/ThreatExchangeTest.rb
ruby/lib/ThreatExchange.rb
ruby/lib/ThreatExchange/version.rb

All IOC submissions must contain a privacy type key in the hash submitted to the method now.

Privacy Type is mandatory for IOC submissions now in ruby library

---

pytx/pytx/common.py
pytx/pytx/malware.py
pytx/pytx/threat_exchange_member.py
pytx/pytx/threat_indicator.py
pytx/pytx/vocabulary.py
ui/js/dashboard.js
ui/js/vocabulary.js

Enforce the PRIVACY_TYPE requirement for submitting new Indicators in pytx and perform a quick check in the UI (which pre-populates the PRIVACY_TYPE dropdown anyways so unless someone is abusing the JS it should already work).
Added some helper properties to the Malware object:
.zfh - return a file handle for the b64 decoded zip file
.zf  - return the raw b64 decoded zip file
.rfh - return a file handle for the b64 decoded and unzipped file
.rf  - return the raw b64 decoded and unzipped file
These properties should be flexible enough for people who want to utilize the sample without having to do the decode/unzip dance at whatever stage they are looking to get to. Required adding a `_unique` class attribute to track properties we don't want people to change.
Fixed a couple other bugs with …

Enforcing PRIVACY_TYPE in pytx/UI

---

ui/js/api.js

Currently a search for `threat_type:X` matches `type:` first and produces this search: `.../threat_?type=X`.

UI: fix for param parsing in search terms.

---

pytx/pytx/threat_exchange_member.py
pytx/pytx/vocabulary.py
ui/js/api.js

I had a quick second :)
Exposes the email of a ThreatExchangeMember in pytx. Also when you drop
the Members menu down in the UI it will create a mailto link with the
POC email address.

Add member email to pytx and UI.

---

pytx/pytx/common.py
pytx/pytx/request.py
pytx/pytx/vocabulary.py
pytx/scripts/get_compromised_credentials.py

Let's try breaking this up.
Allow fields selection for object pull, so you can fetch fields that are not pulled by default like passwords
This is useful for large fetches to avoid using ThreatIndicator.details() for each IOC

Add 'fields' field to Common.objects

---

doc/threat_exchange.md

We are removing the option HAS_BLACKLIST. Effective 9 Jun, this option will be removed from the system. Any indicators set to this value will be changed to HAS_WHITELIST, with a whitelist of the submitters of that indicator.

Removes blacklist from privacy options

---

pytx/pytx/vocabulary.py

HAS_BLACKLIST is being removed as an option from the system.

Removing HAS_BLACKLIST from vocabulary.

---

ui/js/vocabulary.js

HAS_BLACKLIST is being removed from the system. This removes it from the
UI dropdown when adding/editing a Threat Indicator.
Should have added this in the previous PR. My bad! :)

Remove HAS_BLACKLIST from UI dropdown.

---

pytx/pytx/init.py
pytx/pytx/vocabulary.py

init() will now allow you to pass a token_file which contains your
app_id and app_secret on separate lines, or an access_token on a single
line.
init() will now allow you to pass nothing and it will attempt to find
the app_id, app_secret, or access_token in environment variables:
- TX_APP_ID
- TX_APP_SECRET
- TX_ACCESS_TOKEN
This should help for situations where you don't want to store your
app_id and/or app_secret in python scripts.
Related to #27.

Add ability to use file or environment for init.

---

.gitignore
pytx/Makefile
pytx/requirements-dev.txt
pytx/requirements.txt
pytx/setup.py
pytx/tox.ini

**Let's use TLS!**
This is issue #32
The fix here is real simple. Install the option `secure` requirements for the `requests` package.
See more @ http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package
**.gitignore**
Quick update. Add `.DS_Store` which OSX likes to litter the filesystem with.

Have pytx use TLS1.0+ to avoid bad SSL warnings and avoid using bad SSL

---

.gitignore
pytx/docs/quickstart.rst
pytx/pytx/access_token.py
pytx/scripts/get_compromised_credentials.py
pytx/scripts/get_indicators.py
pytx/scripts/get_members.py
pytx/scripts/malware_api.py
pytx/scripts/malware_grabber.py
pytx/tests/access_token_test.py

**Motivation**
- I *almost* checked my access token into the sample scripts twice already. 
- The graph documentation is pretty explicit - don't put your access token in code.
*However*, the sample scripts all require you to add your access token to the code. :-1: 
**The Change**
Speaking with @mgoffin we came up with these rules for how `pytx.access_token.init` should work:
1. Use the value of the 'TX_ACCESS_TOKEN' environment variable.
2. Use the concatenation of the 'TX_APP_ID' and 'TX_APP_SECRET' environment variables.
3. Use the first line of the file '$PWD/.pytx' or ~/.pytx'
4. Use the concatenation of the app_id and app_secret parameters
5. Use the first line of the file 'token_file'
So now `pytx.access_token.init` works that way. For the first 3 cases, there is no need to …

No more access tokens in code

---

pytx/pytx/common.py
pytx/pytx/vocabulary.py

When saving new `ThreatIndicator` objects, consume the response and look for an `id` returned in the response. If we get one, set the id of our `ThreatIndicator` object so we can immediately use it for other things (adding connections, etc.).

Fix .save() for new ThreatIndicator objects

---

doc/threat_exchange.md

Removes verbiage from the documentation about the no longer supported blacklist mode.

Remove spurrious reference to blacklist privacy

---

malware/get_samples.py

Tested that it works in both Python 2.6 and 2.7 now.

Allow get_samples.py to run on Python 2.6

---

php/ThreatExchangeConfig.php

Updates the PHP scripts to use the same environment vars as the python
scripts for loading the OAuth token.

Update PHP scripts to use env vars for OAuth token

---

malware/get_samples.py

Currently, if a malware sample isn't found in the database for a given hash, the only message returned to the user is the fact an exception happened. So, grab the json returned with the error, parse out message and associated hash and print.

An attempt to get the error message values out of the json which is returned in the body of the 400.

---

pytx/pytx/__init__.py
pytx/pytx/access_token.py
pytx/pytx/common.py
pytx/pytx/errors.py
pytx/pytx/logger.py
pytx/pytx/request.py

Retries in `requests` is a bit of a pain, but this should expose the ability for people to retry GET, POST, and DELETE requests as often as they feel they need to in order for the request to succeed. By default we still try and fail after one attempt. This propagates into the generator so for example if we perform a query which will end up with 15 pages and a retry of `3`, we will try to fetch each page as we need to and individually they can be retried up to 3 times before failing.
Failing here is defined by what requests fails on. We create a urllib3 Retry object and specify 500 and 503 responses as ones we will retry.
This PR also adds a logging feature (necessary if people are going to be doing retries and random stuff and want to inspect what pytx is doing/thinking). You can now do …

Add support for retries

---

pytx/docs/quickstart.rst
pytx/pytx/request.py
pytx/pytx/vocabulary.py

I was annoyed duplicating #93 and having to manually parse the
response string which wasn't already JSON the way pytx was
returning.
When an error occurs, we capture the contents of it. We now build up a
dictionary containing all of the error contents from the server response
and we add in the `status_code` and the `url` that the request was made
to. This should make it much easier to parse out and automatically use
within scripts since it's already a dictionary, not a large string that
isn't in JSON.
Example:
```python
from pytx import Malware
from pytx.errors import pytxFetchError
m = Malware()
m.id = "19374-19841-4813-408"
response = None
try:
m.details()
except pytxFetchError, e:
response = e.message
```
The `response` dictionary looks like this:
```python
{
'code': 803,
'fbtrace_id': …
```

Capture error responses better

---

pytx/pytx/common.py

Found this little gem while doing testing in my previous PR:
```python
>>> from pytx import Malware
>>> m = Malware()
>>> m.id
>>> m.id = "12345"
>>> m._DETAILS
'https://graph.facebook.com/12345/'
>>> m.id = "12315343"
>>> m._DETAILS
'https://graph.facebook.com/12345/12315343/'
>>>
```
This fixes it so instead of appending to the URL, we recreate it from scratch with the new `id` value:
```python
>>> from pytx import Malware
>>> m = Malware()
>>> m.id
>>> m.id = "12345"
>>> m._DETAILS
'https://graph.facebook.com/12345/'
>>> m.id = "12315343"
>>> m._DETAILS
'https://graph.facebook.com/12315343/'
>>>
```

Fix details URL breaking when setting `id` attribute more than once

---

pytx/pytx/threat_descriptor.py
pytx/pytx/vocabulary.py

We recently added support for setting/getting an AttackType on a
descriptor.  It’s intent is to describe the class of attack an
indicator was associated with (e.g. Malware, Phishing, etc)
AttackType docs:
https://developers.facebook.com/docs/threat-exchange/reference/apis/attack-type/

Add Attack Type field on ThreatDescriptor

---

pytx/pytx/access_token.py

This makes access_token() use the passed params first, before looking
in environment variables and files.
Making this change to handle the case when you usually are happy with
your env vars or file, but want to use a different token as a one-off
when testing.

Re-prioritize how access_token() finds the token to use

---

ipynb/Getting Started with Sharing.ipynb
ipynb/README.md
ipynb/ThreatExchange Data Dashboard.ipynb

Based on a lot of discussions I’ve had with folks using ThreatExchange,
there’s an interest in tools that make that first sharing of data or an
initial data analysis easier.
This PR adds two ipynb files to perform these common tasks: sharing
data and making sense of the data that you’re able to see.
Happy to share more or build out notebooks that answer other questions
people are looking to solve!

Adds reference iPython Notebooks

---

golang/threatexchange/README.md
golang/threatexchange/threatexchange.go
golang/threatexchange/threatexchange_test.go

This PR is too add GO client for ThreatExchange API's.
It includes examples on usage.
And tests to verify client is correct.
Small thing to note, i'm pointing to my local github repo in README (```go get github.com/meirwah/ThreatExchange/golang/threatexchange```)
because only after this PR merge, I will be able to change this link to the official repo (``` go get github.com/facebook/ThreatExchange/golang/threatexchange ```) .

Add golang client and examples for ThreatExchange

---

pytx/pytx/threat_privacy_group.py

The URL was bad so the members list being returned was always an empty string.

Fix acquiring members for privacy groups.

---

pytx/docs/index.rst
pytx/docs/pytx.threat_tag.rst
pytx/pytx/__init__.py
pytx/pytx/malware.py
pytx/pytx/threat_descriptor.py
pytx/pytx/threat_tag.py
pytx/pytx/vocabulary.py

Threat Tags are independent objects with an 'id' and 'text' field. They
have an edge to 'tagged_objects' so if you include that in your fields
list (which is not there by default when querying the graph) it will
show you the related malware and threat descriptors. Also if you include
'tags' in the fields list when querying for Malware Analyses or Threat
Descriptors, the tags will be available to you.
I cannot test this since tags aren't out yet, but it will at least allow for
the conversation to start if any adjustments need to be made for this :)

Initial implementation for threat tags.

---

pytx/pytx/common.py
pytx/pytx/request.py
pytx/pytx/vocabulary.py

sort_order has been added to the API so that is now supported. Bumped
vocab to include API version 2.6 as well as additions for sort_order and
the change to Attack Types to keep things singular.
One thing to note is for the singular vocab changes. Historically we have said
if the vocab changes in this way we will keep the class attribute the same and
change the string so code doesn't break. However, we are bumping soon to a
pytx v0.5 release. If we wanted to adjust the class attribute to stay true to the
value, now would be the time to do it. I have left the attribute as-is in this PR 
but if we feel differently and want to adjust the attribute as well I can make a 
quick change and include it here too.

Adding sort order and updating vocab.

---

ruby/example/lib/example.rb
ruby/lib/ThreatExchange.rb

Some ruby [client] refactoring:
* break out `get`, `post`, and `delete` http methods to reuse
* moves the exception-catching boilerplate into ^ methods
* swap `filter` and `data` naming with `params`, to make it clear we're talking about HTTP request params

ruby: remove duplication in request methods, and make params uniform

---

ruby/lib/ThreatExchange/client.rb
ruby/lib/ThreatExchange/version.rb

My last PR added `ThreatExchange::Client#assert_params`, but I mixed up the calculation. This fixes it and gives the args a better name.

Ruby client fix for assert_params()

---

pytx/docs/quickstart.rst

Adding reference to the Facebook Documentation for making multiple
requests and using JSONPath to extract data from those requests.
Took me a bit to find these docs searching - thought a link would be
helpful for anyone else that comes along.

pytx/docs Add reference to Facebook Docs

---

pytx/docs/quickstart.rst
pytx/pytx/rtu.py

This adds support for SSL/TLS through Flask using the RTUListener. Developers can create their own custom `SSLContext` with whatever options they deem necessary for their use case and pass it into the RTUListener's `ssl_context` argument.
Also added documentation referencing the Whitelisting of Facebook IPs in the Webhook docs as it pertains to securing your RTU listener.

Add SSL/TLS support for the RTUListener.

---

pytx/pytx/malware.py

Allow you to specify the filename as a param to `Malware.rfh()`

New Malware.rfh() hotness

---

pytx/README.rst
pytx/docs/quickstart.rst
pytx/pytx/common.py
pytx/pytx/request.py
pytx/pytx/threat_descriptor.py
pytx/pytx/vocabulary.py
pytx/scripts/get_compromised_credentials.py

As noted in https://www.facebook.com/groups/threatex/permalink/573588456165790/, we have removed threat type and attack type from ThreatExchange. These options are no longer supported and attempting to use them results in an error. As such, this PR removes them from pytx.

Remove threat type and attack type from pytx

---

pytx/.gitignore
pytx/pytx/__init__.py
pytx/pytx/common.py
pytx/pytx/utils.py

The ``basestring`` builtin type was removed in Python 3.

Fix Python 3 compatability

---

pytx/scripts/malware_family_grabber.py

This adds a new script for quickly dumping out the members of a malware
family in ThreatExchange: as CSV of the variant hashes or the variants
themselves.

Add a new script for dumping out a malware family from ThreatExchange

---

pytx/pytx/common.py

This enables the tags vocabulary to be used in malware/descriptor filtering. By adding the such a filter (i.e. tags="malicious_ip,malware"), the search results will be filtered to the the data which contains any of the tags in the list.

Support ThreatTag Filters in Search Parameters

---

hashing/README.md

Removed “]” accidentally put in link text.

Fix newsroom link

---

ruby/Gemfile.lock
ruby/README.md
ruby/Rakefile
ruby/ThreatExchange.gemspec
ruby/test/client_test.rb
ruby/test/test_helper.rb

Whaaaat? No tests for the ruby client?
* updated rest-client to recent version
* add minitest
* add webmock
* add basic tests for `#members` and `#malware_analyses`
* add to README
I really just wanted a starting point to get some basic test coverage. There are some things I'd like to clean up in client, but not without coverage first.
The updated Gemfile shows 1.0.0 => 1.0.1 It was and is 1.0.1 The last update didn't check in the updated Gemfile.

add some initial tests for ruby client

---

hashing/te-tag-query-java/README.md
hashing/te-tag-query-java/com/facebook/threatexchange/Constants.java
hashing/te-tag-query-java/com/facebook/threatexchange/DescriptorPostParameters.java
hashing/te-tag-query-java/com/facebook/threatexchange/HashFilterers.java
hashing/te-tag-query-java/com/facebook/threatexchange/HashFormatters.java
hashing/te-tag-query-java/com/facebook/threatexchange/Net.java
hashing/te-tag-query-java/com/facebook/threatexchange/SharedHash.java
hashing/te-tag-query-java/com/facebook/threatexchange/SimpleJSONWriter.java
hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java
hashing/te-tag-query-java/com/facebook/threatexchange/Utils.java

* `TETagQuery.java` was large and I finally got around to splitting it up
* Added a new `submit` verb to `TETagQuery` -- follow-on work will include bulk-upload (taking a filename as argument, with one hash per line), and TMK-hash-from-file upload (with bulk-upload option for having a filename each line of which is the path to a `.tmk` file)

Split up monolithic TETagQuery.java; implement post-single-descriptor feature

---

hashing/te-tag-query-java/README.md
hashing/te-tag-query-java/com/facebook/threatexchange/DescriptorPostParameters.java
hashing/te-tag-query-java/com/facebook/threatexchange/HashFilterers.java
hashing/te-tag-query-java/com/facebook/threatexchange/HashFormatters.java
hashing/te-tag-query-java/com/facebook/threatexchange/IDProcessor.java
hashing/te-tag-query-java/com/facebook/threatexchange/Net.java
hashing/te-tag-query-java/com/facebook/threatexchange/SharedHash.java
hashing/te-tag-query-java/com/facebook/threatexchange/SimpleJSONWriter.java
hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java
hashing/te-tag-query-java/com/facebook/threatexchange/Utils.java

Previously a query would get the list of all queried-for descriptor IDs, then go back through and pull details for each. This was a simple coding model but it had the expense of high latency from start of query to arrival of first detail. Switching to a callback model makes the code a bit less obvious but means that we start retrieving details almost immediately.
Test scenario involves running the commands in `hashing/te-tag-query-java/README.md`.

Switch to pagewise-streaming model for bulk download

---

hashing/te-tag-query-java/com/facebook/threatexchange/Constants.java
hashing/te-tag-query-java/com/facebook/threatexchange/Net.java
hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java

```
$ alias jrt='jr com.facebook.threatexchange.TETagQuery'
```
```
$ jrt -h
Usage: TETagQuery [options] {verb} {verb arguments}
Downloads photo/video hashes in bulk from ThreatExchange, given
either a tag name or a list of IDs one per line on standard input.
Options:
-h|--help      Show detailed help.
--list-verbs   Show a list of supported verbs.
--list-tags    Show a list of supported tags.
-q|--quiet     Only print IDs/hashes output with no narrative.
-v|--verbose   Print IDs/hashes output along with narrative.
-s|--show-urls Print URLs used for queries, before executing them.
-a|--app-token-env-name {...} Name of app-token environment variable.
Defaults to "TX_ACCESS_TOKEN".
-b|--te-base-url {...} Defaults to "https://graph.facebook.com/v4.0"
Verbs:
look-up-tag-id
tag-to-ids …
```

Allow command-line override of TE base URL

---

hashing/te-tag-query-java/com/facebook/threatexchange/Constants.java
hashing/te-tag-query-java/com/facebook/threatexchange/HashFormatters.java
hashing/te-tag-query-java/com/facebook/threatexchange/Net.java
hashing/te-tag-query-java/com/facebook/threatexchange/SharedHash.java
hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java

```
alias jtq='java com.facebook.threatexchange.TETagQuery'
```
```
$ jtq tag-to-details pwny | jq .
...
{
"hash_id": "2683772931706491",
"hash_value": "https://evilevillabs.com/evil.php",
"hash_type": "URI",
"added_on": "2020-01-06T14:58:34+0000",
"confidence": "50",
"owner_id": "1064060413755420",
"owner_email": "threatexchange@support.facebook.com",
"owner_name": "Media Hash Sharing Test",
"tags": "pwny,testing,testing-bulk-edit,testing-bulk-edit-for-doc"
}
{
"hash_id": "2265118903591404",
"hash_value": "e8b19da37825a3056e84c522f05eb0a2",
"hash_type": "HASH_MD5",
"added_on": "2020-03-28T17:00:48+0000",
"confidence": "100",
"owner_id": "494491891138576",
"owner_email": "kerl@fb.com",
"owner_name": "Media Hash Sharing RF Test",
"tags": "pwny,testing"
}
...
```

replace media_type/media_priority single-valued requirement with more flexible tags-list logic

---

hashing/te-tag-query-java/README.md
hashing/te-tag-query-java/com/facebook/threatexchange/Constants.java
hashing/te-tag-query-java/com/facebook/threatexchange/HashFormatters.java
hashing/te-tag-query-java/com/facebook/threatexchange/IDProcessor.java
hashing/te-tag-query-java/com/facebook/threatexchange/Net.java
hashing/te-tag-query-java/com/facebook/threatexchange/SharedHash.java
hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java
hashing/te-tag-query-java/com/facebook/threatexchange/ThreatDescriptor.java
hashing/te-tag-query-java/com/facebook/threatexchange/Utils.java

Long ago I was trying to make this a semi-opaque layer atop the TE API. But given the consistency across the [API](https://developers.facebook.com/docs/threat-exchange/reference/apis/threat-descriptors) and [UI download](https://developers.facebook.com/docs/threat-exchange/reference/ui/descriptors#downloading) / [UI upload](https://developers.facebook.com/docs/threat-exchange/reference/submitting#uploading) it no longer makes sense to have different column names for things.
Also this exposes a few more columns, such as `status`.
Testing: re-run all commands at https://github.com/facebook/ThreatExchange/blob/master/hashing/te-tag-query-java/README.md
Also:
```
$ java com.facebook.threatexchange.TETagQuery tag-to-details pwny | jq .
...
{
"id": "2944704542215377",
"td_raw_indicator": …
```

attribute-renames to adhere more closely to the rest of TE

---

hashing/te-tag-query-java/com/facebook/threatexchange/Net.java
hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java

Previous commit's `sharedHash -> threatDescriptor` search-and-replace took `sharedHashes -> threatDescriptores`. Fixing that.

after-neaten global search-and-replace from prior diff

---

hashing/te-tag-query-java/com/facebook/threatexchange/SimpleJSONWriter.java

Tested by running
```
java com.facebook.threatexchange.TETagQuery tag-to-details tag-name-goes-here | tee all.json
```
then ensuring that
```
jq . all.json
```
doesn't flag an error.

correctly escape double quotes in JSON output

---

hashing/tmk/cpp/hashing/filehasher.cpp

There are known [problems](https://unix.stackexchange.com/questions/36310/strange-errors-when-using-ffmpeg-in-a-loop) with using `ffmpeg` in a bash loop. As, `tmk-hash-video` binary uses `ffmpeg`, I couldn't use it in a bash script loop. This PR is a fix for that.

Fix for not being able to use filehasher in a loop.

---

hashing/te-tag-query-java/com/facebook/threatexchange/DescriptorPostParameters.java
hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java

Note this depends on a backend TE API diff which won't land for another hour or two.
Test plan:
```
$ alias jtq
alias jtq='java com.facebook.threatexchange.TETagQuery'
$ jtq -s submit \
-t HASH_SHA1 \
-i dabbad00f00dfeed5ca1ab1ebeefca11ab1ec00a \
-d 'testing te-tag-query submit' \
-l RED \
-s UNKNOWN \
-y INFO \
-r REVIEWED_MANUALLY \
-p HAS_WHITELIST \
-m 1064060413755420,494491891138576 \
--tags pwny,testing \
--related-ids-for-upload 3679532438786765,3149337578431046
URL:
https://graph.facebook.com/v4.0/threat_descriptors/?access_token=REDACTED
POST DATA:
type=HASH_SHA1
&description=testing+te-tag-query+submit
&share_level=RED
&status=UNKNOWN
&privacy_type=HAS_WHITELIST
&privacy_members=1064060413755420%2C494491891138576
&tags=pwny%2Ctesting
&review_status=REVIEWED_MANUALLY …
```

Add --related-ids-for-upload to post request

---

hashing/te-tag-query-java/README.md
hashing/te-tag-query-java/com/facebook/threatexchange/DescriptorPostParameters.java
hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java

Test plan:
* In the TEUI look for indicator type `HASH_SHA1` and indicator text `dabbad00f00dfeed5ca1ab1ebeefca11ab1ec00a`
* Fan out by related in the TEUI and see 5 descriptors
* Run the code on this diff:
```
$ alias jtq='java com.facebook.threatexchange.TETagQuery'
$ jtq -s submit \
-t HASH_SHA1 \
-i dabbad00f00dfeed5ca1ab1ebeefca11ab1ec00a \
-d 'testing te-tag-query submit' \
-l RED \
-s UNKNOWN \
-y INFO \
-r REVIEWED_MANUALLY \
-p HAS_WHITELIST \
-m 1064060413755420,494491891138576 \
--tags pwny,testing \
--related-triples-for-upload-as-json '[{"owner_app_id":494491891138576,"td_indicator_type":"HASH_SHA1","td_raw_indicator":"dabbad00f00dfeed5ca1ab1ebeefca11ab1ec00b"}]'
```
* Again fan out by related in the TEUI and see there are now 6, with the new one being the one just posted

related-triples-for-upload-as-json support

---

hashing/te-tag-query-java/com/facebook/threatexchange/DescriptorPostParameters.java
hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java
hashing/te-tag-query-ruby/TENet.rb
hashing/te-tag-query-ruby/TETagQuery.rb

Two apps, single threat descriptor, initially no reactions by either of them.
```
$ te-tag-query-ruby -a TX_ACCESS_TOKEN_MHST ids-to-details 2589692907727086 | jq .reactions
null
```
First app reacts
```
$ te-tag-query-ruby -a TX_ACCESS_TOKEN_MHST update --reactions-to-add HELPFUL -i 2589692907727086
{"success":true}
$ te-tag-query-ruby -a TX_ACCESS_TOKEN_MHST ids-to-details 2589692907727086 | jq .reactions
[
{
"key": "HELPFUL",
"value": "1064060413755420"
}
]
```
Second app reacts
```
$ te-tag-query-ruby -a TX_ACCESS_TOKEN_MHSRFT update --reactions-to-add HELPFUL,INGESTED -i 2589692907727086
{"success":true}
$ te-tag-query-ruby -a TX_ACCESS_TOKEN_MHST ids-to-details 2589692907727086 | jq .reactions
[
{
"key": "HELPFUL",
"value": "494491891138576,1064060413755420"
},
{
"key": "INGESTED", …
```

Query reactions in Ruby; add/remove reactions in Java and Ruby

---

hashing/te-tag-query-python/README.md
hashing/te-tag-query-python/TE.py
hashing/te-tag-query-python/TETagQuery.py
hashing/te-tag-query-python/te-tag-query-python
hashing/te-tag-query-ruby/README.md
hashing/te-tag-query-ruby/TENet.rb
hashing/te-tag-query-ruby/TETagQuery.rb

First commit: Python port.
Second commit: creation of `AbstractPostSubcommandHandler` for improved code-reuse between `submit` and `update`, as the third commit will introduce a `copy` alongside them.
Third commit: the `copy` functionality.
Fourth commit: some comment-neatens.
Testing: run all the commands in `README.md` for Ruby as well as Python.

Python port; bulk-copy feature

---

hashing/te-tag-query-python/TE.py
hashing/te-tag-query-ruby/TENet.rb

I tried running all of `te-tag-query-ruby tag-to-details media_type_video` and `te-tag-query-python tag-to-details media_type_video` and realized the Python netlib is apparently more brittle with respect to transient 500s than Ruby's or Java's. Mean time to failure is around every 30K/50K descriptors retrieved so this issue only arises on get-all-the-data pulls of bigger datasets.

Retry transient 500s on the Python side

---

hashing/te-tag-query-python/TE.py
hashing/te-tag-query-python/TETagQuery.py
hashing/te-tag-query-ruby/TENet.rb
hashing/te-tag-query-ruby/TETagQuery.rb

Details/rationale in comments.
Tested via
```
te-tag-query-python tag-to-details \
--created-since 2020-06-01T00:00:00Z \
--created-until 2020-06-03T00:00:00Z \
tag-name-goes-here \
| jq .added_on
te-tag-query-python tag-to-details \
--created-since -2weeks \
--created-until -1week \
tag-name-goes-here \
| jq .added_on
```
and checking timestamps are in the desired range.

Python/Ruby created-at filters

---

hashing/te-tag-query-java/README.md
hashing/te-tag-query-java/te-tag-query-java

```
$ ./hashing/te-tag-query-python/te-tag-query-python --help
Usage: ./hashing/te-tag-query-python/TETagQuery.py [options] {verb} {verb arguments}
Downloads descriptors in bulk from ThreatExchange, given
either a tag name or a list of IDs one per line on standard input.
Options:
-h|--help      Show detailed help.
--list-verbs   Show a list of supported verbs.
-q|--quiet     Only print IDs/descriptors output with no narrative.
-v|--verbose   Print IDs/descriptors output along with narrative.
-s|--show-urls Print URLs used for queries, before executing them.
-a|--app-token-env-name {...} Name of app-token environment variable.
Defaults to "TX_ACCESS_TOKEN".
-b|--te-base-url {...} Defaults to "https://graph.facebook.com/v6.0"
Verbs:
look-up-tag-id
tag-to-ids
ids-to-details
tag-to-details …
```

Add invoke-from-anywhere Java wrapper, as for Python/Ruby

---

hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java

Use page size 10 by default since this is needed for large TMK hashes and a priori we don't know which queries will or won't be fetching TMKs.

Use page size 10 by default in the Java implementation

---

hashing/te-tag-query-curl/README.md

Use page size 10 by default since this is needed for large TMK hashes and a priori we don't know which queries will or won't be fetching TMKs.

Use page size 10 by default

---

hashing/te-tag-query-python/TETagQuery.py

This PR adds a python convention for files which contains the main, so that they can be loaded without executing the main if loaded by another library. More details can be found here: https://stackoverflow.com/questions/419163/what-does-if-name-main-do
Test plan:
` ./te-tag-query-python --help
Usage: ./TETagQuery.py [options] {verb} {verb arguments}
Downloads descriptors in bulk from ThreatExchange, given
...
`

[te-tag-query][py] Add __name__ == '__main__'

---

hashing/te-tag-query-ruby/TETagQuery.rb

Testing:
```
$ ruby -I . TETagQuery.rb
Usage: te-tag-query [options] {verb} {verb arguments}
Downloads descriptors in bulk from ThreatExchange, given
either a tag name or a list of IDs one per line on standard input.
Options:
-h|--help      Show detailed help.
--list-verbs   Show a list of supported verbs.
-q|--quiet     Only print IDs/descriptors output with no narrative.
-v|--verbose   Print IDs/descriptors output along with narrative.
-s|--show-urls Print URLs used for queries, before executing them.
-a|--app-token-env-name {...} Name of app-token environment variable.
Defaults to "TX_ACCESS_TOKEN".
-b|--te-base-url {...} Defaults to "https://graph.facebook.com/v6.0"
Verbs:
look-up-tag-id
tag-to-ids
ids-to-details
tag-to-details
paginate
submit
update
copy
```
and
```
$ …
```

mimic https://github.com/facebook/ThreatExchange/pull/252 for Ruby

---

hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java
hashing/te-tag-query-python/TETagQuery.py
hashing/te-tag-query-ruby/TETagQuery.rb

Step 1 in a sequence of PRs to add some recent Ruby-port/Java-port features to the Java port.
This commit moves some submit-handler/update-handler logic to a shared parent class so that it will be easier to reuse code for a new copy-handler on a subsequent PR.
Testing: run all the commands in the `README.md`.

AbstractPostSubcommandHandler refactor

---

hashing/te-tag-query-java/APIExamples.java
hashing/te-tag-query-java/README.md
hashing/te-tag-query-java/com/facebook/threatexchange/DescriptorPostParameters.java
hashing/te-tag-query-java/com/facebook/threatexchange/Net.java
hashing/te-tag-query-java/com/facebook/threatexchange/TETagQuery.java
hashing/te-tag-query-python/README.md
hashing/te-tag-query-python/TE.py
hashing/te-tag-query-python/TETagQuery.py
hashing/te-tag-query-python/api-example-copy.py
hashing/te-tag-query-python/api-example-submit.py
hashing/te-tag-query-python/api-example-update.py
hashing/te-tag-query-ruby/README.md
hashing/te-tag-query-ruby/TENet.rb
hashing/te-tag-query-ruby/TETagQuery.rb
hashing/te-tag-query-ruby/api-example-copy.rb
hashing/te-tag-query-ruby/api-example-submit.rb
hashing/te-tag-query-ruby/api-example-update.rb

The main commit https://github.com/facebook/ThreatExchange/pull/259/commits/33db3614eebebcde3f85f16d36f9eec70479500d demonstrates how to use the API (as currently articulated), pulled out from the main `TETagQuery` programs. The commits below are supporting neatens/enables.
Regression testing: run all the commands in all the `hashing/te-tag-query-*/README.md` files
Testing for the new API examples:
```
cd ../te-tag-query-python
python api-example-submit.py
python api-example-copy.py
python api-example-update.py
cd ../te-tag-query-ruby/
ruby api-example-submit.rb
ruby api-example-update.rb
ruby api-example-copy.rb
cd ../te-tag-query-java/
javac com/facebook/threatexchange/*.java APIExamples.java
java APIExamples
```

API examples

---

hashing/te-tag-query-python/TETagQuery.py
hashing/te-tag-query-python/all-in-one
hashing/te-tag-query-python/all_in_one_lib/all_in_one.py
hashing/te-tag-query-python/all_in_one_lib/collab_config.py
hashing/te-tag-query-python/all_in_one_lib/commands/base.py
hashing/te-tag-query-python/all_in_one_lib/commands/fetch.py
hashing/te-tag-query-python/all_in_one_lib/commands/label.py
hashing/te-tag-query-python/all_in_one_lib/commands/match.py
hashing/te-tag-query-python/all_in_one_lib/common.py
hashing/te-tag-query-python/all_in_one_lib/content_type/base.py
hashing/te-tag-query-python/all_in_one_lib/content_type/meta.py
hashing/te-tag-query-python/all_in_one_lib/content_type/photo.py
hashing/te-tag-query-python/all_in_one_lib/content_type/text.py
hashing/te-tag-query-python/all_in_one_lib/content_type/video.py
hashing/te-tag-query-python/all_in_one_lib/dataset.py
hashing/te-tag-query-python/all_in_one_lib/descriptor.py
hashing/te-tag-query-python/all_in_one_lib/signal_type/base.py
hashing/te-tag-query-python/all_in_one_lib/signal_type/md5.py
hashing/te-tag-query-python/all_in_one_lib/signal_type/pdq.py
hashing/te-tag-query-python/all_in_one_lib/signal_type/raw_text.py
hashing/te-tag-query-python/all_in_one_lib/signal_type/trend_query.py
hashing/te-tag-query-python/all_in_one_lib/signal_type/url.py
hashing/te-tag-query-python/all_in_one_lib/signal_type/video_tmk_pdqf.py

Summary:
This is a heroic stab at an attempt to simplify integration to
ThreatExchange collaborations. The primary thesis is that there are
small number of actual decision points to getting the data for a
collaboration and experimenting with it, but that there are enough
nuances (like, anything other than the tag-query API is suspect), that
the cost to actually onboarding is significant.
This commit attempts to remediate that with the following approach:
1. Encode what encompasses as "collaboration", usually backed by a
privacy group, into a file that can be distributed instead of
a bulky pack of documentation with those same conventions.
2. Provide a fast path for fetching all of the dataset that makes
up a collaboration.
3. Provide reference matching implementation in line with the …

[all-in-one] Base implementation for the all-in-one library

---

.github/workflows/ruby-ci.yaml

This action will help with validating PRs to the ruby library by automating install the gem dependencies and running the existing tests for the ruby library.
Sample Run in my fork showing PR triggered the action and successfully executed the ruby test.
- https://github.com/bodnarbm/ThreatExchange/pull/2

Add ruby ci github action

---

.gitignore

Summary:
Python build process generates artifacts in the `build/`,
`dist/` and `pytx3.egg-info/` folders that should not be
committed in git.
Test Plan:
```
$ pip install setuptools wheel
$ python setup.py sdist bdist_wheel
$ git status
```
Confirm build artifacts are not being enumerated by git
Reviewers: @Dcallies
Subscribers:
Tasks:
Tags:

Ignore python build artifacts in git

---

pytx3/pytx3/commands/fetch.py

Summary:
Sample is supposed to prefer a sample label if provided.
If no label is provided, it only fetches the first 20 items.
I missed a variable :'(
Test Plan:
Used a large dataset from one of our collabs, added a sample tag, then added
enough print()'s to confirm only the sample was being fetched.
Reviewed by: @bodnarbm

[pytx3] Fix bug with fetch --sample labels

---

pytx3/pytx3/cli/fetch.py
pytx3/pytx3/signal_type/url.py

Summary:
This diff tries to improve fetch speeds by making a lot
of asyncronous requests. I structured it to play nicely with some
kind of sequential descriptor-based checkpointing in the future as
well, which would be able to resume from an error/CTRL+C in the middle
of execution as part of some future diff.
Test Plan:
```
$ time time pytx3 -c ~/large_dataset.te.cfg -s /tmp/fetch_speed fetch
...
video_tmk_pdqf: 15201
photo_md5: 8035
video_md5: 8788
trend_query: 75
pdq: 55157
raw_text: 31757
real    54m37.870s
user    4m7.598s
sys     0m38.539s
$ time time pytx3 -c ~/large_dataset.te.cfg -s /tmp/fetch_speed fetch
...
trend_query: 75
video_tmk_pdqf: 15235
photo_md5: 8035
pdq: 55250
video_md5: 8806
raw_text: 31757
real    4m39.773s
user    4m1.313s
sys     1m0.557s
```
Reviewed by: …

[pytx3] Fetch 12x faster with 100x threads

---

pytx3/pytx3/cli/fetch.py
pytx3/pytx3/content_type/meta.py
pytx3/pytx3/dataset.py
pytx3/setup.py

This is a squash of 3 features:
[Incremental Fetch]
Summary:
This diff switches the update model to allow for
incremental updates instead of fully refetching all data,
which it will save network time.
In practice the cost of writing the gigantic PDQF+TMK files
dominates the actual fetch time at this point, so that's the
next diff.
Test Plan:
```
$ time pytx3 -c ~/medium_sized.te.cfg -s /tmp/fetch_speed fetch --until=1589958000 --full
trend_query: 1
video_tmk_pdqf: 131
photo_md5: 8035
pdq: 30
video_md5: 48
raw_text: 120
real    0m15.033s
user    0m6.256s
sys     0m1.673s
$ time pytx3 -c ~/medium_sized.te.cfg -s /tmp/fetch_speed fetch --until=1589968000
Doing an incremental update - this will miss some updates and deletes.
Use --full to force a refetch.
video_tmk_pdqf: 2
video_md5: 1
real …
```

[pytx3] Fetch incrementally & partially + 0.07 Release

---

pytx3/pytx3/cli/fetch.py
pytx3/pytx3/cli/main.py

Summary:
Minor cleanups from the stack that I was too dumb to
figure out how to rebase through properly.
1. Move thread pool to with block (note that this causes delays on CTRL+C now)
2. Catch keyboard interrupt and return 130 like a good program should
3. Make first status print happen faster so you know the tool isn't stuck
Test Plan:
```
$ time pytx3 -c ~/covid19.te.cfg -s /tmp/fetch_speed fetch -n video_tmk_pdqf --full
Ignoring some signal types will lead to only part of the dataset being fetched until fixed with --full.
Processed 1966...
^C
real    0m8.011s
user    0m3.069s
sys     0m0.617s
```

[pytx3] Cleanups from stack

---

hashing/te-tag-query-python/TE.py
hashing/te-tag-query-python/TETagQuery.py

Still needs doc examples, which should be done on a separate PR since the server-side has a bit of rework to do before this will be ready for prime time.
Testing:
```
$ te-tag-query-python power-search --since 100 --tags-are-anded --tags pwny,testing | jq . | head -n 20
{
"raw_indicator": "dabbad00f00dfeed5ca1ab1ebeefca11ab1ec0cf",
"type": "HASH_SHA1",
"added_on": "2020-07-02T19:56:05+0000",
"last_updated": "2020-07-27T18:42:17+0000",
"confidence": 100,
"owner": {
"id": "494491891138576",
"email": "threatexchange@fb.com",
"name": "Media Hash Sharing RF Test"
},
"privacy_type": "HAS_PRIVACY_GROUP",
"review_status": "REVIEWED_AUTOMATICALLY",
"status": "NON_MALICIOUS",
"severity": "INFO",
"share_level": "AMBER",
"tags": null,
"description": "another copy",
"id": "1791017857689049"
}
```

python power-search wrapper

---

pytx3/pytx3/collab_config.py

Summary:
This diff removes the content_types field (didn't get used),
and also makes all fields except labels optional.
This makes the smallest functional config something like:
```
{"labels": ["media_priority_samples"]}
```
Test Plan: Used the config from the summary, successfully fetched.

[pytx] Make more config fields optional

---

pytx3/pytx3/cli/fetch.py

Summary: 
Some leftover bugs from the stack.
Test Plan:
```
pytx3 fetch
```
Doesn't asplode

[pytx3] Fix some bugs with fetch

---

pytx3/pytx3/signal_type/signal_base.py

Summary: In the ye olden days, you would show which types of signals
you supported by which functions didn't throw exceptions.
Now there are some superclasses. Remove the extra signatures
to make that relation more clear.
Test Plan: fetch --full and match some data.

[pytx3] Remove redundant function signatures

---

pytx3/pytx3/cli/fetch.py

Summary: In a previous stack, I had a nasty conflict that I appear to
have fixed incorrectly. This re-adds the code that drains the rest of
the queue at the end of tagging.
Test Plan: pytx3 fetch, gets data instead of erroring.

[pytx3] Fix merge conflict bug in fetch

---

.github/workflows/golang-ci.yaml
api-reference-examples/go/threatexchange/threatexchange.go

This adds a github action to run go tests on the go example in the api-references-example folder. This actually caught an issue with our existing code that is fixed in this PR also.
Test Plan:
Action should run on this PR and we should see a green checkmark when it is completed in the below status checks.

Adding github action for Go API Example

---

api-reference-examples/go/threatexchange/threatexchange.go
api-reference-examples/go/threatexchange/threatexchange_test.go

Facebook graph returns date by default in a string representation
using the ISO-8601 format. For now, we can fix unmarshalling the json
by using a string instead of an int.
Fixes #196
Test Plan:
Tested this locally by setting the environment variables TX_APP_ID and TX_APP_SECRET for a test application and then executed the following in the go implementation folder
```
$ go test -v -run TestQueryThreatDescriptorsOfIpsProxy
=== RUN   TestQueryThreatDescriptorsOfIpsProxy
--- PASS: TestQueryThreatDescriptorsOfIpsProxy (0.77s)
=== RUN   TestQueryThreatDescriptorsOfIpsProxyByFBAdminOwner
--- PASS: TestQueryThreatDescriptorsOfIpsProxyByFBAdminOwner (1.19s)
PASS
ok      _/Users/bodnarbm/github/ThreatExchange/api-reference-examples/go/threatexchange 2.116s
```

[go] fix json unmarshalling for expired_on for ThreatDescriptor

---

hashing/pdq/README.md
hashing/tmk/README.md

There are a number of external links that deep linked to both the old
pdq and tmk folders within the hashing folder. These include links in
academic papers and in news articles regarding the initial opensourcing
of PDQ and TMK.
Adding some simple README files should prevent viewers getting GitHub
404 pages when trying to go to those locations within the new directory
structure.

Add READMEs for old hashing locations to redirect viewers to new folders

---

.github/workflows/pytx3-ci.yaml
pytx3/CONTRIBUTING.md

For fast feedback when submitting PRs, we will want to create a full
CI suite to run on changes for pytx3. To get started, this merely
runs the code through the black code formatter's check function.

Create initial pytx3 ci with lint check

---

.github/workflows/pytx3-ci.yaml
pytx3/.gitignore
pytx3/Makefile
pytx3/setup.py
pytx3/tests/test_common.py

Adds basic test running using pytest to the pr ci builds for pytx3.
Additionally adds a very basic test to give the ci something to run as a starting point.

Add testing to pytx3 ci

---

.github/workflows/pytx3-ci.yaml

Currently our CI tests run only against python 3.8. This adds
support for running CI tests with Python 3.6 and 3.7 also. (Python
3.6 being the lowest we state we support for pytx3).

Support Python 3.6 and 3.7 in CI tests

---

pytx3/pytx3/hashing/pdq_faiss_matcher.py
pytx3/tests/hashing/test_pdq_faiss_matcher.py

Summary
========
Creates a PDQMultiHashIndex that uses the faiss IndexBinaryMultiHash
class. This will use Multi-Index Hashing for searches on hashes, which
should provide for optimistically sub-linear hash lookups.
Test Plan
=========
Create additional unit tests to cover this new class, and run locally with
```shell
$ py.test
```

Create PDQ Hash Index using Multi-Index Hashing

---

pytx3/pytx3/hashing/pdq_faiss_matcher.py
pytx3/tests/hashing/test_pdq_faiss_matcher.py

Summary
========
Presently, we need to keep an companion index in memory to convert
the faiss index search results (which are indices in the index) back
to the PDQ hash string.
This change uses the reconstruct method on the two types of faiss indexes
we are using to recompute those hash values on search results. This
should reduce the memory requirements for these classes (and the
eventual size of the classes on disk once we support serializing them)
by around n*32 bytes, where n is the number of hashes in the index.
Test Plan
=======
Added a common test to the indexes for looking up the hash at a given place, and ensured
that the prior tests all still pass.

Use faiss index to reconstruct hash in search results

---

pytx3/benchmarks/benchmark_pdq_faiss_matchers.py

Summary
=======
An initial simple benchmark for comparing the runtimes of the flat and
multi-index hashing versions of the faiss pdq matchers.
Test Plan
=========
From within the pytx3 folder, and with all dependencies installed (including the 'faiss' extra)
```shell
> python3 benchmarks/benchmark_pdq_faiss_matchers.py
Benchmark: PDQ Faiss Matcher Comparison
Options:
faiss_threads :  1
dataset_size :  250000
num_queries :  1000
thresholds :  [0, 15, 31, 47]
seed :  None
using random seed of  1603988652838031000
use --seed  1603988652838031000  to rerun with same random values
Building Stats:
PDQFlatHashIndex: time to build (s):  0.28624796867370605
PDQMultiHashIndex: time to build (s):  2.1199889183044434
Benchmarks for threshold:  0
PDQFlatHashIndex - Total Time to search  (s): …
```

Initial benchmark script for comparing run times for faiss pdq matchers

---

pytx3/pytx3/hashing/pdq_faiss_matcher.py
pytx3/tests/hashing/test_pdq_faiss_matcher.py

Summary
=======
The underlaying faiss indexes for the PDQHashIndex classes do not
natively support pickling (serialization) of the data to bytes.
Adding support for pickling will allow us to easily save and load
these indexes from files or over a network connection (for example
during a map-reduce or batch job).
This work is dependent upon #309. I will rebase off of #309 once that merges.
Test Plan
======
Added additional testing that runs the common PDQHashIndex tests against a reserialized form of the test subject. This is to ensure that functionality remains the same with the index once it was be serialized and then deserialized.

Add pickle support to pdq hash indexes

---

pytx3/benchmarks/benchmark_pdq_faiss_matchers.py

Summary
=========
To help understand index selection choice on memory requirements,
adding some benchmark output for how approximately how much storage
is needed for the serialized form for the indexes.
Test Plan
========
Ran the benchmark locally and noted the below output
```
(threatexchange) ➜  pytx3 git:(add-memory-benchmark-for-faiss-indexes) python benchmarks/benchmark_pdq_faiss_matchers.py                   
Benchmark: PDQ Faiss Matcher Comparison
Options:
faiss_threads :  1
dataset_size :  250000
num_queries :  1000
thresholds :  [0, 15, 31, 47]
seed :  None
using random seed of  1604086833819350000
use --seed  1604086833819350000  to rerun with same random values
Building Stats:
PDQFlatHashIndex: time to build (s):  0.3096351623535156
PDQFlatHashIndex: approximate size: 7,812KB …
```

Add memory information to faiss index benchmarks

---

pytx3/tests/hashing/test_pdq_faiss_matcher.py

Summary
---------
To prepare for changes related to supporting optional custom ids for the PDQHashIndexes, this PR refactors
the existing tests to
1) Make checks on whether the index is picklable a commont test; and
2) Make tests for extracting hashes by id via `hash_at` index specific.
Making these changes in advance should make it easier to add the custom ids support without added noise in
the test code.
Test Plan
---------
`py.test`

Refactor PDQHashIndex Common Tests

---

.github/labeler.yml

Summary
---------
Any PR after this that touches the PDQ code directly should have a `pdq` label attached to it automatically.
Test Plan
---------
No yaml linter warnings in my IDE.

Add `pdq` labels to PRs affecting pdq code

---

.github/workflows/pdq-ci-cpp.yml

Summary
---------
Adds a very simple CI workflow to test the pdq cpp build using the current `make` default target. This will test both building the code and running the regression tests that the cpp PDQ already has.
Test Plan
---------
This PR should pass its status checks, including the new CI job.

Add basic ci for testing PDQ cpp code.

---

.github/workflows/repo-stale-issues.yml

Summary
---------
Add GitHub action to mark and comment on stale issues, and later close them if there is no activity.
Set the current timeframes to 90 days with no activity before marking an issue as stale, and 2 weeks graceperiod before closing.
Test Plan
---------
Unfortuately, this is difficult to test as the action needs to run in a cron job. Mostly just compared the settings with the examples at https://github.com/actions/stale and ensured that my IDE yaml linter did not identify any errors.

Mark and close stale issues

---

pytx3/benchmarks/benchmark_pdq_faiss_matchers.py
pytx3/pytx3/hashing/pdq_faiss_matcher.py
pytx3/tests/hashing/test_pdq_faiss_matcher.py

Summary
---------
Later PRs will enable tying PDQ Hashes to ThreatExchange IDs to enable reacting to the PDQ hash with a
`SAW_THIS_TOO` tag. This PR lies the foundation for supporting custom ids within the indexes themselves
using the faiss indexes support for custom ids. 
There are some existing issues within faiss for supporting reconstructing hashes from an custom id for 
the MultiHash binary indexes, but this PR contains a workaround until that can be fixed upstream. I will
create the issue in the faiss repo and make PRs there to have those resolved. Until then, the workaround
just adds some additional memory cost but doubling up on the reverse lookup map that is already present
in the faiss data structure.
Test Plan
---------
Added unit test cases for custom ids and tested with …

Support custom ids for PDQ hash indexes

---

pdq/cpp/common/pdqhashtypes.h

Summary
---------
The word array in the Hash256 type is zeroed on the right boundary,
meaning the zeroth element of the word array represents the last 4
hex characters in the hex. However, both the dumpBits and dumpWords
functions in Hash256 assumed the array was zeroed on the left boundary
of the hash.
This fixes the iteration order for those functions to match the output
of the same tool in Java.
Fixes #319
Test Plan
---------
```
➜  cd pdq/cpp 
➜  make clean hashtool256
g++ -g -std=c++11  -I../.. -I. -Wall -Wno-char-subscripts -Werror -O3 bin/hashtool256.cpp common/pdqhashtypes.cpp io/hashio.cpp common/pdqhamming.cpp hashing/pdqhashing.cpp downscaling/downscaling.cpp io/pdqio.cpp hashing/torben.cpp -o hashtool256 -lm
➜  echo "0000111122223333444455556666777788889999aaaabbbbccccddddeeeef …
```

Fix hashtool256 output ordering

---

pytx3/benchmarks/benchmark_pdq_faiss_matchers.py
pytx3/pytx3/hashing/__init__.py

Summary
---------
Adding the PDQHashIndex classes to the `pytx3.hashing` package will make it easier for callers to import, and in the future enable us
to provide fall back implementations that don't use faiss for the cases where faiss is not installed. This also adds an import
warning directing users to install the faiss extra if they want to make use of these extras. 
Test Plan
---------
After uninstalling faiss-cpu from my virtual environment using `pip uninstall faiss-cpu`
```
$ python -c 'from pytx3.hashing import PDQFlatHashIndex'
File "<string>", line 1, in <module>
ImportError: cannot import name 'PDQFlatHashIndex' from 'pytx3.hashing' (/Users/bodnarbm/github/ThreatExchange/pytx3/pytx3/hashing/__init__.py)
$ python -c 'import pytx3.hashing' …
```

Conditionally import PDQ matchers in `pytx3.hashing`

---

.github/workflows/repo-stale-issues.yml

Summary
---------
Adding support for the existing do-not-reap tag to have it not auto close issues that we mark with that tag. This is useful for issues for example where we are requesting community help with addressing but there is no current timeline for.
Additionally, minor fix of the yaml formatting for the messages to make them not insert new lines on the GitHub messages themselves.
Test Plan
---------
yaml linting only. Needs to run on GitHub itself after merging.

Add do-not-reap support for stale issue action

---

pytx3/pytx3/hashing/pdq_faiss_matcher.py
pytx3/tests/hashing/test_pdq_faiss_matcher.py

Summary
---------
Useful especially in the cases where a custom id has been set for the hashes
in the index, allowing the search results to be the id instead of the hash
will help callers that are using that id to lookup the information in another
datastore.
Test Plan
---------
Added tests and ran them with `py.test`

Add option to return only the id when searching PDQ hashes

---

.github/workflows/pytx3-release.yaml
pytx3/setup.py

Summary
---------
To make releasing easy and encourge frequent releases, we can automate the packaging of new versions of pytx3. This workflow will automatically create the pytx3 release and upload it to the Test PyPI repowheneve a commit lands in master that alters the pytx3 version file.
Test Plan
---------
Simple yaml testing for now. After this lands, we will cut a release of pytx3 to test the workflow properly using the test pypi index. Once that is successful, we will followup with another PR that adds uploading to the production pypi index.

Setup CI workflow to automate pytx3 releases

---

.github/workflows/pytx3-release.yaml

Summary
---------
The pypa/gh-action-pypi-publish action does not respect the working-directory setting, so we need to let it know where the dist folder will be from the repo root.
Test Plan
---------
[Executed action on my local fork](https://github.com/bodnarbm/ThreatExchange/runs/1426584148?check_suite_focus=true) (without the github secret) and verified that it make it through the finding the dist folder phase. Note: action still failed before there is no upload token in my fork.

Specify dists folder for pypi packages

---

python-threatexchange/CONTRIBUTING.md

Summary
---------
Basic release steps for publishing to PyPI
Test Plan
---------
Review only - Documentation change.

Add release documentation for releasing to PyPI.

---

python-threatexchange/threatexchange/cli/main.py

Summary
---------
See title
Test Plan
---------
Before:
```
$ threatexchange 
File "/Users/barrett/homebrew/bin/threatexchange", line 33, in <module>
sys.exit(load_entry_point('threatexchange', 'console_scripts', 'threatexchange')())
File "/Users/barrett/dev/github/ThreatExchange/python-threatexchange/threatexchange/cli/main.py", line 149, in main
execute_command(namespace)
File "/Users/barrett/dev/github/ThreatExchange/python-threatexchange/threatexchange/cli/main.py", line 70, in execute_command
if namespace.command_cls is None:
AttributeError: 'Namespace' object has no attribute 'command_cls'
```
After:
```
$ threatexchange 
usage: threatexchange [-h] [--config CONFIG] [--app-token TOKEN] [--state-dir DIR] {fetch,experimental-fetch,match,label} ...
A …
```

Check if no command is given to python-threatexchange and print help if so

---

python-threatexchange/setup.py
python-threatexchange/tests/hashing/test_pdq_utils.py
python-threatexchange/threatexchange/hashing/__init__.py
python-threatexchange/threatexchange/hashing/pdq_faiss_matcher.py
python-threatexchange/threatexchange/hashing/pdq_hasher.py
python-threatexchange/threatexchange/hashing/pdq_utils.py
python-threatexchange/threatexchange/signal_type/pdq.py

Summary
Add Simple pdq matching functionality.
Test Plan
`python3 -m pytest python-threatexchange/tests/hashing/test_pdq_utils.py`

Add simple pdq matcher

---

python-threatexchange/threatexchange/TE.py
python-threatexchange/threatexchange/cli/experimental_fetch.py
python-threatexchange/threatexchange/dataset.py
python-threatexchange/threatexchange/indicator.py
python-threatexchange/threatexchange/signal_type/signal_base.py

Summary
---------
Update experimentalfetch to work with the new version of threat_updates. Make experimentalfetch more resilient by adding error handling and more thorough checkpointing. Update the indicator "storage system" to no longer rely on signal types and instead store based on indicator type.
Test Plan
---------
1. verify fetch still works:
Ran: "threatexchange -c ~/large_dataset_collab.te.cfg fetch --until-timestamp `date -j -vMarm -v1d -v2018y '+%s'`" to competition.
Also used fetch to query the entire large dataset set.
2. Verify experimentalfetch gets everything:
Ran: "threatexchange -c ~/large_dataset_collab.te.cfg experimental-fetch" on the large dataset collaboration and it queried to completion getting ~1.93m records
3. Verify experimentalfetch  --start-time and --end-time …

Update experimentalfetch to work with the new version of threat_updates

---

python-threatexchange/setup.py
python-threatexchange/threatexchange/TE.py
python-threatexchange/threatexchange/common.py

Summary
---------
Because requests is much more high-level, it allows easily setting up
retries / timeouts and can be configured going ahead to support proxies
and .netrc and all the goodness!
Test Plan
---------
Two changes were made. The GET and POST commands.
For GET, I removed 'threatexchange_samples' and ran a random command. The directory was setup as expected using the requests code.
**Output**
```shell
$> threatexchange match text "ball now?"                                                                          ~
Looks like you haven't set up a collaboration config, so using the sample one against public data
Looks like you are running this for the first time. Fetching some sample data.
raw_text: 3
url: 1
pdq: 138
video_tmk_pdqf: 1
photo_md5: 1
video_md5: 2
trend_query: 1  
``` …

Use requests instead of urllib for TE.py

---

python-threatexchange/threatexchange/cli/label.py

Summary
---------
LabelCommand argument spec is used to translate argparse arguments into constructor arguments. These were not in sync. The diff addresses that. It ensures the `LabelCommand.__init__(...)` arg spec is the same as the argparse spec defined in [LabelCommand.init_argparse](https://github.com/facebook/ThreatExchange/blob/64767362c3489c9057ba7a554d330b2ad3ad740c/python-threatexchange/threatexchange/cli/label.py#L33) method.
Test Plan
---------
Command:
```shell
$> threatexchange label false_positive descriptor 3425830734108278       
```
Used to fail with
```
File "/Users/dipanjanm/.pyenv/versions/3.8.6/bin/threatexchange", line 33, in <module>
sys.exit(load_entry_point('threatexchange', 'console_scripts', 'threatexchange')())
File …
```

Get Label command to work

---

python-threatexchange/setup.py
python-threatexchange/threatexchange/common.py
python-threatexchange/threatexchange/content_type/photo.py
python-threatexchange/threatexchange/hashing/ocr_utils.py
python-threatexchange/threatexchange/signal_type/pdq.py
python-threatexchange/threatexchange/signal_type/pdq_ocr.py
python-threatexchange/threatexchange/signal_type/raw_text.py

Summary
---------
This PR adds fetching and matching functionality for the PDQ_OCR signal type. 
(Experimental: If https://github.com/tesseract-ocr/tesseract is installed it can also attempt to get the text from a given file and use it for matching.)
Test Plan
---------
```
$ threatexchange fetch --full 
Looks like you haven't set up a collaboration config, so using the sample one against public data
video_md5: 2
raw_text: 3
pdq_ocr: 2
video_tmk_pdqf: 1
photo_md5: 1
url: 1
trend_query: 1
pdq: 138
```
```
$ threatexchange match photo -H '<PDQ-HASH>,This is a sample text string' --show-false-positives 
Looks like you haven't set up a collaboration config, so using the sample one against public data
<ThreatDescriptor ID>  pdq_ocr disputed
```

Add support for PDQ_OCR signal type

---

hasher-matcher-actioner/hashing-data/main.tf

Summary
---------
It's very easy to leave dangling s3 buckets in our current setup. Allow force deletion for non-empty stuff.
Test Plan
---------
terragraph plan
```
+ resource "aws_s3_bucket" "data_bucket" {
+ acceleration_status         = (known after apply)
+ acl                         = "private"
+ arn                         = (known after apply)
+ bucket                      = (known after apply)
+ bucket_domain_name          = (known after apply)
+ bucket_prefix               = "hma-hashing-data"
+ bucket_regional_domain_name = (known after apply)
+ force_destroy               = true
```

[hma] Force delete s3 buckets (for now)

---

python-threatexchange/threatexchange/cli/command_base.py

Was just bothering me. I also wrote the code that broke it,
so /shrug
Before:
```
$ threatexchange --help
verbs:
{fetch,experimental-fetch,match,label}
which action to do
fetch               download content from ThreatExchange to disk
experimental-fetch  wARNING: This is experimental, you probably want
to
use "Fetch" instead
...
```
After:
```
$ threatexchange --help
verbs:
{fetch,experimental-fetch,match,label}
which action to do
fetch               download content from ThreatExchange to disk
experimental-fetch  warning: This is experimental, you probably want
to
use "Fetch" instead
...
```
Summary
---------
Test Plan
---------

[py-tx] Fix formatting of top level help

---

python-threatexchange/threatexchange/TE.py

Summary
---------
The connect pool is controlled by the adapter, which is closed when the session is closed. If you use new sessions, but reuse the adapter, you'll keep closing the connection pool, which then leads to exceptions.
Fixes: https://github.com/facebook/ThreatExchange/issues/359
Test Plan
---------
Do a fetch on a collaboration with at least 10k items, asplodes before, doesn't asplode afterwards.

[py-tx] Don't reuse adapters

---

python-threatexchange/threatexchange/cli/main.py

Summary
---------
Pasting in the txtoken can be a pain to get right.
One user ran into issues trying to store the file, where
they had a dangling newline at the end. Fix that issue
and try and do better error messages.
Independently, I found that the argument validation
was incorrect, making it extra hard to tell what is
happening.
Fixes #345
Test Plan
---------
```
$ mv ~/.txtoken ~/.txtoken.bak
Can't find App Token, pass it in using one of:
* a cli argument
* in the environment as TX_ACCESS_TOKEN
* in a file at /home/dcallies/.txtoken
https://developers.facebook.com/tools/accesstoken/
[Exit 2]
$ TX_ACCESS_TOKEN=238423849asdf threatexchange fetch
Your current app token (from TX_ACCESS_TOKEN environment variable) is invalid.
Double check that it's an 'App Token' …
```

[py-tx] Trim newlines from .txtoken, better validation

---

python-threatexchange/threatexchange/cli/main.py
python-threatexchange/threatexchange/cli/tests/cli_smoke_test.py

Summary
---------
I've never used pytest, so play with it to write a simple
test that just makes sure all the helps print.
Test Plan
---------
```
$ py.test -s
================================================================= test
session starts
==================================================================
platform linux -- Python 3.6.8, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir:
/data/users/dcallies/fork_te/ThreatExchange/python-threatexchange
collected 1 item
cli/tests/cli_smoke_test.py
$ threatexchange --help
usage: py.test [-h] [--config CONFIG] [--app-token TOKEN] [--state-dir
DIR]
{fetch,experimental-fetch,match,label} ...
A wrapper around multi-stage ThreatExchange operations.
Includes simple matching and writing back. Useful for quickly validating
new
sources of …
```

[py-te] Add some simple tests to learn py.test

---

python-threatexchange/threatexchange/api.py
python-threatexchange/threatexchange/cli/fetch.py
python-threatexchange/threatexchange/cli/label.py
python-threatexchange/threatexchange/descriptor.py

Summary
---------
General python conventions (https://www.python.org/dev/peps/pep-0008/) hold that method names are lower_with_under.
I didn't finish a checkpoint of my main work, and I wanted to put something up before the end of the day, so here you go.
Test Plan
---------
Used only programmatic tools:
```
codemod getJSONFromURL get_json_from_url
codemod getTagIDFromName get_tag_id
codemod getInfoForIDs get_threat_descriptors
codemod validatePostPararmsForSubmit _validate_post_params_for_submit
codemod validatePostPararmsForCopy _validate_post_pararms_for_copy
codemod reactToThreatDescriptor react_to_threat_descriptor
codemod submitThreatDescriptor upload_threat_descriptor
codemod copyThreatDescriptor copy_threat_descriptor
```
Ran 
```
threatexchange fetch
```
To check that it didn't …

[py-tx][high impact] Rename api methods

---

.gitignore
hasher-matcher-actioner/hmalib/dto.py
hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_hasher.py
hasher-matcher-actioner/hmalib/storage/hashstore.py
hasher-matcher-actioner/mypy.ini
hasher-matcher-actioner/requirements-dev.txt
hasher-matcher-actioner/requirements.txt

Summary
---------
The PR turned out to be larger than I had imagined. It does a lot.
1. Adds mypy as a dependency and begins to add type hints to the lambdas. Adds some typing for boto using `boto3-stubs`
1. Converts arbitrary wire-messages (SQS, Dynamo) for hasher lambda into formal data structures
1. Defines a simple wrapper (HashStore) over dynamodb for maintaining hash records, expect more methods from the CLI/Admin surface to go into the wrapper
1. docstring for hasher lambda
Test Plan
---------
```
$> mypy
$> make upload_docker
$> edit hma_lambda_docker_uri variable to point to new sha256 in ECR
$> terraform apply -var "prefix=$(whoami)"
```
Followed by uploading an image to S3 and receiving a match on email.
Note: This was also the first time I edited an existing terraform …

Refactor hasher lambda, define hash store interface, mypy

---

python-threatexchange/threatexchange/cli/dataset_cmd.py
python-threatexchange/threatexchange/cli/experimental_fetch.py
python-threatexchange/threatexchange/cli/main.py
python-threatexchange/threatexchange/dataset.py
python-threatexchange/threatexchange/signal_type/signal_base.py
python-threatexchange/threatexchange/signal_type/trend_query.py
python-threatexchange/threatexchange/threat_updates.py

Summary
---------
Another diff that should have been more diffs! This diff:
1. Adds a formal relationship between indices and signal types
2. Adds a new cli command called "dataset" which can introspect the local store
3. Adds index generation at the end of experimental-fetch
Test Plan
---------
```
$ threatexchange dataset --help
usage: threatexchange dataset [-h] [--rebuild-indices] [--print] [--type STR]
[--indicator-only] [--signal-summary]
Introspect the local ThreatExchange dataset.
Can print out contents in simple formats
(ideal for sending to another system), or regenerate
index files (ideal if distributing indices for some reason)
--rebuild-indices, -r
rebuild indices
--print, -p           print records to …
```

[py-tx] More progress towards indices, dataset command

---

hasher-matcher-actioner/hma-lite/Dockerfile
hasher-matcher-actioner/hma-lite/config/uwsgi.ini
hasher-matcher-actioner/hma-lite/hmalite/app.py
hasher-matcher-actioner/hma-lite/requirements.txt

Summary
---
The flask app doesn't do anything but print "Hello, from the threatexchange API".
Adds a Dockerfile, adds flask to requirements and orchestrates everything with uwsgi, one of the canonical webservers writting in python.
Test Plan
---
```
$> cd hma-lite/
$> docker build -t threatexchange-api:latest -f ThreatExchangeAPI.Dockerfile .
$> docker run -d -p 8080:80 threatexchange-api
```
And then localhost:8080 on your browser.
If you want to develop locally, use flask. First,
```
$> pip install -r requirements.txt # ensures you have flask installed. Only run once.
$> FLASK_APP=hmalite.app:app FLASK_ENV=development flask run
```
And go to the URL you are presented with in the console logs.

Working flask app with dockerfile

---

python-threatexchange/threatexchange/signal_type/index.py
python-threatexchange/threatexchange/signal_type/pdq_index.py
python-threatexchange/threatexchange/signal_type/tests/test_pdq_index.py

Summary
---------
See title. 
~Draft as I am worried this might break imports. 
Test Plan
---------
Created Test
`pytest python-threatexchange/threatexchange/signal_type/tests/test_pdq_index.py`

Adds pdq index wrap for faiss index lib to signal_type

---

hasher-matcher-actioner/hma-lite/hmalite/app.py
python-threatexchange/threatexchange/signal_type/pdq_index.py

Summary
---------
Update serialize for pdq_index to actually follow its type interface 
Test Plan
---------
pytest was green and hmalite ui (to build index still work)

fix pdq_index.serialize to use bytestream param

---

python-threatexchange/threatexchange/cli/hash_cmd.py
python-threatexchange/threatexchange/cli/main.py
python-threatexchange/threatexchange/signal_type/md5.py
python-threatexchange/threatexchange/signal_type/pdq.py
python-threatexchange/threatexchange/signal_type/pdq_ocr.py
python-threatexchange/threatexchange/signal_type/signal_base.py

Summary
---------
This diff adds the "FileHasher" and "StrHasher" interfaces into SignalType, and additionally adds a CLI command to help hash.
The reason I did this is that the current copydays set isn't matching anything, and I can't tell why. I'm worried I generated with the broken version of the pdqhash library.
Rather than doing what I did to generate the PDQhash library, I figured I'd just make it easier to regenerate.
Test Plan
---------
```
$ threatexchange hash --help
usage: threatexchange hash [-h]
[--signal-type {trend_query,raw_text,pdq_ocr,video_tmk_pdqf,photo_md5,video_md5,pdq,url}]
[--as-text] [--read-stdin]
{text,video,photo} content [content ...]
Hash content into signatures.
Reads inputs as filenames by default, or as text with --as-text.
You can also pass in via stdin …
```

[py-tx] Better hashing interfaces

---

.github/workflows/hma-ci-master-push.yaml

Summary
---------
Remove unused `terraform apply` and `terraform destroy` commands in the master CI workflow.
Test Plan
---------
Nope. Only way to know for sure is to merge into master.

Remove unused steps from master CI workflow

---

hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_hasher.py
hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_indexer.py
hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_matcher.py
hasher-matcher-actioner/hmalib/metrics/__init__.py
hasher-matcher-actioner/hmalib/metrics/cloudwatch.py
hasher-matcher-actioner/terraform/main.tf
hasher-matcher-actioner/terraform/pdq-signals/main.tf
hasher-matcher-actioner/terraform/pdq-signals/variables.tf
hasher-matcher-actioner/terraform/variables.tf
hasher-matcher-actioner/tests/scripts/gen-fake-cloudwatch-metrics.py
hasher-matcher-actioner/tests/test_metrics_reporter.py

Summary
---------
* Add a mini-library to measure execution durations and publish to AWS 
* Adds instrumentation to PDQ lambdas. At the end of the lambdas, will flush to cloudwatch.
* Terraform variable to allow measuring metrics
The scripts that will be used to generate load on the lambdas will be added after this is merged.
To the Reviewer, please review each commit separately. The commits are arranged for sane reviewing. 
Test Plan
---------
Individual commits have test plans. Wish we could do stacked diffs here.

Mini-library to measure execution durations and publish to cloudwatch

---

hasher-matcher-actioner/terraform/fetcher/main.tf
hasher-matcher-actioner/terraform/fetcher/outputs.tf
hasher-matcher-actioner/terraform/fetcher/variables.tf
hasher-matcher-actioner/terraform/main.tf

Summary
---------
Pair programmed with @jeberl - base state for the fetcher, with maybe the right permissions, but missing the cloud event for the timer.
Test Plan
---------
```
$ terrform init
$ terraform plan
$ terraform apply
```
Test the lambda by triggering manually

[hma] base terraform configs for fetcher

---

hasher-matcher-actioner/terraform/main.tf
hasher-matcher-actioner/terraform/variables.tf

Summary
---
For accurate cost tracking, we should allow partners to specify tags at one place and pass it along to all the sub-modules we create.
This adds a variable definition and passes along the variable's contents to all submodules known at this time.
Test Plan
---
```
$ terraform apply -var "prefix=$(whoami)"
```
Gave me "Plan: 0 to add, 36 to change, 0 to destroy."
And the output showed tags being added.

Root terraform support additional_tags

---

hasher-matcher-actioner/hmalib/lambdas/fetcher.py

Summary
---------
Dead simple approach to reading configs from the dynamo db.
Test Plan
---------
```
$ aws configure
$ cd hasher-matcher-actioner\hmalib\lambdas
$ python -i .\fetcher.py
$ lambda_handler(None, None)
Triggered at time 19:45:16, found 1 collabs: Sample Collaboration
{'statusCode': 200, 'body': '[{"should_delete": false, "data": "Triggered at time 19:45:16, found 1 collabs: Sample Collaboration"}]'}
```

[hma][fetcher] Read collab configs

---

hasher-matcher-actioner/terraform/fetcher/main.tf
hasher-matcher-actioner/terraform/fetcher/variables.tf
hasher-matcher-actioner/terraform/main.tf
hasher-matcher-actioner/terraform/variables.tf

Summary
---------
Added secret that user inputs as a terraform variable
Test Plan
---------
1. Edit `terraform.tfvars` to include the variables `te_api_token`
2. 
```
terraform init
terraform validate
terraform apply
```
3. validate that the new secret shows up correctly in aws

Store TE api access token in AWS as a secret

---

hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_hasher.py
hasher-matcher-actioner/requirements.txt

Summary
---
At 1MB, some images were not getting hashed because the buffer wasn't getting automatically flushed. I did some digging around.
It appears that we need not write to a file at all. We can manage everything in memory. This depends on another merged PR in threatexchange #420  and accordingly updates the threatexchange version number from #421.
Test Plan
---
Used a docker image built from these sources to run perf tests on ~300 distinct 1 and 10 MB images. The runs were succesful over 100k hashing requests.

PDQ Hash photos without temporary files

---

python-threatexchange/threatexchange/cli/match.py

Summary
---------
One of our partners ran into a silly bug, leftover from the API refactor. Maybe somebody (me) should have done some more tests.
Test Plan
---------
```
$ threatexchange match text -T 'bball now?'
Looks like you haven't set up a collaboration config, so using the sample one against public data
Looks like you are running this for the first time. Fetching some sample data.
File "/home/dcallies/.venv/threatexchange/bin/threatexchange", line 33, in <module>
sys.exit(load_entry_point('threatexchange', 'console_scripts', 'threatexchange')())
File "/data/users/dcallies/fork_te/ThreatExchange/python-threatexchange/threatexchange/cli/main.py", line 194, in main
execute_command(namespace)
File …
```

[py-tx] Fix bug with sample fetch from match

---

hasher-matcher-actioner/terraform/.terraform.lock.hcl
hasher-matcher-actioner/terraform/fetcher/main.tf

Summary
---------
aws secret defaults to recovery_window_in_days of 7 and while a secret is 'scheduled for deletion' it can't be created. If we set this to 0 we avoid this. 
Test Plan
---------
`terraform -chdir=terraform apply`
`terraform -chdir=terraform destroy`
`terraform -chdir=terraform apply`

Update aws_secretsmanager_secret.recovery_window_in_days to 0 for easy apply/destroy

---

hasher-matcher-actioner/Dockerfile
hasher-matcher-actioner/hmalib/lambdas/fetcher.py
hasher-matcher-actioner/requirements.txt
hasher-matcher-actioner/setup.py
python-threatexchange/setup.py

Summary
---------
dataclass is forwards compatible, but only if properly shadowed by the real library. @schatten theorized this was because we were messing with the python path, which seems to be correct.
Fixes  #440
Test Plan
---------
```
$ cd hasher-matcher-actioner
$ docker build . - testington
$ docker run -p 9000:8080 testington hmalib.lambdas.fetcher.lambda_handler
$ sh-4.2# python3.8 -m hmalib.lambdas.pdq.pdq_hasher
```

[hma] Wrap hmalib with setup, install with pip

---

hasher-matcher-actioner/Dockerfile

Summary
---
Docker build times were getting unbearable, the following changes were made:
1) Pinned python runtime base image sha
This allows re-use of the base image. If this changes, all our layers must change and that slows us down.
2) Split dependency installation from hmalib installation
libraries + code is around 200MB. Even though library was rarely changing. Using setup.py egg_info to generate a requirements.txt style file at runtime to populate dependencies.
3) Instead of copying hmalib source code into the python package directory, copy it to the recommended lambda task root [1]
1: https://hub.docker.com/r/amazon/aws-lambda-python
Test Plan
---
Used `$ time  make upload_docker` to time the docker upload process.
Before:
```
Run #1: 4:46
Run #2: 5:33
```
After:
```
Run #1: 2:02 …
```

Split python dependency and library into docker layers

---

hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/terraform/api/main.tf
hasher-matcher-actioner/webapp/src/Matches.jsx

Summary
---------
Updates the match and hash endpoints to be better keyed and add a docstring to describe the expected return format.
Also made slight changes to the 'matches' UI page that will likely soon be superseded by other changes/designs. My next step will be to hook up the match details section.  
Test Plan
---------
Postman as a little involved to get working but if you have that set up (feel free to reachout)
```
terraform -chdir=terraform apply 
make dev_upload_test_data
```
Go to Postman (on `cd webapp/ && npm run`)
The following endpoints were updated/added
- `<api-gateway-invoke-url>/matches`
- `<api-gateway-invoke-url>/hash/<content_id>`
- e.g. `https://<gw-id>.execute-api.us-east-1.amazonaws.com/hash/b.jpg` 
- `<api-gateway-invoke-url>/match/<content_id>`

[HMA] clean up matches and hash api

---

hasher-matcher-actioner/hmalib/aws_secrets.py
hasher-matcher-actioner/terraform/fetcher/main.tf

Changed te_api_key() to use a secret name stored in an environment variable.
Test Plan
---------
1. `terraform apply`
2. Monitor CloudWatch /aws/lambda/brianeriksen_fetcher and ensure the error regarding pulling the secret is no longer seen.

Change AWSSecrets.te_api_key to pull secret using a secret name stored in an environment variable

---

python-threatexchange/threatexchange/hashing/pdq_hasher.py

Summary
---------
#455 called out a bug in 'python-threatexchange/threatexchange/hashing/pdq_hasher.py' Did some digging and found what I think should be a one line fix. 
Using the photo attached to the issue I compared the output with the changes to `threatexchange.hashing.pdq_hasher.pdq_from_file`with our cpp version of pdq (`./pdq/cpp/pdq-photo-hasher` after running make) and found the hashes matched.
Test Plan
---------
See methodology above in summary, unfortunately testing is hard until the fixes in #464 are merged.

[py-tx] update pdq_hasher to handle grayscale

---

hasher-matcher-actioner/terraform/webapp/main.tf

Summary
---------
Updated /webapp/main.tf and changed CloudFront behavior to redirect http traffic to https.
Test Plan
---------
1. Set up terraform.tfvars to create a CloudFront distribution (i.e., `include_cloudfront_distribution = true`)
2. `terraform apply`
3. Add a user to the user pool
4. Look up CloudFront domain name
5. Open a browser and go to http://<CloudFront-domain-name> and validate that the browser redirects to https://<CloudFront-domain-name>

Changed CloudFront behavior to redirect http traffic to https

---

python-threatexchange/threatexchange/hashing/pdq_hasher.py

Summary
---------
#465 worked but upon review had a significant performance hit. The core issue in #455 was only that images with 2 dimensions were resulting in an error. Instead of convert RGB this does the array manipulation in the case only where it is needed (a possible future optimization would be to also down scale the image).
Test Plan
---------
Again tested by using the photo attached to the issue and compared the output with the changes to threatexchange.hashing.pdq_hasher.pdq_from_filewith our cpp version of pdq (./pdq/cpp/pdq-photo-hasher after running make) and found the hashes matched.

[py-tx] pdq hash revert automatic convert and check dim of image array for better perf

---

hasher-matcher-actioner/webapp/package-lock.json
hasher-matcher-actioner/webapp/package.json
hasher-matcher-actioner/webapp/public/index.html
hasher-matcher-actioner/webapp/src/App.jsx
hasher-matcher-actioner/webapp/src/Sidebar.jsx
hasher-matcher-actioner/webapp/src/styles/_app.scss
hasher-matcher-actioner/webapp/src/styles/_sidebar.scss

Summary
---
Changes the primary navigation from a top nav bar to a sidebar based nav. This allows larger primary nav lisss and allows you to use tabs as secondary nav to implement individual screens. Was already being done in the settings screen.
**Other Niceties:**
1. Current route is highlighted in the sidebar.
2. First usage of a css file. Hoping this will become more of a pattern
3. First usage of prop-types. Hoping this too will become a pattern.
4. Adjusted padding and spacing to make things a little more pleasant (subjective)
Test Plan
---
Screenshot, before and after.

Make primary nav vertical and move it to its own file

---

hasher-matcher-actioner/scripts/populate_config_db
hasher-matcher-actioner/scripts/storm_images_queue
hasher-matcher-actioner/terraform/.terraform.lock.hcl
hasher-matcher-actioner/terraform/fetcher/main.tf
hasher-matcher-actioner/terraform/populate_config_db.sh

Summary
---------
Turns out shell quoting in windows (basically required for jq) is difficult. Instead rewrite script in python which is more platform agnostic. 
Fixes  #475
Test Plan
---------
use terraform taint to force recreation of the fetcher configs.
Then apply, see that the new table has the two sample rows.

[hma] get populate_config_db to work on windows

---

python-threatexchange/setup.py
python-threatexchange/tests/test_api.py
python-threatexchange/threatexchange/api.py
python-threatexchange/threatexchange/api_models.py
python-threatexchange/threatexchange/api_representations.py

Summary
---
Add a method to ThreatExchangeAPI
**Addons:**
- An integration test for the API was missing, so added it. Only executed when appropriate env variables are provided.
- A utility method to create threatexchange graph API urls was missing, so added it. A future PR will convert all handwritten URL mangling to calls to this method.
TestPlan
---
```
$ THREAT_EXCHANGE_INTEGRATION_TEST_TOKEN=$(cat ~/.txtoken) pytest -v
...
==== 58 passed, 3 warnings in 1.01s ====
....
```
Lint
```
$ black .
$ mypy threatexchange # produced no new errors :(
```

python-threatexchange supports fetching list of privacy groups an app is a member of

---

hasher-matcher-actioner/hmalib/common/s3_adapters.py
hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_indexer.py
hasher-matcher-actioner/hmalib/metrics/__init__.py
hasher-matcher-actioner/terraform/api/main.tf
hasher-matcher-actioner/terraform/api/variables.tf
hasher-matcher-actioner/terraform/main.tf

Summary
---------
#472 unintentionally broke the api_root lambda as the use of ThreatExchangeS3PDQAdapter depended on environment variables not passed to the api lambda in terraform. 
This adds the environment vars and refactors s3_adapters.py to require the config be created by pulling from the environment var in the same file as the lambda handler.
Test Plan
---------
before all endpoints were returning a 500 error. With these fixes the UI page loads values again and the \hash_count endpoint actually returns a result to Postman (which required a small fix in metrics/__init__.py).

[hma] fix missing lambda env values and refactor to assign in the handler

---

hasher-matcher-actioner/.devcontainer/Dockerfile
hasher-matcher-actioner/.devcontainer/devcontainer.json
hasher-matcher-actioner/.devcontainer/post-create

Summary
---------
Think of a devcontainer as a devserver that runs locally on your docker. This has (at least) the following benefits:
1. Gets everyone to use the same standard tooling
2. No need to manage any tooling on your local macbook/linuxbox/what have you
3. Standardizes vscode extensions so lint/type errors are a thing of the past
Test Plan
---------
1. Install [Visual Studio Code](https://code.visualstudio.com/). VS Code @ FB will not work. :(
2. Install [Remote Container](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) extension
3. In `devcontainer.json`, replace all occurrences of `dipanjanm` with your unixname. TODO (automate)
3. Have docker desktop running
3. With visual studio open, try `[F1]` or `[Cmd+Shift+P]` and select …

Provide a devcontainer for HMA

---

hasher-matcher-actioner/.devcontainer/Dockerfile
hasher-matcher-actioner/.devcontainer/devcontainer.json

Stacked diff alert: Only review [d6bcf46](https://github.com/facebook/ThreatExchange/pull/486/commits/d6bcf4636aef68302137dc9e4041e78db5eae029). Built on #485 
---
Summary
---
Mount a directory from the host to the container. Use a file within it as the bash histfile.
Test Plan
---
1. Rebuilt container once.
2. executed few strange commands
3. Rebuilt container again, verified it has a different container id (implies brand new)
4. ran `history` to find the strange commands

devcontainer: support bash history

---

hasher-matcher-actioner/hmalib/lambdas/actions/action_performer.py
hasher-matcher-actioner/hmalib/models.py
hasher-matcher-actioner/hmalib/tests/test_actioner.py

Summary
---------
This is the basic skeleton of action evaluation / orchestration. The entry point is `lambda_handler` that receives a match message (sent by the matcher).
The processing begins with evaluating what action rules apply to the match message (each action rule implies an action via its action labels). Actions are deduplicated along the way. From there, `perform_action()` is called to perform each action.
After that the applicable ThreatExchange reactions are generated, and then `react_to_threat_exchange()` is called for each reaction.
The next PR will be implementing labeling a match message.
Test Plan
---------
`terraform destroy`
`terraform apply`
upload an image
review logs
also, python -m hmalib.lambdas.actions.action_performer

Initial skeleton of action evaluation.

---

python-threatexchange/threatexchange/threat_updates.py

Summary
---------
`threatexchange experimental-fetch` seem to be broken for first fetch (at least with the `--full` command). Traced the issue to ThreatUpdateFileStore.reset and added a hotfix (probably could also be fixed upstream of this call but haven't investigated further).
Test Plan
---------
Before:
```
$ threatexchange --config '/Users/barrett/dev/tmp/config_te.json' experimental-fetch --full 
File "/Users/barrett/.venv/hma/bin/threatexchange", line 33, in <module>
sys.exit(load_entry_point('threatexchange', 'console_scripts', 'threatexchange')())
File "/Users/barrett/dev/github/ThreatExchange/python-threatexchange/threatexchange/cli/main.py", line 194, in main
execute_command(namespace)
File …
```

[pytx] check if _cached_state exists before clear in threat_updates.py

---

hasher-matcher-actioner/hmalib/common/s3_adapters.py
hasher-matcher-actioner/hmalib/lambdas/fetcher.py
hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_indexer.py
hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_matcher.py
hasher-matcher-actioner/webapp/src/Signals.jsx

Summary
---------
This adds the labels/tags to the metadata object in the index. 
Other minor issues I saw from the logs while testing and fixed:
`pdq_matcher.py` imports was missing stuff from models.py and 
`ThreatExchangeS3PDQAdapter.file_type_str_name` was missing a return statement
`webapp/src/Signals.jsx` should handle the case where there are no signals cleaner
Test Plan
---------
made tmp change to `hasher-matcher-actioner/sample_data/pdq.csv` then ran:
`make dev_upload_test_data` 
and used cloudwatch logs to test: 
```
...
Match found for key: images/b.jpg, hash f8f8f0cee0f4a84f06370a22038f63f0b36e2ed596621e1d33e6b39c4e9c9b22 ->
{'id': 4109214869142910, 'hash': 'f8f8f0cee0f4a84f06370a22038f63f0b36e2ed596621e1d33e6b39c4e9c9b22', 'source': 'te', 'privacy_groups': {'sample_data'}, …
```

[hma] Propagate tags to index metadata + minor fixes

---

hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_matcher.py
hasher-matcher-actioner/hmalib/models.py
hasher-matcher-actioner/hmalib/tests/test_models.py
hasher-matcher-actioner/webapp/src/MatchDetails.jsx

Summary
---------
The goal of this PR is getting us closer to closing the loop on reactions/opinions by building off of the existing structure in [descriptor.py](https://github.com/facebook/ThreatExchange/blob/master/python-threatexchange/threatexchange/descriptor.py). This takes the metadata from the index for matches and creates an object that can be updated later by a syncer/fetcher (or actioner) that can also be surfaced on the UI.
Feel free to review/provide feedback at the commit level as the 3 commits of this PR could probably be there own diffs but testing them really only works all together. 
Commits:
1) creates the new metadata object class + unit test
2) update pdq_matcher to create these object
3) updates the match details API and page to surface this metadata
What's next:
a) …

[hma] Create signal metadata db obj and surface on UI

---

hasher-matcher-actioner/hmalib/lambdas/fetcher.py
hasher-matcher-actioner/hmalib/scripts/populate_config_db.py

Summary
---------
* Adds ThreatExchangeConfig
* Add a script to make it easy to populate test data (since old script doesn't work)
Doesn't actually pull the trigger on moving the rest over to give @mengyangwang  a chance to do more in #494 
Test Plan
---------
```
$  python -m hmalib.scripts.populate_config_db --help
usage: populate_config_db.py [-h] [--table TABLE] {update,load_example_configs,get} ...
Write simple configs to the HMA config database
positional arguments:
{update,load_example_configs,get}
update              Add or edit a config
load_example_configs
Populate db with a default set of configs
get                 get configs
--table TABLE         The name of the config dynamodb table
$ python -m …
```

[hma] ThreatExchang/Collaboration config in HMAConfig, Helper Populate script

---

hasher-matcher-actioner/terraform/collabs_example.json

Summary
---------
While we are iterating quickly @eriksendc said he'd prefer the fetcher to default 'on' for testing.
I know both @mengyangwang  and @Dcallies have been ~working in this area. So I just went with the smallest change to get the desired behavior. Depending on what falls out of the config conversations, this could also be solved by adding a new file and updating: https://github.com/facebook/ThreatExchange/blob/master/hasher-matcher-actioner/terraform/variables.tf#L64 and .tfvars
Personally I think defaulting to off once we get closer to a complete v0 (and settings can be updated in the UI) is a likely end-state. 
Test Plan
---------
Running destroy and apply.
Checking the DynamoDB to confirm fetcher_active=true.
Check tfvars a valid access token to pull test data from TE. …

[hma] fetcher_active default to true

---

python-threatexchange/threatexchange/cli/dataset/simple_serialization.py
python-threatexchange/threatexchange/threat_updates.py

Summary
---------
This is needed for changes in hmalib to be stacked above this and is the result of needing to break up #503
Test Plan
---------
This just propagates a no-op lambda and fixes a type.
`threatexchange --config '/Users/barrett/dev/tmp/config_te.json' experimental-fetch --full`
still works.

[pytx] Add post apply method to apply_updates

---

hasher-matcher-actioner/hmalib/common/config.py
hasher-matcher-actioner/hmalib/common/tests/config_test.py

Summary
---------
Well... here's a thing that does a thing. I went in circles on this for a while on decision points that probably didn't matter.
The key thing I hung on is where to do this:
```
HMAConfig
|
HMAConfigWithSubtype
|
HMAConfigSubtype
```
Or this
```
HMAConfig         HMAConfigWithSubtype
|               - Returns instances of HMAConfigSubtype
HMAConfigSubtype
```
There are tradeoffs in either direction, but decided to go with former. 
I also made the choice(/mistake) to use metaclass magic to provide a default behavior on class name.
Test Plan
---------
Updated unittest, I believe its comprehensive.

[hma][config] Add subtype helper

---

hasher-matcher-actioner/hmalib/common/s3_adapters.py
hasher-matcher-actioner/hmalib/lambdas/fetcher.py
hasher-matcher-actioner/hmalib/models.py
hasher-matcher-actioner/hmalib/tests/test_models.py
hasher-matcher-actioner/mypy.ini
hasher-matcher-actioner/setup.py
hasher-matcher-actioner/terraform/fetcher/main.tf
hasher-matcher-actioner/terraform/fetcher/variables.tf
hasher-matcher-actioner/terraform/main.tf

Summary
---------
Second (and actually significant)  half of the split of #503
This modifies the fetcher to update `PDQSignalMetadata` this has already been mostly reviewed by @schatten as a part of #503. 
Test Plan
---------
I was able to confirm that the fetcher was able to update the db objects in a deployed lambda via cloudwatch log:
After the first fetch and a match was created I went to s3 and deleted the .pdq.te and .checkpoint files. 
I then triggered the fetcher to make sure it wold complete without error and checked the logs to make sure the db object was updated, (paste of one of the logs below.)
```
[INFO]	2021-04-20T17:55:37.849Z	730a56a1-06a8-4204-b448-e03e9425f554	Updated Signal Tags in DB for signal id: <REDACTED> source: te for privacy group: 303636684709969
```

[hma] Have fetcher update dynamo for signal objects 

---

hasher-matcher-actioner/hmalib/lambdas/fetcher.py
hasher-matcher-actioner/terraform/fetcher/main.tf
hasher-matcher-actioner/terraform/fetcher/variables.tf
hasher-matcher-actioner/terraform/main.tf

Summary
---------
Makes it so the fetcher uses the HMAConfig version of its configs as the source of truth, rather than the old table.
Split of #499, interleving with #494.
Test Plan
---------
terraform apply, populate test configs with script, manually trigger fetcher, see logs showing it's doing things.

Convert Fetcher to Use ThreatExchangeConfig (HMAConfig version)

---

hasher-matcher-actioner/hmalib/common/actioner_models.py
hasher-matcher-actioner/hmalib/common/tests/test_actioner_models.py
hasher-matcher-actioner/hmalib/lambdas/actions/action_evaluator.py
hasher-matcher-actioner/hmalib/lambdas/actions/action_performer.py
hasher-matcher-actioner/hmalib/lambdas/actions/reactioner.py
hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_matcher.py
hasher-matcher-actioner/hmalib/models.py
hasher-matcher-actioner/hmalib/tests/test_models.py

Summary
---------
This PR introduces two messages based off of MatchMessage: ActionMessage and ReactionMessage. They are instantiated by the action evaluator and consumed by the action performer and reactioner, respectively. Other code changes include moving Labels to actioner_models.py, removing Labels from the concept of matches and match records (we now have metadata and, later, classifications), and other minor cleanup like renaming things from SNS/sns-something-or-other to AWS/aws-something-or-other. 
Test Plan
---------
4. `make dev_upload_test_data`
5. wait for hashing and matching to occur
6. validate CloudWatch logs: see that action_performer got an ActionMessage
7. validate CloudWatch logs: see that reactioner …

Messages for actions and reactions queues

---

hasher-matcher-actioner/hmalib/common/aws_dataclass.py
hasher-matcher-actioner/hmalib/common/tests/aws_dataclass_test.py

Summary
---------
Breaks out the magic of converting dataclasses to aws-friendly dictionaries to another class. I have no idea if this works for more than just dynamodb items, and so this might be misnamed.
Bonus: 
* Supported for nested datastructures
* And arbitrary sets
Test Plan
---------
added unittest

aws_dataclass

---

hasher-matcher-actioner/.devcontainer/devcontainer.json

Summary
---------
Updates the vscode remote containers settings.
The change also formatted inadvertently devcontainer.json (not a huge fan honestly but didn't want to create another rc file /custom case json format right now)
The value changed are the addition of the following to settings:
```
"settings": {
"terminal.integrated.shell.linux": "/bin/bash", # already there (maybe sub for zsh??)
"editor.formatOnSave": true,
"python.formatting.blackPath": "black",
"[javascriptreact]": {
"editor.defaultFormatter": "rvest.vs-code-prettier-eslint"
}
},
```
and changing `unixname` and `remoteUser` to "REPLACEME" for clarity. 
Test Plan
---------
Rebuilt the remote container 
Opened both a jsx and python file
Made an edit that should be formatted
Saved
Saw that the file was automatically formatted …

[hma][dev] update vscode setting default format on save

---

hasher-matcher-actioner/hmalib/common/actioner_models.py
hasher-matcher-actioner/hmalib/scripts/populate_config_db.py

Summary
---------
@eriksendc asked for actioners to be automatically populated after a terraform apply. This is done by adding them to the `populate_config_db.py` script which is run on terraform apply.
Specifically I added an actioner that sends a POST webhook to the follwoing url: https://webhook.site/ff7ebc37-514a-439e-9a03-46f86989e195. For testing you can go to the url to see what it receives
This highlighted some errors with how subtyping in HMAConfig was done. @Dcallies is investegating that portion but the workaround employed here is to ignore different mypy errors
Test Plan
---------
Run the script locally to see that configs are populated:
```
$ python3 -m hmalib.scripts.populate_config_db load_example_configs
ThreatExchangeConfig(name='303636684709969', fetcher_active=True, …
```

Populate action performers

---

hasher-matcher-actioner/hmalib/common/actioner_models.py
hasher-matcher-actioner/hmalib/common/tests/test_action_rule_evaluation.py
hasher-matcher-actioner/hmalib/lambdas/actions/action_evaluator.py
hasher-matcher-actioner/hmalib/lambdas/fetcher.py
hasher-matcher-actioner/hmalib/scripts/populate_config_db.py
hasher-matcher-actioner/terraform/actions/main.tf
hasher-matcher-actioner/terraform/actions/variables.tf
hasher-matcher-actioner/terraform/fetcher/main.tf
hasher-matcher-actioner/terraform/fetcher/variables.tf
hasher-matcher-actioner/terraform/main.tf

Summary
---------
Implement action rules as config-backed HMAConfig objects.
Test Plan
---------
0. python -m py.test
4. `python -m hmalib.scripts.populate_config_db load_example_configs`
5. `make dev_upload_test_data`
6. wait for hashing and matching to occur
7. validate Cloudwatch logs: see that action_evaluator got an ActionRule back from the config table
8. validate CloudWatch logs: see that action_performer got an ActionMessage

Implement action rules as config-backed objects.

---

hasher-matcher-actioner/hmalib/lambdas/actions/action_performer.py
hasher-matcher-actioner/terraform/.terraform.lock.hcl
hasher-matcher-actioner/terraform/actions/main.tf
hasher-matcher-actioner/terraform/main.tf

Summary
---------
This is needed to read actioner configs from the configs table
Test Plan
---------
Pushed to aws, ran with the following event, and saw that no errors emerged
```
{
"Records": [
{
"body": "{\"ContentKey\": \"key\", \"ContentHash\": \"hash\", \"MatchingBankedSignals\": [{\"BankedContentId\": \"2862392437204724\", \"BankId\": \"bank 4\", \"BankSource\": \"te\", \"Classifications\": []}, {\"BankedContentId\": \"4194946153908639\", \"BankId\": \"bank 4\", \"BankSource\": \"te\", \"Classifications\": []}], \"ActionLabelValue\": \"EnqueForReview\"}"}
]
}
```

give action performer environment variables

---

hasher-matcher-actioner/hmalib/common/actioner_models.py
hasher-matcher-actioner/hmalib/common/tests/test_action_rule_evaluation.py
hasher-matcher-actioner/hmalib/lambdas/actions/action_evaluator.py
hasher-matcher-actioner/hmalib/lambdas/actions/reactioner.py
hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_matcher.py
hasher-matcher-actioner/hmalib/scripts/populate_config_db.py

Summary
---------
The `ActionRule` dataclass had two lists of labels. It's more efficient if they're sets, as we'd been converting the lists to sets on each rule evaluation. Storing as sets straight away prevents the need for that conversion.
Test Plan
---------
0. python -m py.test
4. `python -m hmalib.scripts.populate_config_db load_example_configs`
5. upload "mini-castle.jpg"
6. wait for hashing, matching and actioning to occur
7. validate that the EnqueueMiniCastleForReview WebhookPostActionPerformer is exercised (https://webhook.site/#!/01cef721-bdcc-4681-8430-679c75659867) 
8. upload "sailboat-mast-and-sun.jpg"
9. wait for hashing, matching and actioning to occur 
10. validate that the EnqueueSailboatForReview …

ActionRule: list to set refactor for must and must not have labels

---

hasher-matcher-actioner/hmalib/lambdas/api/middleware.py
hasher-matcher-actioner/hmalib/lambdas/api/tests/test_middleware.py
hasher-matcher-actioner/mypy.ini
hasher-matcher-actioner/requirements-dev.txt

Summary
---
Ammends jsoninator, enabling it to provide an optional type class for the request payload.
Test Plan
---
```
```
Adds a dependency and tests. The test adds an in-process HTTP server. Both old (without typed req bodies) and new (with typed req bodies) APIs are tested.

Support typing request bodies using the jsoninator middleware

---

hasher-matcher-actioner/hmalib/common/actioner_models.py
hasher-matcher-actioner/hmalib/common/config.py
hasher-matcher-actioner/hmalib/common/tests/config_test.py

Summary
---------
Well, it was worth a shot, but trying to type this is impossible because the type itself is dynamically generated.
Simplify the world by just making a straight inheritance. 
Test Plan
---------
unittests & mypy

[hma][config] Delete HMAConfigWithSubtype.SubType

---

hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/matches.py
hasher-matcher-actioner/hmalib/lambdas/api/middleware.py
hasher-matcher-actioner/hmalib/lambdas/api/submit.py

Summary
---------
Creates a new API by which a user can upload content to the system. Functions very similarly to  `/upload` 
this new endpoint will be `/submit/` and will take the following fields:
- submission_type: (always UPLOAD for now)
- content_id: (formerly   only used filename: this will correspond to s3 key (+ image prefix)
- content_type: str (always PHOTO for now)
- content_ref: encoded bytes of the image
- metadata: optional additional fields
Test Plan
---------
Used Postman and built out a UI that will be visible in my next PR (#536) to fully test upload functionality. Works just like the existing upload page except you can pick (must specify) an id for the content, instead of just using the filename.

[hma] Submit Content API

---

hasher-matcher-actioner/scripts/storm_submissions_api
hasher-matcher-actioner/terraform/outputs.tf
hasher-matcher-actioner/webapp/README.md

Summary
---------
* Do not be alarmed by the access token. It is an expired JWT and non-reverse-engineer-able.
* Also slight adjustment to the README to allow for redeploying of webapp
Test Plan
---------
Copy pasted script on an ec2 instance. Ran it with a violating image. Verified that matches appeared on the matches page ~15 seconds later.

Storm submissions API with the same image repeatedly

---

pdq/README.md

Summary
---------
Edit the pdq readme to fix broken license link.
Test Plan
---------
Ensure links to pdq license are still correct.

Fix broken PDQ license link

---

hasher-matcher-actioner/.devcontainer/Dockerfile
hasher-matcher-actioner/.devcontainer/bashrc
hasher-matcher-actioner/.devcontainer/post-create
hasher-matcher-actioner/.devcontainer/zshrc

Summary
---------
* also create bashrc and zshrc files that are copied at build
* Allows further customizing of prompts and general shell goodness
Test Plan
---------
- Rebuilt container fired it up.
- verified that bash history is retained by tailing bash_history on host
- verified that zsh history is retained by tailing zsh_history on host after switching to zsh on guest

Add zsh to devcontainer, track history for it

---

hasher-matcher-actioner/hmalib/lambdas/api/submit.py
hasher-matcher-actioner/webapp/src/pages/SubmitContent.jsx
hasher-matcher-actioner/webapp/src/utils/constants.jsx

Summary
---------
#536 Added upload file. This PR follow the same path but has the API pull filecontents from a url and store it in s3.
Test Plan
---------
https://user-images.githubusercontent.com/7664526/116917105-39941580-ac1c-11eb-8fe4-2fce2c42b269.mov

[hma] enable naive url upload to submit api

---

hasher-matcher-actioner/webapp/src/Api.jsx
hasher-matcher-actioner/webapp/src/Settings.jsx
hasher-matcher-actioner/webapp/src/components/ThreatExchangePrivacyGroupCard.jsx
hasher-matcher-actioner/webapp/src/settings/ThreatExchangeSettingsTab.jsx

Summary
---------
previous PR : https://github.com/facebook/ThreatExchange/pull/516 , https://github.com/facebook/ThreatExchange/pull/544
Task : T88063259
this task is to create ThreatExchange setting page.
this PR is to create the UI page of ThreatExchange 
Future Actions
---------
1. Change buttons to icons and adding more tooltips
2. Add copy text feature for privacy group name(currently has style conflict, might need to rewrite "CopyableTextField" module later)
3. Add matcher active feature to disable matching from privacy group level 
Test Plan
---------
test localhost UI changes
1. test show all privacy groups with loading spin
2. test sync function, it should automatically add privacy groups
3. test update function for each active privacy group
4. test delete function for in_active …

Create threat exchange tab

---

hasher-matcher-actioner/hmalib/common/fetcher_models.py
hasher-matcher-actioner/hmalib/common/tests/test_writebacker.py
hasher-matcher-actioner/hmalib/common/threatexchange_config.py
hasher-matcher-actioner/hmalib/lambdas/api/datasets_api.py
hasher-matcher-actioner/hmalib/scripts/populate_config_db.py
hasher-matcher-actioner/webapp/src/Api.jsx
hasher-matcher-actioner/webapp/src/components/ThreatExchangePrivacyGroupCard.jsx
hasher-matcher-actioner/webapp/src/settings/ThreatExchangeSettingsTab.jsx

Summary
---------
previous PR : https://github.com/facebook/ThreatExchange/pull/516 , https://github.com/facebook/ThreatExchange/pull/544, https://github.com/facebook/ThreatExchange/pull/546
Task : T88063259
this task is to create ThreatExchange setting page.
this PR is to add two fields, matcher_active and privacy group description 
Future Actions
---------
1. Change buttons to icons and adding more tooltips
2. Add copy text feature for privacy group name(currently has style conflict, might need to rewrite "CopyableTextField" module later)
3. use matcher_active to disable matching  
4. update description to add copydays link
Test Plan
---------
2. mypy hmalib
4. make docker
5. make upload_docker 
6. terraform apply
7. test …

Add description matcher active hmaconfig

---

hasher-matcher-actioner/webapp/public/index.html
hasher-matcher-actioner/webapp/src/App.jsx
hasher-matcher-actioner/webapp/src/Settings.jsx
hasher-matcher-actioner/webapp/src/settings/ActionRuleSettingsTab.jsx
hasher-matcher-actioner/webapp/src/settings/ActionSettingsTab.jsx
hasher-matcher-actioner/webapp/src/styles/_app.scss

Summary
---------
This PR introduces a first draft of the Action Rules (in Settings). 
This PR is organized as a "stacked diff". It's easiest to review per commit:
1. Added the concept of a route at the tab level so that page refreshes don't go back to the default tab.
2. Added the Action Rules tab without any real functionality (just getting the main component in place).
3. Added the main functionality: a table with the rules configured so far; the ability to add a rule; editing and deleting a rule is mocked (incomplete functionality).
4. Added validation: Name required and must be unique; Labeled As required; Action required.
5. (skip - just fixing formatting)
6. Added delete functionality.
7. Added edit functionality.
Test Plan
---------
Run the web app, navigate to Settings --> Action …

Actions rule config UI

---

hasher-matcher-actioner/webapp/src/components/CopydaysInformationBlock.jsx
hasher-matcher-actioner/webapp/src/components/HolidaysDatasetInformationBlock.jsx
hasher-matcher-actioner/webapp/src/pages/Settings.jsx
hasher-matcher-actioner/webapp/src/pages/settings/ThreatExchangeSettingsTab.jsx

Summary
--------
Add an information block giving instructions on how to download images from copydays and use them to match.
This is 1 of 2 diffs that fixes #555 The other diff is #560 
Test Plan
---------
No python files were touched. A screenshot from the ThreatExchange settings page is attached.
Updated the blurb to also reflect the test privacy group id.

Copydays information block in ThreatExchange settings page

---

hasher-matcher-actioner/hmalib/models.py
hasher-matcher-actioner/hmalib/tests/test_pdq_models.py

Summary
---------
Uses `transact_write_items`, a low level API to write records and update a counter item in the same transaction.
Partially fulfills requirements for #567 
Design
---
Creates sparse dynamodb items in the same table that contains the items being written. Uses `transact_write_items` to update a counter for every write. Updates by key are super-fast in ddb, so performance impact is negligible.
Rather than inferring the class name, requires that the class explicitly provide a name so that future refactoring does not reset the counters. 
Test Plan
---------
```
$ python -m py.test # Have added tests specific to this functionality
```
Also used the following script in the REPL to update counters in my prefixed dynamodb instance. …

DynamoDB Counts

---

hasher-matcher-actioner/.devcontainer/Dockerfile
hasher-matcher-actioner/.devcontainer/devcontainer.json

Summary
---------
Updates `devcontainer.json` to have support of both zsh and bash using the new prefered settings. (Users can set default for new terminal in their global settings) 
Test Plan
---------
Rebuild container and made sure apply and other dev commands still worked both for `bash` and `zsh`

devcontainers: update dev container to handle custom dotfiles

---

hasher-matcher-actioner/hmalib/common/actioner_models.py
hasher-matcher-actioner/hmalib/scripts/populate_config_db.py

Summary
---------
This PR is to add "headers" to WebhookActionPerformer in DynamoDB
Future Actions
---------
Create apis to create/update/read/delete data in DynamoDB 
Test Plan
---------
2. mypy hmalib
4. delete all WebhookActionPerformer in DynamoDB, then run ```python -m hmalib.scripts.populate_config_db load_example_configs```
5. test changes in DynamoDB
https://user-images.githubusercontent.com/81996660/117886542-5dd79e00-b27d-11eb-9396-59c1dd7ee692.mov

add headers to WebhookActionPerformer

---

hasher-matcher-actioner/hmalib/common/tests/test_writebacker.py
hasher-matcher-actioner/hmalib/common/writebacker_models.py

Summary
---------
This PR...
1. Implements False positive writebacks as a DISAGREE_WITH_TAGS reaction
2. Creates stub class for RemoveOpinion writebacks
3. Changes the descriptions of writebacks to match our v0 implementation plan
4. Removed the INGESTED writebacker which we determined was not worthy of implementing in v0
Test Plan
---------
`mypy hmalib && pytest` 
NOTE: No e2e test since the only code written (step 1 above) is using an already tested class. More e2e tests coming in later PRs

Implement False Positive Writebacks

---

hasher-matcher-actioner/hmalib/lambdas/api/actions_api.py

Summary
---------
Previous PR: https://github.com/facebook/ThreatExchange/pull/573
This PR is to change action apis to use the standard way of naming an api
Test Plan
---------
2. mypy hmalib
4. python -m hmalib.lambdas.api.api_root
5. test all apis in postman
https://user-images.githubusercontent.com/81996660/118333896-8c9e8000-b4da-11eb-8c89-3866bd3f3698.mov

using standard way to naming apis

---

hasher-matcher-actioner/webapp/src/App.jsx
hasher-matcher-actioner/webapp/src/Upload.jsx
hasher-matcher-actioner/webapp/src/pages/ContentDetails.jsx
hasher-matcher-actioner/webapp/src/pages/Dashboard.jsx
hasher-matcher-actioner/webapp/src/pages/Signals.jsx
hasher-matcher-actioner/webapp/src/pages/SubmitContent.jsx
hasher-matcher-actioner/webapp/src/pages/layouts/FixedWidthCenterAlignedLayout.jsx
hasher-matcher-actioner/webapp/src/pages/settings/ActionRuleSettingsTab.jsx

Summary
---------
@eriksendc had called out in #558 that some pages are not using bootstrap the right way. This PR adds a new Layout component which makes it easy for folks to get on with the program and use one common way for laying out a page.
Other than the matches page which has a multi-pane design, all other pages can potentially be migrated. As part of this, few have been and more will be added if this is accepted. For practical purposes, this fixes #558.
I feel the settings pages could do with their own layout because of their tabbed nature. If this appeals to folks, I'll take a stab at that.
Test Plan
---------
Screenshots for the updated pages are shown below.

Add FixedWidthCenterAlignedLayout layout and migrates some pages

---

hasher-matcher-actioner/hmalib/common/s3_adapters.py
hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/webapp/src/Api.jsx
hasher-matcher-actioner/webapp/src/components/settings/ThreatExchangePrivacyGroupCard.jsx
hasher-matcher-actioner/webapp/src/pages/settings/ThreatExchangeSettingsTab.jsx

Summary
---------
This PR is to display last modified time and hash count for each privacy group .pdq.te file in S3 bucket in ThreatExchange Setting page
Test Plan
---------
2. mypy hmalib
4. make docker
5. make upload_docker
6. terraform apply
7. test the change in localhost UI
shows privacy group description:
shows hash count:
shows last modified time:
matches the timestamp in S3:

add last modified time, hash count

---

hasher-matcher-actioner/hmalib/common/mocks.py
hasher-matcher-actioner/hmalib/common/tests/test_writebacker.py
hasher-matcher-actioner/hmalib/common/writebacker_models.py
hasher-matcher-actioner/hmalib/lambdas/actions/writebacker.py
hasher-matcher-actioner/setup.py

Summary
---------
Implement True positive Writbacks to ThreatExchange. This will upsert a new descriptor for the given indicator with:
1. MALICIOUS
2. The same privacy group
3. MANUALLY REVIEWED
If the descriptor does not already exist, the following feilds will also be set:
1. Description = "A ThreatDescriptor uploaded via HMA"
2. Tags = "uploaded_by_hma"
3. share level = "RED
If the descriptor already exists, those fields will be unchanged
Test Plan
---------
1. Created new test application (HMA test)
2. Uploaded all test data threat descriptors again with the new app
3. Deleted old Threat Descriptors from the old testing app (Jesse's terrorist stopping app)
4. Triggered TruePositive writeback locally
5. Watched new ThreatDescriptor get created in ThreatExchange

Implement True Positive Writebacks

---

hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_matcher.py

Summary
---------
previous PR : https://github.com/facebook/ThreatExchange/pull/561
this PR is to fix the issue with matcher_active:
1. fix the issue when disable matcher_active, it will still write the matching record to DynamoDB and publish to SQS queue
2. add lru cache(5 mins) for getting the matcher_active config from dynamoDB
Test Plan
---------
2. mypy hmalib
5. make docker
6. make upload_docker 
7.  terraform apply
Test changes in localhost:
1. disable matcher_active, upload an image, no matching records should be written to dynamoDB
https://user-images.githubusercontent.com/81996660/118562991-c3bf9c00-b73b-11eb-81d2-0f973a30315a.mov

fix matcher_active

---

hasher-matcher-actioner/hmalib/common/content_models.py
hasher-matcher-actioner/hmalib/common/evaluator_models.py
hasher-matcher-actioner/hmalib/common/tests/test_content_models.py
hasher-matcher-actioner/hmalib/lambdas/actions/action_evaluator.py
hasher-matcher-actioner/hmalib/lambdas/actions/action_performer.py
hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/content.py
hasher-matcher-actioner/hmalib/lambdas/api/matches.py
hasher-matcher-actioner/hmalib/lambdas/api/submit.py
hasher-matcher-actioner/terraform/actions/main.tf
hasher-matcher-actioner/terraform/actions/variables.tf
hasher-matcher-actioner/terraform/main.tf
hasher-matcher-actioner/webapp/src/Api.jsx
hasher-matcher-actioner/webapp/src/pages/ContentDetails.jsx
hasher-matcher-actioner/webapp/src/pages/SubmitContent.jsx

How to Review
---------
- [Diff 1/5](https://github.com/facebook/ThreatExchange/pull/583/commits/65d7ae4d3d96fd9003545ce2536ba3589831f407) Creates models for content and action record objects (and unit test)
- [Diff 2/5](https://github.com/facebook/ThreatExchange/pull/583/commits/706fc17de2aa513225186999e2eb4ae58a85f6a7) Begins recording ActionEventRecords in action_performer lambda
- [Diff 3/5](https://github.com/facebook/ThreatExchange/pull/583/commits/e284c33657a9c822cd976eed5df99ebc005da697) Moves existing related endpoints to sub-api `/content/<x>` and expose new models on same sub-api
- [Diff 4/5](https://github.com/facebook/ThreatExchange/pull/583/commits/47cada24ca7bb2fe8c6853a73fb63e075e800ec2) Begins recording content objects in submit API
- [Diff …

[HMA][Multipart] Content Object and ActionEvent Storage + API 

---

hasher-matcher-actioner/hmalib/common/mocks.py
hasher-matcher-actioner/hmalib/common/tests/test_writebacker.py
hasher-matcher-actioner/hmalib/common/writebacker_models.py
hasher-matcher-actioner/hmalib/lambdas/actions/writebacker.py
hasher-matcher-actioner/hmalib/lambdas/fetcher.py

Summary
---------
Last unimplemented writebacker option RemoveOpinion
Test Plan
---------
1. Added unit tests
2.Tested all writebackers together by trigging them locally (not through UI). 
a) Find an indicator that exists in HMA but that our app doesnt have a descriptor for 
b) Ensure that our app has not reacted to any of the other descriptors yet
c) trigger a FalsePositive writeback and watch as other descriptor is reacted to
d) trigger a RemoveOpinion writeback and watch as reaction is removed
e) trigger a TruePositive writeback and watch as a descriptor is created with the right fields and privacy group
f) trigger a RemoveOpinion writeback and watch as descriptor is deleted
3. Tested that Triggering from UI works as well

Implement RemoveOpinion ThreatExchange Writebacker

---

hasher-matcher-actioner/hmalib/lambdas/api/api_root.py

Summary
---------
Prior to this change, two things were wrong:
1. When errors were encountered, they were not logged unless the view function did a log.
2. The request and response bodies were getting logged on cloudwatch which made it incredibly hard to parse them visually.
Test Plan
---------
Deployed the lambdas and made a request to an endpoint that is raising 500s.
**Before**
**After**

For 500 errors, log exception at api_root

---

hasher-matcher-actioner/hmalib/lambdas/api/stats.py
hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_matcher.py
hasher-matcher-actioner/hmalib/metrics/__init__.py

Summary
---------
So far, we were using the number of times the index was searched as a number of matches metric. This is patently false. The number of matches is actually the number of times match records were written.
This adds a new metric, measures it, and uses it to report back stats.
Test Plan
---------
Deployed to prod and saw the number of matches (as viewed in the dashboard graphs) drop.
Note: There is still some work to be done to ensure things are accurate. I'm not sure they are at this point.

For match metrics, add and use correct metric

---

hasher-matcher-actioner/webapp/src/components/OpinionTableCell.jsx

Summary
---------
Writebacks can't currently handle switching directly from True Positive to False Positive. The quickest v0 solution is to disable this and require users to first remove a previous opinion before adding a new opinion. We could potentially change this in the future but for v0 this should work
Decided that a tool tip wasn't really necessary here as having only one enabled action "Remove Opinion" seems to make it clear how to change an opinion. if anyone feels particularly strongly I can add one but already a lot of text/explanations on this page
Test Plan
---------

Can't switch directly from TP <-> FP

---

hasher-matcher-actioner/hmalib/common/signal_models.py
hasher-matcher-actioner/hmalib/common/writebacker_models.py
hasher-matcher-actioner/hmalib/lambdas/api/matches.py
hasher-matcher-actioner/hmalib/lambdas/fetcher.py
hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_matcher.py
hasher-matcher-actioner/hmalib/models.py
hasher-matcher-actioner/terraform/fetcher/main.tf

Summary
---------
Ensure that writebacks flow all the way through the system. From changing opinion in UI -> API -> dynamoDB -> Writebacker -> ThreatExchange ->Fetcher -> dynamoDB -> API -> UI.
A few necessary/helpful changes:
1. Edit fetcher to update the PendingOpinionChange property on a fetch. @BarrettOlson determined that the necessary logic would be to see if the opinion has changed and if so remove any pending change.
1. typing in signal_models to ensure signal_id is always a str
2. typing in fetcher to convert privacy group ID to str
Test Plan
---------
From UI do the following and watch changes be propagated through the system. 
1. Upload an image which our test app currently doesnt have a descriptor for but a noter app has a descriptor in the privacy group
2. Watch match and see …

Close the loop on Writebacks

---

hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_matcher.py
hasher-matcher-actioner/hmalib/models.py

Summary
---------
This changes the matcher to only update/create a metadata object  if it is not found in the table. Once initially created it is the fetcher's job to keep the item up to date.
Test Plan
---------
Test of `write_to_table_if_not_found`
```
import boto3
from hmalib.common.signal_models import PDQSignalMetadata
dynamodb = boto3.resource("dynamodb")
table = dynamodb.Table("barrett-HMADataStore")
print(
PDQSignalMetadata(
"example_id_1",
"example_pg_1",
datetime.datetime.now(),
"te",
"hash_val",
["tag1"],
).write_to_table_if_not_found(table)
)
print(
PDQSignalMetadata(
"example_id_1",
"example_pg_1",
datetime.datetime.now(),
"te",
"hash_val",
["tag1"],
).write_to_table_if_not_found(table)
)
``` 
output:
```
True
False
```
Tested changes to matcher via the UI by uploading an …

[HMA] make pdq_matcher write of metadata be conditional 

---

hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/ActionPerformerRows.jsx

Summary
---------
previoius PR: https://github.com/facebook/ThreatExchange/pull/605
this PR is to resolve issue https://github.com/facebook/ThreatExchange/issues/612
after edit an action, we shouldn't call ```resetForm()```
Test Plan
---------
https://user-images.githubusercontent.com/81996660/119051242-ed253580-b990-11eb-8bd3-758aee2502bf.mov

fix edit action issue

---

hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/datasets_api.py
hasher-matcher-actioner/webapp/src/components/settings/ThreatExchangePrivacyGroupCard.jsx
hasher-matcher-actioner/webapp/src/pages/settings/ThreatExchangeSettingsTab.jsx

Summary
---------
Since we had already added hash counts to the ThreatExchange settings tab, it made sense to add the match counts there as well. I have not added Tate's feedback or played around with the UI. Just replaced last modified with match count.
Last modified is getting tricky because the source of information could be from many places. The config itself is updated. The hash and match counts are updated by separate processes. So, just dropped it from the UI.
Also, removed the /hash_counts/ API and added everything to the same /datasets/ call.
It seems more and more likely that the signals page could go away. There is no information on that page that is not anywhere in the ThreatExchange settings page. And showing the same information in two places becomes confusing.
Test Plan …

[HMA] Add count of matches / privacy group to API and to UI

---

hasher-matcher-actioner/hmalib/lambdas/api/content.py
hasher-matcher-actioner/hmalib/lambdas/api/submit.py
hasher-matcher-actioner/webapp/src/Api.jsx
hasher-matcher-actioner/webapp/src/Sidebar.jsx
hasher-matcher-actioner/webapp/src/Upload.jsx
hasher-matcher-actioner/webapp/src/components/SubmitContentFields.jsx
hasher-matcher-actioner/webapp/src/pages/SubmitContent.jsx
hasher-matcher-actioner/webapp/src/utils/constants.jsx

Summary
---------
This PR does a number of small things to unfortunately connected files which made my usually strategy of breaking up at commit level rough/impossible. Still willing to try if this review becomes onerous. 
Largest Changes:
- swaps "Upload" side bar page with "Submit Content"
- Changes `SubmissionType` enum (python & JS) to only the currently supported methods
- Adds new supported method (Post URL Upload)
- This is what was used and tested on the old upload pages (this allows it to be used on the submit page)
Renaming:
- `ContentIdAndTypeField` ->  `ContentUniqueIdField` 
- done to avoid confusion as the only type we support atm is PHOTO and should be broken up once we support additional
- `metadata` -> `AdditionalFields` (and all associated fields/helpers) 
- change was …

[HMA] Replace Upload page and refresh Submit Page

---

hasher-matcher-actioner/webapp/src/components/ActionHistoryTable.jsx
hasher-matcher-actioner/webapp/src/components/ContentMatchTable.jsx
hasher-matcher-actioner/webapp/src/pages/ContentDetails.jsx

Summary
---------
Makes ActionHistory its own component for the details page. The table shows all actions for a piece of content giving action label and the time it was performed  (most recent first) by default it only displays the two most recent actions but users can see the total count and hit "...see all" to show the rest.
PR also moves opinion change submitted toast to the top right.
Test Plan
---------

[hma] Add ActionHistoryTable to Details page

---

hasher-matcher-actioner/hmalib/lambdas/api/actions_api.py
hasher-matcher-actioner/webapp/src/Api.jsx
hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/ActionPerformerColumns.jsx
hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/ActionPerformerRows.jsx
hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/WebhookActioner.jsx
hasher-matcher-actioner/webapp/src/components/settings/ActionRulesTableRow.jsx
hasher-matcher-actioner/webapp/src/components/settings/ThreatExchangePrivacyGroupCard.jsx
hasher-matcher-actioner/webapp/src/pages/settings/ActionSettingsTab.jsx

Summary
---------
In previous PR [605](https://github.com/facebook/ThreatExchange/pull/605), I've made the field 'Action Name' and 'webhook type' non-editable. 
This PR is to make these two fields editable, the changes involved:
1. Made changes to ```/actions``` api, added two url params ```/actions/<old_name>/<old_config_sub_stype>```
2. Compare old_name with updated name and old_config_sub_stype with updated config sub type, if either one is different then delete the old config and create the new config. Otherwise will update old config
3. Made changes to UI related files to make those two fields editable
Test Plan
---------
1. ```mypy hmalib```
2. ```python -m pytest```
3. ```black hmalib```
4. ```make docker```
5. ```make upload_docker```
6. ```terraform apply```
7. test changes in …

make action performer name and webhook type editable

---

hasher-matcher-actioner/scripts/get_auth_token
hasher-matcher-actioner/scripts/storm_submissions_api
hasher-matcher-actioner/terraform/authentication-shared/main.tf

Summary
---------
mypy wasn't happy with the variable reuse within `scripts/storm_submissions_api.` This address that and allows the user to pass in the token to the script from the command line. 
This PR also adds a script that can request a token if you have AWS developer credentials in your environment which when combined with the changes above makes the test plan command possible.
Test Plan
---------
```
scripts/storm_submissions_api https://<id>.execute-api.us-east-1.amazonaws.com/ '/dev/200000.jpg' 2 --token $(scripts/get_auth_token) --url_mode
```

[hma] Fix typing in storm script and create method to get dev token from cli

---

hasher-matcher-actioner/terraform/authentication/outputs.tf
hasher-matcher-actioner/terraform/outputs.tf

Summary
---------
Output user pool name. This is required to make the 'Grant users access to HMA' wiki entry smoother.
Test Plan
---------
Ran `terraform output`

Add user-pool name to terraform outputs

---

hasher-matcher-actioner/scripts/get_auth_token
hasher-matcher-actioner/scripts/script_utils.py
hasher-matcher-actioner/scripts/storm_submissions_api
hasher-matcher-actioner/terraform/main.tf

Summary
---------
- (title)Moves part of storm_submit_api to util file for reuse
- Adds option to get `RefreshToken` instead of `IdToken` to `get_auth_token` (going to be used in soak testing)
Long term this will make the scripts more maintainable but the short term is a little inconvenience when it comes to using ec2 instances. (requires the copying of two files)
Test Plan
---------
Made sure both storm scripts still worked with changes.

[hma][scripts] Move part of storm_submit_api to util file for reuse

---

hasher-matcher-actioner/webapp/src/Sidebar.jsx
hasher-matcher-actioner/webapp/src/components/ContentMatchPane.jsx
hasher-matcher-actioner/webapp/src/pages/Matches.jsx
hasher-matcher-actioner/webapp/src/pages/layouts/FullWidthLocalScrollingLeftAlignedLayout.jsx
hasher-matcher-actioner/webapp/src/styles/_app.scss
hasher-matcher-actioner/webapp/src/styles/_matches.scss
hasher-matcher-actioner/webapp/src/styles/_sidebar.scss
hasher-matcher-actioner/webapp/src/styles/_variables.scss
hasher-matcher-actioner/webapp/src/utils/constants.jsx

Fixes #630. Can review commit by commit or all at once.
Summary
---------
Changes are mostly visual.
* Added border to sidebar
* Wrote a new layout for full width pages, made matches page use that layout
* Moved the content / signal search bar to the table header
* Added more content to the content details page
* Fancier empty state for no match selected
Test Plan
---------
Clicked around on prod data.
Screenshots attached.

Matches page design feedback

---

hasher-matcher-actioner/webapp/src/components/GraphWithNumberWidget.jsx
hasher-matcher-actioner/webapp/src/pages/Dashboard.jsx

Fixes #635 
Summary
---------
* move Graph below header in stat cards
* switch from red to blue for dashboard chart color
* allow graph to expand to fill the space available
* add loading and error state for stat cards
Test Plan
---------
Took screenshots!

Misc design changes to dashboard

---

hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/ActionPerformerColumns.jsx
hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/ActionPerformerRows.jsx
hasher-matcher-actioner/webapp/src/pages/settings/ActionSettingsTab.jsx

Summary
---------
In previous PR https://github.com/facebook/ThreatExchange/pull/620, I made action's name and type editable. Since action rules are dependent on actions, delete an action or update an action's name may cause issues. In this PR, I made below changes:
- Fetch and save all action rules when refresh the action page
- If an action has one or more action rules
1. disable the delete button, display a help icon to show the reason why the delete button is disabled
2. In edit mode, make action name non-editable, display a hover over message to show the reason why it's non-editable
Test Plan
---------

add validation rules when for update and delete

---

hasher-matcher-actioner/webapp/src/components/settings/ThreatExchangePrivacyGroupCard.jsx

Summary
---------
In ThreatExchange tab, if a privacy group is not in use, the header background will be gray, but the information icon stays blue. 
Test Plan
---------
test changes locally
before:
after:

change information icon background color if privacy group is not in use

---

hasher-matcher-actioner/hmalib/lambdas/api/matches.py
hasher-matcher-actioner/scripts/script_utils.py
hasher-matcher-actioner/terraform/authentication-shared/main.tf
hasher-matcher-actioner/terraform/authentication/main.tf
hasher-matcher-actioner/terraform/outputs.tf

Summary
---------
Expands `HasherMatcherActionerAPI` to support a number of API endpoints useful for testing. 
Sneaky side fixes (can breakout to own PR if requested):
- Remove vestigial `MatchSummary` field
- Fixed an issue in `authentication-shared/main.tf` and adds to `authentication/main.tf` so `get_auth_token` will work for all deployments with the right local aws credentials.
Test Plan
---------
Manually confirmed all new methods work (see bottom of `scripts/script_utils.py`) EXCEPT for `create_action` and `create_action_rule` which I plan to test as part of 'test deployments script' in my next PR.

[hma][scripts] Add API methods to script utils

---

hasher-matcher-actioner/hmalib/common/actioner_models.py

Summary
---------
When writing tests I discovered that  `WebhookGetActionPerformer` and `WebhookDeleteActionPerformer` don't override`WebhookActionPerformer.call()` correctly. This results in an key arg error for all calls to `WebhookActionPerformer.perform_action()`
Meaning Get and Delete Actions won't trigger correctly. 
Test Plan
---------
two line class override fix.

[hma][hotfix] fix broken override of call in WebhookActionPerformer subclass

---

hasher-matcher-actioner/terraform/outputs.tf
hasher-matcher-actioner/terraform/webapp/outputs.tf

Summary
---------
To make the [Installation of HMA](https://github.com/facebook/ThreatExchange/wiki/Installation) easier, include in the terraform outputs the link to view the UI at
Test Plan
---------
```
$ terraform -chdir=terraform apply
...
Terraform will perform the following actions:
Plan: 0 to add, 0 to change, 0 to destroy.
Changes to Outputs:
+ ui_url = "jesses-org-jeberl-hma-webapp.s3-website-us-east-1.amazonaws.com"
...
```
Go to jesses-org-jeberl-hma-webapp.s3-website-us-east-1.amazonaws.com and confirm it leads to the HMA UI

Add UI URL to terraform outputs

---

hasher-matcher-actioner/Makefile

Summary
---------
Some improvement to make the [install flow](https://github.com/facebook/ThreatExchange/wiki/Installation) easier/work.
1. Make `org` a default variable for terraform
2. Fix bug where user name prefix had trailing whitespace which was causing issues with Docker urls
Test Plan
---------
Followed the steps in the install guide: https://github.com/facebook/ThreatExchange/wiki/Installation

Improve Install flow

---

hasher-matcher-actioner/hmalib/lambdas/fetcher.py

Summary
---------
"inria-holidays-test" is not an `int` however our fetcher expects one. If someone creates a local pg config and mistakenly enables the fetcher, the fetcher will get stuck in a retry loop. This PR makes things marginally better by at least checking if the ID is an int (so at least we won't fail on our built-in sample hash set).
Test Plan
---------
Before
`[ERROR] ValueError: invalid literal for int() with base 10: 'inria-holidays-test' Traceback (most recent call last):`
...and retry again and again
After
`Fetch skipped because privacy_group_id(inria-holidays-test) is not an int`

[hma] add check to handle sample ds privacy_group_id

---

hasher-matcher-actioner/webapp/src/components/settings/ActionRuleFormColumns.jsx
hasher-matcher-actioner/webapp/src/components/settings/ActionRulesTableRow.jsx
hasher-matcher-actioner/webapp/src/pages/settings/ActionRuleSettingsTab.jsx

Summary
---------
An ActionRule consists of two sets of Classifications (formerly called Labels): `mustHaveLabels` an `mustNotHaveLabels`. The action rule is run if all the `mustHaveLabels` are present AND none of the `mustNotHaveLabels` are present on the Match. Formerly, the only way to edit these sets ActionRules was via raw JSON. This PR makes editing, viewing, and understanding the Classifications easier.
There are 4 types of Classifications: 
1. `BankIDClassification` which maps to a Dataset ID
2. `BankSourceClassification` which maps to a Dataset Source
3. `BankedContentIDClassification` which maps to the MatchedSignal ID
4. `Classification` which maps to an arbitrary Classification on the Match. For ThreatExchange, this corresponds to Tags on indicators
To edit Classifications, …

Make ActionRule Labels understandable

---

hasher-matcher-actioner/terraform/dashboard/lambda_widget.tpl
hasher-matcher-actioner/terraform/dashboard/main.tf
hasher-matcher-actioner/terraform/dashboard/outputs.tf
hasher-matcher-actioner/terraform/dashboard/variables.tf
hasher-matcher-actioner/terraform/main.tf
hasher-matcher-actioner/terraform/variables.tf
hasher-matcher-actioner/webapp/src/pages/Dashboard.jsx

Summary
---------
Because the dashboard is an added expense, I decided to only create it if the var.measure_performance is true. 
- Also updated the HMA UI Dash to match.
This also fixes the period of the dashboard to actually default to 1 min as intended 
Test Plan
---------
Viewed dashboard to confirm period 5min -> 1min

[hma] have dash use var.measure_performance and set time period to 1 minute

---

hasher-matcher-actioner/webapp/src/utils/DateTimeUtils.jsx

Summary
---------
python's `isoformat()` doesn't include a 'Z' at the end the way javascript expects. The results is the time of the `isoDateString` from the API is assumes to be local time (which is incorrect).
Lot of ways to tackle this. Picked the fastest but am open to feedback.
Ref: https://stackoverflow.com/questions/19654578/python-utc-datetime-objects-iso-format-doesnt-include-z-zulu-or-zero-offset
Test Plan
---------
Before:
After:

[hma] allow js to understand python iso strings 

---

hasher-matcher-actioner/scripts/listener.py
hasher-matcher-actioner/scripts/soak_test_system
hasher-matcher-actioner/scripts/storm_submissions_api
hasher-matcher-actioner/scripts/submit_content_test.py

Summary
---------
Clean up the submit_content_test and listener modules to allow for a cleaner soak_test run structure and interface.
Test Plan
---------
```
ubuntu@ip-<ip>:~/hma-dir$ python3 scripts/soak_test_system --help
usage: soak_test_system [-h] [--api_url API_URL] [--refresh_token REFRESH_TOKEN] [--client_id CLIENT_ID] [--hostname HOSTNAME] [--port PORT] [--submission_batch_size SUBMISSION_BATCH_SIZE] [--second_between_batches SECOND_BETWEEN_BATCHES]
Start a soak test on a deployed HMA instance and submit until cancelled
--api_url API_URL     HMA's API URL
--refresh_token REFRESH_TOKEN
refresh token to be used throughout a long running test
--client_id CLIENT_ID
id of app client for the pool of the refresh …
```

[hma][scripts] Move submit and listen to threads in soak test

---

.gitignore
hasher-matcher-actioner/webapp/src/react-app-env.d.ts

Summary
---------
This file seems to be necessary for Typescript compilation but not needed. Standard practice is to add to .gitignore.
More context: https://github.com/facebook/create-react-app/issues/6560
Test Plan
---------
npm still compiles

git ignore react file

---

hasher-matcher-actioner/terraform/hashing-data/main.tf
hasher-matcher-actioner/terraform/pdq-signals/main.tf

Summary
---------
`resource "null_resource" "provide_sample_pdq_data_holidays"` is created in terraform/hashing-data.
However this means the file with the sample signals is added to s3 before the indexer is created and listening for `aws_sns_topic.threat_exchange_data` notifs.
This means that until more datasets are created and files added to this s3 prefix (likely by syncing the fetcher) OR the indexer is triggered manually no index exists and the matcher fails.
This moves the upload of the sample set to s3 to be after the indexer creation.
Test Plan
---------
`terraform -chdir=terraform apply` and before making any changes to PGs etc make sure an index is actually created.

[hma][tf] Move sample data upload to after indexer creation

---

hasher-matcher-actioner/Makefile

Summary
---------
closes #698 
Which flagged that our [install instructions](https://github.com/facebook/ThreatExchange/wiki/Installation) did not provide context around `backend.tf` and defaulted to using a bucket that only ThreatExchange Eng have access to.
To address this I have updated the Makefile's `make dev_create_instance` (more specifically it's dependency `terraform/backend.tf`) to prompt the user if a backend.tf is not found to give more context and asks before creating the file.
I have already updated the instructions/wiki with more context that also reflects this change. 
Test Plan
---------
```
$ make dev_create_instance …
```

[hma] Prompt the user if terraform/backend.tf doesn't exist

---

hasher-matcher-actioner/terraform/main.tf

Summary
---------
the behavior of `null` in a part of a conditional expression is recommended here:  
https://www.terraform.io/docs/language/expressions/types.html 
However it was not behaving consistently so just added the defaults that should have been used automatically instead of `null`
Test Plan
---------
tf apply and checked that the queue values actually changed to the correct values based on `set_sqs_windows_to_min`

[hma][tf] fix sqs queue_batch_size inconsistency (null wasn't good enough)

---

hasher-matcher-actioner/scripts/listener.py
hasher-matcher-actioner/scripts/soak_test_system

Summary
---------
Soak test is now run from an interactive shell that lets users:
- dynamically increase and decrease the submit volume and rate.
- pause/resume submissions
- stop submitter but automatically wait for listener
Additional support to the soak test script was also added:
- running soak test without listener is now possible
- a list of file paths can be provided for submission instead of the default `sample_data/b.jpg`  file 
- autostart flag added to avoid having to provide input to the shell to begin the soak test
Next:
- Add calculations for latency of each submission by expanding listener
- Stress test: create way to spin up multiple soak test shells deployed across different ec2 instances 
Test Plan
---------
```
$ python3 scripts/soak_test_system --api_url …
```

[hma][scripts] Create interactive shell and expand functionality of soak test

---

hasher-matcher-actioner/hmalib/lambdas/api/stats.py
hasher-matcher-actioner/hmalib/models.py
hasher-matcher-actioner/hmalib/tests/test_pdq_models.py
hasher-matcher-actioner/webapp/src/pages/Dashboard.jsx

Summary
---------
DDB does not block writes when a transaction is in conflict. It errors out. So, we can't do transactions for every write. Will figure something out later, but until them, remove all vestiges of using transactions to count things.
Removed from models and from dashboard too.
Test Plan
---------
```shell
$ python
>>> from hmalib.models import PipelinePDQHashRecord
>>> import boto3
>>> table = boto3.resource('dynamodb').Table('dipanjanm-HMADataStore')
>>> x = PipelinePDQHashRecord.get_from_time_range(table, "2020-02-02T00:00:00", "2022-02-02T00:00:00")[0]
>>> x.write_to_table_if_not_found(table)
False
```
```
```

Stop counting totals in DDB transactions

---

hasher-matcher-actioner/scripts/submit_s3_bucket

Summary
---------
Re-use the thread pool executor rather than create one per iteration.
Left some sample numbers. On my local, we're peaking out at 15k / minute == 250 / second.
Test Plan
---------
Performed the test using 
```
$ ./scripts/submit_s3_bucket --token `cat .authtoken` --prefix "images/inria-holidays/100KB/" --api_url https://<redacted>.execute-api.us-east-1.amazonaws.com/ --loop <redacted> 
```
Verified that load gets generated on the api and hashing lambdas,

[hma][script]Reuse the same thread pool executor for submissions

---

hasher-matcher-actioner/webapp/src/pages/settings/ActionSettingsTab.jsx

Summary
---------
Changed confusing text on Action Settings Tab by making all the pronouns consistent.
Test Plan
---------
Ran web app locally, navigated to http://localhost:3000/settings/actions, confirmed updated text.

Change confusing text on Action Settings Tab

---

python-threatexchange/.devcontainer/Dockerfile
python-threatexchange/.devcontainer/bashrc
python-threatexchange/.devcontainer/devcontainer.json
python-threatexchange/.devcontainer/post-create
python-threatexchange/.devcontainer/zshrc

Summary
---------
In some distant future, we might be able to do a single devcontainer for both python-threatexchange and hma, but for now, have a separate one.
Test Plan
---------
Booted the devcontainer using "Cmd+P" -> "Remote Container: Open Folder.."
The necessary extensions were installed. Once I selected the python interpreter, I could cmd-click into library functions.

Devcontainer for python-threatexchange

---

hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/ActionPerformerColumns.tsx
hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/WebhookActioner.tsx

Summary
---------
This PR is to convert WebhookActioner, ActionPerformerColumns files to tsx files and fix type errors
Future Action
---------
Need to also convert ActionPerformerRows and ActionSettingsTab to tsx file, but there is a known issue with ion-icon package and typescript, will spend little more time to look into this issue
Test Plan
---------
test localhost for all test cases on Action setting tab
https://user-images.githubusercontent.com/81996660/125141707-c7d8bc00-e0e3-11eb-9094-50f2290a5130.mov

convert action settings related files to typescript files

---

python-threatexchange/threatexchange/cli/dataset_cmd.py
python-threatexchange/threatexchange/content_type/meta.py

Summary
---------
Add functionality to the existing `dataset` command to display stats about downloaded data. My proposed changes to the command:
`threatexchange dataset --type <content type>`:
```
% threatexchange --config config.json dataset --type photo
pdq: 14023
photo_md5: 160
video_md5: 23
```
`threatexchange dataset --type <signal type>` (existing functionality):
```
% threatexchange --config config.json dataset --type video_md5
video_md5: 161124
photo_md5: 23
```
`threatexchange dataset --tag <tag name>`:
```
% threatexchange --config config.json dataset --tag media_priority_s1
video_md5: 14529
pdq: 657
photo_md5: 109
```
Test Plan
---------
See above for sample commands run to show filtering on a subset of the data for privacy group <>, app id <>. These commands demonstrate …

Update dataset command to show more stats

---

python-threatexchange/threatexchange/signal_type/pdq_index.py

Summary
---------
In doing MD5 indexing, I am extending PDQIndex and TrivialSignalTypeIndex and giving them s3 storage. However, I want to retain the build method from the super classes.
This change will allow a building sub class instances.
Test Plan
---------
```
$ python -m black threatexchange
$ python -m py.test .
```

threatexchange: Allow subclasses to build pdq indexes

---

hasher-matcher-actioner/hmalib/common/threatexchange_config.py

Summary
---------
This PR will not mark sample test dataset as in_active when users click "sync" button in ThreatExchange settings UI.
Test Plan
---------
2. mypy hmalib
4. make docker
5. make upload_docker 
6. terraform apply
7. test in localhost
before : 
https://user-images.githubusercontent.com/81996660/125684911-1f9edc31-311d-489a-92fa-6e8129adb164.mov
after:
https://user-images.githubusercontent.com/81996660/125684940-1d4021af-be5a-4dd7-b9c1-cbc5cc12c3c6.mov
If sample test dataset is not created, click sync button will not add it
https://user-images.githubusercontent.com/81996660/125691572-c63b8f94-a453-4f81-85d6-ae0978571a45.mov

always mark sample test dataset id as in_use

---

pdq/cpp/Makefile

Summary
---------
GCC 8 added new warnings that cause `make` of `pdq/cpp` to fail due to `-Werror`
I don't think it is worth digging into the example library that is causing the errors so for now I have the Makefile ignore those.
Test Plan
---------
Locally installed gcc 8.5 have saw `make` complete successfully (failing with warnings before) after adding the `-Wno-stringop-truncation -Wno-class-memaccess` flags.

Suppress new GCC 8 warnings in pdq/cpp

---

hasher-matcher-actioner/terraform/api/main.tf
hasher-matcher-actioner/terraform/api/variables.tf
hasher-matcher-actioner/terraform/variables.tf

!!! This is a stacked PR. Only review c32ff57aef541878eac17a5bcece4c4a5edf7a1b "Add params to Partner Local Buckets terraform arg" !!!
Summary
---------
Partners who want to upload their banks to HMA will likely only want to send specific file types and specific folders within buckets to HMA. This PR enables this through prefix filtering and suffix filtering in terraform
Test Plan
---------
Ran the following tests by editing my tfvars file, running `terraform plan`, and looking at what would change in AWS as a result.
Change: `params:{"prefix" : "test/folder/path/"}`
Result:
```
~ resource "aws_s3_bucket_notification" "bucket_notification" {
id     = "jesses-separate-aws-bucket"
~ lambda_function {
+ filter_prefix       = "test/folder/path/"
id                  = …
```

Filter Partner Bucket Uploads to files in specific folders or with specific extensions

---

hasher-matcher-actioner/terraform/api/main.tf

Summary
---------
Not having a partner_bucket var in terraform.tfvars was throwing the following error:
│ Error: Error updating IAM policy arn:aws:iam::521978645842:policy/jeberl_api_root_role_policy20210615212904550900000005: MalformedPolicyDocument: Policy statement must contain resources.
│ 	status code: 400, request id: 24b32dc9-bf43-4611-afe1-e65246ac187b
│
│   with module.api.aws_iam_policy.api_root,
│   on api/main.tf line 159, in resource "aws_iam_policy" "api_root":
│  159: resource "aws_iam_policy" "api_root" {
combined two statements in policy document so its never empty
Test Plan
---------
1. Remove partner_bucket variable
2. Run `terraform -chdir=terraform apply`
3. Runs correctly

Accept Empty Partner Buckets variable in terraform.tfvars

---

hasher-matcher-actioner/webapp/src/components/SubmitContentFields.jsx
hasher-matcher-actioner/webapp/src/pages/SubmitContent.jsx

Summary
---------
Additional fields on content objects are currently a set of strings. If we want to make them a key-value pair in the future we can however the UI should match the current backend as it exists now to avoid confusion. 
Test Plan
---------
Did a full submit to verify functionality. 
Old form: 
Form now looks like this:

[hma][ui] Update additional fields in submit form to reflect API backend.

---

hasher-matcher-actioner/hmalib/common/actioner_models.py
hasher-matcher-actioner/hmalib/common/message_models.py
hasher-matcher-actioner/hmalib/lambdas/actions/action_evaluator.py
hasher-matcher-actioner/hmalib/lambdas/actions/action_performer.py
hasher-matcher-actioner/hmalib/models.py
hasher-matcher-actioner/terraform/actions/main.tf

Summary
---------
We currently accept "AdditionalFields" when partners submit content but don't do anything with the fields they provide. This PR includes additional_fields in Webhooks when sent.
A future PR will add the ability to filter by additional_fields in actionRules 
Note: Also did some clean up of imports in files I touched
Test Plan
---------
1. Create Action and ActionRule that sends all TE matches to webhook https://webhook.site/81bf390d-d2e3-4757-989d-9822a81d85dd/4abcd206-e1cd-40f2-8514-1eb5511abe4f/1
1.  Submit matching Content to HMA with 2 additional_fields set 
2. Confirm that additional fields are included in Webhook response here: https://webhook.site/#!/81bf390d-d2e3-4757-989d-9822a81d85dd/4abcd206-e1cd-40f2-8514-1eb5511abe4f/1

Send additional fields in Action responses

---

hasher-matcher-actioner/hmalib/lambdas/actions/action_evaluator.py
hasher-matcher-actioner/hmalib/lambdas/api/api_root.py

See #738 for context and test plan. Will be easier to review with a new PR and rebase
Test Plan
---------
1. Create a new bucket `jesses-separate-aws-bucket` in the UI that is not controlled by terraform to simulate a separate bucket owned by a partner
2. Add the following line to my `terraform.tfvars` file:
```
local_image_buckets = [{"name": "jesses-separate-aws-bucket", "arn" : "arn:aws:s3:::jesses-separate-aws-bucket"}]
```
3. `make upload_docker && terraform -chdir=terraform apply`
4. using the AWS UI upload images to the bucket
5. Through logs watch them be processed by the api_root lambda, added to the sqs queue, and then loaded and hashed by the pdq_hasher: ![image](https://user-images.githubusercontent.com/24800630/128760967-ea23b9b7-dcfb-4c8b-8e62-4205573820ca.png)

Fix Content ID Bug In Partner Bucket Uploads

---

hasher-matcher-actioner/webapp/src/Api.jsx
hasher-matcher-actioner/webapp/src/pages/ContentDetails.jsx
hasher-matcher-actioner/webapp/src/pages/SubmitContent.jsx
hasher-matcher-actioner/webapp/src/utils/constants.jsx

Summary
---------
Having both an 'upload' and a 'direct upload' option is confusing and unnecessary for the submit UI.  It is still possible the  soon to be renamed 'direct submit' endpoint could be useful outside of the UI context for sending bytes directly in one request, so leaving that for now. It fails for large images anyway...
One of  the reasons I had kept it around up until now was actually because of #598 so folks could still ~demo HMA using Firefox. As a part of this removal I also tried to fix #598.  Which was easier to fix now that we only have one upload flow as I was able to just remove the need to get the path which is not supported the same way in all browsers. 
Test Plan
---------
Made sure the remaining 'upload' flow works for both Firefox and Chrome. If you'd like a …

[hma][ui] Remove old direct upload option

---

hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/submit.py
hasher-matcher-actioner/scripts/get_auth_token
hasher-matcher-actioner/scripts/script_utils.py
hasher-matcher-actioner/scripts/submit_s3_bucket
hasher-matcher-actioner/webapp/src/Api.jsx
hasher-matcher-actioner/webapp/src/pages/SubmitContent.jsx
hasher-matcher-actioner/webapp/src/utils/constants.jsx

Summary
---------
Note: Reviewing commit by commit or as one should both work. RC and ask for commit level details as desired. 
The Submit API as it exists right now [wiki](https://github.com/facebook/ThreatExchange/wiki/Content-Submissions-API) (to be updated post merge), is really 3 different APIs on the same path using an enum so the server can tell requests apart (this isn't great. my bad).
This PR removes 'just make it work' `/submit/` Swiss army endpoint and creates the following three endpoints:
- /submit/url/ - (formerly `SubmissionType.FROM_URL`)
- /submit/bytes/ - (formerly `SubmissionType.DIRECT_UPLOAD`)
- /submit/post_url/ - (formerly `SubmissionType.POST_URL_UPLOAD`)
Luckily due to good client library abstraction, the …

[hma][api] Split submit API into different paths for each submission type.

---

hasher-matcher-actioner/hmalib/common/content_models.py
hasher-matcher-actioner/hmalib/common/tests/test_content_models.py
hasher-matcher-actioner/hmalib/lambdas/actions/action_evaluator.py
hasher-matcher-actioner/hmalib/lambdas/api/content.py
hasher-matcher-actioner/webapp/src/Api.jsx
hasher-matcher-actioner/webapp/src/components/ContentMatchPane.jsx
hasher-matcher-actioner/webapp/src/pages/ContentDetails.jsx

Summary
---------
ContentObject queries used to require content_type. This is problematic because
a) It may be taken to mean `content_type` + `content_id` is unique. But we would like content_id to be globally unique.
b) later pipeline stages (actioning) do not have access to content_type. With additional data now being required in actioning, the content_type was impossible to obtain.
This PR removes the need for content_type in ContentObject.** queries. This will also allow the UI to link to a single page for a content_id and then support different previews based on the content_type returned by the API.
Test Plan
---------
Ran mypy, black and py.test.
Deployed docker image and webapp after tainting.
1. Verified that a URL submission flow works. (including calling webhook)
2. Verified …

`ContentObject` queries no longer require `content_type` #756

---

hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/content.py
hasher-matcher-actioner/hmalib/lambdas/api/submit.py
hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_matcher.py
hasher-matcher-actioner/scripts/script_utils.py
hasher-matcher-actioner/terraform/api/main.tf
hasher-matcher-actioner/terraform/api/variables.tf
hasher-matcher-actioner/terraform/main.tf
hasher-matcher-actioner/terraform/pdq-signals/main.tf

Summary
---------
#749 made a noble attempt to keep `pdq_hasher` and `pdq_matcher` working while adding the unified versions however a few things were missed/not yet handled.
This PR fixes those errors and migrates recent changes to the submit API that were skipped (likely because #750 merged after the implementation and review of the MD5 additions in 749). 
More clean up and migration to the architecture changes that #749 made are needed in follow ups but this should at least get prod/main working e2e again for all submission methods.
Test Plan
---------
Checked that both `upload` and `from url` submit work using `make dev_test_instance` for upload submissions e2e and `./scripts/submit_s3_bucket ...` for url submissions and well as both flows on the UI

[hma][hotfix] fix non-url submissions

---

hasher-matcher-actioner/hmalib/common/content_models.py
hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/submit.py
hasher-matcher-actioner/scripts/hma_client_lib.py
hasher-matcher-actioner/scripts/hma_script_utils.py
hasher-matcher-actioner/scripts/hma_shell
hasher-matcher-actioner/terraform/api/main.tf
hasher-matcher-actioner/terraform/api/variables.tf
hasher-matcher-actioner/terraform/hasher/variables.tf
hasher-matcher-actioner/terraform/main.tf
hasher-matcher-actioner/terraform/matcher/variables.tf
hasher-matcher-actioner/terraform/pdq-signals/outputs.tf

Summary
---------
Created a new submit endpoint `/submit/hash/` for submitting hashes directly. This endpoint currently limited and only supports pdq hashes.
Future work:
- Overwrite flag to be required for resubmits
- Updates to submit UI page to support this option
- Support for MD5 hashes
Test Plan
---------
Submitted the hashes using the new `hma_client_lib.DeployedInstanceClient.submit_test_content_hash` and saw using hma_shell that the following occured:
- Content Object Created
- Match Found
- Action Triggered
```
$ scripts/hma_shell …
```

[hma][api] Add option to submit  PDQ hashes directly 

---

hasher-matcher-actioner/hmalib/lambdas/api/submit.py
hasher-matcher-actioner/scripts/hma_script_utils.py
hasher-matcher-actioner/webapp/src/Api.jsx
hasher-matcher-actioner/webapp/src/pages/SubmitContent.jsx
hasher-matcher-actioner/webapp/src/utils/constants.jsx

Summary
---------
Small change. The submit API for upload returns a signed url to the client. Code calls this a 'post_url' but the url is actually designed to be used in a put request. Also I used an `_` instead of a `-` in the path (we agreed to use the dash awhile ago and should stick to it). 
Test Plan
---------
Made sure both manual submission and `python scripts/hma_client_lib.py` still worked.

[hma][small] Update `post_url` to `put-url` to be clearer and match convention

---

hasher-matcher-actioner/hmalib/common/signal_models.py
hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/matches.py
hasher-matcher-actioner/hmalib/matchers/matchers_base.py
hasher-matcher-actioner/terraform/api/main.tf
hasher-matcher-actioner/terraform/api/variables.tf
hasher-matcher-actioner/terraform/main.tf

Summary
---------
Instead of submitting content to HMA right away, if the user just want to see if a signal they have ~would~ match they can now submit that signal to `/matches/for-hash/` to get what signal on the live indexes should have found.
Test Plan
---------

[hma][api] add get matches for raw hash endpoint

---

hasher-matcher-actioner/scripts/multi_part_pull_request_template

Summary
---
This used to be a reverse-chronological list of commits which would make
less sense when read top to bottom.
Now using a chronological ordering which feels more natural.
Test Plan
---
The PR summary for #763 was crafted using the above change.

Chronological output of commits in `multi_part_pull_request_template` script

---

hasher-matcher-actioner/hmalib/common/content_models.py
hasher-matcher-actioner/hmalib/lambdas/api/submit.py
hasher-matcher-actioner/webapp/src/Api.jsx
hasher-matcher-actioner/webapp/src/pages/SubmitContent.jsx

Summary
---------
Right now the system pipeline depends on `content_id` given by the client. 
Submitting again with the same `content_id` is possible for things like testing but should not be the default.
Additionally trying to submit different content for the same id is likely to mess with the system and result in undefined behavior.  We have some protections to avoid this but more couldn't hurt.
Once merged if a client wants to submit a content object with the same id they must include `force_resubmit=True` in their request. 
I also added the ability to add this flag on the submit UI using a textbox and improve our error handling. 
- full disclosure I took a short cut on the UI work because it is annoying to work in jsx files right now. I will clean up when changing the file to .tsx …

[hma] add resubmit arg to submission requests and require it if content_id is found.

---

python-threatexchange/setup.py

Summary
---------
We changed over to use allow_methods from the old names. However, we then didn't add install hints to make sure those changes were picked up. Add an install hint.
Test Plan
---------
Before:
```
$ pip install --upgrade .
File "/data/users/dcallies/fork_te/ThreatExchange/python-threatexchange/threatexchange/api.py", line 149, in _get_sess
ion
backoff_factor=0.2,  # ~1.5 seconds of retries
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'
```
After:
```
$ pip install --upgrade .
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.facebook.com/v9.0/
```
Well... it's progress.

[pytx] Fix problem with installing wrong version of urllib library

---

hasher-matcher-actioner/hmalib/common/messages/writeback.py
hasher-matcher-actioner/hmalib/common/models/signal.py
hasher-matcher-actioner/hmalib/common/models/tests/test_pipeline_models.py
hasher-matcher-actioner/hmalib/common/s3_adapters.py
hasher-matcher-actioner/hmalib/lambdas/api/matches.py
hasher-matcher-actioner/hmalib/lambdas/pdq/pdq_matcher.py
hasher-matcher-actioner/hmalib/matchers/matchers_base.py
hasher-matcher-actioner/webapp/src/Api.jsx
hasher-matcher-actioner/webapp/src/components/ContentMatchTable.jsx
hasher-matcher-actioner/webapp/src/components/OpinionChangeConfirmModal.jsx
hasher-matcher-actioner/webapp/src/components/OpinionTableCell.jsx

NOTE: All current signal metadata objects will be unusable after this. On matches on your instance, new signal metadata objects will be created. If your opinions have synced with threatexchange, you've nothing to worry about.
Summary
---------
This is in the lead-up to supporting video-md5 signal metadata.
Be sure to go through the module docstring for `hmalib.common.models.signal`
To reviewer: There may be questions on choice of PK / SK for signal metadata. Happy to respond in inline comments. 
Test Plan
---------
```
```
A URL upload for an image in our test privacy groups was done. This resulted in matches and actions. These were visually verified on the pipeline progress page.
On the content details page as shown in …

Make PDQSignalMetadata signal-type agnostic -> ThreatExchangeSignalMetadata

---

hasher-matcher-actioner/terraform/hashing-data/main.tf

Summary
---------
A handrolled SQS config was indistinguishable to terraform from the one it was supposed to update. A principal field was missing. This prevented the sqs bucket notification from getting created.
Added the principals identifier and verified that the generated JSON matches what I had handwritten.
Test Plan
---------
```
$ terraform taint module.hashing_data.aws_s3_bucket_notification.bucket_notifications
$ terraform taint module.hashing_data.aws_sqs_queue_policy.allow_create_events_from_primary_bucket
$ terraform apply
```
Destroy 2, Create 2 < Accept.
Created the bucket notifications on the s3 bucket.

hotfix: ensure open principals on queue policy when creating bucket notifications

---

hasher-matcher-actioner/hmalib/common/configs/actioner.py
hasher-matcher-actioner/hmalib/common/tests/test_action_rule_evaluation.py

Summary
---------
Enable users to include the content ID and content hash in webhook actions.
When we send webhooks in the action framework, the context of the match is included in the data of the HTTP request. However, for the workplace integration, and potentially other integrations as well, including content ID and/or hash in the url or the headers of the request is required.
This diff enables that by parsing the urls and headers of the action rule and replacing the strings `<content-id>` with the matched content ID and `<content-hash>` with the matched content hash
Test Plan
---------
Run `pytest` which will send real requests to the webhook monitoring page
Navigate to [the monitoring page](https://webhook.site/#!/d0dbb19d-2a6f-40be-ad4d-fa9c8b34c8df/11074918-20e3-4f8f-8d72-9b77a3a6f6a …

Parse URLs and headers in Actions

---

hasher-matcher-actioner/hmalib/aws_secrets.py
hasher-matcher-actioner/hmalib/lambdas/api/api_auth.py
hasher-matcher-actioner/terraform/api/main.tf
hasher-matcher-actioner/terraform/api/variables.tf
hasher-matcher-actioner/terraform/fetcher/variables.tf
hasher-matcher-actioner/terraform/main.tf
hasher-matcher-actioner/terraform/variables.tf

Summary
---------
Builds off of #776 
Instead of passing the access token value to api_auth as an raw environment variable, tf will store it in aws_secret and can also be adjusted manually.
This also adds support for multiple access tokens instead of just one therefore the tfvars value defaults to empty list instead of string (though api_auth still has null checks to be safe). e.g. `integration_api_access_tokens  = ['<token1>', '<token2>']`
Test Plan
---------
Made sure all auth flows still worked for failed as expected in the same way they did in #776

[hma][api][auth] store API access token in aws_secret

---

hasher-matcher-actioner/scripts/get_auth_token
hasher-matcher-actioner/scripts/hma_client_lib.py
hasher-matcher-actioner/scripts/hma_script_utils.py
hasher-matcher-actioner/scripts/hma_shell
hasher-matcher-actioner/scripts/submitter.py

Summary
---------
Remove the confusing and overly complex cognito work around/flow for the test scripts as we now have access to the kind of access token added in #776 
Test Plan
---------
`python scripts/hma_client_lib.py` and more.

[hma][scripts] have test scripts use custom access tokens instead of user_pool

---

hasher-matcher-actioner/hmalib/common/models/signal.py
hasher-matcher-actioner/hmalib/lambdas/api/matches.py
hasher-matcher-actioner/hmalib/lambdas/api/middleware.py

Summary
---------
Generalize `/matches/for-hash/` (i.e. the "M") endpoint so that it can support both 'pdq' and 'video_md5'
Also fixes a tiny bug in `ThreatExchangeSignalMetadata.to_json` from changes  #784
Test Plan
---------
Used postman to hit the endpoint using both signal types:
exact pdq:
exact md5:
near pdq:

[hma][api] generalize for-hash and fix to_json for match data

---

hasher-matcher-actioner/hmalib/lambdas/api/api_auth.py
hasher-matcher-actioner/terraform/api/main.tf
hasher-matcher-actioner/terraform/api/outputs.tf
hasher-matcher-actioner/terraform/dashboard/main.tf
hasher-matcher-actioner/terraform/dashboard/variables.tf
hasher-matcher-actioner/terraform/main.tf

Summary
---------
In trying to benchmark the `/matches/for-hash/` endpoint I noticed a few things about the auth lambda added in #776 
1) It was not on the dashboard.
2) Unlike the JWT Authorizer it replaced, it has `authorizer_result_ttl_in_seconds = 0` (default is 300 or 5 mins)
3) Service token method check could be more cached and because it was after a ~non-trivial JWT checks and exceptions throw.
So this PR:
1) Added it to the dashboard next to the API widget (see photo in test plan)
2) Removed that ttl line to enable the default caching (helped benchmark significantly) 
3) Move check for service api tokens to before JWT tokens and cached the method (also boosted benchmark).
With these changes instead of hitting our lambda concurrency limits in auth and rapidly throttling anything …

[hma][api] Adjust auth lambda and add to dashboard

---

hasher-matcher-actioner/webapp/src/Api.tsx
hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/ActionPerformerColumns.tsx
hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/ActionPerformerRows.tsx
hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/WebhookActioner.tsx
hasher-matcher-actioner/webapp/src/components/settings/ActionRuleFormColumns.tsx
hasher-matcher-actioner/webapp/src/components/settings/ActionRulesTableRow.tsx
hasher-matcher-actioner/webapp/src/pages/Settings.tsx
hasher-matcher-actioner/webapp/src/pages/settings/ActionRuleSettingsTab.tsx
hasher-matcher-actioner/webapp/src/pages/settings/ActionSettingsTab.tsx

Issue #779
Summary
---------
OK. Bear with me here...
I went about trying to make the Actions and ActionRules Settings pages update automatically. Formerly, if you added, deleted, or updated an Action, the change would not automatically show up on the ActionRules page until you refreshed. Similarly, changes to actionrules wouldn't show up on the actions page. The solution here was to move the React State components from the child tab classes to the parent settings class so they could be shared.
In making this change however I started doing some refactoring and adding additional tying. These changes grew until I was no longer sure which changes were for the initial feature and which were simply refactors.
All together the new changes are:
- Adding stricter typing across Actions and …

Make Actions and ActionRules Settings pages update automatically

---

hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/terraform/api/main.tf

Summary
---------
See title. To enable this I had to allow the lambda to query for its own Function Configuration because `LastModified` is included in that [result](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda.html#Lambda.Client.get_function_configuration) but not part of the [basic context](https://docs.aws.amazon.com/lambda/latest/dg/python-context.html):
Test Plan
---------

[hma][api] update root reply to include LastModified

---

hasher-matcher-actioner/hmalib/common/models/bank.py
hasher-matcher-actioner/hmalib/lambdas/api/bank.py
hasher-matcher-actioner/webapp/package.json
hasher-matcher-actioner/webapp/src/Api.tsx
hasher-matcher-actioner/webapp/src/App.tsx
hasher-matcher-actioner/webapp/src/Sidebar.tsx
hasher-matcher-actioner/webapp/src/forms/BankDetailsForm.tsx
hasher-matcher-actioner/webapp/src/messages/BankMessages.tsx
hasher-matcher-actioner/webapp/src/pages/bank-management/AddBankModal.tsx
hasher-matcher-actioner/webapp/src/pages/bank-management/ViewAllBanks.tsx
hasher-matcher-actioner/webapp/src/pages/bank-management/ViewBank.tsx
hasher-matcher-actioner/webapp/src/pages/layouts/FixedWidthCenterAlignedLayout.tsx
hasher-matcher-actioner/webapp/src/utils/MediaUtils.tsx

Summary
---------
Adds a new sidebar entry, a form to add and edit banks. Only supports bank name and bank descriptions. 
Uses `formik`: Provides state-management for forms.
Test Plan
---------
* Deploy to my prefix
* Used the UI to add a bank, view all banks, empty state when no banks exist, edit banks.
**Empty State for View All Banks Page**
**Modal to create a new bank**
**View All Banks Page with the newly created bank**
**View single bank**

[banks][ui] view-all, add and edit banks

---

hasher-matcher-actioner/webapp/src/pages/ContentDetailsWithStepper.tsx

Summary
---------
bug: unreached stage's attribute has a value of null and not undefined
bonus: add a manual refresh button
Test Plan
---------
Verified that:
* UI self refreshes until action is done
* Refresh button clicks cause refresh no matter what

bug: Get progress page to auto-refresh

---

hasher-matcher-actioner/scripts/multi_part_pull_request_template

Summary
---------
When I am doing individual commits, I add a lot of context to those commit messages. They get missed out when running the script. This helps by adding the commit message to the output. Now I only have to copy-paste to github.
Test Plan
---------
```shell
EARLIER
-------
user@vm$ ./scripts/multi_part_pull_request_template --pull-request 805
NOW
------
user@vm$ ./scripts/multi_part_pull_request_template --pull-request 805
When I am doing individual commits, I add a lot of context to those commit messages. They get missed out when running the script. This helps by adding the commit message to the output. Now I only have to copy-paste to github.  
```

Add commit message to multi-part-pull-request script

---

hasher-matcher-actioner/.gitignore
hasher-matcher-actioner/PR.md
hasher-matcher-actioner/hmalib/scripts/cli/command_base.py
hasher-matcher-actioner/hmalib/scripts/cli/main.py
hasher-matcher-actioner/hmalib/scripts/cli/run_lambda.py
hasher-matcher-actioner/hmalib/scripts/cli/shell.py
hasher-matcher-actioner/hmalib/scripts/cli/soak.py
hasher-matcher-actioner/hmalib/scripts/common/client_lib.py
hasher-matcher-actioner/hmalib/scripts/common/utils.py

Summary
---------
In future commits, we add a new command that does not need API URLs, just terraform outputs.  
Test Plan
---------
```shell
$ python -m hmalib.scripts.cli.main --refresh-tf-outputs run-lambda --lambda-name hasher
Loading faiss with AVX2 support.
Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
Loading faiss.
Successfully loaded faiss.
Performance measurement requested. Supplying appmetrics instrumentation.
Will use content_id: f561de7a-34af-4df6-98a7-234fa32bc876
```
Provide the value of 'event' to your lambda by definining a module `lambda_local.py` in `hasher-matcher-actioner/`. For hasher, my module looks like:
```python
import json
import uuid
from threatexchange.content_type.photo import PhotoContent
from …
```

Fetch env vars for your prefix and run lambdas locally

---

tmk/cpp/hashing/filehasher.cpp

Summary
---------
otherwise, filenames with spaces fail, and malicious filenames may
potentially cause arbitrary code execution.
Test Plan
---------
ran `make` which succeeded and printed "REGRESSION PASSED"

tmk: handle input filenames with shell metacharacters

---

pdq/cpp/Makefile

./CImg.h:53981:11: error: this 'for' clause does not guard... [-Werror=misleading-indentation]
53981 |           for (int d = 0; d<5; ++d) ndims[d] = (unsigned short)dims[d]; cimg::fwrite(ndims._data,nbdims,nfile); } \
|           ^~~
./CImg.h:54046:7: note: in expansion of macro '_cimg_save_pandore_case'
54046 |       _cimg_save_pandore_case(0,0,1,"int",9);
|       ^~~~~~~~~~~~~~~~~~~~~~~
and many many more expansions of _cimg_save_pandore_case.
-Wno-misleading-indentation support goes back to gcc 4.4, long predating
c++11, so we can assume it is supported by gcc.
Test Plan
---------
ran `make` which succeeded (after other changes in other PRs)

pdq: add -Wno-misleading-indentation for CImg

---

python-threatexchange/benchmarks/benchmark_pdq_faiss_matchers.py
python-threatexchange/tests/hashing/test_index_updates.py
python-threatexchange/tests/hashing/test_pdq_faiss_matcher.py
python-threatexchange/threatexchange/hashing/pdq_faiss_matcher.py
python-threatexchange/threatexchange/signal_type/index.py
python-threatexchange/threatexchange/signal_type/pdq_index.py
python-threatexchange/threatexchange/signal_type/signal_base.py

Summary
---------
* Update signatures for PDQIndex, SignalTypeIndex, threatexchange.hashing.pdq_faiss_matcher.{PDQHashIndex, PDQFlatHashIndex, PDQMultiHashIndex}
* Update usages in test code
* Add test specifically to verify that index updates work (test_index_updates.py)
Test Plan
---------
```
$ python -m black threatexchange
```
Sadly pytx does not use mypy yet. I ran it to find a litany of failing mypy rules. I verified none were introduced by changes I made.

Support adding hashes to PDQIndex, TrivialSignalTypeIndex

---

python-threatexchange/threatexchange/signal_type/pdq_ocr.py
python-threatexchange/threatexchange/signal_type/tlsh_pdf.py

Summary
---------
`python-threatexchange/threatexchange/signal_type/tlsh_pdf.py` was over zealous with its imports meaning that `tlsh` & `pdfminer` were actually required not just an extra if [pdf] was included. 
Moved this imports to the functions themselves instead (like is done with `pdq.py` for `Pillow` etc.)
Test Plan
---------
`pytest python-threatexchange` after `make local_install`

[python-tx] fix import error for not having tlsh installed

---

hasher-matcher-actioner/examples/vpc_deploy/README.md
hasher-matcher-actioner/examples/vpc_deploy/terraform/.terraform.lock.hcl
hasher-matcher-actioner/examples/vpc_deploy/terraform/main.tf
hasher-matcher-actioner/examples/vpc_deploy/terraform/outputs.tf
hasher-matcher-actioner/examples/vpc_deploy/terraform/variables.tf
hasher-matcher-actioner/hmalib/lambdas/api/action_rules.py
hasher-matcher-actioner/hmalib/lambdas/api/actions.py
hasher-matcher-actioner/hmalib/lambdas/api/api_auth.py
hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/bank.py
hasher-matcher-actioner/hmalib/lambdas/api/content.py
hasher-matcher-actioner/hmalib/lambdas/api/datasets.py
hasher-matcher-actioner/hmalib/lambdas/api/matches.py
hasher-matcher-actioner/hmalib/lambdas/api/middleware.py
hasher-matcher-actioner/hmalib/lambdas/api/stats.py
hasher-matcher-actioner/hmalib/lambdas/api/submit.py
hasher-matcher-actioner/hmalib/scripts/common/utils.py
hasher-matcher-actioner/terraform/api/main.tf
hasher-matcher-actioner/terraform/api/outputs.tf
hasher-matcher-actioner/terraform/api/variables.tf
hasher-matcher-actioner/terraform/main.tf
hasher-matcher-actioner/terraform/terraform.tfvars.example
hasher-matcher-actioner/terraform/variables.tf
hasher-matcher-actioner/webapp/package-lock.json
hasher-matcher-actioner/webapp/package.json
hasher-matcher-actioner/webapp/src/Api.tsx
hasher-matcher-actioner/webapp/src/App.tsx
hasher-matcher-actioner/webapp/src/Sidebar.tsx

Summary
---------
Builds off of #819 (so only the top three commits should be new with the two commit below that being fixes from 819)
Adds 3 new tfvars:
- `vpc_id` : id of vpc which to restrict the API.
-  `vpc_subnets` : list of private subnets to connect to the `aws_vpc_endpoint` used to access the private API
- `security_groups` : list of security groups to connect to the `aws_vpc_endpoint` used to access the private API
This also adds `examples/vpc_deploy/` to hma to make testing of these changes possible.
Test Plan
---------
Made sure deploy and unit tests still worked without passing in the new arguments. (i.e. does not break existing)
Also ran 30 min soak test that seemed to behave normally. 
Used `examples/vpc_deploy/terraform` + other steps documented in README.md to create a …

[hma][api] Add VPC support to HMA API 

---

hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/submit.py
hasher-matcher-actioner/hmalib/scripts/common/utils.py
hasher-matcher-actioner/terraform/api/main.tf
hasher-matcher-actioner/terraform/api/variables.tf
hasher-matcher-actioner/terraform/main.tf
hasher-matcher-actioner/terraform/variables.tf

Summary
---------
Along with `submit/hash/` `submit/url/` etc. this adds an `submit/s3/` endpoint to submit content from an s3 bucket the HMA has been given access to via `partner_image_buckets` in `terraform.tfvars` (I also disable bucket notifications by default for the old s3 integration, they now require `enable_partner_upload_notification = true`
Will update docs after merge for now here is an example/how to use:
Example tf vars arg:
```
partner_image_buckets = [{
"name" : "example-bucket-name-with-test-media",
"arn" : "arn:aws:s3:::example-bucket-name-with-test-media",
"params" : {}
}]
```
Example submit using changes to `hmalib/scripts/common/utils.py` payload:
```python
api.submit_via_s3_object(
content_id="barrett-test-s3-object-submit-1", …
```

[hma][api] add s3 api submit support

---

hasher-matcher-actioner/Makefile
hasher-matcher-actioner/requirements-dev.txt
hasher-matcher-actioner/terraform/terraform.tfvars.example

Summary
---------
Our Makefile is designed to make using/deploying HMA a little easier however it was created back when `terraform.tfvars` was a lot simpler. We shouldn't assume 'prefix' and create the file automatically anymore. 
I changed the `terraform/terraform.tfvars` make target to instead just let the user know they need the file and exit if it can't find it. 
Also made a few minor changes to `terraform/terraform.tfvars.example` and added `dev_install_hmacli` to install the python cli via the Makefile.
Removed `dev_clear_configs` because it just deletes two files and is more likely to be used by mistake than be helpful.
Test Plan
---------
With terraform/terraform.tfvars not present
```
$ make terraform/terraform.tfvars
ACTION REQUIRED: terraform/terraform.tfvars is needed to …
```

[hma][make] update Makefile to not assume `prefix` & add command for hmacli install

---

hasher-matcher-actioner/hmalib/lambdas/fetcher.py

Summary
---------
see title.
Test Plan
---------
`make upload_docker`
`make make dev_apply_with_newest_docker_image` # with access token that has PGs access 
open UI go to settings hit `sync`
trigger fetcher manually or wait for it to trigger
make sure those in the fetch_active = false state are skipped 
- s3 objects aren't updated
- logs that the skip is occurring are taking place

[hma] check if fetcher is active in lambda

---

python-threatexchange/threatexchange/cli/dataset/simple_serialization.py
python-threatexchange/threatexchange/descriptor.py
python-threatexchange/threatexchange/threat_updates.py

Summary
---------
This the result of trying to run `threatexchange fetch` on one of the new collections for a few hours, and just fixing whatever thing came up.
At least one of them is actually a bug with the Facebook API, but we can work around it on the client side for now.
I now regret many stupid choices about how I set up serialization, and fetching, with the root of all evil being not choosing SQLite as the base storage layer.
Should fix #844 
Test Plan
---------
```
$ threatexchange fetch  # Completes on a big test collaboration
```

[pytx] Fix various bugs with threat_updates and CLI fetch

---

hasher-matcher-actioner/.devcontainer/Dockerfile

Summary
---------
The key server sks-keyservers.net has been deprecated for some time which means the only valid keyserver in the Dockerfile is pgp.mit.edu. This change adds two other key servers that are verified working in replacement of the sks ones.
When I first tried to get the devcontainer working for HMA, I was getting errors that none of the keyservers were working which lead me down this rabbit hole. An hour later, the mit one was working 🤷 , but the sks links definitely do not work anymore.
From the sks-keyservers.net page:
> This service is deprecated. This means it is no longer maintained, and new HKPS certificates will not be issued. Service reliability should not be expected.
Test Plan
---------
Verified both new key servers work locally during the devcontainer setup:
```
#9 …
```

Remove the use of sks keyservers

---

hasher-matcher-actioner/hmalib/scripts/cli/storm.py
hasher-matcher-actioner/hmalib/scripts/common/utils.py
hasher-matcher-actioner/scripts/submit_s3_bucket

Summary
---------
This is an older change I meant to put up earlier. If you have AWS credentials this will allow hmacli to submit using an sns topic as well as the web interface for storm commands. This also gets us closer to consolidating scripts further
Test Plan
---------
Updated doc string with new order of args (in future PR I want to clarify and spilt up s3-object and s3-bucket)
```
$ hmacli storm -m "<filepath>" -c 100 -v upload
$ hmacli storm -m "<filepath>" -c 100 -v bytes
$ hmacli storm -m "<signed-url>" -c 100 -v url
$ hmacli storm -m "<bucket>:<key>" -c 100 -v s3
$ hmacli storm -m "<pdq-hash>" -c 100 -v hash
```
```
hmacli storm --media "<bucket>:<key>" -v --sns_topic arn:aws:sns:us-east-1:<acount-id>:<prefix>-submission2021102120070926530438200001 sns-s3
Started adding tasks …
```

[hma][cli] add sns support to storm cli command

---

hasher-matcher-actioner/hmalib/banks/bank_operations.py
hasher-matcher-actioner/hmalib/common/models/bank.py

Summary
---
To support the upcoming fetcher overhaul which requires signals without members, we need this capability.
Test
---
```
```

Support bank members without media attached

---

hasher-matcher-actioner/webapp/src/pages/SubmitContent.tsx

Summary
---------
Selecting to "submit another" does not clear the content form, but it does clear what is stored in the state. It appears to the user that the content field is filled out, but if they submit again without modifying the input, it will actually send an empty string. Since the state get's reset, we just need to set the value of the input to the current state.
This use case probably never happens in practice since it would mean a user is submitting the same content URL multiple times with different IDs, but it happened to me when testing something else :). It may also be worthwhile to add a check for an empty content URL.
This is what would be added to dynamo if you reached this bug:
Test Plan
---------
Ran the UI with changes locally and confirmed that after clicking "Submit …

Fix content input from not resetting when selecting to submit another

---

hasher-matcher-actioner/hmalib/lambdas/ddb_stream_counter.py

Summary
---------
Adds the parameterized count to the HMADataStore stream counter.
Test Plan
---------
Updated my lambda function to use these code changes and testing submitting a photo and video.
Test data added (images/videos were uploaded via the HMA UI, the match was added to dynamo manually):
Resulting counts:

Use parameterized counts for the HMADataStore stream counter

---

hasher-matcher-actioner/.gitignore
hasher-matcher-actioner/hmalib/scripts/common/client_lib.py

Summary
---------
`hmalib_extensions/` should be ignored by git, `__init__.py` and one other file are committed as an example but all other files added are expected to be third party additions/custom implementations. 
Test Plan
---------
```
cp settings.py.example
make dev_apply_with_newest_docker_image
make dev_test_instance
```

[hmalib][script] add hmalib_extensions/ to gitignore and small changes to client_lib.py 

---

python-threatexchange/threatexchange/cli/match.py

Summary
---------
If you don't have a `threatexchange_samples` folder and run something `threatexchange match text "example"`
The cli match command will try and fetch, however it still needs to use the tag_fetch version that was renamed but missed in #744. 
Test Plan
---------
Before:
```
#with `threatexchange_samples` folder deleted
python-threatexchange $ threatexchange match text "example"                                                                                                                                                                                                                                                                                                                                                   
...
AttributeError: module 'threatexchange.cli.fetch' has no …
```

[pytx] hot fix - fetch of sample data to use tag_fetch renamed in (#744)

---

python-threatexchange/benchmarks/benchmark_pdq_faiss_matchers.py

Summary
---------
PR merged awhile go [made `custom_ids` required](https://github.com/facebook/ThreatExchange/pull/811/files#diff-d150baf7a027ad595b5696c7b16f8e4fc7d99da4a83fe1ababeae118384b548bR133) 
This change has `benchmark_pdq_faiss_matchers.py` respect this change
Test Plan
---------
Before:
```
$ python3 benchmarks/benchmark_pdq_faiss_matchers.py --dataset-size 100000
....
File "benchmarks/benchmark_pdq_faiss_matchers.py", line 131, in <module>
flat_index.add(dataset, custom_ids=custom_ids)
File "/Users/barrett/dev/github/ThreatExchange/python-threatexchange/threatexchange/hashing/pdq_faiss_matcher.py", line 143, in add
i64_ids = list(map(uint64_to_int64, custom_ids))
TypeError: 'NoneType' object is not iterable
```
After:
```
$ python3 …
```

[pytx] quick fix of benchmark script - pdq index requires custom ids

---

hasher-matcher-actioner/Dockerfile

Summary
---------
Comment only change in Docker added because how to test local pytx changes for hma without a version bump/push is common enough that documenting how to do so seems worth it.
Test Plan
---------
comment only change

[pytx][minor] update dockerfile with steps for testing local pytx changes

---

python-threatexchange/threatexchange/hashing/pdq_faiss_matcher.py
python-threatexchange/threatexchange/signal_type/pdq_index.py
python-threatexchange/threatexchange/signal_type/tests/test_pdq_index.py

Summary
---------
To support variable threshold in HMA ideally each match returned can be paired with its distance.
Though since `python-threatexchange/threatexchange/hashing/pdq_faiss_matcher.py` has been around for over a year I added a new `search_with_distance` instead of changing the results given form `search` 
I also added a PDQFlatIndex to `python-threatexchange/threatexchange/signal_type/pdq_index.py` so that index type can be used in HMA as well.
Test Plan
---------
fixed a bug in pytest so it now checks the distance for matches for `PDQIndex`

[pytx] update faiss_matcher to have option to return distance & add PDQFlatIndex

---

.github/workflows/python-threatexchange-ci.yaml
python-threatexchange/mypy.ini
python-threatexchange/setup.py
python-threatexchange/threatexchange/api_representations.py
python-threatexchange/threatexchange/cli/command_base.py
python-threatexchange/threatexchange/cli/dataset/simple_serialization.py
python-threatexchange/threatexchange/cli/dataset_cmd.py
python-threatexchange/threatexchange/cli/fetch.py
python-threatexchange/threatexchange/cli/hash_cmd.py
python-threatexchange/threatexchange/cli/main.py
python-threatexchange/threatexchange/cli/match.py
python-threatexchange/threatexchange/cli/tag_fetch.py
python-threatexchange/threatexchange/collab_config.py
python-threatexchange/threatexchange/common.py
python-threatexchange/threatexchange/content_type/content_base.py
python-threatexchange/threatexchange/content_type/meta.py
python-threatexchange/threatexchange/dataset.py
python-threatexchange/threatexchange/descriptor.py
python-threatexchange/threatexchange/hashing/pdq_faiss_matcher.py
python-threatexchange/threatexchange/signal_type/pdq_index.py
python-threatexchange/threatexchange/signal_type/raw_text.py
python-threatexchange/threatexchange/signal_type/signal_base.py
python-threatexchange/threatexchange/signal_type/trend_query.py
python-threatexchange/threatexchange/threat_updates.py

Summary
---------
This is the remaining pieces from break up #873 and is mostly just around fixing types.
I would recommend reviewing commit by commit. 
- no logic changes
- minor fixes + typing
- type + some logic fixes / casting
- threat_update specific typing
- adds stuff to github actions
- typing fixes needed from files in #875 
Test Plan
---------
Repeat of #873 testing after rebase

[pytx] mypy supportand fixes

---

hasher-matcher-actioner/hmalib/lambdas/unified_indexer.py
hasher-matcher-actioner/terraform/fetcher/main.tf
hasher-matcher-actioner/terraform/indexer/main.tf
hasher-matcher-actioner/terraform/indexer/variables.tf
hasher-matcher-actioner/terraform/main.tf
hasher-matcher-actioner/terraform/variables.tf

Banks will not emit update events for every member added/removed. Instead indexer will run on a schedule and:
a) if rebuilding, get all datafiles for TE and all members for banks.
b) if updating, get updated datafiles for TE and updated members for banks.
Note, this PR only reads existing s3 datafiles on a schedule. The banks related things will happen as part of a later PR.
To ensure we don't develop what is unnecessary, we'll start off with the rebuilding arc, do some performance tests to see at what data size rebuilding is ineffective and then work on delta updates.
Test Plan
---
1. Deployed to my instance.
2. Deleted index/ prefix objects in the s3 bucket
3. Manually ran the indexer
4. Verified that the index was re-created

Run indexer on a schedule instead of on events

---

hasher-matcher-actioner/hmalib/lambdas/matcher.py
hasher-matcher-actioner/hmalib/matchers/matchers_base.py
hasher-matcher-actioner/setup.py

Summary
---------
I been testing 0.29 for ThreatExchange on HMA in my next PR and it works. Would rather keep main-hma on most recent version as soon as we are ~confident it won't break.
Also saw that a method incorrectly referred to a `content_hash` as a `signal_value` when creating `MatchRecord` wanted to address ASAP to avoid the confusion spreading. Also updated call site in matcher lambda to avoid this happening again there.
Test Plan
---------
`make upload_docker`
`make dev_apply_with_newest_docker_image`  
`make dev_test_instance`

[hma] pytx version bump and keyword arg name fix in matcher_base

---

README.md

Summary
---------
Add some more context about license of repository.
Test Plan
---------
`grep -ri license` to look for any other files that might have been missed. Found a bunch of reference to missing files in api-examples, but nothing that looked like CImg.h's issue.

Update README for #868

---

pdq/README.md

Instead point to the top-level license, pending a deletion of the duplicate license files.
Summary
---------
I could have done this as part of the commit that deleted them, but preview is useful. I can probably delete files from the github UI, but am lazy. 
Test Plan
---------
Viewed preview, clicked on link.

Update PDQ README for  #868

---

hasher-matcher-actioner/hmalib/common/models/pipeline.py
hasher-matcher-actioner/hmalib/common/models/tests/test_pipeline_models.py
hasher-matcher-actioner/hmalib/lambdas/api/matches.py
hasher-matcher-actioner/hmalib/matchers/matchers_base.py

Summary
---------
Now that the PDQIndex provides distance for matches why not record it in match record and surface them on the API?
Note: All video_md5 matches recorded at 0 (as expected)
Test Plan
---------
Deployed and took a hash from `sample_data/holidays-jpg1-pdq-hashes.csv` e.g. `431dfd4204ad7b54ec6203bdfd42033fbfa5ec42033dfcc4033bf631dccc031c`
Modified it slightly and ran (after setting auth token):
`hmacli storm  --media "431dfd4204ad7b54ec6203bdfd42033fbfa5ec42033dfcc4033bf631dccc0310" --verbose -c 1 hash`  
Checked results in postman (with auth token in header):
GET `https://{{api_id}}.execute-api.us-east-1.amazonaws.com/api/matches/match/?content_id=<id-of-match-ui>`
```JSON
{
"match_details": [
{
"content_id": "<id-of-match-ui>",
"content_hash": …
```

[hma] record match distance in match record and surface on API

---

hasher-matcher-actioner/hmalib/common/configs/fetcher.py
hasher-matcher-actioner/hmalib/matchers/matchers_base.py

Summary
---------
Base for a config that can add additional similarity distance filtering beyond the ceiling set in `python-threatexchange/threatexchange/signal_type/pdq_index.PDQIndex`
Test Plan
---------
Rebased with #883 to set and checked new logs
created and saved config in python
```python3
from hmalib.common.configs.fetcher import AdditionalMatchSettingsConfig
from hmalib.common import config as hmaconfig
import getpass
hmaconfig.HMAConfig.initialize(f"{getpass.getuser()}-HMAConfig")
config = AdditionalMatchSettingsConfig("inria-holidays-test", pdq_match_threshold=20)
hmaconfig.create_config(config)
print(AdditionalMatchSettingsConfig.get("inria-holidays-test"))
```
Simliar to #883 test plan + read logs:
"Match was found at 31.0 distance but exceeds custom threshold of 20 for pg, …

[hma] add AdditionalMatchSettingsConfig for pdq threshold to filter matches

---

hasher-matcher-actioner/hmalib/lambdas/api/datasets.py
hasher-matcher-actioner/hmalib/lambdas/api/matches.py

Summary
---------
Depends on #885 and #883 (and has their commits)
Take the distance recorded in #883 and also adds it to `/for-hash/`
Provides endpoints on the `/datasets/` path for 
- listing all     
- GET `/datasets/match-settings`
- listing one
- GET `/datasets/match-settings/<key>`
- creating/updating 
- POST `/datasets/match-settings` `{  "privacy_group_id": <key>, "pdq_match_threshold": <val>}`
- deleting
- DELETE `/datasets/match-settings/<key>`
Test Plan
---------
Tested all new dataset endpoints and new response format for `/matches/for-hash/`
`https://{{api_id}}.execute-api.us-east-1.amazonaws.com/api/matches/for-hash/?signal_type=pdq&signal_value=f8f8f0cee0f4a84f06370a22038f63f0b36e2ed596621e1d33e6b39c4e9c9b22`
```json
{
"matches": [
{
"match_distance": 0, …
```

[hma][api] AdditionalMatchSettingsConfig adjustable from API and match distance in /for-hash/ results

---

hasher-matcher-actioner/webapp/src/Api.tsx
hasher-matcher-actioner/webapp/src/App.tsx
hasher-matcher-actioner/webapp/src/components/Loader.tsx
hasher-matcher-actioner/webapp/src/messages/BankMessages.tsx
hasher-matcher-actioner/webapp/src/pages/bank-management/Members.tsx
hasher-matcher-actioner/webapp/src/pages/bank-management/ViewBankMember.tsx

Summary
---------
When adding new members, I found myself looking at the dynamodb items page to see if a hash had been generated yet. This page makes this process simpler.
Test Plan
---------
Add a new bank member, click on its link to go to its new page and use the 'refresh' button on the new page to see signals loading.
**Screenshot showing the new 'View Member' link on the all members page**
**Screenshot showing the new 'View Member' page. Notice the 'refresh' button**

Add a page showing bank members

---

hasher-matcher-actioner/hmalib/common/mappings.py
hasher-matcher-actioner/hmalib/indexers/s3_indexers.py
hasher-matcher-actioner/hmalib/lambdas/unified_indexer.py
hasher-matcher-actioner/hmalib/matchers/matchers_base.py
hasher-matcher-actioner/terraform/matcher/main.tf

Summary
---------
1) Updates indexer to build new PDQFlatIndex and store it in s3
2) Updates matcher_base to consider configured thresholds when picking matcher have a choice between  
- PDQIndex (31 max)
- PDQFlatIndex (52 max) 
- limits based on hardcoded value in python-threatexchange (possible to make dynamic as well) 
What is missing but plan to leave for next PR (if it is alright with reviewer):
- tf variable for enable disable FlatIndex usage
- UI support
Test Plan
---------
(Gave live demo of postman tests)
Tested e2e by submitting hashes of variable distance from given sample set hash and making sure matcher we found or not found accordingly when thresholds were configured for various distances. 
`hmacli storm  --media "ffffffffffffff4f06370a22038f63f0b36e2ed596621e1d33e6b39c4e9c9 …

[hma] add support for PDQ match threshold >31

---

hasher-matcher-actioner/hmalib/indexers/s3_indexers.py
hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/indexes.py
hasher-matcher-actioner/terraform/api/main.tf
hasher-matcher-actioner/terraform/api/variables.tf
hasher-matcher-actioner/terraform/indexer/outputs.tf
hasher-matcher-actioner/terraform/main.tf
hasher-matcher-actioner/webapp/src/Api.tsx
hasher-matcher-actioner/webapp/src/App.tsx
hasher-matcher-actioner/webapp/src/pages/Settings.tsx
hasher-matcher-actioner/webapp/src/pages/settings/ActionRuleSettingsTab.tsx
hasher-matcher-actioner/webapp/src/pages/settings/IndexSettingsTab.tsx
hasher-matcher-actioner/webapp/src/pages/settings/SettingsTabPane.tsx

Summary
---------
With banks, indexing runs on a pre-determined frequency. This may not be fast enough for our users when they are demoing something or need to test changes out.
This shows the last_modified times of the current set of indexes on the 'settings' portion of the HMA UI and allows a user to trigger an async rebuild of the index.
Test Plan
---------
mypy, black, py.test on local.
**Screenshot 1: the new UI pane with the rebuild button**
**Screenshot 2: logs of indexer when the rebuild button was clicked**

[hma] Add a settings pane for getting index last modified and rebuilding on demand

---

hasher-matcher-actioner/hmalib/common/messages/match.py
hasher-matcher-actioner/hmalib/common/models/bank.py
hasher-matcher-actioner/hmalib/common/models/models_base.py
hasher-matcher-actioner/hmalib/common/models/tests/test_bank_member_signals_to_process.py
hasher-matcher-actioner/hmalib/common/models/tests/test_signal_uniqueness.py
hasher-matcher-actioner/hmalib/common/s3_adapters.py
hasher-matcher-actioner/hmalib/indexers/metadata.py
hasher-matcher-actioner/hmalib/lambdas/actions/action_evaluator.py
hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/matches.py
hasher-matcher-actioner/hmalib/lambdas/unified_indexer.py
hasher-matcher-actioner/hmalib/matchers/matchers_base.py
hasher-matcher-actioner/terraform/datastore/main.tf
hasher-matcher-actioner/terraform/indexer/main.tf
hasher-matcher-actioner/terraform/indexer/variables.tf
hasher-matcher-actioner/terraform/main.tf

Summary
---------
Indexer is not the only consumer of bank member signals. So, the Pending index which was sparse worked out fine. However, there are two complications:
a) rebuilding is not going away, there needs to be a way to read all bank member signals. All of them even if there are writes between page reads. So sort_key needs to increment.  
b) other consumers (eg. publish bank to threatexchange) The pending index was meant for a single consumer only and for a one time use. We need something more durable.  
The new BankMemberSignalCursorIndex is durable. We don't remove items from it on successfully processing. Since the SK is monotonically increasing, there is no chance of missing out on keys.  Updates to existing signals (remove) will result in bringing the updated item to the end …

[HMA] Indexer sources hashes from banks as well as te data

---

hasher-matcher-actioner/hmalib/matchers/matchers_base.py

Summary
---------
This PR fixes two bugs
1) `filter_match_results` we unintentional edit match objects that belong to the index's state. Editing those objects directly had the effect of having subsequent calls behave incorrectly if made while the modified index was still in memory.
- fix: just make a copy....
2) if a PDQ match was found in multiple PGs one with a threshold above 31, the second one would use the wrong default (52 instead of 31). To address this I made the return value of `get_privacy_group_matcher_pdq_threshold` required and if a custom threshold is not set return the `PDQ_CONFIDENT_MATCH_THRESHOLD`  defined in the pytx signaltype class. 
2b) we checked distance threshold for all signal types, I updated `filter_match_results` to take in signal type and only check custom …

[hma] address matcher bugs

---

hasher-matcher-actioner/hmalib/lambdas/api/datasets.py
hasher-matcher-actioner/webapp/src/Api.tsx
hasher-matcher-actioner/webapp/src/App.tsx
hasher-matcher-actioner/webapp/src/components/settings/ThreatExchangePrivacyGroupCard.tsx
hasher-matcher-actioner/webapp/src/pages/settings/ActionRuleSettingsTab.tsx
hasher-matcher-actioner/webapp/src/pages/settings/SettingsTabPane.tsx
hasher-matcher-actioner/webapp/src/pages/settings/ThreatExchangeSettingsTab.tsx
hasher-matcher-actioner/webapp/src/styles/_app.scss

Summary
---------
This PR does a few things (as well as depending on #893). I'll leave it to the reviewer if you'd prefer reviewing by commit or not.
1) Stylist refactor of ThreatExchange Dataset setting page
- remove match count (for now) as it is broken
- have Hash count visible without needing to click a button
- have description in drop down instead of harder to read tooltip
- break up setting card in to set of subcards
2) Add closable Advanced Settings sub-card
- includes form with validation via formik for `pdq_match_threshold`
3) API support for dataset object fetches to surface and existing update posts to mutate the adv match settings fields
- limited to optional pdq_match_threshold at this time.
Test Plan
---------
Before: …

[hma][ui] add support for setting custom pdq match thresholds on dataset settings page

---

hasher-matcher-actioner/webapp/src/utils/TextFieldsUtils.tsx

Summary
---
This was something that had annoyed me for a while. It just looks unprofessional.
Testing
---
**Before**
**After**

Add padding to the popover for <CopyableTextField>

---

hasher-matcher-actioner/hmalib/lambdas/api/bank.py
hasher-matcher-actioner/webapp/src/Api.tsx
hasher-matcher-actioner/webapp/src/components/ReturnTo.tsx
hasher-matcher-actioner/webapp/src/messages/BankMessages.tsx
hasher-matcher-actioner/webapp/src/pages/ContentDetails.tsx
hasher-matcher-actioner/webapp/src/pages/bank-management/Members.tsx
hasher-matcher-actioner/webapp/src/pages/bank-management/ViewBankMember.tsx

Summary
---------
We have supported bank member signals that do not have media attached, (eg added via a fetcher), in ddb for a while. This PR adds:
a) an API to create such member signals
b) Ensure that the all-bank-members and single-bank-member pages both render correctly and show some information.
Test Plan
---------
black, mypy and py.test on local.
Added a few detached video members using postman.
**Screenshot 1: Single Bank Member page for a detached member signal**
**Screenshot 2: All Bank Members page with some detached member signals**

Detached bank UI

---

hasher-matcher-actioner/webapp/src/App.tsx
hasher-matcher-actioner/webapp/src/AppWithNotifications.tsx
hasher-matcher-actioner/webapp/src/components/ContentMatchTable.tsx
hasher-matcher-actioner/webapp/src/pages/Settings.tsx
hasher-matcher-actioner/webapp/src/pages/settings/ActionPerformerSettingsTab.tsx
hasher-matcher-actioner/webapp/src/pages/settings/ActionRuleSettingsTab.tsx
hasher-matcher-actioner/webapp/src/pages/settings/ThreatExchangeSettingsTab.tsx
hasher-matcher-actioner/webapp/src/styles/_app.scss

**Screenshot: Before**
**Screenshot: After**
While adding a new error toast, I realized: 
-  our toasts were not typed. You only had one type of toast. No failure, success etc. 
- also, all pages declared their own containers which made styling impossible and violated DRY  
This changeset uses React's [`useContext`](https://reactjs.org/docs/hooks-reference.html#usecontext) to provide interested components an _option_ to simply fire-and-forget notifications. The styling is centrally managed and so is the markup.  This allows you to stack notifications, and centrally control them. 
Also, you need not pass props around. Because this is context and not props, any interested component can gain access without requiring the tree to be stirred..
Test Plan 
--- 
tried some actions which trigger …

Toast UI infra

---

hasher-matcher-actioner/hmalib/aws_secrets.py
hasher-matcher-actioner/hmalib/common/threatexchange_config.py
hasher-matcher-actioner/hmalib/lambdas/api/datasets.py
hasher-matcher-actioner/hmalib/lambdas/fetcher.py
hasher-matcher-actioner/hmalib/writebacker/writebacker_base.py
hasher-matcher-actioner/terraform/api/main.tf
hasher-matcher-actioner/terraform/variables.tf
hasher-matcher-actioner/webapp/src/Api.tsx
hasher-matcher-actioner/webapp/src/components/HolidaysDatasetInformationBlock.tsx
hasher-matcher-actioner/webapp/src/pages/settings/ThreatExchangeSettingsTab.tsx
hasher-matcher-actioner/webapp/src/pages/settings/ThreatExchangeTokenEditor.tsx

Summary
---------
- includes webapp API method too  
- includes empty state for when privacy groups have not been synced. - removes card border around the test dataset because it looked weird as we added more settings - Uses <SettingsTabPane> at par with most other settings pages  
Test Plan
---------
* Cleared all ThreatExchangeConfig manually to see empty state.
* Used the token editor to supply a malformed token
* Used the token to supply a well-formed but invalid token
* Upon submitting this well-formed but invalid token
* Now, submit a valid token (not showing the token for security)
* Used the sync button to get privacy groups back

[HMA] Make threatexchange token optional and allow updates from the UI

---

hasher-matcher-actioner/hmalib/banks/bank_operations.py
hasher-matcher-actioner/hmalib/common/models/bank.py
hasher-matcher-actioner/hmalib/common/models/tests/test_bank_member_removes.py
hasher-matcher-actioner/hmalib/lambdas/api/bank.py
hasher-matcher-actioner/webapp/src/Api.tsx
hasher-matcher-actioner/webapp/src/messages/BankMessages.tsx
hasher-matcher-actioner/webapp/src/pages/bank-management/ViewBankMember.tsx

Summary
---------
As part of the 'banks-be-done' plan, we need to be able to remove banks members from the banks ui.
This PR allows that to be done. You can review commit by commit or at once. The key changes are:
* support marking is_removed = True for members in the API. This also removes the signals from the GSI used to build HMA indexes.
* in get_all_bank_members(), filter out is_removed members
* support removing bank members in the UI
Test Plan
---------
* py.test, black and mypy 
https://user-images.githubusercontent.com/217056/146830811-6a209dc7-43fd-46c5-9bae-4e305c02513c.mov

[hma] Remove bank members from the UI

---

hasher-matcher-actioner/.devcontainer/.gitignore
hasher-matcher-actioner/.devcontainer/devcontainer.json.example

Summary
---------
Discover that all the environment variables in example given is for mac. Spend a few hours trying to figure out what is going wrong. Conclude that there's no default that works for both. Force people to edit their own.
Will require updating CONTRIBUTING.MD afterwards.
Test Plan
---------
I was able to boot it on windows, but many errors related to CLRF. Going to attempt to refresh repository in lf mode and try again.

[devcontainer] Try and make devcontainer work windows

---

python-threatexchange/threatexchange/cli/cli_config.py

Summary
---------
This will replace what is currently represented by:
1. txtoken
2. collab config files
And gives us the option to do multi-config fetching and so on.
A separate PR will contain the proposed interface for fetching.
Test Plan
---------
Uhhh... there were no squiggles in VSCode?

[py-tx] Interface for collab configuration

---

python-threatexchange/threatexchange/fetcher/__init__.py
python-threatexchange/threatexchange/fetcher/fetch_api.py
python-threatexchange/threatexchange/fetcher/fetch_state_base.py

Summary
---------
Third time's the charm? This is an attempt to both generalize the fetch interface, and to delete mistakes of the past with the threat_updates API. 
It's basically the threat_updates API again, except with less weird intermediate translations via function as arguments.
A simple interface that represents fetch APIs, which should cover all 5 fetch approaches I am tracking:
1. ThreatExchange tagged_objects
2. ThreatExchange threat_updates
3. StopNCII.org 
4. NCMEC Industry Hash DB
5. A hardcoded set of signals
It also contains a simple interface for storage that I think should work for both HMA and py-te, in line with goals of aligning them.
1. py-te CLI handles multiple APIs/collabs
2. py-te state moves to .threatexchange (since its now a lot more complicated)
3. py-te uses …

[py-tx] Fetcher API interface

---

hasher-matcher-actioner/.devcontainer/Dockerfile
hasher-matcher-actioner/.devcontainer/devcontainer.json.example

v15 is no longer supported and it is advised to not use odd number releases in production.
Additionally:
- remove sks keyservers when installing yarn
- fix missing comma in devcontainer example
- rebuild container without cache (installs node, installs dependencies)
- webapp build (npm start) browser opens

Upgrade Node to v16, v15 is no longer supported

---

hasher-matcher-actioner/hmalib/common/models/bank.py
hasher-matcher-actioner/hmalib/matchers/matchers_base.py

Summary
---------
When writing out the [WIP wiki page](https://github.com/facebook/ThreatExchange/wiki/Creating-and-Managing-Banks) for banks, I realized that configuring actions to be taken when match.bank == foo was not possible. This was because of a mistake I made in one of my earlier commits.
This PR fixes that. Moving forward, the match message properties (as in action rules) will be like:
```
Label(key='BankIDClassification', value='<bank_id>'), 
Label(key='BankSourceClassification', value='bnk'), 
Label(key='BankedContentIDClassification', value='<bank_member_id>'), 
Label(key='Classification', value='<bank or bank_member tags>'), 
...
Label(key='Classification', value='<more bank or bank_member tags>'), 
```
Bonus: Also fixes a bug which used the wrong literal for sets (`{}` …

Bank action evaluation fixups

---

hasher-matcher-actioner/webapp/src/components/PillBox.tsx
hasher-matcher-actioner/webapp/src/forms/BankMemberForm.tsx
hasher-matcher-actioner/webapp/src/pages/bank-management/ViewBankMember.tsx

Summary
---------
Editing bank member tags can potentially lead to partners overusing them. We want banks to be the unit of classification rules. Until we discuss this more, disallowing edits to bank member tags when creating and editing them.
Test Plan
---------

BankMember tags are not editable

---

hasher-matcher-actioner/hmalib/common/models/bank.py
hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/matches.py
hasher-matcher-actioner/webapp/src/Api.tsx
hasher-matcher-actioner/webapp/src/components/ContentMatchTable.tsx
hasher-matcher-actioner/webapp/src/pages/ContentDetails.tsx
hasher-matcher-actioner/webapp/src/pages/layouts/FullWidthLeftAlignedLayout.tsx

Summary
---------
The content details page definitely had/has some cobwebs on it. This PR does a little clean up and updates the Matches table to show Bank and Dataset membership. 
This resulted in changing one of the fields returned from the `/matches/match/` endpoint
-  `te_signal_details` (instead of the ambiguous `metadata`)  
- and adding the new `banked_signal_details` 
- which unfortunately at the moment is forced to be backed by an inefficient ddb scan (added warning comment)
Test Plan
---------
Befores:
Afters:
Now with Links!
https://user-images.githubusercontent.com/7664526/152242138-49fd27db-f2c2-41d9-bde6-63394a746771.mov

[hma][api][ui] update match details table to include signal bank details if present

---

hasher-matcher-actioner/webapp/src/App.tsx
hasher-matcher-actioner/webapp/src/AppWithConfirmations.tsx
hasher-matcher-actioner/webapp/src/Sidebar.tsx
hasher-matcher-actioner/webapp/src/components/EmptyState.tsx
hasher-matcher-actioner/webapp/src/components/settings/ActionPerformer/ActionPerformerRows.tsx
hasher-matcher-actioner/webapp/src/pages/bank-management/Members.tsx
hasher-matcher-actioner/webapp/src/pages/bank-management/ViewAllBanks.tsx
hasher-matcher-actioner/webapp/src/pages/bank-management/ViewBankMember.tsx
hasher-matcher-actioner/webapp/src/pages/settings/ThreatExchangeSettingsTab.tsx

Summary
---------
I found myself using empty states again in ActionRuleSettings and a TODO in ViewAllBanks asking me to consolidate them.  Also, with the new <EmptyState> ThreatExchangeSettingsTab would have two CTA's so added a conditional that hides 'Sync' when empty state is shown.  
s/d58d5846ab21145d1d24d6b882ec3d58613cbf62) Consolidate confirmations into a single component
Confirming some action on the UI is  a pretty common workflow. I have noticed many Modals scattered through the codebase all trying the same thing.  This, much like toasts introduced in #897 adds common infrastructure to do confirmations.  It also ports over almost all instances of confirmations. Except ActionRules because that is turning out to be harder to extract because of other changes I am making.  
Test …

Infra for confirmations; dedicated empty state component

---

hasher-matcher-actioner/.devcontainer/Dockerfile

Summary
---------
Fixes a bug where if an ARM architecture machine attempts to use the base image in the dev Dockerfile, it will use the ARM version and fail. amd64 is now specified to address this. 
This shouldn't change anything for other users of the dev container but they will still need to rebuild. 
Test Plan
---------
Built devcontainer with change on both an M1 Pro Mac and an Intel Core i9 machine without errors.

[devcontainer] update Dockerfile base image to specify AMD64 

---

pdq/cpp/Makefile

Summary
---------
Some of the ignore warning flags added a long time ago are not longer supported by all version of clang/gcc. Adding `-Wno-unknown-warning-option` should allow those version to still successfully build the pdq cpp executables.
Test Plan
---------
ran `make` and confirmed successful compilation both on macOS and linux machines:
- Apple clang version 13.0.0 (clang-1300.0.29.30) arm64-apple-darwin21.3.0
- g++ (GCC) 8.5.0 20210514 (Red Hat 8.5.0-3)

[pdq][cpp] add -Wno-unknown-warning-option to Makefile flags avoid error for unrecognized flags

---

hasher-matcher-actioner/Makefile
hasher-matcher-actioner/mypy.ini
hasher-matcher-actioner/requirements-dev.txt
hasher-matcher-actioner/setup.py

Summary
---------
`mypy=0.812` has a dependency that was breaking for the install commands for python3.8+ macOS on arm64. This should hopefully address that. I also updated the make install for hmalib to use `-e` which fixed an issue where my dev venv was not find `hmalib` when I tried running `hmacli` commands 
This should change anything for devcontainer users but I think it is important that install works outside of this as well.
(aside: My personal use case is if I am jumping between hmalib and python-theatexchange (or a third project) being able to use the hmacli to run quick checks or tests outside of the devcontainer  is helpful)
Test Plan
---------
Confirmed that `make dev_install_hmacli` run in both native macOS and linux devcontainer without error.

[hma][hmalib] bump mypy version and update hmacli install command

---

hasher-matcher-actioner/terraform/.terraform.lock.hcl
hasher-matcher-actioner/terraform/durable-fs/main.tf
hasher-matcher-actioner/terraform/durable-fs/outputs.tf
hasher-matcher-actioner/terraform/durable-fs/variables.tf
hasher-matcher-actioner/terraform/hasher/main.tf
hasher-matcher-actioner/terraform/hasher/variables.tf
hasher-matcher-actioner/terraform/main.tf

Summary
---
This file system will be used to write content hashes by the hashing lambda so that we can build indexes to use for retroaction.
Test Plan
---
```
$ terraform init
$ terraform apply
```
Added the following snippet to the hashing lambda and deployed.
```python
with open(f"/mnt/durable-storage/{context.aws_request_id}.file", "w") as f:
f.write("Hello, World!")
from os import listdir
logger.info(listdir("/mnt/durable-storage/"))
```
Hit test on the AWS console a few times, deployed a new version of the lambda and then checked the logs..
Saw the following
```
[INFO]	2022-02-24T03:21:05.008Z	9e057c0d-2027-468a-b797-f261d3964178	['944d7e76-0fb5-4a7b-9104-de86fd90dfc0.file', 'a36b2c1b-1ef4-47d0-aa5c-7f69498c12fd.file', '57e95dc9-efaa-4707-abac-ab1017c7c7ed.file', …
```

Add an EFS durable file system for hashing lambda

---

hasher-matcher-actioner/docs/docusaurus.config.js

Summary
---------
A [recently added workflow](https://github.com/facebook/ThreatExchange/runs/5514990131?check_suite_focus=true) failed because the hrefs were wrongly setup.
Test Plan
---------
```
dipanjanm@<devcontainer>:/workspaces/ThreatExchange/hasher-matcher-actioner/docs$ npm run build 
> docs@0.0.0 build
> docusaurus build
[INFO] [en] Creating an optimized production build...
..... stuff
[SUCCESS] Generated static files in build.
[INFO] Use `npm run serve` command to test your build locally.
```
This [SUCCESS] did not happen earlier. We got the same error as in the logs of the workflow.

hot-fix: docusaurus hrefs

---

hasher-matcher-actioner/docs/docusaurus.config.js

Test Plan
---------
this change, did you add test, run something locally...-->

hotfix: use appropriate baseUrl. github repo names are case-sensitive

---

hasher-matcher-actioner/terraform/hasher/main.tf

Summary
---------
Adding a VPC to the hasher lambda seem to prevent it from adding to an SQS queue (for matching) or writing to ddb (for HashRecord)
Because VPC is only needed for efs which is not part of the HMA pipeline yet. I think the best hotfix is just to comment out these setting to unblock the hashing lambda and follow up with the needed changes / network setting to support the filesystem that won't break things. 
Test Plan
---------
```
...
make dev_apply_with_newest_docker_image 
...
make dev_test_instance
...
```

[hma][hotfix] comment out vpc setting for hasher lambda 

---

hasher-matcher-actioner/hmalib/lambdas/api/matches.py
hasher-matcher-actioner/hmalib/lambdas/hashing.py
hasher-matcher-actioner/hmalib/matchers/matchers_base.py
hasher-matcher-actioner/scripts/benchmark_for_match_api.py
hasher-matcher-actioner/terraform/.terraform.lock.hcl

Summary
---------
Similar the GET `matches/for-hash/` endpoint this PR adds a:
POST `matches/for-media` endpoint.
Aside: also adds some typing fixes that shouldn't change behavior.
Note: for this PR reviewing commit by commit is the same as file by file (though the commit message might still add some limited context).
The endpoint expects a json request body:
```
{
"content_url": "<pre-signed url of media's bytes>",
"content_type": "[photo|video]"
}
```
and responds in the form:
```
{
"signal_to_matches": {
"<signal_type>": {
"<signal_value/hash>": [
<match with details if any are found>
]
}
}
}
``` 
Example (bytes behind url match a banked hash/image):
POST https://{{api_id}}.execute-api.us-east-1.amazonaws.com/api/matches/for-media/
```
{
"content_url": …
```

[hma][api] add prototype hash + match synchronous API 

---

hasher-matcher-actioner/hmalib/common/models/pipeline.py

Summary
---------
I added a HashRecord class that contains data for content_hash and content_id to the pipeline.py file.
Test Plan
---------
```
hasher-matcher-actioner $ python -m py.test hmalib/common/models/pipeline.py
hasher-matcher-actioner $ python -m mypy hmalib/common/models/pipeline.py
hasher-matcher-actioner $ python -m black hmalib/common/models/pipeline.py
```

added HashRecord class to pipeline.py on separate branch

---

python-threatexchange/setup.py
python-threatexchange/threatexchange/cli/cli_config.py
python-threatexchange/threatexchange/cli/dataset_cmd.py
python-threatexchange/threatexchange/cli/fetch_cmd.py
python-threatexchange/threatexchange/cli/hash_cmd.py
python-threatexchange/threatexchange/cli/label_cmd.py
python-threatexchange/threatexchange/cli/main.py
python-threatexchange/threatexchange/cli/match_cmd.py
python-threatexchange/threatexchange/cli/tests/cli_smoke_test.py
python-threatexchange/threatexchange/cli/tests/e2e_test_helper.py
python-threatexchange/threatexchange/cli/tests/hash_cmd_test.py
python-threatexchange/threatexchange/cli/tests/sample_data_e2e_test.py
python-threatexchange/threatexchange/signal_type/signal_base.py
python-threatexchange/threatexchange/signal_type/url.py

Summary
---------
This diff adds a backstop for testing, which is simple e2e tests that pretend to be executing the CLI. Each test:
1. Is treated like a fresh install of threatexchange. You can change this by just overriding the setUp() method and move it to a setUpBeforeClass type deal.
2. Has helpers for triggering CLI runs, or looking for specific output.
Test Plan
---------
New unittests!

Cli e2e testing

---

pdq/cpp/hashing/pdqhashing.cpp
tmk/.gitignore
tmk/README.md
tmk/cpp/Makefile
tmk/cpp/algo/tmkfv.cpp
tmk/cpp/bin/tmk-hash-video.cpp
tmk/cpp/hashing/filehasher.cpp

Summary
---------
Had similar issues as described in https://github.com/facebook/ThreatExchange/issues/189 so made several edits which allow compilation to succeed on Windows.
I also added some flags to reduce `ffmpeg`'s noisy output (if verbose was not enabled).
There are still changes needed to the Makefile, but I haven't attempted merging those yet. In brief:
Instead of:
`CC=g++ -O2 -std=c++14 -I../..`
Use:
`CC_WIN=g++ -O2 -std=gnu++14 -I../..`
for:
- ./hashing/filehasher.o
- tmkdump
- tmk-clusterize
- tmk-query
- tmk-two-level-score
You will also need to install `make`, e.g., via [choco](https://community.chocolatey.org/packages/make) and [MinGW](https://osdn.net/projects/mingw/). Note that, MinGW needs to be added to the system path in order to compile and use the executables.
The …

WIP: Compilation changes for Windows

---

hasher-matcher-actioner/hmalib/banks/bank_operations.py
hasher-matcher-actioner/requirements-dev.txt
hasher-matcher-actioner/setup.py

Summary
---
Add a bank_operation that supports batch signal additions to a bank. With threatexchange → banks being worked on, I have a hunch this will be useful. No optimizations yet, but get the API up.
- An NGO partner had asked me for this feature
- I felt the need to use this when creatng a bank with a large number of objects.
Because CI started failing, I added a second [commit](https://github.com/facebook/ThreatExchange/pull/961/commits/1884fec1c625249343daf848a917720dc2698a81) upgrading black and click to this PR. If reviewer wants, can be moved to its own PR. 
Test Plan
---
Used this to successfully create a bank with million + records. Usual python suspects (mypy, black, py.test)

[HMA] Add dumb API for batch detached signal additions

---

hasher-matcher-actioner/hmalib/banks/bank_operations.py
hasher-matcher-actioner/hmalib/lambdas/unified_indexer.py
hasher-matcher-actioner/hmalib/metrics/__init__.py

Summary
---
The indexing process has multiple stages. One of the newer ones is getting member signals from banks.
So far, it was not getting measured. Now that we are building 1M+ banks, this becomes a significant part of the indexing duration.
Add a metric name and measure it during index building.
Test Plan
---
Deployed to my personal hma instance.
Attached screenshot of cloudwatch metrics. Notice `get_bank_data` in the graph.
During the course of 1 day, as I added more members to the bank, the index building time increased specifically because the `get_bank_data` time increased.

During index building, measure time to fetch data from banks.

---

tmk/README.md
tmk/cpp/bin/tmk-clusterize.cpp
tmk/cpp/bin/tmk-query-with-faiss.cpp
tmk/cpp/bin/tmk-query.cpp
tmk/cpp/bin/tmk-two-level-score.cpp

Summary
---------
This is an improvement to https://github.com/facebook/ThreatExchange/pull/959.
- Minor bug fix: 0bed18fd86869b349689bb30aa6b1c375ff95822
- Eliminates the OOM faults from the existing version, and is generally a lot simpler. It seems to be very slightly faster as well.
- Switch to unordered maps. Since we are running this in parallel, we can achieve faster lookups, and there is no advantage to use ordered maps since we are sorting the final output anyway.
- Rather than iterating through the entire loop twice, and checking whether or not it's a degenerate pair within the inner loop, this optimization allows for just a single run through to produce all of the unique pairs.
```cpp
for (unsigned int i = 0; i < filenames.size() - 1; i++) {
for (unsigned int j = i + 1; j < …
```

Parallel processing - improved

---

python-threatexchange/threatexchange/cli/cli_state.py
python-threatexchange/threatexchange/cli/dataset_cmd.py
python-threatexchange/threatexchange/cli/fetch_cmd.py
python-threatexchange/threatexchange/extensions/text_tlsh/tests/test_tlsh_hash_and_match.py
python-threatexchange/threatexchange/fetcher/apis/fb_threatexchange_api.py
python-threatexchange/threatexchange/fetcher/apis/fb_threatexchange_signal.py
python-threatexchange/threatexchange/fetcher/simple/state.py
python-threatexchange/threatexchange/signal_type/md5.py
python-threatexchange/threatexchange/signal_type/pdq.py
python-threatexchange/threatexchange/signal_type/pdq_ocr.py
python-threatexchange/threatexchange/signal_type/raw_text.py
python-threatexchange/threatexchange/signal_type/signal_base.py
python-threatexchange/threatexchange/signal_type/tests/test_hash_from_x.py
python-threatexchange/threatexchange/signal_type/trend_query.py
python-threatexchange/threatexchange/signal_type/url.py
python-threatexchange/threatexchange/signal_type/url_md5.py

Summary
---------
This is the result of a few hours of work trying to fix up fb_threatexchange.
Features:
1. HasFbThreatExchangeIndicatorType allows signal types to record their fb type
2. (Maybe dangerous/should be removed) Will fall back to trying the signal name otherwise
Misc fixes:
1. Fix cli storage not using all correct translations by switching to the helper
4. Fix errors during serialization leaving partial files by writing to a tmpfile first
5. Fix display from fetch always showing "since the beginning of time"
Test Plan
---------
```
$ threatexchange config api fb_threat_exchange -I 303636684709969
[fb_threat_exchange] HMA Test Collaboration (Superset) - Up to date, at 2021-12-19T04:09:52
Rebuilding match indices...
Building index for raw_text with 1 …
```

[pytx] Incremental progress fixing up fb_threat_exchange

---

python-threatexchange/threatexchange/cli/cli_config.py
python-threatexchange/threatexchange/cli/cli_state.py
python-threatexchange/threatexchange/cli/dataset_cmd.py
python-threatexchange/threatexchange/cli/match_cmd.py
python-threatexchange/threatexchange/extensions/text_tlsh/tests/test_tlsh_hash_and_match.py
python-threatexchange/threatexchange/signal_type/url.py

Summary
---------
Lambdas can capture variables in unexpected ways. In this case, the "index" variable was being overridden each loop, being left with the last value. A trick you can use to force it to capture the right value is to set it as a default value to an argument, which is evaluated at declaration time (whereas captured variables are evaluated at runtime).
Also minor renames, of the index accessor, which I plan to follow up with others as well:
```
settings.index  # Indices
settings.collabs  # collab configs
settings.fetchers  # apis
...
```
Test Plan
---------
I had a collaboration that had URLs, but not URL MD5s, and the md5s were evaluated second, which would be None. This generated a None attribute error without the fix.

[pytx] fix subtle bug with match

---

README.md
python-threatexchange/threatexchange/cli/hash_cmd.py
python-threatexchange/threatexchange/cli/tests/e2e_test_helper.py
python-threatexchange/threatexchange/cli/tests/hash_cmd_test.py
python-threatexchange/threatexchange/signal_type/signal_base.py

Summary
---------
Opening this PR in favor of closing https://github.com/facebook/ThreatExchange/pull/984 for cleanliness.
What this PR does
1. Adds an error handling for file not found exception for `hash_cmd.py`
2. Makes TextHasher extend FileHasher. 
Since `threatexchange hash text file.txt` or `threatexchange hash url file.txt` would not return hashes.
3. ~~Raise a ValueError for text_tlsh when the input text is too short.~~
How to add `tlsh` extension for Threatexchange
```
$ threatexchange config extensions add threatexchange.extensions.text_tlsh
```
Test Plan
---------
`make test`

Fix validation on threatexchange hash inputs

---

hasher-matcher-actioner/hmalib/common/tests/test_timebucket.py
hasher-matcher-actioner/hmalib/common/timebucketizer.py
hasher-matcher-actioner/hmalib/indexers/lcc.py
hasher-matcher-actioner/hmalib/indexers/tests/test_lcc_indexer.py

Summary
---------
I made and connected a Timebucketizer instance to my LCCIndexer class and its build_index_from_last_24h method. I added Hash Records to the TB instance and built those records into an index. I also queried a hash record from the test index to check that the index is populated.
Test Plan
---------
To run and test the LCC indexer, run the command below.
`python -m py.test hmalib/indexers/tests/test_lcc_indexer.py::TestLCCIndexer::test`

Connecting Timebucketizer instance to LCC Indexer class

---

python-threatexchange/threatexchange/cli/hash_cmd.py
python-threatexchange/threatexchange/cli/tests/hash_cmd_test.py

Summary
---------
I wasn't looking close enough and missed this in the original PR, apologies!
Return codes can inform you if a program executed as expected. Return code 0 = success, 2 = user error (invalid arguments, etc)
```
$ threatexchange hash noexist
$ echo $?  # Display return code
0
$ threatexchange hash noexist
$ echo $?  # Display return code
2
```
Test Plan
---------
Updated test

[pytx] threatexchange hash to give error on invalid file

---

hasher-matcher-actioner/CONTRIBUTING.md

devcontainer.json.example was removed a while ago and looks like this doc update was missed

Update CONTRIBUTING.md for devcontainer.json

---

hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/lcc.py
hasher-matcher-actioner/terraform/api/main.tf

Summary
---------
I added a get_index method that gets the latest index to the LCC API. I also called it inside the lcc_hasher method so that the index can query a hash_value from a bottle request.

Add get_index() and  connect lcc_hasher() to LCCIndexer

---

hasher-matcher-actioner/hmalib/hashing/unified_hasher.py
hasher-matcher-actioner/hmalib/lambdas/api/matches.py
hasher-matcher-actioner/hmalib/lambdas/hashing.py
hasher-matcher-actioner/terraform/hasher/main.tf

Summary
---------
Use signal-type-mapping (rely on dynamic config drivent mappings).
Open hma-config access to hashing lambda.
Test Plan
---------
Ran locally. Running remote is harder because submissions don't work with refactor yet.
```sh
$ python -m hmalib.scripts.cli.main run-lambda --lambda-name hasher
Loading faiss with AVX2 support.
Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
Loading faiss.
Successfully loaded faiss.
Performance measurement requested. Supplying appmetrics instrumentation.
Unable to load THREAT_EXCHANGE_API_TOKEN_SECRET_NAME from env
/home/dipanjanm/.local/lib/python3.8/site-packages/pdqhash/__init__.py:3: UserWarning: Hash vector order changed between version 0.1.8 and 0.2.0. See …
```

Make hasher work with pytx refactored

---

python-threatexchange/threatexchange/cli/config_cmd.py
python-threatexchange/threatexchange/cli/exceptions.py
python-threatexchange/threatexchange/cli/main.py

Summary
---------
Test Plan
---------
```
$ pip install <extension>
$ threatexchange config extension add <extension>
$ threatexchange dataset
$ pip uninstall <extension>
$ threatexchange dataset
Some extensions are no longer loadable! Fix them with the `config extension` command:
<extension>
$ threatexchange config extension remove <extension>
```

[pytx] CLI can fix extension failures itself

---

python-threatexchange/threatexchange/cli/cli_state.py
python-threatexchange/threatexchange/cli/fetch_cmd.py
python-threatexchange/threatexchange/cli/main.py
python-threatexchange/threatexchange/common.py
python-threatexchange/threatexchange/fetcher/apis/file_api.py
python-threatexchange/threatexchange/fetcher/apis/static_sample.py
python-threatexchange/threatexchange/fetcher/apis/stop_ncii_api.py
python-threatexchange/threatexchange/fetcher/apis/tests/test_stopncii.py
python-threatexchange/threatexchange/fetcher/fetch_api.py
python-threatexchange/threatexchange/fetcher/fetch_state.py
python-threatexchange/threatexchange/fetcher/simple/state.py
python-threatexchange/threatexchange/fetcher/simple/tests/test_state.py

Summary
---------
The flow of information through the system is:
API.fetch() => Delta => Store => Index => Metadata
NCMEC's API is like the tag-based ThreatExchange API, and it's not stored as hash => record, it's actually stored record => [hash, hash, hash] which is incompatible with many assumptions made along the way.
After lots of mulling, I think the solution is to:
1. Separate considerations about storing the record that the fetch() API produces
2. Converting the format from the fetch() update store to the signal => metadata
As a part of that, I need to mess with a lot of the interfaces above. There are more changes that I want to make, and I tried to checkpoint with this diff.
The final version I want to end up with is:
1. Storing what the update format is from fetch should move …

[py-tx][backwards incompatible] Split Update Format and Index Format

---

pdq/cpp/Makefile
pdq/cpp/README.md
tmk/cpp/Makefile
tmk/cpp/README.md

Summary
---------
M1's Apple clang  i.e. the builtin g++ doesn't work out of the box for the pdq or tmk c++ implementations. However gcc (g++-11 if installed via homebrew) still works fine.
- the Apple clang issues for tmk just seem to be linking errors however for pdq the resulting executables actually have incorrect behavior.  `Hash256::hammingNorm` and `Hash256::hammingDistance` do not return the correct results when the compiler is given a -02 flag or higher
I think it likely that Apple clang has a bug that will eventually be fixed but for how gcc should be used. 
Test Plan
---------
1. install gcc 
2. update CXX in Makefile(s) to point to gcc's g++ instead of builtin Apple clang
3. Run `make` in `tmk/cpp` and `pdq/cpp` and make sure both regression tests pass.

[hashing][minor][fix] update cpp Makefiles and README on details of running on M1

---

python-threatexchange/threatexchange/cli/config_cmd.py
python-threatexchange/threatexchange/cli/fetch_cmd.py
python-threatexchange/threatexchange/fetcher/apis/fb_threatexchange_api.py
python-threatexchange/threatexchange/fetcher/apis/file_api.py
python-threatexchange/threatexchange/fetcher/apis/static_sample.py
python-threatexchange/threatexchange/fetcher/apis/stop_ncii_api.py
python-threatexchange/threatexchange/fetcher/apis/tests/test_stopncii.py
python-threatexchange/threatexchange/fetcher/fetch_api.py
python-threatexchange/threatexchange/fetcher/fetch_state.py
python-threatexchange/threatexchange/fetcher/simple/state.py
python-threatexchange/threatexchange/fetcher/simple/tests/test_state.py

Summary
---------
This PR:
1. Deletes fetch_once() to standardize on the nicer fetch_iter
2. Removes delta.has_more, since it's now implied by the interface
3. Adds ABC to a few fetch classes to make it easier to verify they are implemented as expected.
Test Plan
---------
unittests, but also ran fetch for sample, (clear, threatexchange match -- bball now?)

[pytx] Delete fetch_once(), long live fetch_iter()

---

.github/workflows/tmk-ci-cpp.yml
tmk/cpp/Makefile

Summary
---------
pdq/cpp has a gh action but tmk/cpp was missing one. This adds it.
There is a side benefit that it now you mistakenly commit your local FFMPEG path the CI will fail (something that I missed and committed a few PRs ago by mistake which is also fixed here)
Test Plan
---------
Created this PR made sure both the new and existing gh action pass.

Add CI action for tmk/cpp make regtest

---

python-threatexchange/threatexchange/cli/cli_config.py
python-threatexchange/threatexchange/cli/config_cmd.py
python-threatexchange/threatexchange/cli/dataclass_json.py
python-threatexchange/threatexchange/cli/main.py
python-threatexchange/threatexchange/fetcher/apis/ncmec_api.py
python-threatexchange/threatexchange/fetcher/apis/tests/test_ncmec.py
python-threatexchange/threatexchange/fetcher/fetch_state.py
python-threatexchange/threatexchange/ncmec/hash_api.py
python-threatexchange/threatexchange/ncmec/tests/__init__.py
python-threatexchange/threatexchange/ncmec/tests/test_hash_api.py
python-threatexchange/threatexchange/stopncii/api.py

Summary
---------
This one got away from me a little bit:
1. SignalExchangeAPI implementation for NCMEC
2. CLI configuration updates to store credentials
3. Random bug fixes where I found them
Test Plan
---------
```
$ threatexchange config collab edit ncmec --help
usage: threatexchange config collab edit ncmec [-h] [--create] [--enable [{0,1}] | --disable] [--only-signal-types [NAME [NAME ...]]] [--not-signal-types [NAME [NAME ...]]] [--only-owners [ID [ID ...]]] [--not-owners [ID [ID ...]]] [--only-tags [TAG [TAG ...]]] [--not-tags [TAG [TAG ...]]] [--json] [--environment [Industry,NGO,Exploitative]] collab_name
positional arguments:
collab_name           the name of the collab
--create, -C          indicate you …
```

[pytx] Fetcher Implementation for NCMEC, Many Supporting Changes

---

python-threatexchange/threatexchange/cli/main.py
python-threatexchange/threatexchange/cli/tests/cli_smoke_test.py
python-threatexchange/threatexchange/cli/tests/e2e_test_helper.py

Summary
---------
Calling with so subcommands is not an error, but generates an assertion failure shortly afterwards. Fix that I guess
Test Plan
---------
Unittest
```
$ threatexchange
<see help>
```

Missing toplevel command

---

python-threatexchange/threatexchange/cli/hash_cmd.py
python-threatexchange/threatexchange/cli/match_cmd.py
python-threatexchange/threatexchange/cli/tests/hash_cmd_test.py

Summary
---------
This one is just a fix for something that was bother me, as I continue to procrastinate implementing StopNCII.org's API. It's inspired by grep (and will likely add similar file notations as grep at some point).
```
$ echo "Some text" | threatexchange hash text     
$ threatexchange hash text a_file.txt b_file.txt
$ threatexchange hash text -- Some text
```
Test Plan
---------
Added unittests

[pytx] Cleaner behavior for `threatexchange hash`

---

python-threatexchange/threatexchange/cli/main.py

Summary
---------
Going through all the commands
Test Plan
---------
```
$ $ threatexchange --help
usage: threatexchange [-h] {config,fetch,match,label,dataset,hash} ...
The flow the CLI is generally:
1. Configure collaborations and APIs with (or skip to use fake sample data)
$ threatexchange config collab edit
$ threatexchange config api  # to set up credentials if needed
2. Fetch data and build match indices
3. Match data
$ threatexchange match photo my_photo.jpg
4. Contribute labels to external APIs
$ threatexchange label photo my_photo.jpg dog 
$ threatexchange label photo my_photo.jpg --false-positive
Additionally, there are a number of utility commands
* threatexchange dataset
* …
```

[pytx][cli] Root help cleanup

---

python-threatexchange/threatexchange/cli/fetch_cmd.py

Summary
---------
Continuing help refreshes, here's fetch
Test Plan
---------
```
$ threatexchange fetch --help
usage: threatexchange fetch [-h] [--clear] [--skip-index-rebuild] [--limit LIMIT] [--time-limit-sec SEC] [--only-api {sample,local_file,stop_ncii,ncmec,fb_threat_exchange}] [--only-collab NAME]
Download content from signal exchange APIs to disk.
Fetches data for collaborations that you've configured with
$ threatexchange config collab edit
Fetching is checkpointed, and you can safely interrupt by using CTRL+C.
Some APIs require that you regularly re-fetch them within some number
of days or else the stored data becomes invalid.
--clear               delete fetched state and checkpoints (you almost never …
```

[pytx][cli] fetch help refresh

---

pdq/cpp/common/pdqhashtypes.cpp
pdq/cpp/common/pdqhashtypes.h

Summary
---------
Add a standalone function for hashToHex in PDQ CPP implementation. So, VPDQ python binding can use this function instead of NumPy vector translation. 
Test Plan
---------
Won't affect pdq CPP. Test correctness it in python-binding PR.

[VPDQ] Add standalone function for vpdq-python import

---

python-threatexchange/threatexchange/cli/helpers.py
python-threatexchange/threatexchange/cli/tests/e2e_test_helper.py
python-threatexchange/threatexchange/cli/tests/hash_cmd_test.py

Summary
---------
Folks found the empty argument behavior confusing, and on reflection, I find it confusing too, Instead use `-`. Also force it to be considered required. 
Test Plan
---------
Test on cli, also add regression test.

[pytx][cli] Dash for stdin for `hash`, `match` and friends

---

python-threatexchange/threatexchange/cli/hash_cmd.py

Summary
---------
Continuing onward, now to `hash`
Test Plan
---------
```
$ threatexchange hash --help
usage: threatexchange hash [-h] [--signal-type {pdq,video_md5,url_md5}] {photo,video,url} ...
Take content and convert it into signatures (aka hashes)
You can pass in data to the command in a few different ways:
(Note - you may not be able to hash text without an extension)
```
$ threatexchange hash photo my_photo.jpg
$ echo This is my cool text | threatexchange hash text -
$ threatexchange hash text -- This is my cool text
```
<SignalType> <hash string>
positional arguments:
{photo,video,url}     what kind of content to hash
files                 list of files or -- to interpret remainder as a string …
```

[py-tx][cli] hash --help rewrite

---

.github/workflows/vpdq-ci-cpp.yml
vpdq/README.md
vpdq/cpp/bin/vpdq-hash-video.cpp
vpdq/cpp/regtest.py

Summary
---------
Invofe ffmpeg by using $PATH 'ffmpeg' in CPP implementation instead of binary's address. So, the ffmpeg's path is optional if it is installed properly.
Test Plan
---------
Run through the regression test without ffmpeg path argument.
python3 regtest.py -d ../ThreatExchange/vpdq/output-hashes -i ../ThreatExchange/tmk/sample-videos

[VPDQ] Make ffmpeg path optional

---

python-threatexchange/threatexchange/cli/cli_config.py
python-threatexchange/threatexchange/cli/config_cmd.py
python-threatexchange/threatexchange/cli/tests/cli_smoke_test.py
python-threatexchange/threatexchange/cli/tests/config_cmd_collabs_test.py
python-threatexchange/threatexchange/cli/tests/hash_cmd_test.py
python-threatexchange/threatexchange/fetcher/apis/fb_threatexchange_api.py
python-threatexchange/threatexchange/fetcher/apis/file_api.py
python-threatexchange/threatexchange/fetcher/apis/ncmec_api.py
python-threatexchange/threatexchange/fetcher/collab_config.py

Summary
---------
This one got away from me a little:
1. Fixes #1033
2. Allows annotating collab configs to add descriptions
3. Removes many unused properties in the base collab config
4. slightly change the output of `threatexchange config collab list` to play nicer with `cut`
5. Smoke test can now print all the helps with -v
Test Plan
---------
Regression test added for 1 above
See this gist for the new helps: https://gist.github.com/9a401821d7bec85575e9af9ac9b98eec
(Generated by pt.test -v smoke_test.py)

[py-tx][cli] Many Improvements to `collab edit` --help

---

python-threatexchange/threatexchange/cli/cli_config.py
python-threatexchange/threatexchange/cli/cli_state.py
python-threatexchange/threatexchange/cli/config_cmd.py
python-threatexchange/threatexchange/cli/dataset_cmd.py
python-threatexchange/threatexchange/cli/fetch_cmd.py
python-threatexchange/threatexchange/cli/label_cmd.py
python-threatexchange/threatexchange/cli/tests/dataset_cmd_test.py

Summary
---------
If you call dataset as your first command, instead of doing nothing, fetch first.
Test Plan
---------
```
$ rm -r ~/.threatexchange
$ tx fetch --clear
Looks like you haven't set up a collaboration config, so using the sample one against sample data
Clearing fetched state
dcallies@eecd010a7c71:/workspaces/devcontainer-ThreatExchange/python-threatexchange$ tx dataset
You haven't fetched any state, so we'll call `fetch` for you!
Looks like you haven't set up a collaboration config, so using the sample one against sample data
[sample] Sample Signals - Up to date
Rebuilding match indices...
Building index for trend_query with 1 signals...
Index for trend_query ready
Building index for video_md5 with 2 signals...
Index for video_md5 ready
Building index for raw_text with 3 …
```

[pytx][cli] Handle demo dataset empty, settings helpers

---

python-threatexchange/threatexchange/cli/config_cmd.py

Summary
---------
Apparently an argparse bug of some kind.
Test Plan
---------
```
tx config api fb_threatexchange --help
usage: threatexchange config api fb_threatexchange [-h] [--list-available-collabs | --import-collab IMPORT_COLLAB] [--api-token API_TOKEN]
Configure Facebook ThreatExchange integration
--list-available-collabs, -L
query the API to list available collabs
--import-collab IMPORT_COLLAB, -I IMPORT_COLLAB
import a collaboration by privacy group ID
```
```
tx config api fb_threatexchange --help
usage: threatexchange config api fb_threatexchange [-h] [--list-available-collabs | --import-collab IMPORT_COLLAB | --api-token API_TOKEN]
Configure Facebook ThreatExchange integration
-h, …
```

[pytx] Fix missing help for --api-token option

---

python-threatexchange/threatexchange/__main__.py

Summary
---------
Learned about this today!
Test Plan
---------
Before:
```
$ python3 -m threatexchange --help
/usr/local/bin/python3: No module named threatexchange.__main__; 'threatexchange' is a package and cannot be directly executed
```
After:
```
$ python3 -m threatexchange --help
usage: __main__.py [-h] {config,fetch,match,label,dataset,hash} ...
...
```

[pytx] allow to run as module

---

python-threatexchange/threatexchange/cli/config_cmd.py
python-threatexchange/threatexchange/cli/hash_cmd.py
python-threatexchange/threatexchange/cli/match_cmd.py
python-threatexchange/threatexchange/cli/tests/config_cmd_extension_test.py
python-threatexchange/threatexchange/cli/tests/fake_extension.py
python-threatexchange/threatexchange/common.py

Summary
---------
Reported by @tigerchensh , the behavior of these commands did not behave as he expected, doing some cleanups to help.
Also fix an older issue (that I could have sworn I fixed in another PR?) where the hash command is too restrictive on what it allows as a hasher.
Test Plan
---------
New test
```
tx hash --help
usage: threatexchange hash [-h] [--signal-type {pdq,url_md5,video_md5}] {photo,text,url,video} ...
Take content and convert it into signatures (aka hashes)
You can pass in data to the command in a few different ways:
(Note - you may not be able to hash text without an extension)
```
$ threatexchange hash photo my_photo.jpg
$ echo This is my cool text | threatexchange hash text -
$ threatexchange hash text -- This is my cool text
```
<SignalType> <hash string> …
```

[pytx] Extensions SignalType ContentType fixups

---

python-threatexchange/threatexchange/cli/main.py

Summary
---------
A simple command that is a shortcut to `rm -r ~/.threatexchange`, but doesn't require you to know where the state directory is.
Test Plan
---------
```
$ tx config collab list
fb_threatexchange Example Hash Sharing
$ ls ~/.threatexchange 
collab_configs  config.json  fetched  index
$ tx --factory-reset
Resetting to factory defaults.
$ ls ~/.threatexchange/
ls: cannot access '/home/dcallies/.threatexchange/': No such file or directory
```
--help
```
$ tx --help
usage: threatexchange [-h] [--factory-reset] {config,fetch,match,label,dataset,hash} ...
The flow the CLI is generally:
1. Configure collaborations and APIs with (or skip to use fake sample data)
$ threatexchange config collab edit
$ …
```

[pytx][cli] Factory reset command

---

python-threatexchange/mypy.ini
python-threatexchange/threatexchange/exchanges/clients/fb_threatexchange/descriptor.py

Summary
---------
mypy has a lot of flags that can enforce stricter typing. You only get out of typing what you put in.
Turning these all on causes a lot of errors, and I'm not even sure how to fix all of them. Instead mark what our intentions are, and then slowly turn it up.
We have a few strategies to deal with the backlog: try and enable everything, then blocklist all the old files. Turn one at a time on and fix as we go.
Test Plan
---------
If we enable all these flags right now:
```
Found 287 errors in 53 files (checked 102 source files)
```
mypy it passes

[pytx] Begin making mypy more strict

---

python-threatexchange/threatexchange/cli/config_cmd.py
python-threatexchange/threatexchange/cli/dataclass_json.py
python-threatexchange/threatexchange/cli/tests/config_cmd_collabs_test.py
python-threatexchange/threatexchange/cli/tests/config_cmd_extension_test.py
python-threatexchange/threatexchange/cli/tests/e2e_test_helper.py
python-threatexchange/threatexchange/cli/tests/fake_extension.py

Summary
---------
It started as a fix for the fact that set types weren't being parsed correctly. It completely got away from me.
Test Plan
---------
Added unittest, also run
```
$ tx config extensions add threatexchange.cli.tests.fake_extension
$ tx config collab edit fake fake --an-int 1 --a-str a --an-enum OPTION_A --a-list 1,2,3 --a-set 3,2 -C
$ tx config collab print fake
{
"an_int": 1,
"a_str": "a",
"a_list": [
"1",
"2",
"3"
],
"a_set": [
2,
3
],
"an_enum": "a",
"name": "fake",
"api": "fake",
"enabled": true,
"optional": null
}
```

[pytx] Fix NCMEC esp-filter, add too many more features

---

python-threatexchange/threatexchange/exchanges/clients/ncmec/hash_api.py
python-threatexchange/threatexchange/exchanges/clients/ncmec/tests/test_hash_api.py

Summary
---------
On my local (MacOS M1) I was seeing py.test failures:
> FAILED threatexchange/exchanges/clients/ncmec/tests/test_hash_api.py::test_mocked_get_hashes - AssertionError: assert 1508872800 == 1508858400
> FAILED threatexchange/exchanges/impl/tests/test_ncmec.py::test_fetch - AssertionError: assert 1508872800 == 1508858400
This was a difference of 4 hours which led me to look into the offset in datetime offsetss
Looks like at least locally, `strptime()` was interpreting the timestamp as "aware" and converting GMT to EST before calculating   the int values.
From the docs: 
https://docs.python.org/3.10/library/datetime.html#technical-detail
> Changed in version 3.7: When the %z directive is provided to the strptime() method, the UTC offsets can have a colon as a separator …

[pytx][exchange] update datetime string 

---

python-threatexchange/benchmarks/benchmark_pdq_faiss_matchers.py
python-threatexchange/threatexchange/extensions/vpdq/vpdq_faiss.py
python-threatexchange/threatexchange/hashing/__init__.py
python-threatexchange/threatexchange/hashing/pdq_faiss_matcher.py
python-threatexchange/threatexchange/signal_type/pdq.py

Summary
---------
`Pillow` & `faiss-cpu` are now install_requires not part of extra_require so these checks are now superfluous 
Test Plan
---------
py.test

[pytx][pdq] Removed unneeded local import checks for Pillow faiss-cpu libs

---

.github/workflows/python-threatexchange-ci.yaml
python-threatexchange/threatexchange/extensions/vpdq/video_vpdq.py

Summary
---------
Add vpdq_index as the index type for video_vpdq. So, when matching with videos, it can utilize the vpdq_index.
Test Plan
---------
Manually hash, fetch, match and check
```
threatexchange config extensions add threatexchange.extensions.vpdq
threatexchange hash --signal-type video_vpdq video ../ThreatExchange/tmk/sample-videos/chair-19-sd-bar.mp4 >> file.txt
threatexchange config collab edit local_file --filename file.txt  'file.txt' --create
threatexchange fetch
threatexchange match video ../ThreatExchange/tmk/sample-videos/chair-19-sd-bar.mp4
```
Result
```
video_vpdq - (file.txt) WORTH_INVESTIGATING
```
If add some print to show the matching percentage result(videos used to match are chair-19... and chair-20..., the latter one is a second longer in video duration):
``` …
```

[PYTX] Add vpdq_index as the default matching type for video_vpdq signal type

---

.github/workflows/hma-ci.yaml
hasher-matcher-actioner/hmalib/common/configs/tests/test_tx_apis.py
hasher-matcher-actioner/hmalib/common/configs/tx_apis.py
hasher-matcher-actioner/hmalib/common/mappings.py
hasher-matcher-actioner/hmalib/common/models/tests/ddb_test_common.py
hasher-matcher-actioner/hmalib/scripts/migrations/2022_07_24_default_signal_exchange_apis.py
hasher-matcher-actioner/terraform/migrations/main.tf

Summary
---
Hashing has been made to work with pytx-1.0. Fetchers are next, because without them, matchers can't function.
For fetchers to work, they need to get all collabs. To get all collabs, we need to get all supported signal exchanges.
This PR adds toggle-able signal exchanges.
You can add a signal-exchange using their fully-qualified class name. By default, add FBThreatExchange and LocalFile.
Test Plan
---
Added unit tests.
Ran migration using `$ terraform -chdir=terraform apply`.
Then, in console, verified that both are 'enabled'.
```
$ python
>>> [
t.to_concrete_class()
for t in ToggleableSignalExchangeAPIConfig.get_all()
if t.enabled
]
[
<class 'threatexchange.exchanges.impl.fb_threatexchange_api.FBThreatExchangeSignalExchangeAPI'>,
<class …
```

[UnbreakingFetch][1/n]: Allow adding / toggling SignalExchangeAPIs

---

hasher-matcher-actioner/hmalib/common/aws_dataclass.py
hasher-matcher-actioner/hmalib/common/configs/tests/test_tx_apis.py
hasher-matcher-actioner/hmalib/common/mappings.py
hasher-matcher-actioner/hmalib/common/models/tests/ddb_test_common.py
hasher-matcher-actioner/hmalib/common/models/tests/test_bank_member_signals_to_process.py
hasher-matcher-actioner/hmalib/common/tests/aws_dataclass_test.py
hasher-matcher-actioner/hmalib/lambdas/api/matches.py
hasher-matcher-actioner/hmalib/matchers/matchers_base.py

Summary
---
For HMAConfig to represent NCMECCollabConfig, it needs to support Enums. Add that support and a test guarding it.
There is also a quality of life improvement as part of a second commit, I recommend reviewing commit by commit. 
There is also a third commit which applies name changes done as part of #1095. If reviewer would like, I'd be happy to break things up into 3 diff PRs, but decided against because the change is simple enough.
P.S. I'm strongly considering dropping our clearly lagging implementation in favour of dacite, but that would throw a wrench into the current project.
For HMAConfig to represent NCMECCollabConfig, it needs to support Enums. Add that support and a test guarding it.  P.S. I'm strongly considering dropping our clearly lagging implementation in favour …

Support Enums in aws_dataclass     

---

python-threatexchange/threatexchange/exchanges/impl/fb_threatexchange_api.py
python-threatexchange/threatexchange/exchanges/impl/fb_threatexchange_signal.py
python-threatexchange/threatexchange/signal_type/md5.py
python-threatexchange/threatexchange/signal_type/url.py

Summary
---------
Originally, I thought that we'd be able to get away with only indicator type from the ThreatExchange data, since it greatly simplifies the conversion between the ThreatIndicators and signal metadata. However, the existence of DEBUG_STRING prototyping, as well as DATA means that we have to take into account tags as well.
This unfortunately puts is in positions where we can have essentially multiple opinions from the same source. For this, I just chose to concatenate without deduping. 
Test Plan
---------
This PR is super gross, and comes with no testing. This is somewhat related to the fact that the underlying threatexchange library was always super gross. I'm tempted to beg for leniency on cleaning up and testing if I can provide proof that it seems to work on large …

[pytx] Handle type+tag combos in fb_threatexchange

---

python-threatexchange/threatexchange/cli/tests/fake_extension.py
python-threatexchange/threatexchange/extensions/pdq_ocr/pdq_ocr.py
python-threatexchange/threatexchange/extensions/tlsh/text_tlsh.py
python-threatexchange/threatexchange/extensions/vpdq/video_vpdq.py
python-threatexchange/threatexchange/signal_type/pdq.py
python-threatexchange/threatexchange/signal_type/raw_text.py
python-threatexchange/threatexchange/signal_type/signal_base.py
python-threatexchange/threatexchange/signal_type/trend_query.py
python-threatexchange/threatexchange/signal_type/url.py

Summary
---------
This is confusing since not all SignalTypes support distance. In addition, not all signal types support the same distance. 
Mypy is smart enough to tell that new arguments are backwards compatible.
Test Plan
---------
mypy & py.test

[pytx] No more dist in SignalType.compare_hash

---

python-threatexchange/threatexchange/extensions/vpdq/tests/test_vpdq_faiss.py
python-threatexchange/threatexchange/extensions/vpdq/vpdq_index.py
python-threatexchange/threatexchange/extensions/vpdq/vpdq_util.py

Summary
---------
Before the fix in vpdq_index.py, the test which queries/indexs an empty video will fail at the stage of converting to faiss vector at faiss_index.range_search.
Before the fix in vpdq_util.py, the test which queries/indexs an empty signal_str will fail for json converting an empty string at function json_to_vpdq.
Test Plan
---------
Pass test cases for querying and indexing empty video/signal string.

[PYTX]VPDQ Add support for detecting and handling empty video

---

vpdq/cpp/hashing/filehasher.cpp

Summary
---------
One of the todos in (https://github.com/facebook/ThreatExchange/projects/4)
Silence ffmpeg for non-verbose options. Thus, in python-binding library vpdq will produce hashes silently working with python-threatexchange.
Test
---------
Run through regression test nonverbose and see if ffmpeg prints anything.

[VPDQ] Silence ffmpeg for nonverbose option

---

python-threatexchange/threatexchange/cli/main.py

Summary
---------
This warning doesn't apply to the library, since we aren't compatible with any state that existed before this.
Test Plan
---------
Before:
```
ThreatExchange/pdq/data/bridge-mods$ tx hash photo *
/home/dcallies/.local/lib/python3.8/site-packages/pdqhash/__init__.py:3: UserWarning: Hash vector order changed between version 0.1.8 and 0.2.0. See https://github.com/faustomorales/pdqhash-python/issues/1 for more details.
warnings.warn(
pdq f8f8f0cee0f4a84f06370a22038f63f0b36e2ed596621e1d33e6b39c4e9c9b22
pdq f8f8f0cee0f4a84f06370a2a038f63f0b36e26d596621e1d33e6b39c4e9c9b22
```
After:
```
ThreatExchange/pdq/data/bridge-mods$ tx hash photo *
pdq f8f8f0cee0f4a84f06370a22038f63f0b36e2ed596621e1d33e6b39c4e9c9b22
pdq f8f8f0cee0f4a84f06370a2a038f63f0b36e26d596621e1d33e6b39c4e9c9b22 …
```

[pytx] Squelch pdq warning

---

pdq/php/pdqhasher.php
pdq/php/pdqhashertest.php

Summary
---------
The pure php implementation appears to have the methods for boxAlongRows and boxAlongCols mixed up.  This is obfuscated by the fact that in the pure php example. images are "downsampled" to 128x128. With the same number of rows and columns `computeJaroszFilterWindowSize` will end up the same for both `boxAlongRows` and `boxAlongCols`.
however if downsampling were to be removed the values passed to these two meethods would be mixed and you receive undefined index warnings.
```
Warning: Undefined array key 2 in /Volumes/code/ThreatExchange/pdq/php/pdqhasher.php on line 247
PHP Warning:  Trying to access array offset on value of type null in /Volumes/code/ThreatExchange/pdq/php/pdqhasher.php on line 247
```
Test Plan
---------
after removing downsampling
Using a 2px x 418px …

Correct Methods for boxAlongCols and boxAlongRows to ensure proper jarroz window sizes match dimensions

---

python-threatexchange/threatexchange/exchanges/clients/ncmec/hash_api.py

Summary
---------
#1089 seeming 'fix' broke something our ability to request. @Dcallies informed me that `_DATE_FORMAT_STR` needs the literal `"Z"`
What the `%z` was trying to fix was that `datetime` created from `content_xml.str("maxTimestamp")` is assumed to be in the local machine timezone. This change replaces that erroneous tz info to be `utc` specific.
Test Plan
---------
I ran pytest inside and outside of the python-threatexchange dev container.
This add "Z" back to `_DATE_FORMAT_STR` so it should address the breakage but I will need @Dcallies help to verify.

[pytx][exchanges] prevent datetime object from using local tz (use utc in from_xml)

---

python-threatexchange/threatexchange/hashing/pdq_hasher.py
python-threatexchange/threatexchange/signal_type/pdq.py
python-threatexchange/threatexchange/signal_type/signal_base.py

Summary
---------
We generally consider quality score < 50 to not be usable. Sadly we don't expose the quality score in the hash (though I think we should in the future). 
When a hash is not computable, the interface is expected to return empty string (see hash_cmd), but it's undocumented, so fix that too.
Test Plan
---------
There's not a test suite for this currently. I'll plead for regression testing post 1.x, but would accept a block for test.

[pytx] PDQ Quality filter

---

python-threatexchange/threatexchange/extensions/vpdq/tests/test_vpdq_faiss.py
python-threatexchange/threatexchange/extensions/vpdq/vpdq_index.py
python-threatexchange/threatexchange/signal_type/index.py
vpdq/cpp/hashing/filehasher.cpp

Summary
---------
vpdq_index_match should be an internal implementation detail lives in vpdq_Index class. Thus, move it to the right place.
Test Plan
---------
vpdq pytests

[Pytx] Vpdq move vpdq_index_match to vpdq_Index class

---

python-threatexchange/pytest.ini
python-threatexchange/threatexchange/cli/tests/hash_cmd_test.py

Summary
---------
This adds a pytest.ini file to ignore the pdq warning, and also convert future warnings into errors.
This also found one minor error, which is also fixed.
Test Plan
---------
py.test

[py-tx] pytest.ini and handle warns

---

python-threatexchange/threatexchange/cli/match_cmd.py

Summary
---------
Help text had an old name for the --hashes flag (--as-hashes) and didn't provide as much context.
TBH this could be changed to `--as-signal` but that it likely to be more confusing than helpful at this point naming is hard.
Test Plan
---------
$ tx config extensions add threatexchange.extensions.vpdq.manifest
before:
$ tx match --hashes video  -- "hi"
Too many SignalTypes for --as-hashes. Use also --only-signal
after:
$ tx match --hashes video  -- "hi"
Error: 'video' supports more than one SignalType. for '--hashes' also use '--only-signal' to specify one of ['video_md5', 'video_vpdq']

[pytx][cli] update outdated help text in match command for --hashes arg

---

python-threatexchange/threatexchange/exchanges/clients/ncmec/hash_api.py
python-threatexchange/threatexchange/exchanges/impl/ncmec_api.py
python-threatexchange/threatexchange/exchanges/impl/tests/test_ncmec.py

Summary
---------
This PR is the result of stress testing on the NCMEC hash DB API, and fixes some issues discovered.
Fixes #1105
The largest one is that checkpointing behavior wasn't sane, due to the NCMEC API's behavior of not returning entries in entry order. Though https://report.cybertip.org/hashsharing/v2/documentation.pdf suggests that we can use maxTimestamp from each return in order to plan the next fetch, observed behavior doesn't seem to support this.
However, [to, from) behavior seems to be correct, (to = inclusive, from=exclusive), and so instead of using from=0 to=now() and relying on maxTimestamp, we can instead try and pick correctly-sized time ranges.
However, the actual data in the database is randomly distributed, so the "correct" time range must be discovered through …

[pytx][ncmec] Handle NCMEC API returning out-of-order entries in NCMECSignalExchangeAPI

---

python-threatexchange/threatexchange/signal_type/index.py

Summary
---------
This PR introduces a new comparison result, which now lives in index.py instead of signal base. It also provides a fast solution when you use only a float or a int as the distance.
Why live there? Because we can replace the match concept in index at the same time!
At the end of this, the default behavior might be:
```
$ threatexchange match blah input.file
pdq 17 'Foo Collab'
pdq_ocr 14(text:89%) 'Has OCR'
vpdq 78%(index:22%) 'Bar Collab'
tmk_pdqf 0.81,0.91 'no one uses tmk :"('
raw_text 41% 'Zed Collab yo'
trend_query True 'Trend Query Collab'
an_embedding 0.19 'Goes zero to one'
square_euclidean 14420 'Wow so big'
zalgo d̵͚͌ì̶̘s̵̠̎t̴̺̉a̴͎̾ṋ̸̛ć̸̣ë̸̝
```
Test Plan
---------

[pytx][dist][1/3]  Match Distance Cleanup: Replacement ComparisonResult

---

vpdq/README.md

Summary
---------
Current vpdq/readme doesn't have any information about the python-binding library. Update those in the readme.

[VPDQ] Update vpdq/readme

---

python-threatexchange/threatexchange/cli/tests/fake_extension.py
python-threatexchange/threatexchange/extensions/pdq_ocr/pdq_ocr.py
python-threatexchange/threatexchange/extensions/tlsh/text_tlsh.py
python-threatexchange/threatexchange/extensions/vpdq/video_vpdq.py
python-threatexchange/threatexchange/signal_type/index.py
python-threatexchange/threatexchange/signal_type/pdq/signal.py
python-threatexchange/threatexchange/signal_type/raw_text.py
python-threatexchange/threatexchange/signal_type/signal_base.py
python-threatexchange/threatexchange/signal_type/tests/signal_type_test_helper.py
python-threatexchange/threatexchange/signal_type/trend_query.py
python-threatexchange/threatexchange/signal_type/url.py

Summary
---------
We now swap out HashComparisonResult (soon to SignalComparisonResult) to the new struct.
Also some fixes to the base revision that I was too lazy to change.
Test Plan
---------
py.test && mypy

[pytx][dist][stacked 2/3] Swap HashComparison to distance

---

vpdq/MANIFEST.in
vpdq/python/README.md
vpdq/setup.py

Summary
---------
Add a readme in vpdq/python/ that describes the python-library and link to this github. Use it as the README shown on the PyPI website.

[VPDQ]Add vpdq/python/readme for Pypi usage

---

vpdq/vpdq-release.py

Summary
---------
Update vpdq-release script to only build source distribution since linux platform build wheel cannot be uploaded to PyPI.

[VPDQ] Update vpdq-release.py to only generate source distribution

---

python-threatexchange/threatexchange/cli/fetch_cmd.py

Summary
---------
The NCMEC API doesn't return entries in ascending order. We caught it because the progress time was jumping around. So add that as a feature in the CLI.
Test Plan
---------
pending

[pytx][cli] Defense against time rewinds

---

python-threatexchange/threatexchange/cli/fetch_cmd.py
python-threatexchange/threatexchange/cli/main.py

Summary
---------
Expose access to the verbose logging, which is especially useful during fetch.
Test Plan
---------
```
$ tx --help
usage: threatexchange [-h] [--factory-reset] [--verbose] {config,fetch,match,label,dataset,hash} ...
The flow the CLI is generally:
1. Configure collaborations and APIs with (or skip to use fake sample data)
$ threatexchange config collab edit
$ threatexchange config api  # to set up credentials if needed
2. Fetch data and build match indices
3. Match data
$ threatexchange match photo my_photo.jpg
4. Contribute labels to external APIs
$ threatexchange label photo my_photo.jpg dog 
$ threatexchange label photo my_photo.jpg --false-positive
Additionally, there …
```

[pytx] Expose access to verbose from help

---

python-threatexchange/threatexchange/cli/dataset_cmd.py

Summary
---------
Flagged by @BarrettOlson , this one is a little confusing given we also have --only-signals
Test Plan
---------
```
x dataset --help
usage: threatexchange dataset [-h] [--rebuild-indices | --clear-indices | --signal-summary | --print-signals] [--only-signals SIGNAL_TYPE [SIGNAL_TYPE ...] | --only-content CONTENT_TYPE [CONTENT_TYPE ...]] [--print-zeroes] [--only-collabs NAME [NAME ...]] [--only-tags STR [STR ...]] [--print-signals-only | --csv]
Introspect fetched data.
Can print out contents in simple formats
(ideal for sending to another system), or regenerate
index files (ideal if distributing indices for some reason)
Example commands:
```
$ threatexchange dataset
$ threatexchange dataset -c 'Sample Data'
$ threatexchange dataset -c 'Sample Data' -P --csv > collab.csv …

[pytx] dataset command signals_only => print_signals_only

---

python-threatexchange/threatexchange/exchanges/impl/fb_threatexchange_api.py

Summary
---------
Noticed stress testing fb_threatexchange, the numbers didn't match what I expected at all. Turns out we were using the same list for everything for some reason.
This doesn't have any affect on correctness, but does waste a lot of memory.
Test Plan
---------
Before:
```
$ TX_VERBOSE=1 tx fetch
2022-08-05 19:18:14,660 I] Fetching all sample's configs
2022-08-05 19:18:14,660 I] Fetching all local_file's configs
2022-08-05 19:18:14,660 I] Fetching all stop_ncii's configs
2022-08-05 19:18:14,660 I] Fetching all ncmec's configs
2022-08-05 19:18:14,660 I] Fetching all fb_threatexchange's configs
2022-08-05 19:18:17,683 I] fetch() with 100 new records
2022-08-05 19:18:19,258 I] fetch() with 200 new records
2022-08-05 19:18:20,765 I] fetch() with 300 new records …
```

[pytx][fb_threatexchange] fix fetch() impl re-using state

---

python-threatexchange/threatexchange/cli/match_cmd.py
python-threatexchange/threatexchange/cli/tests/fake_extension.py
python-threatexchange/threatexchange/extensions/vpdq/tests/test_vpdq_faiss.py
python-threatexchange/threatexchange/signal_type/index.py
python-threatexchange/threatexchange/signal_type/signal_base.py
python-threatexchange/threatexchange/signal_type/tests/signal_type_test_helper.py
python-threatexchange/threatexchange/signal_type/tests/test_pdq_index.py
python-threatexchange/threatexchange/signal_type/tests/test_raw_text.py

Summary
---------
Various followups from the discussion on distance, that I was bad about keeping separate:
1. match_info => similarity_info
2. Comparing signals now lives in either MatchesStr or FileHasher, since those are the only contexts where it makes sense to do so.
Test Plan
---------

[pytx] SignalType now abstract compare_hash moved to FileHasher

---

python-threatexchange/threatexchange/extensions/vpdq/tests/test_vpdq_faiss.py
python-threatexchange/threatexchange/extensions/vpdq/video_vpdq.py
python-threatexchange/threatexchange/extensions/vpdq/vpdq_index.py
python-threatexchange/threatexchange/signal_type/index.py

Summary
---------
Adds a distance impl with the new interface.
```
$ tx match -S video_vpdq -H video ~/hash.txt 
video_vpdq 99%[62%] (Sample Signals) INVESTIGATION_SEED
```
Alternatives:
```
video_vpdq 99.27%(98.55%)
video_vpdq 99.27%(i:98.55%)
video_vpdq 99.27%(c:98.55%)
video_vpdq 99.27%(vs98.55%)
video_vpdq 99.27%(v.98.55%) 
video_vpdq 99.27%(vs.98.55%)
video_vpdq 99.27%(vs-98.55%)
video_vpdq 99.27%(vs_98.55%)
video_vpdq 99.27%(comp:98.55%)
video_vpdq 99.27%(index:98.55%)
video_vpdq 99%(98%)
video_vpdq 99%(index:98%)
video_vpdq 99/98%
video_vpdq 99|98%
video_vpdq 99[98%]
video_vpdq 99v98%
video_vpdq 99x98%
video_vpdq 99%(banked:98%)
```
Test Plan
---------
You saw it live! Copy sample hash to file, manually edit it to change the distance.
mypy and py.test
With new ==, here's what …

[pytx][vpdq][stacked] vpdq distance

---

vpdq/benchmark/README.MD
vpdq/benchmark/benchmark.py
vpdq/cpp/CMakeLists.txt

Summary
---------
Benchmark on vPDQ with CPP and python-binding implementations. Both benchmarks run through the sample video set (fourteen 480x720 videos and one 1280x720 video). CPP implementation uses -02 flag and python-binding uses vpdq 0.0.6. Benchmark mark runs on MacBook Pro (16-inch, 2021), Apple M1 Pro, 32 GB Ram and the result is in README.MD. vPDQ performs well on 64 x 64 which comes from the pdq algorithm's support on this "magic" resolution.

[vPDQ] Benchmark CPP and python-binding implmentations

---

python-threatexchange/threatexchange/cli/tests/fake_extension.py
python-threatexchange/threatexchange/exchanges/helpers.py
python-threatexchange/threatexchange/exchanges/impl/fb_threatexchange_api.py
python-threatexchange/threatexchange/exchanges/impl/ncmec_api.py
python-threatexchange/threatexchange/exchanges/impl/tests/test_ncmec.py
python-threatexchange/threatexchange/exchanges/signal_exchange_api.py
python-threatexchange/threatexchange/exchanges/tests/test_state.py

Summary
---------
Adds the collab config to converting to signal type, which allows us to filter after the state has been fetched in places like the NCMEC API without worrying about the state being invalid.
To keep the diff small, only update the interface.
At this point, every single method of SignalExchangeAPI now takes collab. We may want to consider making it standard that one API instance = for one collab, which prevents from needing to pass it around everywhere. 
If we choose to do so, it's potentially right now, so need to sync with @schatten .
Test Plan
---------

[pytx] Add collab config to convert to signal

---

python-threatexchange/threatexchange/exchanges/impl/fb_threatexchange_api.py

Summary
---------
We are parsing reactions wrong, but personally I'm kinda baffled by why it's returning in this format, since I don't think it's stored in that format. Just parse it correctly for the time being.
Test Plan
---------
Successfully parsed td id 4132471233453431 with multiple reactions.

[pytx][fb_threatexchange] Fix unxpected reaction format

---

python-threatexchange/threatexchange/extensions/vpdq/manifest.py
python-threatexchange/threatexchange/extensions/vpdq/tests/test_vpdq_faiss.py
python-threatexchange/threatexchange/extensions/vpdq/tests/test_vpdq_hash_and_match.py
python-threatexchange/threatexchange/extensions/vpdq/vpdq.py

Summary
---------
Rename VideoVPDQSignal to VPDQSignal
Test Plan
---------
Py.test and CLI manual test. Big shout out to the percentage match results.

[pytx] Rename signal type video_vpdq to vpdq

---

python-threatexchange/threatexchange/cli/dataset_cmd.py
python-threatexchange/threatexchange/cli/tests/dataset_cmd_test.py

Summary
---------
A tiny tweak that would have to be made pre-1.0.0, re-order the print output to make it slightly easier to use `cut` rather than `grep -o` to parse these into signals for other commands.
I think there are some other suspicious behaviors of the output of the command that might be worth looking into (I'm not sure the conditional print behavior will be fully understandable by users, but that can be a future problem.
Test Plan
---------
Update unittests
```
$ tx dataset -P | head -n 5
Looks like you haven't set up a collaboration config, so using the sample one against sample data
trend_query {"and": [{"or": ["basketball", "basket ball", "basket-ball", "bball", "hoops"]}, {"or": ["play", "tonight", "today", "now"]}], "not": ["tomorrow", "baseball", "hockey", "football", …
```

[pytx] Update print order in dataset_cmd

---

python-threatexchange/threatexchange/signal_type/pdq/__init__.py

Summary
---
This change makes tx.signal_type.pdq consistent with other modules like
tx.signal_type.md5 and tx.signal_type.raw_text.
pdq is the only module that is also a subpackage,
Test
---
CI.

Allow import of threatexchange.signal_type.pdq.PdqSignal

---

python-threatexchange/threatexchange/cli/cli_config.py
python-threatexchange/threatexchange/cli/config_cmd.py
python-threatexchange/threatexchange/cli/fetch_cmd.py
python-threatexchange/threatexchange/cli/label_cmd.py
python-threatexchange/threatexchange/cli/main.py
python-threatexchange/threatexchange/cli/tests/fake_extension.py
python-threatexchange/threatexchange/exchanges/clients/fb_threatexchange/api.py
python-threatexchange/threatexchange/exchanges/clients/ncmec/hash_api.py
python-threatexchange/threatexchange/exchanges/clients/ncmec/tests/test_hash_api.py
python-threatexchange/threatexchange/exchanges/clients/stopncii/api.py
python-threatexchange/threatexchange/exchanges/impl/fb_threatexchange_api.py
python-threatexchange/threatexchange/exchanges/impl/file_api.py
python-threatexchange/threatexchange/exchanges/impl/ncmec_api.py
python-threatexchange/threatexchange/exchanges/impl/static_sample.py
python-threatexchange/threatexchange/exchanges/impl/stop_ncii_api.py
python-threatexchange/threatexchange/exchanges/impl/tests/test_ncmec.py
python-threatexchange/threatexchange/exchanges/impl/tests/test_stopncii.py
python-threatexchange/threatexchange/exchanges/signal_exchange_api.py
python-threatexchange/threatexchange/exchanges/tests/test_state.py
python-threatexchange/threatexchange/interface_validation.py

Summary
---------
Potentially the last interface change for 1.0.0. Put up for discussion with @schatten 
Test Plan
---------
```
$ tx --factory-reset
$ tx config api fb_threatexchange -L
Couldn't authenticate fb_threatexchange, it's missing authentification!
You can fix this by:
1. threatexchange config api fb_threatexchange --api-token
2. populating an environment variable called TX_ACCESS_TOKEN
3. creating (and maybe `chmod 400`) a file with credentials at ~/.txtoken
$ TX_ACCESS_TOKEN='a' tx config api fb_threatexchange -L
Invalid auth for fb_threatexchange: Invalid credentials from environment variable TX_ACCESS_TOKEN
$ TX_ACCESS_TOKEN="$(cat ~/.txtoken.bak)" tx config api fb_threatexchange -L
<works>
```
NCMEC
```
$ tx config collab edit ncmec -C ncmec --environment …
```

[pytx] tie SignalExchangeAPI  instantiation with collab + authentication 

---

python-threatexchange/mypy.ini
python-threatexchange/threatexchange/cli/cli_config.py
python-threatexchange/threatexchange/cli/config_cmd.py
python-threatexchange/threatexchange/cli/dataset/simple_serialization.py
python-threatexchange/threatexchange/cli/main.py
python-threatexchange/threatexchange/cli/tests/e2e_test_helper.py
python-threatexchange/threatexchange/cli/tests/fake_extension.py
python-threatexchange/threatexchange/exchanges/auth.py
python-threatexchange/threatexchange/exchanges/impl/fb_threatexchange_api.py
python-threatexchange/threatexchange/exchanges/impl/file_api.py
python-threatexchange/threatexchange/exchanges/impl/ncmec_api.py
python-threatexchange/threatexchange/exchanges/impl/static_sample.py
python-threatexchange/threatexchange/exchanges/impl/stop_ncii_api.py
python-threatexchange/threatexchange/exchanges/signal_exchange_api.py
python-threatexchange/threatexchange/exchanges/tests/test_state.py
python-threatexchange/threatexchange/extensions/manifest.py
python-threatexchange/threatexchange/signal_type/pdq/pdq_faiss_matcher.py

Summary
---------
It turns out that this change would have been backwards compatible :/ 
At least it gives us a model for how to go forward - we can use mixins to add functionality a little at a time, and merge into the base class during major versions.
Adds a mixin for SignalExchanges with authentication, which is compatible with the superclasses version.
Test Plan
---------
Also added the template for increasing strictness over time, and applied it to the new auth.py module

[pytx] Mixin for SignalExchange with Auth

---

vpdq/python/vpdq.pyx
vpdq/setup.py

Summary
---------
This diff adds a dead-simple script to call the hashing function, which is installed with vpdq. 
Test Plan
---------
```
$ pip uninstall vpdq
$ ./vpdq/vpdq-release.py -i
$ vpdq tmk/sample-videos/pattern-longer-no-bar.mp4 
d3d8981ba52c59e79fb4b295bed80905036b1dbe57b292c8ea4fb525f52c400e,100,0.000
db58897b042c5de7dfb49a55ae588905016b8cba57b69ac0b64f9d27f52c480e,100,1.000
04b7874955ab62a5381a64795d78e5a1a0257e5feafad419952fd0b7acf0a342,100,2.000
48bda94154e24a14e1caf07ded409ef4c54661ebf4b93a29bc0757d13dace2d2,100,3.000
48b594892dbdd75b2a895f31a0ad795e8e5a58bc86f10c80c3e69f097837e596,100,4.000
36cdafd957b06737be24523a4f1368766ffca7008295f4230a743119d78fa029,100,5.000
30392c1d322759120c7b39b53e968103a6c1e37527d01eecc7df6170f6fc1ccf,100,6.000 …
```

[vpdq] Simple wrapping script

---

python-threatexchange/threatexchange/extensions/vpdq/vpdq_index.py

Summary
---------
A definite facepalm by me. Left over from switching () to []
Test Plan
---------
Before:
```
tx match video https://github.com/facebook/ThreatExchange/blob/main/tmk/sample-videos/chair-19-sd-bar.mp4?raw=true
vpdq 100%[100%]) (video_bank) INVESTIGATION_SEED
```
After:
```
tx match video https://github.com/facebook/ThreatExchange/blob/main/tmk/sample-videos/chair-19-sd-bar.mp4?raw=true
vpdq 100%[100%] (video_bank) INVESTIGATION_SEED
```

[pytx][vpdq] Fix typo in match str

---

.github/workflows/hma-ci.yaml
hasher-matcher-actioner/hmalib/common/configs/tests/test_tx_collab_config.py
hasher-matcher-actioner/hmalib/common/configs/tx_collab_config.py
hasher-matcher-actioner/hmalib/common/tests/test_s3_adapters.py
hasher-matcher-actioner/hmalib/indexers/lcc.py
hasher-matcher-actioner/hmalib/matchers/filters.py
hasher-matcher-actioner/hmalib/matchers/tests/test_match_filters.py
hasher-matcher-actioner/scripts/set_threatexchange_source

Summary
---
[tx_apis.py](https://github.com/facebook/ThreatExchange/blob/main/hasher-matcher-actioner/hmalib/common/configs/tx_apis.py) makes it possible for users to add any number of signal exchange APIs.
These may have their own collab config objects. This change allows you to dynamically create such classes and CRUD them using the regular `hmalib.common.config.*` APIs.
Test Plan
---
Thorough unit tests.
Specifically tests FBThreatExchange and NCMEC APIs and verifies their individual attributes were accurately stored and returned.

Dynamically generate ddb-backed HMAConfigs from CollaborationConfigBase subclasses

---

hasher-matcher-actioner/hmalib/common/configs/tests/test_tx_collab_config.py
hasher-matcher-actioner/hmalib/common/configs/tx_collab_config.py
hasher-matcher-actioner/hmalib/common/models/bank.py
hasher-matcher-actioner/hmalib/common/models/tests/test_bank_info.py

Summary
---------
Please review commit by commit.
We allow any serializable object to be written and retrieved from the bank. We'll start storing fetch checkpoints here.  
Each collab config must be connected to a bank_id, otherwise what do we do with this collab?  To make the API feel more natural, allow users to deal with `EditableCollaborationConfig` objects rather than the actualized `CollaborationConfigBase` object. This allows free access to the `import_as_bank_id` property.  
Test Plan
---------
Test cases for each change.

[multi] Store generic bank_info against each bank; connect tx_collab_configs to bank_ids

---

python-threatexchange/setup.py

Summary
---------
Attempt to fix an error reported when trying to install python-threatexchange with older numpy version already installed. 
Debating if we should add version requirements to the other libraries without them as well...
Test Plan
---------
`python-threatexchange $ make local_install`
without error

[pytx][setup] Set minimum numpy version

---

python-threatexchange/threatexchange/exchanges/clients/stopncii/api.py
python-threatexchange/threatexchange/exchanges/impl/stop_ncii_api.py

Summary
---------
This is what I get for not thoroughly testing. Better late then never I suppose.
This looks like it's backwards compatible, but I'm actually swapping the order twice - so anyone who got the API fetching previously by putting them in the "wrong" order will still be okay.
Test Plan
---------
1. Put credentials in ~/.tx_stopncii_keys
2. tx config collab edit stop_ncii -C stop_ncii_prod
3. tx fetch
This uncovers a new bug - we're not picking up the vMD5s...

[py-tx][stopncii] Fix auth bugs

---

python-threatexchange/threatexchange/cli/.local_install_detection.txt
python-threatexchange/threatexchange/cli/main.py

Summary
---------
I keep reaching for this command and not finding it, so add it. Prints either the version from pip, or if it can tell its a local install, tries to read the git hash
Test Plan
---------
```
$ threatexchange --version
1.0.3 dev-4cfde6eb6a5d8c8629dd616ea73a23fcf147c28d
$ threatexchange --version
1.0.3
```

[pytx] --version to print the version

---

python-threatexchange/threatexchange/exchanges/impl/fb_threatexchange_api.py

Summary
---------
Meta team is tracking, but this would break other functionality like filtering only specific owners, so the safest thing is to treat the record as deleted, even though this has other bad effects, as noticed in the code comment.
Test Plan
---------
Example collaboration has one inconsistent API record, before - get exception, afterwards - one less record.

[pytx] Filter out descriptors with missing owners due to API bug

---

python-threatexchange/threatexchange/exchanges/clients/stopncii/api.py
python-threatexchange/threatexchange/exchanges/impl/stop_ncii_api.py

Summary
---------
StopNCII.org has a test instance with benign hashes that can be used to test an integration. This allows pytx fetch to work transparently.
Until today, the stopncii credentials string looked like
**Format 1**
```
<function_key>,<subscription_key>
```
Now, it can be
**Format 2**
```
<function_key>,<subscription_key>,<base_url>
```
This is optional. If base_url is not provided, the default one is used.
Test Plan
---------
```
$ threatexchange --factory-reset 
$ threatexchange config collab edit stop_ncii --create test-stop-ncii
$ ... edit ~/.tx_stopncii_keys...
$ cat ~/.tx_stop_ncii_keys
<FetchHashesFunctionKey>,<subscriptionKey>,[https://devapi.stopncii.org/api]
...
Building index for pdq with 2668 signals...
Index for pdq ready
...
$ threatexchange …
```

Support overriding BASE_URL for stopncii.org APIs

---

hasher-matcher-actioner/hmalib/common/aws_dataclass.py
hasher-matcher-actioner/hmalib/common/tests/aws_dataclass_test.py
hasher-matcher-actioner/hmalib/common/tests/test_aws_dataclass.py

Summary
---
Some attributes in HMAConfigs can be optional.
HMAConfig objects at present do not support optional because it is a unioned type. I think they should.
This change enables those unioned types which are optional. A unit test has been added for
optional attributes. A second test has been added to ensure unions like t.Union[int, float], or t.Union[...2+ types] do not work.
Test Plan
---
New tests for aws_dataclass

Support `t.Optional[]` types in HMAConfig

---

hasher-matcher-actioner/hmalib/common/models/bank.py
hasher-matcher-actioner/hmalib/common/models/tests/test_bank_member_with_key.py

Summary
---
Items fetched from hash exchanges will have a known key. This is codified in the [SignalExchangeAPI](https://github.com/facebook/ThreatExchange/blob/main/python-threatexchange/threatexchange/exchanges/signal_exchange_api.py#L25). This change allows you to use the bank_member_key as a the SignalExchangeAPI's `TUpdateRecordKey`.
There are other mechanisms which might be more appropriate to signal that a bank_member with the id already exists. (eg. silently fail; switch to update; or return False instead of raising an error). I'm not sure which one I want. Consider this to likely change in subsequent PRs as the fetching code starts using the new `add_bank_member_with_key` method.
Test Plan
---
added test to verify that repeat usage with same id causes a key error to be thrown.

Allow bank-members with known keys to be inserted; error when re-inserting

---

.gitignore
python-threatexchange/threatexchange/exchanges/clients/stopncii/api.py
python-threatexchange/threatexchange/exchanges/clients/stopncii/tests/test_api.py

Summary
---------
The StopNCII.org API is emitting undocumented enum values (see #1211). This will allow them to be loadable.
Test Plan
---------
Call `StopNCIIAPI.fetch_hashes()` on the [Test | Production] instance.
Before: `ValueError: 'Undefined' is not a valid StopNCIICSPFeedbackValue`
After: 
- will not raise error to block fetching process.
- will omit `StopNCIIHashRecord` that fails to `dacite`.
- will print an error log to notice user, including error message, original json string of the omitted `StopNCIIHashRecord`.

[fix] add undefined in StopNCIICSPFeedbackValue

---

hasher-matcher-actioner/hmalib/common/configs/tx_collab_config.py
hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/bank.py
hasher-matcher-actioner/hmalib/lambdas/api/collabs.py
hasher-matcher-actioner/webapp/src/Api.tsx
hasher-matcher-actioner/webapp/src/App.tsx
hasher-matcher-actioner/webapp/src/Sidebar.tsx
hasher-matcher-actioner/webapp/src/messages/CollabMessages.tsx
hasher-matcher-actioner/webapp/src/pages/collaborations/ViewCollaborations.tsx

Summary
---------
Adding / updating collabs and managing their import-as-banks was getting too challenging. This puts a readonly UI where we'll add more as the operations become clear.
This will replace the datasets settings panel.
I find that "Collaborations" are a top-level construct and make sense to locate at the same level as banks.
Test Plan (I got screenshots)
---------

Add API + UI to view collaborations

---

hasher-matcher-actioner/hmalib/common/mappings.py
hasher-matcher-actioner/hmalib/common/models/bank.py
hasher-matcher-actioner/hmalib/common/models/tests/test_bank_member_with_key.py
hasher-matcher-actioner/hmalib/common/models/tests/test_signal_uniqueness.py
hasher-matcher-actioner/hmalib/fetching/bank_store.py
hasher-matcher-actioner/hmalib/fetching/fetcher.py
hasher-matcher-actioner/hmalib/indexers/s3_indexers.py
hasher-matcher-actioner/hmalib/lambdas/api/bank.py
hasher-matcher-actioner/hmalib/scripts/cli/run_lambda.py
hasher-matcher-actioner/setup.py
hasher-matcher-actioner/webapp/src/pages/bank-management/ViewBank.tsx

Summary
---------
Interesting files:
- bank_store.py
- fetcher.py
fetcher.py has a Fetcher class which will be invoked in a lambda. This will cause it to get all current collabs and run `Fetcher._execute_for_collab` to be called for each collab.
`_execute_for_collab` ends up calling fetch_iter for SignalExchangeAPI. Each row of the output of fetch_iter is then processed via `SignalExchangeAPI.fetch_value_merge` to determine whether it is an add/update or a delete.
Each add/update is then processed via `SignalExchangeAPI.naive_convert_to_signal_type` to identify signals to be added or updated.
While the deletes result in bank-member deletes, the adds / updates result in bank-member + bank-member-signal writes.
Test Plan
---------
```python
import boto3
import logging
from …
```

HMA FetchStore implementation backed by row-based calling of SignalExchangeAPI classmethods

---

hasher-matcher-actioner/.devcontainer/Dockerfile
hasher-matcher-actioner/Dockerfile
hasher-matcher-actioner/terraform/migrations/main.tf
hasher-matcher-actioner/workspace.code-workspace

Summary
---
- Docker copy does not succeed without atleast one file
- add python-threatexchange to our regular devcontainer workspaces so we've got python-threatexchange to work with
- add working directory to migrations; it was failing on our CI deploy
- update keyserver key in devcontainer dockerfile - the current one stopped working and stackoverflow gave this answer
Test Plan
---
Will know after CI. Locally making these changes on our ec2 host allowed CI to work.

[smol] Get docker build to work and miscellaneous changes

---

hasher-matcher-actioner/hmalib/aws_secrets.py
hasher-matcher-actioner/hmalib/common/threatexchange_config.py
hasher-matcher-actioner/hmalib/lambdas/api/api_auth.py
hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/datasets.py
hasher-matcher-actioner/hmalib/lambdas/fetcher.py
hasher-matcher-actioner/hmalib/writebacker/writebacker_base.py
hasher-matcher-actioner/terraform/api/main.tf
hasher-matcher-actioner/terraform/api/variables.tf
hasher-matcher-actioner/terraform/fetcher/main.tf
hasher-matcher-actioner/terraform/fetcher/variables.tf
hasher-matcher-actioner/terraform/main.tf

Summary
---
So far, we were using terraform to manage secrets because the number of secrets (credentials) was controlled by terraform.
With the new extensions model, we need to manage an arbitrary number of secrets. Think NCMEC, StopNCII etc. It would be best to be able to manage them from HMA UI itself. That way, updating your keys if they change or adding a new collab for a never before used signal exchange becomes possible without developer support.
Test Plan
---
```
$ terraform plan / apply.
```
Use the python REPL to test out `get_secret`, `put_secret` methods in AWS Secrets. 
1. Verify that put_secret creates OR updates secrets 
2. Verify that get_secret works for existing secrets and throws ValueError for non-existing ones.

Support user managed secrets using AWS Secrets Manager

---

hasher-matcher-actioner/hmalib/common/models/bank.py
hasher-matcher-actioner/hmalib/indexers/index_store.py
hasher-matcher-actioner/hmalib/lambdas/api/indexes.py
hasher-matcher-actioner/hmalib/lambdas/common.py
hasher-matcher-actioner/hmalib/lambdas/hashing.py
hasher-matcher-actioner/hmalib/lambdas/matcher.py
hasher-matcher-actioner/hmalib/lambdas/unified_indexer.py
hasher-matcher-actioner/hmalib/matchers/matchers_base.py
hasher-matcher-actioner/terraform/.terraform.lock.hcl
hasher-matcher-actioner/terraform/authentication-shared/main.tf
hasher-matcher-actioner/terraform/indexer/main.tf
hasher-matcher-actioner/terraform/main.tf
hasher-matcher-actioner/terraform/matcher/main.tf

Summary
---------
This is mostly doing what mypy fails to do. Tried out some common HMA flows (submitting an image, building an index, matching against an index) and solved what the logs deemed broken.
In hasher-matcher-actioner/hmalib/lambdas/common.py, we've extracted out a function that's common across all lambdas. This new function allows you to get a config backed signal_type_mapping easily.
A new addition is an S3 backed index store. The older way was to provide a mixin, but that won't fly with the new threatexchange extensions model because we want _any_ SignalTypeIndex class to be used and dynamically generated classes do not pickle.
Test Plan
---------
Terraform build / apply.
Tested out a submission..
tested out an index build..
- indexes are getting built regularly from a …

[hma] Fix indexing, matching and hashing

---

hasher-matcher-actioner/hmalib/lambdas/api/middleware.py
hasher-matcher-actioner/hmalib/lambdas/api/submit.py

Summary
---
With new pytx, submit APIs need to know the supported signal types and content types. The way to do that is using the signal_type mapping in our middleware.py
hmalib.lambdas.middleware.jsoninator is an  bottle plugin that does automatic serialization and deserialization of request / response bodies.
Now, jsoninator takes additional signal_type_mapping parameters allowing it to deserialize objects that need signal_type_mapping.
Test Plan
---
Where all submission to the UI were failing, after doing these changes, they succeed.

Allow using config backed signal_type_mapping in all submit APIs.

---

python-threatexchange/threatexchange/cli/fetch_cmd.py
python-threatexchange/threatexchange/exchanges/clients/ncmec/hash_api.py
python-threatexchange/threatexchange/exchanges/clients/ncmec/tests/test_hash_api.py

Summary
---------
Fixes #1225
NCMEC has recently changed its API: https://report.cybertip.org/hashsharing/v2/documentation/
Alongside inline hashes of the form <hash_name>hash_value</hash_name> there are a few formats that are too large to put inline that are of the form <hash_name ... />. Our previous code asserted that everything would be of the former, which is how we detected it.
On a more strategic level, this is the second time (after the StopNCII fix) where we were bitten by unexpected API behavior and strict parsing. It might be worth it to go over NCMEC (and the other APIs) and split into a strict and non-strict mode, and default to non-strict.
While the strict approach is great for detecting API changes, which is leading to upstream fixes, I'm not sure if users want to …

[py-tx] Fix NCMEC large fingerprints

---

hasher-matcher-actioner/hmalib/common/configs/tests/test_tx_apis.py
hasher-matcher-actioner/hmalib/common/configs/tx_apis.py
hasher-matcher-actioner/hmalib/lambdas/api/api_root.py
hasher-matcher-actioner/hmalib/lambdas/api/exchanges.py
hasher-matcher-actioner/terraform/api/main.tf
hasher-matcher-actioner/webapp/src/Api.tsx
hasher-matcher-actioner/webapp/src/messages/ExchangeMessages.tsx
hasher-matcher-actioner/webapp/src/pages/Settings.tsx
hasher-matcher-actioner/webapp/src/pages/settings/ExchangesTab.tsx
hasher-matcher-actioner/webapp/src/pages/settings/ThreatExchangeSettingsTab.tsx

Summary
---
When I tried to get into the prod instance, there were no exchanges configured with the appropriate credentials.
This adds the ability for users to update the credentials for APIs that are already available in HMA.
Test Plan
---
terraform apply, webapp run
https://user-images.githubusercontent.com/217056/206073736-aae02149-6a6f-4d5d-88ea-21dfea5f1d4b.mp4
Fig 1: Test changing credentials for APIs.
https://user-images.githubusercontent.com/217056/206076591-c5004d45-df83-4747-810a-ac41b4a042af.mp4
Fig 2: Add a new exchange API

[hma][ui] Support updating credentials for exchanges from HMA UI

---

python-threatexchange/threatexchange/exchanges/clients/stopncii/api.py
python-threatexchange/threatexchange/exchanges/clients/stopncii/tests/test_api.py

Summary
---------
Calling `StopNCII().submit_feedbacks()` will throw an `AttributeError` even though parameter is fine.
A unittest to catch this error is included in this PR.
Test Plan
---------
`StopNCII().submit_feedbacks()` should not raise error expect for `NetworkError`, etc.

stopncii submit_feedbacks will throw AttributeError

---

hasher-matcher-actioner/hmalib/common/models/bank.py
hasher-matcher-actioner/hmalib/fetching/bank_store.py
hasher-matcher-actioner/hmalib/fetching/fetcher.py
hasher-matcher-actioner/hmalib/fetching/tests/__init__.py
hasher-matcher-actioner/hmalib/fetching/tests/test_fetcher_and_bank_store.py

Summary
---
Most of the new code sets up a Fake exchange that can return whatever data we command. This is stolen from test_state in python-threatexchange.
Expresses 4 of the behaviors in the issue. I'm a little confused about what the others are so will add them after discussing with the team.
Test Plan
---
New unit test, py.test, black, mypy yada yada.

fix #1222: Add unit test for fetcher; fix bugs found as a result

---

hasher-matcher-actioner/hmalib/common/configs/tx_apis.py
hasher-matcher-actioner/hmalib/lambdas/api/collabs.py
hasher-matcher-actioner/webapp/src/Api.tsx
hasher-matcher-actioner/webapp/src/components/PillBox.tsx
hasher-matcher-actioner/webapp/src/messages/CollabMessages.tsx
hasher-matcher-actioner/webapp/src/pages/collaborations/AddCollaborationModal.tsx
hasher-matcher-actioner/webapp/src/pages/collaborations/ViewCollaborations.tsx
hasher-matcher-actioner/webapp/src/pages/settings/ExchangesTab.tsx

Summary
---
Adds a new modal that allows the user to add a new collab config. Some of this modal can be hidden. Eg why should the user have to type out the api name again? Why not enable by default.
Test Plan
---
Tested for NCMEC and FB ThreatExchange.
https://user-images.githubusercontent.com/217056/206873136-bab7fedb-5ef6-4c19-96a1-2dcb43c7e196.mp4

UI to add new collab configs

---

pdq/README.md

I've run into a number of platforms who aren't aware of the quality pass, and so think we should add it directly in the readme.
#accept2ship please

[pdq] README to refer to reference thresholds

---

python-threatexchange/README.md

Summary
---------
Addresses #1245
Order of keys in the README doesn't match what is expected in the application
https://github.com/facebook/ThreatExchange/blob/main/python-threatexchange/threatexchange/exchanges/impl/stop_ncii_api.py#L79
Test Plan
---------
Changes the README, not a functional change

Update StopNCII key order in README.md

---

python-threatexchange/setup.py
python-threatexchange/threatexchange/cli/tests/e2e_test_helper.py
python-threatexchange/threatexchange/exchanges/clients/fb_threatexchange/api.py
python-threatexchange/threatexchange/exchanges/signal_exchange_api.py
python-threatexchange/threatexchange/tests/hashing/test_pdq_faiss_matcher.py

Summary
---------
Unfortunately the test breaking were not showing up locally, so I used a dev container to get a close as possible to the gh action ENV so I could repro and fix.
Test Plan
---------
py.test and gh actions

[pytx] fix broken gh actions for pytest and lint

---

python-threatexchange/threatexchange/cli/cli_state.py
python-threatexchange/threatexchange/cli/dataset/simple_serialization.py
python-threatexchange/threatexchange/cli/hash_cmd.py
python-threatexchange/threatexchange/cli/match_cmd.py
python-threatexchange/threatexchange/cli/tests/e2e_test_helper.py
python-threatexchange/threatexchange/cli/tests/match_cmd_test.py
python-threatexchange/threatexchange/exchanges/fetch_state.py
python-threatexchange/threatexchange/exchanges/impl/fb_threatexchange_api.py
python-threatexchange/threatexchange/exchanges/impl/stop_ncii_api.py
python-threatexchange/threatexchange/exchanges/tests/test_state_compatibility.py
python-threatexchange/threatexchange/signal_type/tests/test_raw_text.py
python-threatexchange/threatexchange/tests/hashing/test_pdq_faiss_matcher.py

Summary
---------
A new version of black is out, which adds some new rules! Surprisingly, doing `pip install --upgrade -e .[all]` didn't upgrade the version, I had to do it manually. 
It may be getting close to where we want to try and set a py env
Test Plan
---------
`black` in the root directory, see no changes.

[py-tx] Black 23.1.0

---

python-threatexchange/setup.py

Summary
---------
I did this for `hasher-matcher-actioner/setup.py` awhile ago but we hadn't yet done it for `python-threatexchange/setup.py`
This resulted in a regression in our CI tests because `dacite==1.8.0` was overzealous with their new caching functionality.  (not to mention a debugging nightmare)
See https://github.com/konradhalas/dacite/issues/215 
as they have yet to release 1.8.1 can should contains the fix I have pinned 1.7.0 for now.
To prevent this or related issue from happening in the future, I went ahead and pinned the other dependencies as well. We should periodically update them but confirm there are no test breakages when doing so to avoid this regression. 
Test Plan
---------
Previously failing pytest runs in CI and locally should now pass.

[pytx] pin setup.py dependency lib versions to prevent test regressions

---

python-threatexchange/threatexchange/exchanges/impl/stop_ncii_api.py

Summary
---------
I needed to run stats for the program today, and realized I wanted this general capability. Doing this here makes the output of dataset backwards incompatible/inconsistent for -P, but we might want to standardize on everything after the collab name being unspecified. 
I originally started this as a stats thing, but it's actually easier to use grep/uniq -c to generate fast numbers.
Test Plan
---------
```
$ tx config collab stop_ncii stop_ncii -C 
$ tx fetch
$ tx dataset -P | awk '{$2 = "..."; print $0}' | sort | uniq
```
Some of this data is faked for demonstration
```
pdq ... 'stop_ncii' DISPUTED
pdq ... 'stop_ncii' INVESTIGATION_SEED
pdq ... 'stop_ncii' POSITIVE_CLASS
video_md5 ... 'stop_ncii' DISPUTED
video_md5 ... 'stop_ncii' INVESTIGATION_SEED
video_md5 ... …
```

[pytx] Improved record printing, starting with StopNCII

---

python-threatexchange/threatexchange/exchanges/signal_exchange_api.py

While reading through the docs in SignalExchangeAPI found some typos.

fix typos in SignalExchangeAPI class

---

hasher-matcher-actioner/hmalib/common/configs/tx_apis.py
hasher-matcher-actioner/hmalib/scripts/migrations/2022_04_02_default_content_signal_type_configs.py

Summary
---------
See title. @Dcallies was right to ask for this in #1281 but I didn't add them before merge.
Test Plan
---------
Tested 3 cases
1. Made sure the command still ran if the configs didn't exist
2. Made sure the command gave the expected warning if they did exist
3. Used an expired token and made sure the command threw the error instead of just displaying the incorrect/misleading warning message.

[hma][deploy] add code check on ClientError in set up scripts

---

python-threatexchange/Dockerfile
python-threatexchange/README.md
python-threatexchange/threatexchange/cli/main.py

Summary
---------
Reduce user friction by providing a Docker container for the CLI. This eliminates the need for the user to have to care about Python.
To make for a clean Docker image layout, the persistent state directory is now configurable. While the default remains `~/.threatexchange`, it can now be overridden by setting a `TX_STATEDIR` environment variable.
Test Plan
---------
```
$ docker build --tag threatexchange .
$ docker run threatexchange --help
usage: threatexchange [-h] [--factory-reset] [--version] [--verbose]
{config,fetch,match,label,dataset,hash} ...
...
```

Dockerize python-threatexchange

---

python-threatexchange/.devcontainer/devcontainer.json

Summary
---------
Install the dev dependencies as defined in the `setup.py` - `pytest`, `black`, and so on.
Test Plan
---------
Rebuild devcontainer and check for presence of `pytest` command.

[pytx] devcontainer: install pip "extras" for development

---

hasher-matcher-actioner/webapp/package-lock.json
python-threatexchange/threatexchange/cli/match_cmd.py
python-threatexchange/threatexchange/matcher/file_matcher.py
python-threatexchange/threatexchange/matcher/hash_matcher.py
python-threatexchange/threatexchange/matcher/matcher.py

Summary
---------
An example of decoupling the matcher logic from the CLI into its own module and generic base class which allows for creation of specific matcher 'types' -- this was the simplest way to separate the logic for file matching and raw hash matching. 
Test Plan
---------
This is an RFC, but ran it locally and it all works.

[RFC][HMA-in-a-bottle] Possible example of creating a modular matcher

---

hasher-matcher-actioner/hmalib/lambdas/api/matches.py
hasher-matcher-actioner/setup.py
hasher-matcher-actioner/terraform/fetcher/main.tf

Summary
---------
Had to resolve a set of errors to get to the `for-hash` api issue (would normally be different PR but the first two are 1 liners)
1. update python-threatexchange version because of fetch error handling
2. fetcher IAM policy updated to enable to query of bank member to sub parts of  banks_datastore. 
3. Patch signal type check of field check on `distance` to remove error for `for-hash` API
Test Plan
---------
Confirmed that with changes fetcher can get values from API for sample set and build index and with the python code change that a valid matches data will return.

[hma] address missing distance field on `/for-hash/` result objects 

---

pdq/python/pdqhashing/hasher/pdq_hasher.py

Summary
---------
Accessing individual pixels with Image.getpixel() is extremely slow, so by loading all the pixels before iterating there will be a huge performance gain.
This speeds up hashing by around 10% every image!
Also, there is a redundant `numCols, numRows = img.size()` for some reason that I also removed. This does not affect noticeably affect speed, and it does not affect functionality at all.
Test Plan
---------
Tested with a variety of image types. All of them passed.
No further tests will needed to be added because this just loads the image's pixels before iteration.

[pdq] Avoid function call by loading pixels before iteration

---

vpdq/cpp/hashing/filehasher.cpp
vpdq/cpp/io/vpdqio.cpp
vpdq/python/vpdq.pyx

The video files are being read using `popen()`, but they are not closed before going out of scope. Unlike fstream, which automatically releases resources, `popen()` requires a corresponding `pclose()`.
I fixed this by calling `pclose()` before the opened file goes out of scope in order to release the files.
---
Additionally, `avformat_open_input()` and `avformat_alloc_context()` require releasing after allocation.
`avformat_open_input()` is released by `avformat_close_input()`, which will also call `avformat_free_context()`. If `avformat_open_input()` fails, the context will be automatically freed during the failure so nothing more has to be done.
I fixed the leak by calling `avformat_close_input()` before the returns of functions that opened input.
---
Finally, in the Python binding, …

[vpdq] Fix resource leak during hashing

---

pdq/python/pdqhashing/hasher/pdq_hasher.py

Summary
---------
Apply missing matrix scaling factor during discrete cosine transform calculation.
This is in the CPP implementation, but the scaling factor is not applied in the Python implementation. It produces the exact same hash, but the DCT matrix will be different internally.
CPP version (from pdqhashing.cpp):
```cpp
static float* fill_dct_matrix_64_cached() {
static bool initialized = false;
static float buffer[16 * 64];
if (!initialized) {
const float matrix_scale_factor = std::sqrt(2.0 / 64.0);
for (int i = 0; i < 16; i++) {
for (int j = 0; j < 64; j++) {
buffer[i * 64 + j] = matrix_scale_factor *
cos((M_PI / 2 / 64.0) * (i + 1) * (2 * j + 1));
}
}
initialized = false;
}
return &buffer[0];
}
```
Test Plan
---------
Run the Python tests and see they all pass. You can change …

[pdq] Apply missing DCT scaling factor

---

vpdq/cpp/hashing/matchTwoHash.cpp
vpdq/cpp/hashing/matchTwoHash.h

Summary
---------
Use idiomatic C++ in general:
- Iterate over vectors with range based for loops
- Use std::cout instead of printf for verbose output. 
Reduce repeated code by moving them into two functions: filterFeatures and findMatches.
I also fixed casting to the wrong type for the result. It should be a double but it was cast to a float. C++ doesn't need the dividend to be cast at all.
If you use 100.0 it's guaranteed to be a double since C++11, otherwise you have to use the suffix "f".
I made the parameters const because that's what `filehasher.h` does, even if they're passed by value.
Test Plan
---------
Compare old output to new output and see that they're the same.
regtest.py is not very useful with these changes because it will be using this function to test. There should …

[vpdq] Cleanup matchTwoHash

---

pdq/cpp/bin/clusterize256x.cpp
pdq/cpp/bin/hashtool256.cpp
pdq/cpp/common/pdqhamming.h
pdq/cpp/common/pdqhashtypes.cpp
pdq/cpp/common/pdqhashtypes.h
pdq/cpp/io/hashio.cpp
pdq/cpp/io/hashio.h
vpdq/cpp/CMakeLists.txt
vpdq/cpp/Makefile
vpdq/cpp/io/vpdqio.cpp

Summary
---------
While I was testing vpdq on Windows I had to make a couple changes to get it to build with pdq.
They're solid changes in general, so I thought I would upload them.
Use C++11 STL over OS dependent functions in general:
- Change file pointers to streams 
- File pointers were used with getline() which is POSIX only. Replaced file pointers **_only wherever necessary_** with streams and use std::getline(). I tried to change as little as possible here.
- Use C++ random device instead of random() which is POSIX only 
- This could have been done with rand() but I just used the C++11 one because it's a C++ project
- Fix __builtin_popcount where hamming*() should have been used
- There's a define in `pdqhamming.h` which chooses either a lookup table or __builtin_popcount based on …

[pdq] Replace POSIX dependent functions with STL equivalent

---

.github/workflows/vpdq-ci-cpp.yml
vpdq/cpp/regtest.py

Summary
---------
Improvements to the regression test for local runs:
- Create output dir if it doesn't exist
- Create output files if they do not exist
- Changed default directories so that they work locally
- Remove duplicate code just for verbosity option
With these changes you can just run regtest.py and it will run locally with the defaults.
Before, the defaults were set to stuff like "/ThreatExchange/vpdq/output-hashes". I don't know why.
You can also run `regtest.py` from anywhere, you don't have to be in cpp/build.
I also changed all of the os.path stuff to Path. It's much nicer to work with.
I don't see a reason why the cpp CI test working directory shouldn't be set to the whole directory, especially since it accesses it anyway to get the sample hashes.
Test Plan
---------
Run …

[vpdq] Regression test improvements for local development

---

open-media-match/.devcontainer/omm_config.py
open-media-match/src/OpenMediaMatch/__init__.py
open-media-match/src/OpenMediaMatch/blueprints/__init__.py
open-media-match/src/OpenMediaMatch/blueprints/curation.py
open-media-match/src/OpenMediaMatch/blueprints/hashing.py
open-media-match/src/OpenMediaMatch/blueprints/matching.py
open-media-match/src/OpenMediaMatch/templates/index.html.j2

Summary
---------
Define the hasher, matcher and curator roles. Allow them to be enabled or disabled via config. Separate those role functions out into discrete Flask "Blueprints" with URL prefixes for easy Layer 7 routing. Add stubs for a handful of example functions from the README.
The index endpoint ('/') is distinct in function from '/status',  so separate it out. Add a basic HTML page here so that user is greeted with something human-readable to show they're up and running.
Test Plan
---------
Local `curl` commands

OMM: Roles and blueprints

---

open-media-match/CONTRIBUTING.md

Adds `/status` to endpoint to get `I-AM-ALIVE` response
Summary
---------
Switches endpoint from `/` to `/status` to receive `I-AM-ALIVE` response in "hello world" exercise for *open-media-match*
Test Plan
---------
N/A

Edit status endpoint in `open-media-match` hello world exercise

---

open-media-match/src/OpenMediaMatch/storage/default.py
open-media-match/src/OpenMediaMatch/storage/interface.py
open-media-match/src/OpenMediaMatch/storage/mocked.py

Summary
---------
Adds a shim for storage for a few interfaces, including a mock for storage.
TODO: I know I need to add `threatexchange` to a dependency somewhere, but I didn't see it (looked for a setup.py), will either add it in a followup PR once I find it or add it here. I suspect I just need to read CONTRIBUTING. 
Test Plan
---------
For now, just python repl
```
>>> import OpenMediaMatch.storage.default as s
>>> inst = s.DefaultOMMStore()
>>> inst.get_signal_type_configs()
{'pdq': SignalTypeConfig(enabled=True, signal_type=<class 'threatexchange.signal_type.pdq.signal.PdqSignal'>), 'video_md5': SignalTypeConfig(enabled=True, signal_type=<class 'threatexchange.signal_type.md5.VideoMD5Signal'>)}
```

[omm] Interfaces for storage

---

python-threatexchange/setup.py

Some percentage of this library is typed, and I think this is the correct way to mark it.
In a following PR I'll bump the version number.

[pytx] Add py.typed marker to threatexchange

---

pdq/php/pdqhasher.php

Summary
---------
Within the second loop, it consistently referenced the last $d value from the first loop, potentially causing adverse effects on images with a small intGradientSum, particularly when the final $d value from the first loop was substantial.

The computation of intGradientSum was found to be inaccurate.

---

open-media-match/pyproject.toml
open-media-match/src/OpenMediaMatch/__init__.py
open-media-match/src/OpenMediaMatch/app_resources.py
open-media-match/src/OpenMediaMatch/blueprints/hashing.py
open-media-match/src/OpenMediaMatch/migrations/env.py
open-media-match/src/OpenMediaMatch/models.py
open-media-match/src/OpenMediaMatch/storage/interface.py

Summary
---------
Use the storage interfaces to pull the currently configured SignalType / ContentTypes, then download the content from the given URL and then process it.
Test Plan
---------
```bash
curl 'localhost:5000/h/hash?'\
'url=https://github.com/facebook/ThreatExchange/blob/main/pdq/data/bridge-mods/aaa-orig.jpg?raw=true&'\
'content_type=photo'
```
Response:
```
{
}
```

[omm] Hash api implementation first draft

---

open-media-match/src/OpenMediaMatch/blueprints/hashing.py

Summary
---------
Followups from #1355 suggested by @dougneal
Test Plan
---------
```
$ curl 'localhost:5000/h/hash?' \
'url=https://github.com/facebook/ThreatExchange/blob/main/pdq/data/bridge-mods/aaa-orig.jpg?raw=true'
{
}
```
```
$ curl 'localhost:5000/h/hash?' \
'url=https://github.com/facebook/ThreatExchange/raw/main/tmk/sample-videos/chair-19-sd-bar.mp4'
<!doctype html>
<html lang=en>
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>unsupported url ContentType: &#39;application/octet-stream&#39;, if you know the expected type, provide it with content_type</p>
```
```
$ curl 'localhost:5000/h/hash?' \
'url=https://github.com/facebook/ThreatExchange/raw/main/tmk/sample-videos/chair-19-sd-bar.mp4&' \ …
```

[omm][api] Hash api to detect content type

---

open-media-match/.devcontainer/devcontainer.json

Summary
---------
I keep wanting to touch a local install of python-threatexchange in my devcontainer, but it's not in the folder. I have my local checkout in my home, for this works for me, and this lets others do either something similar or add symlinks for workarounds.
Test Plan
---------
Rebuild devcontainer, navigate to /host-home-mount

[omm][devcontainer] Add home mount for ease of access to local files

---

open-media-match/src/OpenMediaMatch/app_resources.py
open-media-match/src/OpenMediaMatch/blueprints/hashing.py
open-media-match/src/OpenMediaMatch/blueprints/matching.py
open-media-match/src/OpenMediaMatch/models.py
open-media-match/src/OpenMediaMatch/storage/interface.py
open-media-match/src/OpenMediaMatch/storage/mocked.py

Summary
---------
1. Implement `lookup` API
2. Put in a placeholder for how one fetches the index (this is probably the only callsite)
3. Made a helper for json-ifying errors (though running into weird problems with the lints getting confused about whether the file exists or not - suspect this is interference with `__init__.py`
Test Plan
---------
```
$ curl -i 'localhost:5000/m/lookup?signal_type=pdq&signal=f8f8f0cee0f4a84f06370a22038f63f0b36e2ed596621e1d33e6b39c4e9c9b22'
HTTP/1.1 200 OK
Content-Type: application/json
{
"matches": [
10,
13,
12,
4,
8,
6,
16,
3,
15,
2,
14,
1
]
}
```
Errors:
```
$ curl -i 'localhost:5000/m/lookup?signal_type=pdq&signal=1234'
HTTP/1.1 400 BAD REQUEST
Content-Type: application/json
{
"message": "invalid signal type: invalid PDQ hash"
}
```
```
$ curl -i …
```

[omm] implement lookup and mock index

---

open-media-match/src/OpenMediaMatch/app.py
open-media-match/src/OpenMediaMatch/background_tasks/build_index.py
open-media-match/src/OpenMediaMatch/background_tasks/fetcher.py

Summary
---------
I'm still not sold on any particular solution in #1367, so we're just avoiding making any decisions and punting it down the road. At least someone can start figuring this out based on the passed in objects maybe,
Test Plan
---------
mypy hopefully

[omm] background task placeholders

---

open-media-match/src/OpenMediaMatch/app.py
open-media-match/src/OpenMediaMatch/blueprints/curation.py
open-media-match/src/OpenMediaMatch/database.py
open-media-match/src/OpenMediaMatch/storage/default.py
open-media-match/src/OpenMediaMatch/storage/interface.py
open-media-match/src/OpenMediaMatch/storage/mocked.py

Summary
---------
This PR:
1. Does some more work on the bank data model, which should flex it out to allow bank -> content -> hashes
2. Rewrites some of the sqlalchemy in whatever the heck the mainline docs use: https://flask-sqlalchemy.palletsprojects.com/en/3.1.x/quickstart/ and https://docs.sqlalchemy.org/en/20/orm/basic_relationships.html#one-to-many
3. Breaks the existing curation API while I continue tooling on it
As part of this, I couldn't figure out a way to make both sqlalchemy and dataclasses happy at the same time, so we're doing something immensely stupid and just translating between them.
Test Plan
---------
mypy

[omm][temporarily breaking] Bank relationships and some storage iface

---

open-media-match/.devcontainer/docker-compose.yaml
open-media-match/CONTRIBUTING.md
open-media-match/src/OpenMediaMatch/blueprints/curation.py
open-media-match/src/OpenMediaMatch/tests/test_api.py

Summary
---------
* Fix straggler reference to `current_app` in `blueprints/creation.py` 
* Add a test for the `/c/banks` banks index method
* Make the database ephemeral by default
* Add a section to `CONTRIBUTING.md` to explain
I ran into some confusing behaviour when changing the database schema in a branch, running a migration, then going back to main and rebuilding the container for an unrelated reason. This turned out to be caused by the fact that the docker volume holding the postgres database persists across the container lifecycle. After some deliberation I decided that persisting the database like this would cause more problems than it solves, and a clean build each time would be better and more supportable.
If the user wants to override this and set up a persistent volume, they …

[omm] Database fixes

---

open-media-match/src/OpenMediaMatch/database.py
open-media-match/src/OpenMediaMatch/tests/test_api.py
open-media-match/src/OpenMediaMatch/tests/test_database.py
open-media-match/src/OpenMediaMatch/tests/utils.py

Summary
---------
Adds a CollaborationConfig table that allows configuring the connection between external APIs and banks.
It doesn't attempt to actually use this table.
Test Plan
---------
Added a simple test to exercise serialization (though I didn't deeply verify it). 
As part of this diff, the fixture for app WILL NOW CLEAR YOUR TABLES in order to make it possible to test inserting data.

[omm] Collaboration Config table

---

open-media-match/src/OpenMediaMatch/blueprints/curation.py
open-media-match/src/OpenMediaMatch/tests/test_api.py

Summary
---------
Convert some calls over to storage interface. 
Test Plan
---------
```
$ flask reset_all_tables
$ flask seed
$ curl -i 'localhost:5000/c/banks'
HTTP/1.1 200 OK
Server: Werkzeug/2.3.7 Python/3.11.4
Date: Fri, 29 Sep 2023 21:34:06 GMT
Content-Type: application/json
Content-Length: 71
Connection: close
[
{
"matching_enabled_ratio": 1.0,
"name": "TEST_BANK"
}
]
$ curl -i 'localhost:5000/c/bank/TEST_BANK'
HTTP/1.1 200 OK
Server: Werkzeug/2.3.7 Python/3.11.4
Date: Fri, 29 Sep 2023 21:37:39 GMT
Content-Type: application/json
Content-Length: 59
Connection: close
{
"matching_enabled_ratio": 1.0,
"name": "TEST_BANK"
}
$ curl -i 'localhost:5000/c/bank/TEST_BANK2'
HTTP/1.1 404 NOT FOUND
Server: Werkzeug/2.3.7 Python/3.11.4
Date: Fri, 29 Sep 2023 21:37:48 GMT
Content-Type: …
```

[omm] bank methods to storage iface

---

open-media-match/src/OpenMediaMatch/database.py
open-media-match/src/OpenMediaMatch/tests/test_api.py

Summary
---------
Bank names should allow digits, except in first char
Test Plan
---------
Added tests to test_api.py to validate that invalid names result in HTTP 500 response codes

[omm] Allow digits in bank names except as first character

---

open-media-match/src/OpenMediaMatch/blueprints/hashing.py

Summary
---------
Fleshed out the hash_media_post function. Validates input, and submits the (single) file upload to the corresponding signal_types.
Test Plan
---------
Basic positive & negative testing:
```
vscode ➜ /workspace $ curl localhost:5000/h/hash -F photo=@screenshot-1.jpg
{
"pdq": "d6530e83f9e9346da58ccb3616c6f0f3690e07c9f431d9660bc33e0e95a4c1f1"
}
vscode ➜ /workspace $ curl localhost:5000/h/hash -F video=@ScreenRecording.mov
{
"video_md5": "52210dccb6893e61592808f9bd52f4a1"
}
vscode ➜ /workspace $ curl localhost:5000/h/hash -F video=@ScreenRecording.mov -F photo=@screenshot-1.jpg
{
"message": "Only one file allowed per request"
}
vscode ➜ /workspace $ curl localhost:5000/h/hash -F photo=@screenshot-1.jpg -F photo=@screenshot-2.jpg
{
"message": "Only one file allowed per …
```

Implementation of hash POST with file upload

---

open-media-match/src/OpenMediaMatch/app.py
open-media-match/src/OpenMediaMatch/blueprints/development.py
open-media-match/src/OpenMediaMatch/blueprints/hashing.py
open-media-match/src/OpenMediaMatch/blueprints/matching.py

- fix: change __init__.py to app.py in hello world instructions
- feat: add a query endpoint to combine hashing and matching
Summary
---------
Adds a /query endpoint which allows you to specify an image and signal type and it will return matches for that image 
and signal type with the DB.
Test Plan
---------
Test manually
```
vscode ➜ /workspace $ curl 
'localhost:5000/query?signal_type=pdq&url=https://github.com/facebook/ThreatExchange/blob/main/pdq/data/misc-images/b.jpg?raw=true'
{
"matches": [
1,
13,
11,
8,
5,
15,
12,
10,
7,
6,
4,
3
]
}```

Add a query endpoint to combine hashing and matching

---

open-media-match/src/OpenMediaMatch/app.py
open-media-match/src/OpenMediaMatch/blueprints/matching.py
open-media-match/src/OpenMediaMatch/database.py
open-media-match/src/OpenMediaMatch/storage/default.py
open-media-match/src/OpenMediaMatch/storage/interface.py
open-media-match/src/OpenMediaMatch/storage/mocked.py
open-media-match/src/OpenMediaMatch/tests/test_api.py

Summary
---------
Create a new matching interface that exercises all the enabled/disable logic and returns a list of banks. 
Test Plan
---------
```
$ curl -i 'localhost:5000/m/lookup?signal=f8f8f0cee0f4a84f06370a22038f63f0b36e2ed596621e1d33e6b39c4e9c9b22&signal_type=pdq'
HTTP/1.1 200 OK
Server: Werkzeug/3.0.0 Python/3.11.4
Date: Wed, 04 Oct 2023 17:33:35 GMT
Content-Type: application/json
Content-Length: 18
Connection: close
[
"TEST_BANK"
]
```

[omm] Matching by banks

---

open-media-match/src/OpenMediaMatch/blueprints/curation.py
open-media-match/src/OpenMediaMatch/blueprints/hashing.py

Summary
---------
Add-to-bank now accepts file upload as well.
Test Plan
---------
Manual testing so far:
```
vscode ➜ /workspace $ curl localhost:5000/c/bank/TEST_BANK/content -F photo=@src/OpenMediaMatch/tests/b.jpg
{
"id": 17,
"signals": {
}
}
vscode ➜ /workspace $ curl 'localhost:5000/m/lookup?signal_type=pdq&signal=f8f8f0cee0f4a84f06370a22038f63f0b36e2ed596621e1d33e6b39c4e9c9b22'
{
"matches": [
6,
13,
10,
7,
4,
11,
9,
8,
5,
15,
2,
1
]
}
```

Add-to-bank now accepts file upload as well.

---

open-media-match/src/OpenMediaMatch/app.py
open-media-match/src/OpenMediaMatch/blueprints/curation.py

Summary
---------
Create command to allow seeding a lot of data based on bank and hash variables.
Test Plan
---------
```
$ flask seed_enourmous
```
Will seed 100 banks and 100k hashes between all banks.

[OMM] Add Command to Seed large amounts of data for testing

---

open-media-match/src/OpenMediaMatch/blueprints/matching.py

Summary
---------
Fixed file-based matching to support multiple signal types.
Test Plan
---------
```
vscode ➜ /workspace/src/OpenMediaMatch $ !128
curl localhost:5000/m/lookup -F photo=@b.jpg
{
"pdq": [
"TEST_BANK"
]
}
vscode ➜ /workspace/src/OpenMediaMatch $ !129
curl localhost:5000/m/lookup -F video=@screen.mov
{
"video_md5": []
}
```

Fix for file-based matching.

---

open-media-match/.devcontainer/gunicorn_omm_config.py
open-media-match/Dockerfile
open-media-match/pyproject.toml

Summary
---------
Choosing a production environment is key to how we do background tasks, so let's go with gunicorn.
Just testing enough to make sure it boots.
Test Plan
---------
```
OMM_CONFIG=/workspace/.devcontainer/gunicorn_omm_config.py gunicorn 'app:create_app()'
```

[omm] Very early poking of gunicorn

---

open-media-match/.devcontainer/omm_config.py
open-media-match/pyproject.toml
open-media-match/src/OpenMediaMatch/app.py
open-media-match/src/OpenMediaMatch/background_tasks/build_index.py
open-media-match/src/OpenMediaMatch/background_tasks/development.py
open-media-match/src/OpenMediaMatch/background_tasks/fetcher.py

Summary
---------
This is NOT the answer for #1367, this is just something to hold us over while we continue iterating on the background task design.
I can already see issues with just running on an interval:
1. Interval delay between hash added and when hash will match
2. Need to record somewhere that it is in progress and the result - this is probably duplicate with what every persistent task scheduler does
3. For at least build index, most of the time you don't need to do anything, so we need to detect that.
Test Plan
---------
Look at de logs:
```
[2023-10-10 14:48:36,464] CRITICAL in app: DEVELOPMENT: Started background tasks with apscheduler.
* Debugger is active!
* Debugger PIN: 649-591-200
[2023-10-10 14:48:51,465] INFO in build_index: Running the build_all_indices background task …
```

[omm] Add development background tasks with apscheduler

---

open-media-match/docker-compose.yaml
open-media-match/omm_config.py

Summary
---------
I didn't think I'd need this initially, but I've been trying to spin up the 2 services (app and db) in my own compose and point at it with my own service name that is something other than `db`.
Test Plan
---------
Ran it locally and it still works.

[omm] Allow overriding the host and db name via environment variables.

---

open-media-match/.devcontainer/omm_config.py
open-media-match/src/OpenMediaMatch/app.py
open-media-match/src/OpenMediaMatch/background_tasks/fetcher.py
open-media-match/src/OpenMediaMatch/persistence.py
open-media-match/src/OpenMediaMatch/storage/interface.py
open-media-match/src/OpenMediaMatch/storage/postgres/impl.py
open-media-match/src/OpenMediaMatch/tests/test_api.py

Summary
---------
1. Implement more mocked methods from DefaultOMMStore
2. Add installed extension selection to DefaultOMMStore constructor
3. Switch over to passing a fully instantiated instance via config
4. Small improvements to fetch
Test Plan
---------
Visit UI page, still is up

[omm] Improvements to the omm_config

---

.github/workflows/python-threatexchange-ci.yaml

Summary
---------
Looks like there's a hidden dependency on distutils somewhere that triggers in 3.12. So, let's force 3.11 temporarily.
Test Plan
---------
Lets see what CI does

[py-tx] Attempt to fix CI

---

open-media-match/CONTRIBUTING.md

I keep losing these when I rebuild, so add some shortcuts

[omm] Update CONTRIBUTING.md

---

open-media-match/src/OpenMediaMatch/storage/postgres/flask_utils.py
open-media-match/src/OpenMediaMatch/tests/utils.py

Summary
---------
I see more lobjects than I expect in my current database, so just double checking that it's not from cleanup not working.
In the long term we probably need something like the vacuum utility to search for dangling OIDs and fix them.
Test Plan
---------
assert passes

Lobject clean

---

open-media-match/.devcontainer/omm_config.py
open-media-match/src/OpenMediaMatch/app.py
open-media-match/src/OpenMediaMatch/background_tasks/build_index.py
open-media-match/src/OpenMediaMatch/blueprints/matching.py
open-media-match/src/OpenMediaMatch/storage/interface.py
open-media-match/src/OpenMediaMatch/storage/mocked.py
open-media-match/src/OpenMediaMatch/storage/postgres/impl.py
open-media-match/src/OpenMediaMatch/tests/omm_config.py

Summary
---------
This feels more gross than I expected, but:
1. Allow a config option to control indices via cache
2. Then create tasks to populate those caches in the background
There's definitely still some improvements that could be done here - going from postgres -> local file, but then not persisting the local file is something that could be improved.
Test Plan
---------
1. Setup big PDQ index with 10M hashes
2. Build index - 4 minutes
3. Start up server from cold, pre-loads index in ~45 seconds
4. Query multiple times from UI, here was the last of 3:
```
[2023-12-22 04:46:46,990] DEBUG in ui: [query] hashing input
[2023-12-22 04:46:46,994] DEBUG in hashing: Processing upload of type photo, filename=high-saturation.jpg, mimetype=image/jpeg
[2023-12-22 04:46:47,055] DEBUG in ui: …
```

[omm] Local cache option to only serve indexes from preload

---

open-media-match/src/OpenMediaMatch/storage/interface.py
open-media-match/src/OpenMediaMatch/storage/mocked.py
open-media-match/src/OpenMediaMatch/storage/postgres/database.py
open-media-match/src/OpenMediaMatch/storage/postgres/impl.py
open-media-match/src/OpenMediaMatch/tests/test_postgres_storage_impl.py

Summary
---------
* Maybe the last tweaks to stored ExchangeData for a while, the ability to download and retain everything that the API gives back
* Fix a few database bugs exposed as a result.
Test Plan
---------
New unittest

[omm] bug fixes for db foreign keys; store original API data

---

open-media-match/src/OpenMediaMatch/app.py
open-media-match/src/OpenMediaMatch/blueprints/ui.py
open-media-match/src/OpenMediaMatch/templates/components/dev_mode_bar.html.j2
open-media-match/src/OpenMediaMatch/utils/dev_utils.py

Summary
---------
Cleans up some issues identified in #1504, and additionally makes these more accessible in the dev UI by placing them in the bar.
Test Plan
---------
1. Run CLI commands and see that they created hashes that showed as indexed
2. Factory reset and do for the UI
The UI bar:

[omm] Seed data fixups

---

.github/workflows/vpdq-release.yaml

Summary
---------
Add build dependencies so release so that Github Action doesn't fail during Python build.
I think you can just re-run the action and don't need the version bumped to v0.1.1.
Test Plan
---------
Build tested working on my fork (publish fails though, obviously):
https://github.com/ianwal/ThreatExchange/actions/runs/7580134442/job/20645457925

[vpdq] Fix Python Github Action release

---

vpdq/.gitignore
vpdq/cpp/CMakeLists.txt
vpdq/setup.py

Summary
---------
The only environment I was able to get vpdq working before was the docker image container we are using for omm (because I'm on a lamer windows machine).
I attempted to install 0.2.0 there, but wasn't able to get it to install without some more changes.
The problem I had:
```
INFO:setup.py:Compiling libvpdq with Make...
CRITICAL:setup.py:/usr/bin/ld: libvpdq.a(filehasher.cpp.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/vpdq-hash-video.dir/build.make:111: vpdq-hash-video] Error 1
make[1]: *** [CMakeFiles/Makefile2:101: CMakeFiles/vpdq-hash-video.dir/all] Error 2
make: *** …
```

[vpdq] Handle pthread error in devcontainer; ignore more build dirs

---

vpdq/cpp/vpdq/cpp/io/vpdqio.cpp

Small quick fix. Resolves a compilation error when `-Werror` is used.
Summary
---------
There's an unused variable that causes a compilation error when `-Werror` is used. The constant doesn't appear to be used anywhere else.

[vpdq] Remove unused constant

---

open-media-match/.devcontainer/omm_config.py

Summary
---------
Now that we can authenticate the individual exchanges, go ahead and add the rest that come with `fb_threatexchange`.
Test Plan
---------
Look at the UI:

[omm] Add the rest of the default exchanges

---

.github/workflows/python-threatexchange-ci.yaml

Summary
---------
- Fix vpdq CI for #1568 by installing dependencies.
- Bump CI action versions
- `vpdq-ci-python.yaml` runs these new versions so might as well upgrade now that we're touching this file.
Let me know if you think of something better. Not too experienced with Github Actions, so maybe there is a way to avoid duplicating this. Alternatively, we could shove this in a bash file in vpdq directory and run that instead.
Test Plan
---------
Ran it on my fork and vpdq successfully builds. Other format (unrelated to vpdq) format errors still cause the overall workflow to fail, though.

Fix threatexchange-ci vpdq build, bump action versions

---

python-threatexchange/setup.py

Summary:
---------
Fix ModuleNotFoundError "packaging" when using CLI from docker.
Tested on M1 pro mac and seems to fix it.
In case of issues with other devices I kindly request for RFC before merging.
Fixes:
---------
Cannot run the docker container:
https://github.com/facebook/ThreatExchange/blob/main/python-threatexchange/README.md#run-the-cli-in-docker-container
Tested on M1 pro mac, below sample of the output I get without the change:
docker run threatexchange {command}
File "/usr/local/bin/threatexchange", line 5, in <module>
from threatexchange.cli.main import main
File "/usr/local/lib/python3.11/site-packages/threatexchange/cli/main.py", line 43, in <module>
from threatexchange.signal_type.pdq import signal
File …

Fix ModuleNotFoundError "packaging" when using docker

---

hasher-matcher-actioner/src/OpenMediaMatch/app.py

Summary
---------
In talking with @jagraff, it would be mighty helpful to have the ability to override the file line-by-line via environment variable. So we do that, choosing the prefix "OMM_"
Test Plan
---------
```
$ .devcontainer/startup.sh
$ curl localhost:5000/site-map |  awk  -F / '{ print $2 }' | sort | uniq -c | sort -nr
13 c
5 dev
3 ui
3 m
2 
1 status",
1 static
1 site-map",
1 h
$ OMM_ROLE_CURATOR='' .devcontainer/startup.sh
$ curl localhost:5000/site-map |  awk  -F / '{ print $2 }' | sort | uniq -c | sort -nr
5 dev
3 ui
3 m
2 
1 status",
1 static
1 site-map",
1 h
1 ",
```

[hma] Add prefixed env to config options

---

hasher-matcher-actioner/src/OpenMediaMatch/blueprints/ui.py
hasher-matcher-actioner/src/OpenMediaMatch/templates/bootstrap.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/exchange_status.html.j2

Summary
---------
Alas, my hope of keeping only a single mondo UI page is shattered. Instead we populate the navbar with subpages.
Test Plan
---------
Click on all the navbar links, look at it.

[hma][ui] Split up home into subpages

---

.github/workflows/hma-ci.yaml
hasher-matcher-actioner/Dockerfile
hasher-matcher-actioner/README.md
hasher-matcher-actioner/docker-compose.yaml
hasher-matcher-actioner/pyproject.toml
hasher-matcher-actioner/reference_omm_configs/development_omm_config.py

Summary
---------
This sets up the demo docker compose on root directory to be able to run HMA as a standalone locally for demo purposes. 
Test Plan
---------
```bash
$ docker compose up
```

[HMA] Docker compose demo set-up

---

hasher-matcher-actioner/src/OpenMediaMatch/static/js/autoreload.js
hasher-matcher-actioner/src/OpenMediaMatch/static/js/main.js
hasher-matcher-actioner/src/OpenMediaMatch/static/js/match_dbg.js
hasher-matcher-actioner/src/OpenMediaMatch/templates/bootstrap.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/match_dbg_upload.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/pages/match_dbg.html.j2

Summary
---------
I am terrible at javascript, thank you chatGPT for for the help.
This PR adds some meat to the match debugger, namely that it will take images and return the results of hashing them. A future diff will then tell you whether the various algorithms think they are a match.
Test Plan
---------
https://github.com/facebook/ThreatExchange/assets/1654004/c30faf9b-ef12-49b8-9f78-1b73e66edcf9

[hma] Match debug page is more implemented

---

hasher-matcher-actioner/pyproject.toml
hasher-matcher-actioner/reference_omm_configs/json_log_omm_config.py
hasher-matcher-actioner/src/OpenMediaMatch/app.py
hasher-matcher-actioner/src/OpenMediaMatch/utils/formatters.py

Summary
---------
Enables custom flask log formatting. Added example omm_config with json formatting for reference
Test Plan
---------
To test, replace 
`OMM_CONFIG: /build/reference_omm_configs/development_omm_config.py`
with 
`OMM_CONFIG: /build/reference_omm_configs/json_log_omm_config.py`
in `docker-compose.yaml`, then start the app. It should then log in json format after startup.

Enable custom logging format

---

hasher-matcher-actioner/src/OpenMediaMatch/app.py

Fixes #1566
In order to prevent the apscheduler from executing twice in debug mode, hasher-matcher-actioner checks whether WERKZEUG_RUN_MAIN=="true" before starting the scheduler, because in debug mode the Flask service will initialize twice - werkzeug will set that environment variable only for the "outer" process, meaning that if werkzeug is the WSGI server this is a reliable way to only run the scheduler once in debug mode. However, the "production" version of HMA uses gunicorn as the WSGI server. Since gunicorn doesn't set that enviornment variable, the production version of HMA will incorrectly not trigger the scheduler. This PR fixes this by adding a check for debug mode before checking for WERKZEUG_RUN_MAIN in the environment.

HMA: Enable gunicorn task scheduling

---

vpdq/cpp/CMakeLists.txt
vpdq/cpp/vpdq/cpp/hashing/ffmpegutils.cpp
vpdq/cpp/vpdq/cpp/hashing/ffmpegutils.h
vpdq/cpp/vpdq/cpp/hashing/ffmpegwrapper.cpp
vpdq/cpp/vpdq/cpp/hashing/ffmpegwrapper.h
vpdq/cpp/vpdq/cpp/hashing/filehasher.cpp
vpdq/cpp/vpdq/cpp/hashing/filehasher.h
vpdq/cpp/vpdq/cpp/hashing/hasher.cpp
vpdq/cpp/vpdq/cpp/hashing/hasher.h
vpdq/cpp/vpdq/cpp/hashing/matchTwoHash.cpp
vpdq/cpp/vpdq/cpp/hashing/matchTwoHash.h

Summary
---------
Refactor video hashing. The combined class of hashing and decoding frames was complicated and difficult to understand. This PR splits it up into smaller classes, which also allows different frame types to be used in the future with minimal changes.
- Moved some FFmpeg custom types into separate files for better readability.
- Hashing is split into two new classes: `VpdqHasher` and `FFmpegHasher`.
- `VpdqHasher` takes care of all hashing operations and just runs the generic hashing algorithm as frames are added.
- A template is used as the frame type in `VpdqHasher` as opposed to an abstract class with derived frame types to avoid needing to dynamically allocate every frame. A generic frame is added that works without FFmpeg as an example, but is not used for anything …

[vpdq] Refactor video hashing

---

.devcontainer/devcontainer.json
Dockerfile.vpdq
vpdq/CONTRIBUTING.md
vpdq/README.md

Summary
---------
- Add Dockerfile for development convenience
- Note: User still needs to setup and use venv for the Python bindings. This container is just for setting up an environment. But `pip install -e .` works out the box for the bindings.
- Add devcontainer config to use the Dockerfile with VSCode
- Autogenerated by the devcontainer VSCode extension.
- Add Docker documentation
- Added the missing `pkg-config` to dependencies
- Fixed some documentation markdown issues
- [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) VSCode extension is very handy.
Not sure the best practice if other devcontainers are added to the repo, but for now this works.
Test Plan
---------
Markdown renders as expected.
Container builds successfully.
vpdq …

[vpdq] Add vpdq Dockerfile for development

---

python-threatexchange/.devcontainer/Dockerfile
python-threatexchange/setup.py
python-threatexchange/threatexchange/signal_type/pdq/pdq_hasher.py

Summary
---------
fixes #1568
- `python -m mypy threatexchange` was failing before, fixed type errors
Also fixed `python-threatexchange` devcontainer build problems
- couldn't build vpdq before, needed to install cmake and required packages found [here](https://github.com/facebook/ThreatExchange/blob/main/vpdq/cpp/CMakeLists.txt#L75)
Test Plan
---------
tested in devcontainer inside `python-threatexchange` dir

[py-tx] Fix Type Errors

---

pdq/python/pdqhashing/tests/hash256_test.py
pdq/python/pdqhashing/tests/pdq_test.py

Fixed tests for Python pdq implementation.
Summary
---------
Fixed SAMPLE_MEDIA path (had one too many parent dirs) within[ pdq_test.py](https://github.com/facebook/ThreatExchange/blob/ee9b1b516ab55d698efb1e28dae1f721f45eb16e/pdq/python/pdqhashing/tests/pdq_test.py). Also changed `self.assertNotEquals` to `self.assertNotEqual` on line 23 of [ pdq_test.py](https://github.com/facebook/ThreatExchange/blob/ee9b1b516ab55d698efb1e28dae1f721f45eb16e/pdq/python/pdqhashing/tests/pdq_test.py) (note: typo in commit message).
Tests within pdq/python/pdqhashing/tests now complete correctly (pytest, Python3.12, MacOS 14.5)
Test Plan
---------
Run existing tests for Python build.

Fixed tests for Python PDQ implementation

---

vpdq/cpp/vpdq/cpp/hashing/hasher.h

Summary
---------
`VpdqHasher` currently doesn't join its hashing threads on destruction.
This is a problem if `VpdqHasher::finish()` is not called and VpdqHasher is destroyed. The threads will be destroyed while not joined which causes an abort.
Also remove the template specialization code so that this file doesn't depend on FFmpeg libraries at all. These aren't necessary after #1605.
I spotted this while integrating vpdq in another project. I was using Python bindings and when an exception occurred from Python during hashing the entire program would deadlock.
Test Plan
---------
Current regtest doesn't cover this because `finish()` is always called in `filehasher.cpp`. This would be something for a unit test.
But I tested by removing the `finish()` call in `filehasher.cpp` and ran …

[vpdq] Ensure VpdqHasher joins threads on destruction

---

hasher-matcher-actioner/.devcontainer/startup.sh
hasher-matcher-actioner/src/OpenMediaMatch/blueprints/ui.py
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/create_exchange_modal.html.j2

Summary
---------
Fixes #1601  API Select in the Create Exchange form
also fixes issue with startup.sh script, devcontainer was failing before
Test Plan
---------
before
after

[HMA] Fix Create Exchange API Selector

---

python-threatexchange/threatexchange/exchanges/clients/fb_threatexchange/api.py
python-threatexchange/threatexchange/exchanges/clients/ncmec/hash_api.py
python-threatexchange/threatexchange/exchanges/clients/stopncii/api.py
python-threatexchange/threatexchange/exchanges/clients/techagainstterrorism/api.py
python-threatexchange/threatexchange/exchanges/clients/techagainstterrorism/test.py
python-threatexchange/threatexchange/exchanges/clients/techagainstterrorism/tests/test_api.py
python-threatexchange/threatexchange/exchanges/clients/utils/common.py

Summary
---------
Hi
Bruce here from Tech Against Terrorism 👋 
This PR contains Step 1 from [this issue](https://github.com/facebook/ThreatExchange/issues/1610) integrating the Tech Against Terrorism Hash List API into `python-threatexchange`
I used StopNSCII & NCMEC inside `/client/exchanges/` as initial guidance. 
**Caveat**
Our API returns a pre-signed URL to a JSON file for our hash list, instead of paginated results. I'm wondering how we want to handle this moving forward into part 2 (Once we're happy with part 1) ? 
Test Plan
---------
**Manual**
For manual testing you can use python shell to simply instantiate the `TATHashListAPI` with your TCAP username and password.
```
tat_api = TATHashListAPI(username=USER_NAME, password=PASSWORD)
response = tat_api.get_hash_list()
``` …

[pytx] Add Tech Against Terrorism Hash API

---

python-threatexchange/threatexchange/exchanges/clients/stopncii/api.py
python-threatexchange/threatexchange/exchanges/signal_exchange_api.py
python-threatexchange/threatexchange/signal_type/pdq/signal.py

Summary
---------
fixes #1609
validates hash length in SignalExchangeAPIWithSimpleUpdates (used by stopNCII, file, etc)
Test Plan
---------
reproduce error by adding `"00000000000000000000000000000000"` to the list of example PDQ hashes and try to run `tx fetch`
```
...
Building index for pdq with 17 signals...
File "/home/vscode/.local/bin/tx", line 33, in <module>
sys.exit(load_entry_point('threatexchange', 'console_scripts', 'tx')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/workspaces/ThreatExchange/python-threatexchange/threatexchange/cli/main.py", line 321, in main
inner_main()
File "/workspaces/ThreatExchange/python-threatexchange/threatexchange/cli/main.py", line 314, in inner_main
execute_command(settings, namespace) …
```

[py-tx] Validate hash length

---

python-threatexchange/threatexchange/extensions/README.md

Summary
---------
Update the extensions wiki to recommend using `signal_type_test_helper.py` for testing new SignalType implementations
fixes #1612 
Test Plan
---------
just a README update, no tests

Update Extensions Wiki for signal_type_test_helper

---

Dockerfile.vpdq
hasher-matcher-actioner/src/OpenMediaMatch/blueprints/curation.py
hasher-matcher-actioner/src/OpenMediaMatch/migrations/env.py
hasher-matcher-actioner/src/OpenMediaMatch/migrations/script.py.mako
hasher-matcher-actioner/src/OpenMediaMatch/templates/bootstrap.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/add_to_bank_form.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/banks_grid.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/content_signal.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/create_exchange_modal.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/dev_mode_bar.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/exchange_status.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/index_status.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/match_dbg_upload.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/match_form.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/nav_bar.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/pages/banks.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/pages/exchanges.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/pages/home.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/pages/match_dbg.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/tests/test_api.py
hasher-matcher-actioner/src/OpenMediaMatch/tests/test_database.py
hasher-matcher-actioner/src/OpenMediaMatch/tests/utils.py
hasher-matcher-actioner/src/OpenMediaMatch/utils/formatters.py
vpdq/cpp/pdq/cpp/hashing/torben.cpp
vpdq/cpp/pdq/cpp/hashing/torben.h
vpdq/python/tools/generate_hashes.py

Summary
---------
The internal linter is complaining again, so do a fixup. There were a couple of tricky cases
1. jinja template files, which I chose to implement via `{# Comment #}`
2. A section of vpdq declared in the public domain in #1508. I am not a lawyer, so I tried to pick a compromise solution, @Ianwal seems to have left github so can't ask him his opinion.
Test Plan
---------
Let's see if CI is happy, and then I'll just view the HMA UI to make sure it still loads

Add required copyright headers to files missing it

---

hasher-matcher-actioner/src/OpenMediaMatch/tests/test_api.py

Summary
---------
We have some old #type:  ignore from when Mypy wasn't able to parse some of the more complicate generics, but a new version seems to be able to handle them. We're not getting an error for an unneeded type:ignore
Test Plan
---------
mypy locally, it passes

[hma] Fix CI for new mypy version

---

hasher-matcher-actioner/src/OpenMediaMatch/blueprints/curation.py
hasher-matcher-actioner/src/OpenMediaMatch/storage/interface.py
hasher-matcher-actioner/src/OpenMediaMatch/storage/mocked.py
hasher-matcher-actioner/src/OpenMediaMatch/storage/postgres/impl.py
hasher-matcher-actioner/src/OpenMediaMatch/tests/test_api.py

Summary
---------
- add functionality to delete a content_signal from a bank
- there's already a implementation for `bank_remove_content` that I utilized
Test Plan
---------
- tested locally by adding something to a bank and then hitting the new endpoint to delete it

add endpoint to delete a content_signal from a bank

---

hasher-matcher-actioner/src/OpenMediaMatch/blueprints/curation.py
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/banks_grid.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/create_exchange_modal.html.j2

Summary
---------
This PR updates the input validations for the bank page and the exchanges page
The bank names should now auto format on blur.
Test Plan
---------
Tested locally:
Bank Page:
- Enter different bank names. For invalid names, verify that the "Create New Bank" button is disabled and you see the appropriate error message
- Enter different bank names. For valid names, verify that the "Create New Bank" button is not disabled and is submittable and you do not see an error message
- Enter an existing bank name. Verify that you see an alert instead of being redirected for an error page.
Exchanges Page (create exchange form):
- Enter different bank names. For invalid names, verify that you see the appropriate error message and the "Create" button is disabled
- Enter an invalid json …

Update Input Validation

---

hasher-matcher-actioner/src/OpenMediaMatch/blueprints/ui.py
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/dev_mode_bar.html.j2

Summary
---------
This checks the status of the Sample API, Tx API, and bank seeding, and updates the dev mode buttons on the homepage if they already exist.
https://github.com/user-attachments/assets/0b7c6db8-7259-4664-9ac7-33920359f86c
Test Plan
---------
- Click "Sample API", verify the page reloads and the button is disabled and shows that the API already exists
- Do the same with Tx API and "Seed Banks"
- Click "Factory Reset" and verify the page reloads and buttons are usable again

Check dev mode functionality on page load

---

python-threatexchange/threatexchange/exchanges/clients/fb_threatexchange/api.py
python-threatexchange/threatexchange/exchanges/clients/ncmec/hash_api.py
python-threatexchange/threatexchange/exchanges/clients/ncmec/tests/data.py
python-threatexchange/threatexchange/exchanges/clients/ncmec/tests/test_hash_api.py
python-threatexchange/threatexchange/signal_type/signal_base.py

Summary
---------
Building on top of #1624 by @aryzle:
1. Remove untyped dicts and use dataclass objects
2. Deal with some weird tricky cases with parsing feedback
Test Plan
---------
updated unittests
querying lookup against test_NGO api, and saw gets work.
Will make another pass on upvote/downvote, not sure if it works yet.

[py-tx] Implement NCMEC Upvote/Downvote in reference API

---

hasher-matcher-actioner/src/OpenMediaMatch/blueprints/development.py

Summary
---------
remove dev/query_media function as it's no longer used. existing, non dev endpoints have the same functionality
Test Plan
---------

remove dev:query_media function as it's no longer used

---

hasher-matcher-actioner/src/OpenMediaMatch/static/js/match_dbg.js
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/match_dbg_upload.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/pages/match_dbg.html.j2

Summary
---------
Adds distance between two image hashes on the match debug page.
Test Plan
---------
- Upload two images, verify that the distance is displayed
- Replace one of the images, verify that the distance is re-calculated

Add image hash distance

---

.github/workflows/python-threatexchange-ci.yaml

Removed the Python 3.8 CI, and added the Python 3.12 CI. Fixes issue #1661 
Tested by creating a pr in my forked repository to trigger the python-threat exchange CI workflow on the updated branch and verified that all three tests (3.9, 3.11, 3.12) passed.
Link to updated workflow verification: https://github.com/Mackay-Fisher/ThreatExchange/actions/runs/11376387652

Updated Cli to remove python 3.8 and add python 3.12

---

hasher-matcher-actioner/pyproject.toml
hasher-matcher-actioner/src/OpenMediaMatch/blueprints/matching.py
hasher-matcher-actioner/src/OpenMediaMatch/storage/postgres/database.py
hasher-matcher-actioner/src/OpenMediaMatch/storage/postgres/impl.py
hasher-matcher-actioner/src/OpenMediaMatch/tests/test_api.py
hasher-matcher-actioner/src/OpenMediaMatch/tests/test_postgres_storage_impl.py

Summary
---------
Fixes an issue reported in #1673
My best guess on how this happened is because of a partial failure on deletion - I had thought that this would be enforced by transactions, but it appears in production it's possible object unlink can go through without the object being fully deleted.
It might also be possible to add this with a listener of some kind, but making this segment a little more defensive might be overall a good idea in general.
Test Plan
---------
Reproduced the issue in a unittest, then make the fix.

[hma] add recovery from lobj failure

---

python-threatexchange/threatexchange/content_type/content_base.py
python-threatexchange/threatexchange/content_type/photo.py

Summary
---------
This is a part of the issue #1665
This has been discussed previously in PR #1669 
* Create RotationType enum in content_base.py 
* Use StrEnum to make the enum’s values independent of the order
* Create 6 helper functions in PhotoContent 
* 5 functions are to rotate the image in different angles 
* 1 function is to try all different rotations 
Test plan
---------
@dcallies said not to write a unittest at this stage.
However, I was able to show that the code is correct by writing a simple bit of python:
```
from threatexchange.content_type.photo import PhotoContent
file_path = pathlib.Path("threatexchange/tests/hashing/resources/LA.png")
with open(file_path, "rb") as f:
image_data = f.read()
all_rotations = PhotoContent.all_simple_rotations(image_data)
for rotation_type, …
```

[py-tx] Create rotation helper functions in PhotoContent using Pillow

---

python-threatexchange/threatexchange/tests/test_api.py
python-threatexchange/threatexchange/tests/test_common.py

Summary
---------
* This resolves issue #1685 
* I updated these 2 tests from unittest to pytest
* https://github.com/facebook/ThreatExchange/blob/main/python-threatexchange/threatexchange/tests/test_api.py
* https://github.com/facebook/ThreatExchange/blob/main/python-threatexchange/threatexchange/tests/test_common.py
Test Plan
---------

[pytx] Convert threatexchange/tests/ to py.test

---

pdq/README.md

Summary
---------
Closes #1676  
Updated pdq README with a note on dihedral pdq hashes following this [comment](https://github.com/facebook/ThreatExchange/issues/1676#issuecomment-2466331532)
Test Plan
---------
Script to test this is [here](https://github.com/facebook/ThreatExchange/issues/1676#issuecomment-2466333264)

Update README with note on dihedral pdq hashes

---

python-threatexchange/threatexchange/signal_type/pdq/pdq_index2.py
python-threatexchange/threatexchange/signal_type/pdq/pdq_utils.py
python-threatexchange/threatexchange/signal_type/pdq/signal.py
python-threatexchange/threatexchange/signal_type/tests/test_pdq_index2.py

Summary
---------
Resolve issue #1613 . 
This PR introduces a new PDQIndex2 class for managing and querying a PDQ hash-based index using FAISS. Key changes include:
* **_PDQHashIndex**: A wrapper around the FAISS index to handle adding hashes and performing searches using the FAISS library.
* **PDQIndex2**: A class for managing a PDQ index, which includes:
* The ability to add PDQ hashes and associate them with entries. 
* A query method for searching the index for matching entries based on a query hash. 
* A serialize and deserialize method for persisting and loading the index from binary streams using pickle. 
Test Plan
---------
I have included several test cases for this, currently all in one file.
For the bug in issue #1318, I have created 2 test cases relating to it:
* [Test how the …

[pytx] Implement a new cleaner PDQ index solution

---

vpdq/README.md

Summary
---------
I was looking at vPDQ again and noticed the initial docs has a lot of words and can be hard to understand.
Tabulating (?) the TMK comparison and adding a simple high level diagram of how vPDQ works can help new readers understand the project better.
- Add simple high level mermaid diagram for vPDQ data flow.
- [github supports rendering mermaid diagrams](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams). VSCode can render markdown, but currently requires an extension like [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) to render it.
- This diagram doesn't really follow any particular format like UML.
- Put TMK+PDQF / vPDQ …

[vpdq] Add data flow diagram, misc docs cleanup

---

python-threatexchange/threatexchange/cli/storage/interfaces.py

This PR copies the ISignalTypeConfigStore interface from HMA's storage/interface.py to python-threatexchange/threatexchange/storage/interfaces.py. This is for the first part of issue #1689, I am not sure if I was supposed to preemptively change anything within the files or directly move them up first.
I played it safe and made no functional changes in this PR, please let me know if I was supposed to implement the dbm change and I will get the pr back up as quick as possible.
Tests not applicable.

[py-tx] Move ISignalTypeConfigStore to python-threatexchange/storage/interfaces.py

---

python-threatexchange/threatexchange/content_type/preprocess/__init__.py
python-threatexchange/threatexchange/content_type/preprocess/unletterboxing.py

Summary
---------
Looking at the content of 1.2.1 it somehow doesn't include the preprocessing file. I suspect that is because the file is empty, but don't know why that might be. 
Test Plan
---------
Installing locally with a non-empty file causes it to appear in the build dir when I do `python setup build`, while it doesn't when it's zero length.

[pytx] Mess with init to try and get it to package

---

hasher-matcher-actioner/pyproject.toml

Summary
---------
With migration of interfaces, we now need higher versions by default!
Test Plan
---------
Go go gadget continuous integration

[hma] Require pytx >= 1.2.2

---

.github/workflows/python-threatexchange-ci.yaml

Summary
---------
Fix for CI failure (#1711)
See [Github Runner Ubuntu docs](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/customizing-github-hosted-runners#installing-software-on-ubuntu-runners) for reasoning:
> Always run sudo apt-get update before installing a package. In case the apt index is stale, this command fetches and re-indexes any available packages, which helps prevent package installation failures.
Test Plan
---------
Tested with full CI run on my fork: https://github.com/ianwal/ThreatExchange/actions/runs/12309870754/job/34357563408?pr=26
I verified the rest of the Actions in this repo run apt-get update before apt-get install.

[vpdq] Fix CI python-threatexchange action failure due to missing apt-get update

---

hasher-matcher-actioner/src/OpenMediaMatch/background_tasks/fetcher.py
hasher-matcher-actioner/src/OpenMediaMatch/storage/interface.py
hasher-matcher-actioner/src/OpenMediaMatch/storage/mocked.py
hasher-matcher-actioner/src/OpenMediaMatch/storage/postgres/impl.py
python-threatexchange/threatexchange/cli/storage/interfaces.py

Summary
This resolves the 3rd part of issue #1689 
Delete ISignalTypeConfigStore in HMA
In HMA, import ISignalTypeConfigStore from pytx to be included in IUnifiedStore
Test Plan
I was not entirely sure what to test to verify. There was a module issue, so I added the init py to allow for the module usage in HMA. I am not sure if that was the correct approach however that is the pr referenced in #1725 
Update: Yay the version change worked!

[HMA] Remove ISignalTypeConfigStore from HMA

---

vpdq/cpp/vpdq/cpp/hashing/hasher.h

Summary
---------
Fix (rare) case of platform returning `0` thread count via [`std::thread::hardware_concurrency()`](https://en.cppreference.com/w/cpp/thread/thread/hardware_concurrency) causing hashing failure.
Current behavior:
If the user provides `0` for the thread-count to get an automatic number of hashing threads and hardware_concurrency returns `0`, then the video will not be hashed.
Expected behavior:
If the user provides `0` for the thread-count to get an automatic number of hashing threads and hardware_concurrency returns `0`, then the video will should be hashed with a single-thread.
---
Simulated scenario where the bug does occur causes immediate regtest failure:
Modified code to set thread_count to 0:
```cpp
template <typename TFrame>
VpdqHasher<TFrame>::VpdqHasher(
size_t …
```

[vpdq] Fix failure if system returns 0 thread count

---

hasher-matcher-actioner/src/OpenMediaMatch/storage/postgres/impl.py

See: #1734 https://github.com/facebook/ThreatExchange/issues/1734
Summary
---------
Previously:
`Old checkpoint doesn't match, race condition?`
New message:
`Checkpoint has changed since fetch started - multiple fetch processes may be running simultaneously.`
I think this is a pretty nice message after reviewing the surrounding context.
Test Plan
---------
Only replacing error message, so no updates needed.

(doc update): Change Tweak Message For Checkpointing Sanity Check Failure

---

hasher-matcher-actioner/reference_omm_configs/scaled_deployment_curator_omm_config.py
hasher-matcher-actioner/reference_omm_configs/scaled_deployment_hasher_omm_config.py
hasher-matcher-actioner/src/OpenMediaMatch/migrations/versions/21cb8a3df884_.py
hasher-matcher-actioner/src/OpenMediaMatch/persistence.py
hasher-matcher-actioner/src/OpenMediaMatch/storage/interface.py
hasher-matcher-actioner/src/OpenMediaMatch/utils/fetch_benchmarking.py
python-threatexchange/threatexchange/cli/cli_config.py
python-threatexchange/threatexchange/cli/main.py
python-threatexchange/threatexchange/cli/storage/interfaces.py
python-threatexchange/threatexchange/exchanges/clients/ncmec/hash_api.py
python-threatexchange/threatexchange/exchanges/helpers.py
python-threatexchange/threatexchange/exchanges/impl/file_api.py
python-threatexchange/threatexchange/exchanges/tests/test_state_compatibility.py
python-threatexchange/threatexchange/extensions/vpdq/vpdq_util.py

Summary
---------
New version of black! Format everything!
Test Plan
---------
```
black hasher-matcher-actioner python-threatexchange
```

[hma/pytx] Black format everything

---

python-threatexchange/threatexchange/exchanges/clients/ncmec/hash_api.py
python-threatexchange/threatexchange/exchanges/clients/ncmec/tests/data.py
python-threatexchange/threatexchange/exchanges/clients/ncmec/tests/test_hash_api.py
python-threatexchange/threatexchange/exchanges/impl/ncmec_api.py
python-threatexchange/threatexchange/exchanges/impl/tests/test_ncmec.py
python-threatexchange/threatexchange/exchanges/tests/test_state_compatibility.py

Summary
---------
sometimes ncmec fails to make progress after hitting a second w/ a large number of results: https://github.com/facebook/ThreatExchange/issues/1679. when that happens (diff of end and start is a second and we have lots of data), store checkpoints occasionally via a next pointer
Test Plan
---------
confirmed that resuming from a checkpoint works around the cursed second

ncmec: store checkpoint on large fetches

---

python-threatexchange/threatexchange/signal_type/tests/test_hash_from_x.py
python-threatexchange/threatexchange/signal_type/tests/test_md5_hash.py
python-threatexchange/threatexchange/signal_type/tests/test_pdq_index.py
python-threatexchange/threatexchange/signal_type/tests/test_pdq_index2.py
python-threatexchange/threatexchange/signal_type/tests/test_raw_text.py
python-threatexchange/threatexchange/signal_type/tests/test_url_md5_hash.py

Summary
---------
Previous tests were in unittest, and should now be inline with pytest (resolves #1686)
Previous tests in `signal_type` were converted to pytest
Formatted with `black hasher-matcher-actioner python-threatexchange`.
Test Plan
---------
Added tests.

Pytest: `unittest` => `pytest` Conversion

---

hasher-matcher-actioner/src/OpenMediaMatch/blueprints/matching.py
hasher-matcher-actioner/src/OpenMediaMatch/tests/test_e2e_workflow.py

Summary
---------
This PR changes the API responses for the GET and POST `/m/lookup` APIs based on issue #1681. The motivation being - users of the API need to know the content IDs so that they can turn content IDs off if they're causing false positives. Also, callers may find it useful to log / analyze matching distance as well.
**API response before:** (API just returns list on bank names with matches)
```
["FOO_BANK"]
```
**API response w/this change:** (API returns a dict of bank names with matches + details about each match)
```
{
"FOO_BANK": [
{
"content_id": 16,
"distance": "13"
}
]
}
```
Note: I modified tests that were calling `/raw_lookup` because there were no tests for the `/lookup` API. I also did that in part because I think we could remove `raw_lookup` once this is merged …

[HMA] Change matching API to return more metadata

---

hasher-matcher-actioner/src/OpenMediaMatch/blueprints/curation.py
hasher-matcher-actioner/src/OpenMediaMatch/tests/test_api.py

Summary
---------
This PR implements the exchange delete API which previously would just return a 501 when called.
Test Plan
---------
Unit tests + I manually tested this in my local HMA dev env & UI.

[HMA] Implement exchange delete API

---

.github/workflows/pdq-ci-cpp.yml
pdq/cpp/hashing/pdqhashing.cpp

Summary
---------
Fix pdq CI test failure on Ubuntu 24.04 (#1757 for pdq only)
`imagemagick` isn't installed by Ubuntu 24.04 by default anymore, and it's a runtime dependency of CImg for decoding images. Installing it fixes the issue.
- Install `imagemagick` before building pdq
- This is the ONLY required change to get the build working.
- Added multiple OS profiles to the CI to make it easier to spot a failure caused by OS differences in the future.
- The only thing I had to debug this issue with was this runtime message: ` [CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file './reg_test/../../data/reg-test-input/dih/bridge-1-original.jpg'.` It would have been very helpful to be able to see the failure was …

[pdq] Fix pdq CI failure caused by ubuntu-latest 22.04 --> 24.04 update

---

python-threatexchange/benchmarks/README.MD
python-threatexchange/benchmarks/benchmark_pdq_faiss_matchers.py
python-threatexchange/benchmarks/benchmark_vpdq_index.py

Summary
---------
Update the benchmarks, plus `benchmark_pdq_faiss_matchers.py` didn't have any results in the markdown file, so I added that as well.
Test Plan
---------
Yes

Update benchmarks with PDQ Faiss results

---

hasher-matcher-actioner/src/OpenMediaMatch/blueprints/matching.py
hasher-matcher-actioner/src/OpenMediaMatch/tests/test_api.py
hasher-matcher-actioner/src/OpenMediaMatch/tests/test_match_api.py
hasher-matcher-actioner/src/OpenMediaMatch/tests/utils.py

Summary
---------
A prior PR accidentally used the wrong distance API, and the type checker couldn't tell, likely due to the number of generics used along the way.
The real villain here is the lack of comprehensive testing on the lookup APIs, which I made the start of here.
Fixes #1766
Test Plan
---------
Added regression test, breaks before with the stack trace from #1766, works after.

[hma] Fix lookup with dist

---

hasher-matcher-actioner/src/OpenMediaMatch/blueprints/matching.py
hasher-matcher-actioner/src/OpenMediaMatch/tests/test_e2e_workflow.py
hasher-matcher-actioner/src/OpenMediaMatch/tests/test_match_api.py

Summary
---------
In #1767, I attempted to fix #1766, but missed the actual APIs in the stacktrace because I am a hack and a fraud.
Add regression tests for /lookup as well.
As part of fixing this, I added some missing type annotations, which caught a few other bugs. I also chose to align all the APIs to the same shapes, which of course will be backwards incompatible, but I don't think current users are relying on the ones I changed being 100% stable at the moment. 
Test Plan
---------
Regression tests, will ask @prenner if it really works this time.

[hma] Align lookup APIs, fix more bugs

---

python-threatexchange/README.md

Response to #1772 - make a direct link to the extension page for list of exchanges, etc are connected.

[py-tx] Add reference to implemented exchanges in README.md

---

python-threatexchange/threatexchange/exchanges/clients/techagainstterrorism/api.py
python-threatexchange/threatexchange/exchanges/clients/techagainstterrorism/tests/test_api.py

Summary
---------
Added the missing created on field to the `TATHashListEntry` in `techagainstterrorism/api.py`
Test Plan
---------
Manual:
`tx fetch` should now successfully run
Auto
`pytest`

added missing created_on field to TAT API

---

.github/workflows/python-threatexchange-release.yaml

Summary
---------
I broke PyPi publishing when changing to pyproject.toml...
I can build the wheel locally, so hoping there's no problems
```
python -m build
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
- hatch-fancy-pypi-readme
- hatchling
* Getting build dependencies for sdist...
* Building sdist...
* Building wheel from sdist
* Creating isolated environment: venv+pip...
* Installing packages in isolated environment:
- hatch-fancy-pypi-readme
- hatchling
* Getting build dependencies for wheel...
* Building wheel...
Successfully built threatexchange-1.2.7.tar.gz and threatexchange-1.2.7-py3-none-any.whl
```
Test Plan
---------
Ran build locally

[CI] Fix PyPi Publishing

---

python-threatexchange/DESCRIPTION.rst
python-threatexchange/pyproject.toml

Summary
---------
Apparently, we can't handle `DESCRIPTION.rst`... so I think it's easier just to put it in the toml file directly.
Test Plan
---------
Yeah

DESCRIPTION.rst => into `pyproject.toml` file

---

hasher-matcher-actioner/src/OpenMediaMatch/templates/components/banks/add_to_bank_form.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/banks/banks_grid.html.j2

Summary
---------
Reported in #1799
I think this generalizes pretty well any place we have a selector, but will leave creating a standard js function to a followup.
Also does a tiny bit of restyling on this form to use more of the bootstrap classes: https://getbootstrap.com/docs/4.0/components/forms/
Test Plan
---------
All files are available because content type is not selected
(if we wanted to be comprehensive, we could disable this while type was unselected)

[hma] Auto-select input type on bank add

---

hasher-matcher-actioner/reference_omm_configs/development_omm_config.py
hasher-matcher-actioner/reference_omm_configs/scaled_deployment_curator_omm_config.py
hasher-matcher-actioner/src/OpenMediaMatch/app.py
hasher-matcher-actioner/src/OpenMediaMatch/blueprints/ui.py

Summary
---------
Add UI_ENABLED config variable.
This allows users to enable the UI in production environments by setting UI_ENABLED to True in their OMM config. I modified the code to split the logic for handling when it's a production environment and handling when the UI is enabled.
* PRODUCTION now defaults to False
* UI_ENABLED defaults to False
Test Plan
---------
Unit tests. I also verified the dev-specific buttons on the homepage don't show when it's not production.

Add UI_ENABLED config variable for HMA

---

tmk/cpp/Makefile
tmk/cpp/bin/tmk-query-with-faiss.cpp

Summary
---------
Fixes broken build of tmk-query-with-faiss on Linux systems with the latest version of FAISS.
Test Plan
---------
Tested on Ubuntu 22.04 with GCC 12. Should work with default GCC 11 too.
1. Built FAISS from sources (took latest commit in the FAISS repo).
2. Built "parallel" TMK version `make parallel`.

[tmk] Fix build on Linux with latest FAISS

---

python-threatexchange/threatexchange/exchanges/clients/techagainstterrorism/api.py

Summary
---------
We received an update from Tech Against Terrorism that they are changing the subdomain of their API:
Test Plan
---------
I verified their server responds when I `curl` it using the new subdomain, so I'm pretty confident this will work.

Update TAT API base URL

---

vpdq/cpp/CMakeLists.txt

Summary
---------
I noticed a data race was detected on my fork CI and local runs.
This appears to be a false-positive with some interaction with TSan and UBSan and std::thread.
https://github.com/google/sanitizers/issues/1106
This issue recommends disabling both TSan and UBSan to fix it.
Example:
```
==================
WARNING: ThreadSanitizer: data race (pid=200212)
Write of size 8 at 0x7204000017b0 by thread T23:
#0 pipe ../../../../src/libsanitizer/tsan/tsan_interceptors_posix.cpp:1850 (libtsan.so.2+0x579ea) (BuildId: 38097064631f7912bd33117a9c83d08b42e15571)
#1 __sanitizer::IsAccessibleMemoryRange(unsigned long, unsigned long) ../../../../src/libsanitizer/sanitizer_common/sanitizer_posix_libcdep.cpp:276 (libubsan.so.1+0x210d3) (BuildId: 7fb91acab7dace1c66b29cc8969bf4b0128afa15)
#2 …
```

[vpdq] Fix TSan + UBSan false-positive

---

hasher-matcher-actioner/src/OpenMediaMatch/blueprints/hashing.py

@Dcallies this is the change I needed to make VPDQ usable through the Curator Web UI, since it uses `hash_media_from_form_data` internally.
This is the same thing that the `hash_media` endpoint does when receiving a `url`, as that uses FileHasher, not BytesHasher.
We'd probably also need something in Hashing to have support for `URLContent` and `TextContent`, but that'd require different UI completely (text input instead of file input)

OMM: Update hashing to support FileHashers

---

hasher-matcher-actioner/src/OpenMediaMatch/background_tasks/build_index.py
hasher-matcher-actioner/src/OpenMediaMatch/blueprints/matching.py
hasher-matcher-actioner/src/OpenMediaMatch/storage/postgres/database.py
hasher-matcher-actioner/src/OpenMediaMatch/tests/test_postgres_storage_impl.py
hasher-matcher-actioner/src/OpenMediaMatch/utils/memory_utils.py

Summary
---------
This is for #1813 I added memory logging around index operations ( Building, Download, Swap ) to monitor usage. I generated 150K hashes to have a big enough DB.
Without the changes here I saw a jump between reloads of 50-80MB while only freeing 5-15MB in between the process. 
Start: 
102MB → 150MB → 265MB → 285MB → 346MB → 378MB → 450MB
In a span of 10 minutes. 
PDQ loads: 48MB → 77MB → 76MB
```
CachedIndex[pdq] Index load: +48.21 MB
CachedIndex[pdq] Index load: +77.24 MB  
CachedIndex[pdq] Index load: +75.99 MB
[2025-08-08 03:57:04,926] INFO in matching: CachedIndex[video_md5] Periodic task memory: start=285.62 MB, storage=285.62 MB, end=298.36 MB (change: +12.74 MB)
[2025-08-08 03:57:05,040] INFO in matching: CachedIndex[pdq] Index load: 285.62 MB -> 362.86 MB (+77.24 …
```

[HMA] #1813 Clear out memory on index building to prevent bloating.

---

hasher-matcher-actioner/src/OpenMediaMatch/blueprints/matching.py
hasher-matcher-actioner/src/OpenMediaMatch/blueprints/ui.py
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/banks/banks_grid.html.j2
hasher-matcher-actioner/src/OpenMediaMatch/templates/components/banks/match_form.html.j2

Summary
---------
Fixes #1844
This PR Allows for the front-end to bypass the enabled ratio on queries to match content as well as add the functionality to the matching lookup as an optional arg. 
This is useful to check what the content may match on different banks regardless of the enabled_ratio while also giving a visual of what is the current enabled value for the banks. This is an optional setting on the UI as to keep the same behavior.
Test Plan
---------
Tested locally adding the same image to multiple banks and then changing their enabled ratio. I then requested the match bypassing enabled ratio and all got returned and then did a couple without the bypass to see the coinflip still working.
Before:
After:

[HMA] Bypass Enabled Ratio for UI
